-- 自动生成(generate_cheese_lua.py ← data_cache/cheese_tips.json)，勿手改。
-- 本周「逃课」清单：mapIds 是候选 uiMapID（12.x 同名地图多个 ID），插件挑第一个能打点的。
GearInsightCheese = { updated="2026-09-25", forDate="2026-09-25", resetNote="按游戏日（北京时间 07:00 服务器更新为界）；过期自动隐藏", resetNoteEn="By game day (server reset at 07:00 Beijing time); expired entries hide automatically",
  items={
    { id="w0925-hunt-fangtang", period="day", tag="周常", title="中秋芳糖 3 秒吃完：传送追猎大厅，选最上面的 3 星追猎 → 虚影风暴 43 / 69，倒数三二一进度拉满", summary="本 CD 第一个 3 秒芳糖镜。直接传送追猎大厅，无脑选列表最上方的追猎；接完插件会立刻标出坐标，跟着飞到虚影风暴 43 / 69。站到那个点上，倒数三二一追猎进度就拉满。",
      tagEn="Weekly", titleEn="Mid-Autumn lucky mirror in 3 seconds: teleport to the Hunt Hall, take the top hunt → Voidstorm 43 / 69, done in a 3-2-1 countdown", summaryEn="The first 3-second lucky mirror of this lockout. Teleport straight to the Hunt Hall and take the hunt at the top of the list; the waypoint appears right away - fly to Voidstorm 43 / 69. Stand on the spot and the hunt bar fills in a 3-2-1 countdown.",
      fromDay="2026-09-25", untilDay="2026-09-25",
      steps={
        { text="传送追猎大厅，选列表最上方的追猎", mapName="", mapIds={}, x=nil, y=nil, textEn="Teleport to the Hunt Hall and take the hunt at the top of the list", mapNameEn="" },
        { text="飞到虚影风暴 43 / 69，站到点上", mapName="虚影风暴", mapIds={2405,2479,2444,2397,2506}, x=43, y=69, textEn="Fly to Voidstorm 43 / 69 and stand on the spot", mapNameEn="Voidstorm" },
        { text="倒数三二一，追猎进度直接拉满", mapName="", mapIds={}, x=nil, y=nil, textEn="Count 3-2-1 and the hunt bar is full", mapNameEn="" },
      } },
    { id="w0925-delve-collegiate", period="day", tag="地下堡", title="丰裕 S 级「学府骚动」（银月城 40.7 / 53.7）：路线很短适合开宝图，救出 NPC 帮打巨额伤害", summary="今天学府骚动是丰裕 S 级。进门丢一个「小花」就能炸掉怪半管血；路线很短，适合开地下堡宝图。第一时间把 NPC 救出来，他会帮你打出巨额伤害。",
      tagEn="Delve", titleEn="Bountiful S-tier Collegiate Calamity (Silvermoon 40.7 / 53.7): very short route, great for a delve map; the rescued NPC hits hard", summaryEn="Collegiate Calamity is Bountiful S-tier today. Toss a flower on entry to blow away half a pack's health; the route is short, so it is a good place to use a delve map. Free the NPC right away - he helps with huge damage.",
      fromDay="2026-09-25", untilDay="2026-09-25",
      steps={
        { text="银月城 40.7 / 53.7 进「学府骚动」（丰裕）", mapName="银月城", mapIds={2393,2443,2525}, x=40.7, y=53.7, textEn="Silvermoon 40.7 / 53.7: enter Collegiate Calamity (Bountiful)", mapNameEn="Silvermoon City" },
        { text="丢一个小花，怪直接掉半管血；路线短，适合开宝图", mapName="", mapIds={}, x=nil, y=nil, textEn="Toss a flower and mobs lose half their health; short route, good for a delve map", mapNameEn="" },
        { text="第一时间救出 NPC，他会帮打巨额伤害", mapName="", mapIds={}, x=nil, y=nil, textEn="Free the NPC first - he deals huge damage", mapNameEn="" },
      } },
    { id="w0925-delve-harandar", period="day", tag="地下堡", title="丰裕「哈籁深沟」：点道具放 AOE 风暴，适合坦克一波拉；有位移的职业走小坡一键直达尾王", summary="银月城的地下堡机器人 7001 型可以直接传送过去。里面点击道具能放 AOE 风暴，适合坦克一波拉；有位移技能的职业前往小坡，可以一键直达尾王。上周拿到的弹簧依旧可以带出来。",
      tagEn="Delve", titleEn="Bountiful Harandar gulch delve: the item casts an AoE storm, great for a tank mega-pull; classes with movement can take the small slope straight to the last boss", summaryEn="The Delve-O-Bot 7001 in Silvermoon teleports you there. Inside, the item unleashes an AoE storm - perfect for a tank mega-pull; classes with a movement skill can head up the small slope and reach the last boss in one go. The spring from before can still be carried out.",
      fromDay="2026-09-25", untilDay="2026-09-25",
      steps={
        { text="银月城找「地下堡机器人 7001 型」，选「至暗之夜的地下堡」传送", mapName="", mapIds={}, x=nil, y=nil, textEn="In Silvermoon, talk to the Delve-O-Bot 7001 and pick the Midnight delves teleport", mapNameEn="" },
        { text="进哈籁深沟：点击道具放 AOE 风暴，坦克一波拉", mapName="", mapIds={}, x=nil, y=nil, textEn="Enter the Harandar gulch delve: click the item for an AoE storm, tank one big pull", mapNameEn="" },
        { text="有位移的职业前往小坡，一键直达尾王；弹簧照样能带出来", mapName="", mapIds={}, x=nil, y=nil, textEn="Classes with movement: go to the small slope, straight to the last boss; the spring can still be taken out", mapNameEn="" },
      } },
    { id="w0923-hunt-fangtang", period="week", tag="周常", title="小号随时召唤芳糖镜：追猎大厅选蛇岛追猎 → 盘卷蛇岛 58 / 43，关掉自动拾取后开箱再取消，追猎进度直接拉满", summary="小号也能随时开芳糖镜。传送到追猎大厅，选蛇岛的追猎（列表第三个）；出来直接去盘卷蛇岛 58 / 43。先在 ESC → 选项 → 控制 里关掉「自动拾取」，然后对宝藏开箱、取消、再开箱，反复几次追猎进度就满了。注意：每个宝藏下线就失效。装了 HandyNotes 的，在世界地图上勾选「宝藏」就能看到所有芳糖坐标。",
      tagEn="Weekly", titleEn="Summon the lucky mirror on any alt: pick the Coiling Isles hunt in the Hunt Hall → Coiling Isles 58 / 43, turn off Auto Loot, then open and cancel the cache repeatedly to max the hunt bar", summaryEn="Alts can pop the lucky mirror any time. Teleport to the Hunt Hall and pick the Coiling Isles hunt (third in the list); head straight to Coiling Isles 58 / 43. First turn off Auto Loot (Esc → Options → Controls), then open the treasure, cancel, and open again - a few rounds fill the hunt bar. Note: each treasure stops working once you log out. With HandyNotes, tick Treasures on the world map to see every mirror spot.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="传送追猎大厅，选择蛇岛的追猎（列表第三个）", mapName="", mapIds={}, x=nil, y=nil, textEn="Teleport to the Hunt Hall and pick the Coiling Isles hunt (third in the list)", mapNameEn="" },
        { text="出来直接前往盘卷蛇岛 58 / 43", mapName="盘卷蛇岛", mapIds={2512}, x=58.1, y=43.6, textEn="Head straight to Coiling Isles 58 / 43", mapNameEn="Coiling Isles" },
        { text="ESC → 选项 → 控制：关掉「自动拾取」；对宝藏开箱后取消、反复几次，进度拉满。宝藏下线即失效", mapName="", mapIds={}, x=nil, y=nil, textEn="Esc → Options → Controls: turn off Auto Loot; open the treasure and cancel a few times until the bar is full. Treasures stop working after you log out", mapNameEn="" },
      } },
    { id="w0923-arena-call", period="week", tag="周常", title="「竞技场的召唤」打人机就行：银月城 49 / 65 找大法师艾萨斯·逐日者接任务，再对话选第一项", summary="银月城 49 / 65 找大法师艾萨斯·逐日者接「竞技场的召唤」。接完再跟他对话、选第一个选项，进的是人机竞技场，打电脑就能完成。这条可以和英雄项链任务一起做。",
      tagEn="Weekly", titleEn="'Call of the Arena' with bots only: take it from Archmage Aethas Sunreaver at Silvermoon 49 / 65, then talk again and pick the first option", summaryEn="Take 'Call of the Arena' from Archmage Aethas Sunreaver at Silvermoon 49 / 65. Talk to him again and pick the first option - it queues you into a bot arena, so beating the AI completes it. Can be done together with the hero necklace quest.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="银月城 49 / 65 找大法师艾萨斯·逐日者，接「竞技场的召唤」", mapName="银月城", mapIds={2393,2443}, x=49, y=65, textEn="Silvermoon 49 / 65: take 'Call of the Arena' from Archmage Aethas Sunreaver", mapNameEn="Silvermoon City" },
        { text="再次对话选第一项 → 进人机竞技场，打电脑即可完成", mapName="", mapIds={}, x=nil, y=nil, textEn="Talk again and pick the first option → bot arena, beat the AI to finish", mapNameEn="" },
      } },
    { id="w0923-void-back", period="week", tag="外观", title="虚空银月城背景本周开放：接「追踪萨拉塔斯」收 100 个微弱的虚空低语（地下堡 3 次或盘卷蛇岛水域刷怪），交任务后 4 个残渣合成", summary="银月城接任务的地方，右手边温蕾萨·风行者给「追踪萨拉塔斯」：收集 100 个微弱的虚空低语。打 3 次地下堡，或者去盘卷蛇岛这片水域（约 64 / 38）刷怪都行；小技巧是先吃「硫磺鱼」，怪物会自动被戳瞎双眼，刷得很快。交任务后用 4 个残渣合成，就是那个帅气的虚空背景。",
      tagEn="Cosmetic", titleEn="Void Silvermoon back cosmetic opens this week: take 'Tracking Salatrancer', collect 100 Faint Void Whispers (3 delves, or farm the Coiling Isles waters), turn in and combine 4 remnants", summaryEn="Right next to the quest spot in Silvermoon, Vereesa Windrunner gives 'Tracking Salatrancer': collect 100 Faint Void Whispers. Run 3 delves, or farm the waters of the Coiling Isles (~64 / 38); tip: eat the sulfur fish first and mobs get blinded automatically, much faster. Turn it in and combine 4 remnants for the void back cosmetic.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="银月城：右手边温蕾萨·风行者接「追踪萨拉塔斯」（收集 100 个微弱的虚空低语）", mapName="", mapIds={}, x=nil, y=nil, textEn="Silvermoon: Vereesa Windrunner on the right gives 'Tracking Salatrancer' (collect 100 Faint Void Whispers)", mapNameEn="" },
        { text="打 3 次地下堡，或去盘卷蛇岛这片水域刷怪（约 64 / 38）；先吃「硫磺鱼」，怪物自动被戳瞎双眼", mapName="盘卷蛇岛", mapIds={2512}, x=64, y=37.6, textEn="Run 3 delves, or farm the Coiling Isles waters (~64 / 38); eat the sulfur fish first so mobs get blinded", mapNameEn="Coiling Isles" },
        { text="交任务后用 4 个残渣合成 → 虚空银月城背景", mapName="", mapIds={}, x=nil, y=nil, textEn="Turn in, then combine 4 remnants → Void Silvermoon back cosmetic", mapNameEn="" },
      } },
    { id="w0923-nagtar-spores", period="week", tag="世界任务", title="奈格塔尔每 2 小时刷孢子世界任务：银月城 48 / 51 接「双决战」→ 右前方传送英雄难度 → 直走 7 步在蘑菇旁左右来回", summary="奈格塔尔（虚影风暴）每 2 小时刷一次孢子世界任务。银月城 48 / 51 接「双决战」，右前方传送门选英雄难度；进去直走 7 步，在蘑菇旁左右来回走就行。营地刷出额外世界任务时，直接跳下去到小河边。记得先交英雄箱子并打开，奖励多一倍；旁边 NPC 还能再来一遍。",
      tagEn="World Quest", titleEn="Nagtar spore world quest every 2 hours: take 'Double Showdown' at Silvermoon 48 / 51 → heroic portal ahead on the right → walk 7 steps and strafe beside the mushroom", summaryEn="Nagtar (Voidstorm) spawns a spore world quest every 2 hours. Take 'Double Showdown' at Silvermoon 48 / 51 and use the portal ahead on the right, heroic difficulty; walk 7 steps and strafe beside the mushroom. When the camp spawns an extra world quest, jump down to the stream. Turn in and open the heroic chest first for double rewards; the NPC next to it lets you go again.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="银月城 48 / 51 接「双决战」", mapName="银月城", mapIds={2393,2443}, x=48.2, y=51.5, textEn="Silvermoon 48 / 51: take 'Double Showdown'", mapNameEn="Silvermoon City" },
        { text="右前方传送（英雄难度）→ 直走 7 步，在蘑菇旁左右来回即可", mapName="", mapIds={}, x=nil, y=nil, textEn="Portal ahead on the right (heroic) → walk 7 steps, strafe back and forth beside the mushroom", mapNameEn="" },
        { text="营地刷出额外世界任务时，直接跳下去到小河边", mapName="", mapIds={}, x=nil, y=nil, textEn="When the camp spawns an extra world quest, jump down to the stream", mapNameEn="" },
        { text="先交英雄箱子并打开 = 奖励翻倍；旁边 NPC 还能再来一遍", mapName="", mapIds={}, x=nil, y=nil, textEn="Turn in and open the heroic chest first = double rewards; the NPC beside it lets you run it again", mapNameEn="" },
      } },
    { id="w0923-housing-weekly", period="week", tag="周常", title="家宅周常一分钟：接任务 → 点小眼睛一键加入队伍 → 右键团长头像「访问」→ 进屋立刻完成", summary="本周家宅周常很简单：接任务后点任务追踪上的小眼睛，一键加入别人的队伍；右键团长头像选「访问」，进他的屋子任务立刻完成，一分钟搞定。",
      tagEn="Weekly", titleEn="Housing weekly in one minute: take it → click the eye to join a group → right-click the leader's portrait, Visit → done as soon as you enter", summaryEn="This week's housing weekly is easy: after taking it, click the eye icon on the tracker to join a group; right-click the leader's portrait and choose Visit - the quest completes the moment you enter their house. One minute.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="接家宅周常 → 点任务追踪上的小眼睛，一键加入队伍", mapName="", mapIds={}, x=nil, y=nil, textEn="Take the housing weekly → click the eye icon on the tracker to join a group", mapNameEn="" },
        { text="右键团长头像选「访问」→ 进屋立刻完成", mapName="", mapIds={}, x=nil, y=nil, textEn="Right-click the leader's portrait, Visit → completes as you enter", mapNameEn="" },
      } },
    { id="w0923-raid-buff", period="week", tag="团本", title="进团本先跟最左侧 NPC 对话，领 2% Buff", summary="本周进团本别忘了先跟入口最左侧的 NPC 对话，领一个 2% 的 Buff。",
      tagEn="Raid", titleEn="In the raid, talk to the leftmost NPC first for a 2% buff", summaryEn="Before pulling in the raid this week, talk to the leftmost NPC at the entrance for a 2% buff.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="团本入口：对话最左侧 NPC，领 2% Buff", mapName="", mapIds={}, x=nil, y=nil, textEn="Raid entrance: talk to the leftmost NPC for the 2% buff", mapNameEn="" },
      } },
    { id="w0922-hunt-double", period="day", tag="周常", title="追猎 6 倍今日双地图（限时返场）：追猎大厅传送 → 永歌森林 46 / 55 站几秒拉满 → 回大厅接第二站 虚影风暴 43 / 69", summary="今天追猎 6 倍开双地图，限时返场，本周少见。从追猎大厅直接传送：第一站永歌森林 46 / 55，站住几秒进度就满；开完格子回大厅接第二站虚影风暴 43 / 69，手快两秒搞定。两站都刷完再走。",
      tagEn="Weekly", titleEn="Hunts x6 today, two maps (limited-time return): teleport from the Hunt Hall → Eversong Woods 46 / 55, stand a few seconds → back to the hall for the second one, Voidstorm 43 / 69", summaryEn="Hunts x6 runs on two maps today, a rare limited-time return. Teleport from the Hunt Hall: first stop Eversong Woods 46 / 55, stand a few seconds and the bar fills; open the cache, return to the hall and take the second one, Voidstorm 43 / 69, done in two seconds if you're quick. Clear both before leaving.",
      fromDay="2026-09-22", untilDay="2026-09-22",
      steps={
        { text="追猎大厅传送 → 永歌森林 46 / 55，站住几秒进度拉满，开格子", mapName="永歌森林", mapIds={2395,2567}, x=46, y=55, textEn="Hunt Hall teleport → Eversong Woods 46 / 55, stand a few seconds to fill the bar, open the cache", mapNameEn="Eversong Woods" },
        { text="回追猎大厅接第二站 → 虚影风暴 43 / 69，两秒完成", mapName="虚影风暴", mapIds={2405,2479,2444,2397,2506}, x=43, y=69, textEn="Back to the Hunt Hall, take the second hunt → Voidstorm 43 / 69, done in two seconds", mapNameEn="Voidstorm" },
      } },
    { id="w0922-delve-atalaman", period="day", tag="地下堡", title="丰裕「阿塔阿曼」（永歌森林 60 / 81）：撞泡泡召青蛙 + 拿笛子，双 Buff 输出拉满；带小号，门口对话一键传送", summary="今日丰裕是阿塔阿曼。进去别忘拿笛子；地上的泡泡一定去撞，召出青蛙公主一群青蛙冰伤极高，两个 Buff 叠着输出拉满。带小号也方便，门口对话 NPC 一键传送去拿奖励。",
      tagEn="Delve", titleEn="Bountiful Atal'Aman (Eversong 60 / 81): pop the bubbles for frogs + grab the flute, two buffs for max damage; bring an alt, talk at the entrance for a one-click teleport", summaryEn="Today's Bountiful delve is Atal'Aman. Don't forget the flute on the way in; always pop the bubbles on the ground to summon the frog princess's swarm (huge frost damage) - with both buffs up you melt everything. Alts are easy too: talk to the NPC at the entrance for a one-click teleport to the rewards.",
      fromDay="2026-09-22", untilDay="2026-09-22",
      steps={
        { text="永歌森林 60 / 81（祖阿曼交界）进「阿塔阿曼」（今日丰裕）", mapName="永歌森林", mapIds={2395,2567}, x=60, y=81, textEn="Enter Atal'Aman at Eversong Woods 60 / 81 (Zul'Aman border), Bountiful today", mapNameEn="Eversong Woods" },
        { text="别忘拿笛子；地上的泡泡一定去撞 → 召青蛙群冰伤极高，双 Buff 输出拉满", mapName="", mapIds={}, x=nil, y=nil, textEn="Grab the flute; always pop the bubbles → frog swarm with huge frost damage, both buffs = max output", mapNameEn="" },
        { text="带小号：门口对话 NPC 一键传送去拿奖励", mapName="", mapIds={}, x=nil, y=nil, textEn="Alts: talk to the NPC at the entrance for a one-click teleport to the rewards", mapNameEn="" },
      } },
    { id="w0921-delve-collegiate", period="day", tag="地下堡", title="丰裕「学府骚动」（银月城 40.7 / 53.7）：追踪栏出现斧头「揭示伪装的暴光之刃」必打——用它激活伪装者就能直接尾王，路线超短", summary="今天丰裕的学府骚动非常好刷（宏伟宝库栏位直接升级）。追踪栏出现斧头图标「揭示伪装的暴光之刃」就必打：只激活几波怪就能直接尾王。冒绿光的 NPC 别碰；把另外 4 个 NPC 解救出来，他们帮打，躺赢。",
      tagEn="Delve", titleEn="Bountiful Collegiate Calamity (Silvermoon 40.7 / 53.7): when the axe item 'Exposing Blade' shows up, always take it - reveal the impostors and go straight to the last boss, super short route", summaryEn="Today's Bountiful Collegiate Calamity is a free Great Vault upgrade. When the axe icon 'Exposing Blade' appears in the tracker, always take it: only a few packs to activate, then straight to the last boss. Don't touch the green-glowing NPCs; free the other 4 and they carry the fight.",
      fromDay="2026-09-21", untilDay="2026-09-21",
      steps={
        { text="银月城 40.7 / 53.7 进「学府骚动」（今日丰裕）", mapName="银月城", mapIds={2393,2443,2525}, x=40.7, y=53.7, textEn="Enter Collegiate Calamity (Bountiful today) at Silvermoon 40.7 / 53.7", mapNameEn="Silvermoon City" },
        { text="追踪栏出斧头「揭示伪装的暴光之刃」必打：激活几波怪即可直接尾王", mapName="", mapIds={}, x=nil, y=nil, textEn="Take the axe item 'Exposing Blade' when it appears: activate a few packs and go straight to the last boss", mapNameEn="" },
        { text="冒绿光的 NPC 别碰；解救其他 4 个 NPC 帮打躺赢", mapName="", mapIds={}, x=nil, y=nil, textEn="Don't touch green-glowing NPCs; free the other 4 NPCs and let them fight for you", mapNameEn="" },
      } },
    { id="w0921-valeera-ring-of-glory", period="day", tag="速通", title="瓦娘最快升 80 故事线：「荣耀之环」（盘卷蛇岛东 约 44.2 / 22.6），珍玩选「钝顿的青睐」，配 SilverDragon 一键开图，小 boss 全部吃晕", summary="今天带瓦娘刷等级最快的是荣耀之环的故事线。瓦莉拉效能珍玩选「钝顿的青睐」（打错放的奇珍召迷途精魂，每下 6 个易爆精魂）；配合 SilverDragon 一键开图找目标。怪非常少，小 boss 全部可以吃晕，切记控住；带上「盐击者」一路前进即可。",
      tagEn="Speedrun", titleEn="Fastest Valeera-to-80 story line today: The Ring of Glory (east Coiled Isles ~44.2 / 22.6), pick the Dunmore's Favor trinket, use SilverDragon to reveal the map, every mini boss is stunnable", summaryEn="Fastest Valeera leveling today is the Ring of Glory story line. Pick Dunmore's Favor for Valeera's utility trinket (misplaced curios spawn lost spirits, 6 volatile spirits per hit); use SilverDragon to reveal objectives. Very few mobs and every mini boss can be stunned - keep them locked down and push forward with the Saltstriker.",
      fromDay="2026-09-21", untilDay="2026-09-21",
      steps={
        { text="荣耀之环入口：盘卷蛇岛东侧 约 44.2 / 22.6", mapName="盘卷蛇岛", mapIds={2512}, x=44.2, y=22.6, textEn="Ring of Glory entrance: east Coiled Isles, ~44.2 / 22.6", mapNameEn="Coiling Isles" },
        { text="瓦莉拉效能珍玩选「钝顿的青睐」；SilverDragon 一键开图", mapName="", mapIds={}, x=nil, y=nil, textEn="Valeera utility trinket: Dunmore's Favor; SilverDragon to reveal the map", mapNameEn="" },
        { text="怪非常少，小 boss 全部吃晕；带盐击者前进即可", mapName="", mapIds={}, x=nil, y=nil, textEn="Very few mobs, stun every mini boss; push forward with the Saltstriker", mapNameEn="" },
      } },
    { id="w0920-weekly-toy", period="day", tag="周常", title="三条周常原地完成：紫球边放「海象人冰钓帐」玩具，坐上无脑点球，进度一直涨（还能蹭别人的）", summary="「干扰敌方基地的行动」那三条周常（异界决战 / 虚空侵袭 / 地下堡任务板各一）不用跑图：在紫色虚空球旁边放下玩具「海象人冰钓帐」，坐进去点球，人不动进度无限涨；有人放了帐篷直接蹭，十秒搞定。别忘了先在银月城 49 / 65 的任务板把「地下堡」那条接上，三条一起完成。",
      tagEn="Weekly", titleEn="Three weeklies without moving: drop the Tuskarr Ice Fishing Tent toy beside the purple orb, sit and spam-click the orb - progress keeps ticking (or use someone else's tent)", summaryEn="The three 'disrupt the enemy base' weeklies (Otherworld / Void Incursion / Delve board) need no running: put the Tuskarr Ice Fishing Tent toy next to a purple void orb, sit in it and click the orb - progress keeps rising while you stand still; if someone already placed a tent just use it, ten seconds. Take the Delve weekly from the Silvermoon quest board at 49 / 65 first so all three complete together.",
      fromDay="2026-09-20", untilDay="2026-09-20",
      steps={
        { text="先在银月城任务板 49 / 65 接「地下堡」周常（和另外两条一起完成）", mapName="银月城", mapIds={2393,2443}, x=49, y=65, textEn="Take the Delve weekly from the Silvermoon quest board at 49 / 65 first (completes together with the other two)", mapNameEn="Silvermoon City" },
        { text="找一个紫色虚空球，旁边放下玩具「海象人冰钓帐」（1 小时冷却），坐进去无脑点球，进度自己涨；有别人的帐篷直接蹭", mapName="", mapIds={}, x=nil, y=nil, textEn="Find a purple void orb, drop the Tuskarr Ice Fishing Tent toy (1h cooldown) beside it, sit in and spam-click the orb - progress keeps ticking; someone else's tent works too", mapNameEn="" },
      } },
    { id="w0917-timewalking", period="week", tag="时光漫游", title="本周大灾变时光漫游：每号 5 分钟一把，周常摸勇士 / 英雄轨道装", summary="4.0 时光漫游周，随机本极快；银月城 48 / 64 找大法师艾萨斯·逐日者接周常「穿越时光的翱翔之路」，打满 5 把交任务开「奎尔萨拉斯宝藏」——勇士或英雄轨道一件（S2 勇士 295–308 · 英雄 308–321），小号一起过一遍。",
      tagEn="Timewalking", titleEn="Cataclysm Timewalking this week: ~5 minutes per run, weekly gives a Champion / Hero track piece", summaryEn="Cataclysm Timewalking week, random dungeons are very fast. In Silvermoon (48 / 64) talk to Archmage Aethas Sunreaver for the weekly \"A Timely Flight Through Time\"; after 5 runs turn it in for the Cache of Quel'Thalas treasures — one Champion or Hero track piece (S2 Champion 295–308 · Hero 308–321). Run alts through too.",
      fromDay="2026-09-17", untilDay="2026-09-22",
      steps={
        { text="银月城 48 / 64 找大法师艾萨斯·逐日者，接周常「穿越时光的翱翔之路」", mapName="银月城", mapIds={2393,2443}, x=48, y=64, textEn="Silvermoon 48 / 64: talk to Archmage Aethas Sunreaver and take the weekly \"A Timely Flight Through Time\"", mapNameEn="Silvermoon City" },
        { text="随机时光漫游本 ×5（每把约 5 分钟）", mapName="", mapIds={}, x=nil, y=nil, textEn="Random Timewalking dungeon ×5 (about 5 minutes each)", mapNameEn="" },
        { text="回 48 / 64 交任务，开箱 = 勇士轨道 295–308 或英雄轨道 308–321 一件（按拾取专精）", mapName="银月城", mapIds={2393,2443}, x=48, y=64, textEn="Return to 48 / 64, turn in, open the cache = one Champion track 295–308 or Hero track 308–321 piece (by loot spec)", mapNameEn="Silvermoon City" },
      } },
  },
  sources={
    { platform="B站", author="魔兽阿落", title="超级中秋芳糖3秒吃完 丰裕S级速刷 每日地下堡狩猎逃课推荐9.25中秋快乐~", url="https://www.bilibili.com/video/BV1wWaM6rE3e/", date="2026-09-25" },
    { platform="视频号", author="魔兽阿落", title="超级中秋芳糖3秒吃完 丰裕S级速刷", url="https://weixin.qq.com/sph/A1tQKm0kvC", date="2026-09-25" },
    { platform="B站", author="魔兽阿落", title="小号随时开启芳糖镜 本周指南保姆全路线 周常快速完成 虚空银月城背景", url="https://www.bilibili.com/video/BV1qwhb6pEsH/", date="2026-09-23" },
    { platform="视频号", author="魔兽阿落", title="本周指南 小号随时开启芳糖镜 周常快速完成 虚空银月城背景", url="https://weixin.qq.com/sph/Atcjgy23hZ", date="2026-09-23" },
    { platform="B站", author="魔兽阿落", title="超级福利双芳糖 本周罕见狩猎新地图 永歌风暴丰裕刷爆限时返场 每日地下堡狩猎逃课推荐", url="https://www.bilibili.com/video/BV1JBh66tEAT/", date="2026-09-22" },
    { platform="B站", author="魔兽阿落", title="超级弹簧符文 无限大跳玩具 丰裕爽刷白送 瓦娘80最快满级 每日地下堡逃课推荐", url="https://www.bilibili.com/video/BV1Cchv67Esa/", date="2026-09-21" },
    { platform="Icy Veins", author="Icy Veins", title="The Ring of Glory Delve Guide（east Coiled Isle ~44.15/22.60）", url="https://www.icy-veins.com/wow/the-ring-of-glory-delve-guide", date="2026-09-21" },
    { platform="Wowhead", author="Wowhead", title="Delves in Midnight - Locations（Collegiate Calamity 40.6/53.7）", url="https://www.wowhead.com/guide/midnight/delves-season-companion-nemesis-rewards-locations", date="2026-09-17" },
    { platform="Icy Veins", author="Icy Veins", title="Atal'Aman Delve Guide（west Zul'Aman, Eversong border）", url="https://www.icy-veins.com/wow/atal-aman-delve-guide", date="2026-09-19" },
  } }
