-- 自动生成(generate_cheese_lua.py ← data_cache/cheese_tips.json)，勿手改。
-- 本周「逃课」清单：mapIds 是候选 uiMapID（12.x 同名地图多个 ID），插件挑第一个能打点的。
GearInsightCheese = { updated="2026-10-03", forDate="2026-10-03", resetNote="按游戏日（北京时间 07:00 服务器更新为界）；过期自动隐藏", resetNoteEn="By game day (server reset at 07:00 Beijing time); expired entries hide automatically",
  items={
    { id="w1003-silvermoon-paragon", period="week", tag="声望", title="银月宫廷巅峰箱子发光 → 永歌森林 43.4 / 47.4 名望军需官：1500 灰岩 + 2000 金币，每个角色都能领", summary="视频标注「仅限本周」。做完聚会周常后打开声望栏，银月宫廷的巅峰箱子发光就去晴风村南边的银月宫廷名望军需官对话领取；之后每个角色都能再领一次。视频实测要求全程只保持一个角色在线，多开会被顶掉、奖励消失。巅峰没打满怎么办视频没讲完。",
      tagEn="", titleEn="", summaryEn="",
      fromDay="2026-10-03", untilDay="2026-10-06",
      steps={
        { text="做完聚会周常 → 打开声望栏，确认「银月宫廷」巅峰箱子在发光", mapName="", mapIds={}, x=nil, y=nil, textEn="", mapNameEn="" },
        { text="永歌森林 43.4 / 47.4（晴风村南）：和「银月宫廷名望军需官」对话领取 1500 灰岩 + 2000 金币", mapName="永歌森林", mapIds={2395,2567}, x=43.4, y=47.4, textEn="", mapNameEn="" },
        { text="换其他角色登录可各再领一次；⛔ 全程只保持一个角色在线，不要多开（视频实测会被顶掉、奖励消失）", mapName="", mapIds={}, x=nil, y=nil, textEn="", mapNameEn="" },
      } },
    { id="w1003-ring-of-glory-adoption", period="day", tag="地下堡", title="今日丰裕「荣耀之环」五星故事线「领养大会」（盘卷蛇岛 72.4 / 57.7）：带小号方便，尾王打两次", summary="两个五星故事线之一。带小号只要在进度打满前让小号进本；不要提前营救动物，有时会触发 bug 导致小号拿不到奖励；尾王需要击败两次，但没有难度。",
      tagEn="", titleEn="", summaryEn="",
      fromDay="2026-10-03", untilDay="2026-10-03",
      steps={
        { text="盘卷蛇岛 72.4 / 57.7：进入今日丰裕「荣耀之环」（故事线「领养大会」）", mapName="盘卷蛇岛", mapIds={2512}, x=72.4, y=57.7, textEn="", mapNameEn="" },
        { text="带小号：进度打满前让小号进本即可；⛔ 不要提前营救动物（可能卡 bug，小号拿不到奖励）", mapName="", mapIds={}, x=nil, y=nil, textEn="", mapNameEn="" },
        { text="尾王需要击败两次", mapName="", mapIds={}, x=nil, y=nil, textEn="", mapNameEn="" },
      } },
    { id="w1003-atalaman-frogs", period="day", tag="地下堡", title="今日丰裕「阿塔阿曼」五星故事线（永歌森林 60 / 81）：青蛙祭坛加速、青蛙泡泡秒怪，小号找青蛙直接传宝箱", summary="两个五星故事线之一（视频标题写作「蛙全不同」）。入口青蛙祭坛加移动速度，水池里的青蛙泡泡给强力 buff 秒怪；小号只要在进度打满前进本，大号打完尾王后小号和青蛙对话直接传送到宝箱。",
      tagEn="", titleEn="", summaryEn="",
      fromDay="2026-10-03", untilDay="2026-10-03",
      steps={
        { text="永歌森林 60 / 81（祖阿曼交界）：进入今日丰裕「阿塔阿曼」", mapName="永歌森林", mapIds={2395,2567}, x=60, y=81, textEn="", mapNameEn="" },
        { text="点入口处的青蛙祭坛加移动速度；采水池里的青蛙泡泡拿强力 buff 秒怪", mapName="", mapIds={}, x=nil, y=nil, textEn="", mapNameEn="" },
        { text="带小号：进度打满前进本 → 大号打完尾王 → 小号和青蛙对话直接传送到宝箱", mapName="", mapIds={}, x=nil, y=nil, textEn="", mapNameEn="" },
      } },
    { id="w1003-twilight-crypts-fast", period="day", tag="地下堡", title="今日丰裕「暮光地穴·不灭的神灵」速通（祖阿曼 28.4 / 80.6）：拿药水冲中间环形路，聚怪撞杀，拆图腾完成故事", summary="今日丰裕 4 个：影卫营、荣耀之环、阿塔阿曼、暮光地穴。暮光地穴进门拿药水，最快冲到中间环形路段，带小怪聚拢后让爬行怪撞杀；摧毁图腾完成故事线，戴面具可增加伤害，助力击杀 Boss。入口坐标来自外部资料（Wowprimer 写在祖阿曼西南小山洞），未在游戏内验证。",
      tagEn="", titleEn="", summaryEn="",
      fromDay="2026-10-03", untilDay="2026-10-03",
      steps={
        { text="祖阿曼 28.4 / 80.6（西南小山洞，外部资料、未游戏内验证）：进入「暮光地穴」", mapName="祖阿曼", mapIds={2437}, x=28.4, y=80.6, textEn="", mapNameEn="" },
        { text="进门拿药水 → 以最快速度冲到中间环形路段", mapName="", mapIds={}, x=nil, y=nil, textEn="", mapNameEn="" },
        { text="带着小怪聚拢，再让爬行怪撞杀；摧毁图腾完成故事线", mapName="", mapIds={}, x=nil, y=nil, textEn="", mapNameEn="" },
        { text="戴面具可增加伤害 → 击杀 Boss", mapName="", mapIds={}, x=nil, y=nil, textEn="", mapNameEn="" },
      } },
    { id="w0927-hunter-basilisk-blitz", period="day", tag="猎人", title="猎人补抓特殊山羊：影卫营「蛇怪闪击」故事 → 界门 → 离开 → 多恩主城驯服", summary="仅限影卫营当日「蛇怪闪击」故事。视频展示进入故事、点击界门、右键头像离开，再到多恩主城补抓NPC山羊；短片未交代完整前置、增益持续时间和宠物正式名称，按步骤测试，不保证其他故事可用。",
      tagEn="Hunter", titleEn="Hunter special goat tame: Shadowguard Point 'Basilisk Blitz' story → gateway → leave → tame in Dornogal", summaryEn="Only for the current Basilisk Blitz story in Shadowguard Point. The video enters the story, clicks the gateway, leaves via the portrait menu, then tames the NPC goat in Dornogal. The short clip does not establish all prerequisites, buff duration, or the pet's exact name; test the shown flow only.",
      fromDay="2026-09-27", untilDay="2026-09-27",
      steps={
        { text="确认影卫营当前故事为「蛇怪闪击」后进入；不要套用到其他故事", mapName="", mapIds={}, x=nil, y=nil, textEn="Enter Shadowguard Point only when the active story is Basilisk Blitz; do not apply this to other stories", mapNameEn="" },
        { text="点击视频所示界门 → 右键角色头像选择离开", mapName="", mapIds={}, x=nil, y=nil, textEn="Click the gateway shown in the video → right-click your portrait and choose Leave", mapNameEn="" },
        { text="到多恩主城寻找视频中的NPC山羊并尝试特殊驯服；视频未给坐标和完整前置", mapName="", mapIds={}, x=nil, y=nil, textEn="In Dornogal, find the NPC goat shown and attempt the special tame; the video gives no coordinates or full prerequisites", mapNameEn="" },
      } },
    { id="w0927-coiled-hunt-wall", period="day", tag="日常", title="今日芳糖：狩猎大厅右下三个周常 → 盘卷蛇岛 52 / 43 靠墙往返", summary="传送狩猎大厅，按视频选择右下方三个周常，再到盘卷蛇岛 52 / 43 的墙边往返移动增加狩猎进度。视频未给任务正式名称和固定收益数量。",
      tagEn="Daily", titleEn="Today's lucky mirror: bottom-right three Hunt Hall weeklies → Coiled Isle 52 / 43 wall loop", summaryEn="Teleport to the Hunt Hall, take the three bottom-right weeklies shown, then move back and forth along the wall at Coiled Isle 52 / 43 to gain hunt progress. The video does not provide the official quest names or a fixed reward amount.",
      fromDay="2026-09-27", untilDay="2026-09-27",
      steps={
        { text="传送狩猎大厅，选择视频所示右下方三个周常", mapName="", mapIds={}, x=nil, y=nil, textEn="Teleport to the Hunt Hall and take the three bottom-right weeklies shown", mapNameEn="" },
        { text="盘卷蛇岛 52 / 43：贴墙来回移动，增加狩猎进度", mapName="盘卷蛇岛", mapIds={2512}, x=52, y=43, textEn="Coiled Isle 52 / 43: move back and forth along the wall to gain hunt progress", mapNameEn="The Coiled Isle" },
      } },
    { id="w0927-ring-of-glory-bountiful", period="day", tag="地下堡", title="今日丰裕「荣耀之环」（盘卷蛇岛 72.4 / 57.7）：流程短、怪少，小Boss可晕并利用陷阱", summary="进入后到内图南侧找固定出现的「钝颅」并交互；推进短流程，对小Boss使用晕眩并利用地面陷阱。外部入口坐标由用户游戏内确认，内部坐标不套到外图。",
      tagEn="Delve", titleEn="Today's Bountiful Ring of Glory (Coiled Isle 72.4 / 57.7): short route, few mobs, stun mini-bosses and use traps", summaryEn="Inside, head to the south side of the internal map for the fixed NPC shown, then follow the short route, stun mini-bosses and use floor traps. The external entrance coordinate was verified in game by the user; internal coordinates are kept separate.",
      fromDay="2026-09-27", untilDay="2026-09-27",
      steps={
        { text="盘卷蛇岛 72.4 / 57.7：进入今日丰裕「荣耀之环」", mapName="盘卷蛇岛", mapIds={2512}, x=72.4, y=57.7, textEn="Coiled Isle 72.4 / 57.7: enter today's Bountiful Ring of Glory", mapNameEn="The Coiled Isle" },
        { text="内图南侧找固定出现的「钝颅」并交互；小Boss吃晕，可利用地面陷阱", mapName="", mapIds={}, x=nil, y=nil, textEn="Find the fixed NPC on the south side of the internal map; stun mini-bosses and use the floor traps", mapNameEn="" },
      } },
    { id="w0927-sunkiller-sanctum", period="day", tag="地下堡", title="戮日圣殿（虚影风暴 54.1 / 47.7）：穿紫门拿分身和移速，三小Boss尾王", summary="进入视频所示故事后穿过虚空紫门，利用分身和移动速度推进；尾王由三个小Boss组成。视频称持续刷出的小怪可用于小号练级，但未提供经验效率，可能受轮换或热修改动。",
      tagEn="Delve", titleEn="Sunkiller Sanctum (Voidstorm 54.1 / 47.7): pass through purple gates for clones and speed, then three mini-bosses", summaryEn="In the story shown, pass through the purple void gates and use the clone and movement-speed effects to progress; the final encounter is three mini-bosses. The video suggests the respawning adds for alt leveling but gives no XP rate, and rotation or hotfixes may change it.",
      fromDay="2026-09-27", untilDay="2026-09-27",
      steps={
        { text="虚影风暴 54.1 / 47.7：进入戮日圣殿", mapName="虚影风暴", mapIds={2405}, x=54.1, y=47.7, textEn="Voidstorm 54.1 / 47.7: enter Sunkiller Sanctum", mapNameEn="Voidstorm" },
        { text="穿过虚空紫门取得分身和移速，推进到三个小Boss构成的尾王战", mapName="", mapIds={}, x=nil, y=nil, textEn="Pass through the purple void gates for clones and speed, then reach the three-mini-boss finale", mapNameEn="" },
        { text="持续刷出的小怪仅按视频标为练级候选；未验证经验效率和长期有效性", mapName="", mapIds={}, x=nil, y=nil, textEn="Treat the respawning adds only as a leveling candidate from the video; XP efficiency and long-term availability are unverified", mapNameEn="" },
      } },
    { id="w0926-zulaman-fangtang", period="day", tag="日常", title="方糖①：祖阿曼三狩猎", summary="祖阿曼方糖和盘卷蛇岛方糖是两条独立追猎；祖阿曼三狩猎飞到祖阿曼 43 / 30 的小桥，不能套用蛇岛坐标。",
      tagEn="Daily", titleEn="Lucky mirror 1: Zul'Aman three-hunt", summaryEn="The Zul'Aman and Coiling Isles lucky mirrors are separate hunts. For the Zul'Aman three-hunt, fly to the small bridge at Zul'Aman 43 / 30; never reuse a Coiling Isles coordinate.",
      fromDay="2026-09-26", untilDay="2026-09-26",
      steps={
        { text="追猎大厅选择「祖阿曼」三狩猎（独立方糖路线）", mapName="", mapIds={}, x=nil, y=nil, textEn="Choose the Zul'Aman three-hunt in the Hunt Hall (a separate lucky-mirror route)", mapNameEn="" },
        { text="祖阿曼 43 / 30 小桥：飞到点上完成三狩猎", mapName="祖阿曼", mapIds={2437}, x=43, y=30, textEn="Zul'Aman 43 / 30 small bridge: fly to the point to finish the three-hunt", mapNameEn="Zul'Aman" },
      } },
    { id="w0926-coiling-fangtang", period="day", tag="日常", title="方糖②：盘卷蛇岛 52 / 43 靠墙来回（6 倍刷新）", summary="蛇岛方糖独立完成：到盘卷蛇岛 52 / 43 靠墙来回，利用 6 倍刷新快速完成。",
      tagEn="Daily", titleEn="Lucky mirror 2: Coiling Isles 52 / 43 wall loop (x6 refresh)", summaryEn="The Coiling Isles lucky mirror is separate: loop along the wall at 52 / 43 for the x6 refresh.",
      fromDay="2026-09-26", untilDay="2026-09-26",
      steps={
        { text="盘卷蛇岛 52 / 43 靠墙来回（6 倍刷新）", mapName="盘卷蛇岛", mapIds={2512}, x=52, y=43, textEn="Loop along the wall at Coiling Isles 52 / 43 (x6 refresh)", mapNameEn="Coiling Isles" },
      } },
    { id="w0926-nalador-bountiful", period="day", tag="地下堡", title="丰裕：纳拉多尔岛（盘卷蛇岛 61 / 61）战龟全秒", summary="选最简单故事线，进本先捡完地上道具；上战龟开启无敌形态，回头清怪，笛子召唤的 Boss 也能秒。",
      tagEn="Delve", titleEn="Bountiful Nalador Isle (Coiling Isles 61 / 61): war turtle clear", summaryEn="Take the easiest story and collect ground items first; then use the war turtle's invulnerability to clear mobs and the flute-summoned boss.",
      fromDay="2026-09-26", untilDay="2026-09-26",
      steps={
        { text="盘卷蛇岛 61 / 61 进丰裕「纳拉多尔岛」：选最简单故事线，先捡完地上道具", mapName="盘卷蛇岛", mapIds={2512}, x=61, y=61, textEn="Enter Bountiful Nalador Isle at Coiling Isles 61 / 61: take the easiest story and collect all ground items first", mapNameEn="Coiling Isles" },
        { text="上战龟开启无敌形态，回头清怪；笛子召唤的 Boss 也能秒", mapName="", mapIds={}, x=nil, y=nil, textEn="Mount the war turtle for invulnerability, clear back through the mobs; the flute-summoned boss also dies instantly", mapNameEn="" },
      } },
    { id="w0925-hunt-fangtang", period="day", tag="周常", title="中秋芳糖 3 秒吃完：传送追猎大厅，选最上面的 3 星追猎 → 虚影风暴 43 / 69，倒数三二一进度拉满", summary="本 CD 第一个 3 秒芳糖镜。直接传送追猎大厅，无脑选列表最上方的追猎；接完插件会立刻标出坐标，跟着飞到虚影风暴 43 / 69。站到那个点上，倒数三二一追猎进度就拉满。",
      tagEn="Weekly", titleEn="Mid-Autumn lucky mirror in 3 seconds: teleport to the Hunt Hall, take the top hunt → Voidstorm 43 / 69, done in a 3-2-1 countdown", summaryEn="The first 3-second lucky mirror of this lockout. Teleport straight to the Hunt Hall and take the hunt at the top of the list; the waypoint appears right away - fly to Voidstorm 43 / 69. Stand on the spot and the hunt bar fills in a 3-2-1 countdown.",
      fromDay="2026-09-25", untilDay="2026-09-25",
      steps={
        { text="传送追猎大厅，选列表最上方的追猎", mapName="", mapIds={}, x=nil, y=nil, textEn="Teleport to the Hunt Hall and take the hunt at the top of the list", mapNameEn="" },
        { text="飞到虚影风暴 43 / 69，站到点上", mapName="虚影风暴", mapIds={2405,2479,2444,2397,2506}, x=43, y=69, textEn="Fly to Voidstorm 43 / 69 and stand on the spot", mapNameEn="Voidstorm" },
        { text="倒数三二一，追猎进度直接拉满", mapName="", mapIds={}, x=nil, y=nil, textEn="Count 3-2-1 and the hunt bar is full", mapNameEn="" },
      } },
    { id="w0925-delve-collegiate", period="day", tag="地下堡", title="丰裕 S 级「学府骚动」（银月城 40.7 / 53.7）：路线很短适合开宝图，救出 NPC 帮打巨额伤害", summary="今天学府骚动是丰裕 S 级。进门丢一个「小花」就能炸掉怪半管血；路线很短，适合开地下堡宝图。第一时间把 NPC 救出来，他会帮你打出巨额伤害。",
      tagEn="Delve", titleEn="Bountiful S-tier Collegiate Calamity (Silvermoon 40.7 / 53.7): very short route, great for a delve map; the rescued NPC hits hard", summaryEn="Collegiate Calamity is Bountiful S-tier today. Toss a flower on entry to blow away half a pack's health; the route is short, so it is a good place to use a delve map. Free the NPC right away - he helps with huge damage.",
      fromDay="2026-09-25", untilDay="2026-09-25",
      steps={
        { text="银月城 40.7 / 53.7 进「学府骚动」（丰裕）", mapName="银月城", mapIds={2393,2443,2525}, x=40.7, y=53.7, textEn="Silvermoon 40.7 / 53.7: enter Collegiate Calamity (Bountiful)", mapNameEn="Silvermoon City" },
        { text="丢一个小花，怪直接掉半管血；路线短，适合开宝图", mapName="", mapIds={}, x=nil, y=nil, textEn="Toss a flower and mobs lose half their health; short route, good for a delve map", mapNameEn="" },
        { text="第一时间救出 NPC，他会帮打巨额伤害", mapName="", mapIds={}, x=nil, y=nil, textEn="Free the NPC first - he deals huge damage", mapNameEn="" },
      } },
    { id="w0925-delve-harandar", period="day", tag="地下堡", title="丰裕「哈籁深沟」：点道具放 AOE 风暴，适合坦克一波拉；有位移的职业走小坡一键直达尾王", summary="银月城的地下堡机器人 7001 型可以直接传送过去。里面点击道具能放 AOE 风暴，适合坦克一波拉；有位移技能的职业前往小坡，可以一键直达尾王。上周拿到的弹簧依旧可以带出来。",
      tagEn="Delve", titleEn="Bountiful Harandar gulch delve: the item casts an AoE storm, great for a tank mega-pull; classes with movement can take the small slope straight to the last boss", summaryEn="The Delve-O-Bot 7001 in Silvermoon teleports you there. Inside, the item unleashes an AoE storm - perfect for a tank mega-pull; classes with a movement skill can head up the small slope and reach the last boss in one go. The spring from before can still be carried out.",
      fromDay="2026-09-25", untilDay="2026-09-25",
      steps={
        { text="银月城找「地下堡机器人 7001 型」，选「至暗之夜的地下堡」传送", mapName="", mapIds={}, x=nil, y=nil, textEn="In Silvermoon, talk to the Delve-O-Bot 7001 and pick the Midnight delves teleport", mapNameEn="" },
        { text="进哈籁深沟：点击道具放 AOE 风暴，坦克一波拉", mapName="", mapIds={}, x=nil, y=nil, textEn="Enter the Harandar gulch delve: click the item for an AoE storm, tank one big pull", mapNameEn="" },
        { text="有位移的职业前往小坡，一键直达尾王；弹簧照样能带出来", mapName="", mapIds={}, x=nil, y=nil, textEn="Classes with movement: go to the small slope, straight to the last boss; the spring can still be taken out", mapNameEn="" },
      } },
    { id="w0923-hunt-fangtang", period="week", tag="周常", title="小号随时召唤芳糖镜：追猎大厅选蛇岛追猎 → 盘卷蛇岛 58 / 43，关掉自动拾取后开箱再取消，追猎进度直接拉满", summary="小号也能随时开芳糖镜。传送到追猎大厅，选蛇岛的追猎（列表第三个）；出来直接去盘卷蛇岛 58 / 43。先在 ESC → 选项 → 控制 里关掉「自动拾取」，然后对宝藏开箱、取消、再开箱，反复几次追猎进度就满了。注意：每个宝藏下线就失效。装了 HandyNotes 的，在世界地图上勾选「宝藏」就能看到所有芳糖坐标。",
      tagEn="Weekly", titleEn="Summon the lucky mirror on any alt: pick the Coiling Isles hunt in the Hunt Hall → Coiling Isles 58 / 43, turn off Auto Loot, then open and cancel the cache repeatedly to max the hunt bar", summaryEn="Alts can pop the lucky mirror any time. Teleport to the Hunt Hall and pick the Coiling Isles hunt (third in the list); head straight to Coiling Isles 58 / 43. First turn off Auto Loot (Esc → Options → Controls), then open the treasure, cancel, and open again - a few rounds fill the hunt bar. Note: each treasure stops working once you log out. With HandyNotes, tick Treasures on the world map to see every mirror spot.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="传送追猎大厅，选择蛇岛的追猎（列表第三个）", mapName="", mapIds={}, x=nil, y=nil, textEn="Teleport to the Hunt Hall and pick the Coiling Isles hunt (third in the list)", mapNameEn="" },
        { text="出来直接前往盘卷蛇岛 58 / 43", mapName="盘卷蛇岛", mapIds={2512}, x=58.1, y=43.6, textEn="Head straight to Coiling Isles 58 / 43", mapNameEn="Coiling Isles" },
        { text="ESC → 选项 → 控制：关掉「自动拾取」；对宝藏开箱后取消、反复几次，进度拉满。宝藏下线即失效", mapName="", mapIds={}, x=nil, y=nil, textEn="Esc → Options → Controls: turn off Auto Loot; open the treasure and cancel a few times until the bar is full. Treasures stop working after you log out", mapNameEn="" },
      } },
    { id="w0923-arena-call", period="week", tag="周常", title="「竞技场的召唤」打人机就行：银月城 49 / 65 找大法师艾萨斯·逐日者接任务，再对话选第一项", summary="银月城 49 / 65 找大法师艾萨斯·逐日者接「竞技场的召唤」。接完再跟他对话、选第一个选项，进的是人机竞技场，打电脑就能完成。这条可以和英雄项链任务一起做。",
      tagEn="Weekly", titleEn="'Call of the Arena' with bots only: take it from Archmage Aethas Sunreaver at Silvermoon 49 / 65, then talk again and pick the first option", summaryEn="Take 'Call of the Arena' from Archmage Aethas Sunreaver at Silvermoon 49 / 65. Talk to him again and pick the first option - it queues you into a bot arena, so beating the AI completes it. Can be done together with the hero necklace quest.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="银月城 49 / 65 找大法师艾萨斯·逐日者，接「竞技场的召唤」", mapName="银月城", mapIds={2393,2443}, x=49, y=65, textEn="Silvermoon 49 / 65: take 'Call of the Arena' from Archmage Aethas Sunreaver", mapNameEn="Silvermoon City" },
        { text="再次对话选第一项 → 进人机竞技场，打电脑即可完成", mapName="", mapIds={}, x=nil, y=nil, textEn="Talk again and pick the first option → bot arena, beat the AI to finish", mapNameEn="" },
      } },
    { id="w0923-void-back", period="week", tag="外观", title="虚空银月城背景本周开放：接「追踪萨拉塔斯」收 100 个微弱的虚空低语（地下堡 3 次或盘卷蛇岛水域刷怪），交任务后 4 个残渣合成", summary="银月城接任务的地方，右手边温蕾萨·风行者给「追踪萨拉塔斯」：收集 100 个微弱的虚空低语。打 3 次地下堡，或者去盘卷蛇岛这片水域（约 64 / 38）刷怪都行；小技巧是先吃「硫磺鱼」，怪物会自动被戳瞎双眼，刷得很快。交任务后用 4 个残渣合成，就是那个帅气的虚空背景。",
      tagEn="Cosmetic", titleEn="Void Silvermoon back cosmetic opens this week: take 'Tracking Salatrancer', collect 100 Faint Void Whispers (3 delves, or farm the Coiling Isles waters), turn in and combine 4 remnants", summaryEn="Right next to the quest spot in Silvermoon, Vereesa Windrunner gives 'Tracking Salatrancer': collect 100 Faint Void Whispers. Run 3 delves, or farm the waters of the Coiling Isles (~64 / 38); tip: eat the sulfur fish first and mobs get blinded automatically, much faster. Turn it in and combine 4 remnants for the void back cosmetic.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="银月城：右手边温蕾萨·风行者接「追踪萨拉塔斯」（收集 100 个微弱的虚空低语）", mapName="", mapIds={}, x=nil, y=nil, textEn="Silvermoon: Vereesa Windrunner on the right gives 'Tracking Salatrancer' (collect 100 Faint Void Whispers)", mapNameEn="" },
        { text="打 3 次地下堡，或去盘卷蛇岛这片水域刷怪（约 64 / 38）；先吃「硫磺鱼」，怪物自动被戳瞎双眼", mapName="盘卷蛇岛", mapIds={2512}, x=64, y=37.6, textEn="Run 3 delves, or farm the Coiling Isles waters (~64 / 38); eat the sulfur fish first so mobs get blinded", mapNameEn="Coiling Isles" },
        { text="交任务后用 4 个残渣合成 → 虚空银月城背景", mapName="", mapIds={}, x=nil, y=nil, textEn="Turn in, then combine 4 remnants → Void Silvermoon back cosmetic", mapNameEn="" },
      } },
    { id="w0923-nagtar-spores", period="week", tag="世界任务", title="奈格塔尔每 2 小时刷孢子世界任务：银月城 48 / 51 接「双决战」→ 右前方传送英雄难度 → 直走 7 步在蘑菇旁左右来回", summary="奈格塔尔（虚影风暴）每 2 小时刷一次孢子世界任务。银月城 48 / 51 接「双决战」，右前方传送门选英雄难度；进去直走 7 步，在蘑菇旁左右来回走就行。营地刷出额外世界任务时，直接跳下去到小河边。记得先交英雄箱子并打开，奖励多一倍；旁边 NPC 还能再来一遍。",
      tagEn="World Quest", titleEn="Nagtar spore world quest every 2 hours: take 'Double Showdown' at Silvermoon 48 / 51 → heroic portal ahead on the right → walk 7 steps and strafe beside the mushroom", summaryEn="Nagtar (Voidstorm) spawns a spore world quest every 2 hours. Take 'Double Showdown' at Silvermoon 48 / 51 and use the portal ahead on the right, heroic difficulty; walk 7 steps and strafe beside the mushroom. When the camp spawns an extra world quest, jump down to the stream. Turn in and open the heroic chest first for double rewards; the NPC next to it lets you go again.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="银月城 48 / 51 接「双决战」", mapName="银月城", mapIds={2393,2443}, x=48.2, y=51.5, textEn="Silvermoon 48 / 51: take 'Double Showdown'", mapNameEn="Silvermoon City" },
        { text="右前方传送（英雄难度）→ 直走 7 步，在蘑菇旁左右来回即可", mapName="", mapIds={}, x=nil, y=nil, textEn="Portal ahead on the right (heroic) → walk 7 steps, strafe back and forth beside the mushroom", mapNameEn="" },
        { text="营地刷出额外世界任务时，直接跳下去到小河边", mapName="", mapIds={}, x=nil, y=nil, textEn="When the camp spawns an extra world quest, jump down to the stream", mapNameEn="" },
        { text="先交英雄箱子并打开 = 奖励翻倍；旁边 NPC 还能再来一遍", mapName="", mapIds={}, x=nil, y=nil, textEn="Turn in and open the heroic chest first = double rewards; the NPC beside it lets you run it again", mapNameEn="" },
      } },
    { id="w0923-housing-weekly", period="week", tag="周常", title="家宅周常一分钟：接任务 → 点小眼睛一键加入队伍 → 右键团长头像「访问」→ 进屋立刻完成", summary="本周家宅周常很简单：接任务后点任务追踪上的小眼睛，一键加入别人的队伍；右键团长头像选「访问」，进他的屋子任务立刻完成，一分钟搞定。",
      tagEn="Weekly", titleEn="Housing weekly in one minute: take it → click the eye to join a group → right-click the leader's portrait, Visit → done as soon as you enter", summaryEn="This week's housing weekly is easy: after taking it, click the eye icon on the tracker to join a group; right-click the leader's portrait and choose Visit - the quest completes the moment you enter their house. One minute.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="接家宅周常 → 点任务追踪上的小眼睛，一键加入队伍", mapName="", mapIds={}, x=nil, y=nil, textEn="Take the housing weekly → click the eye icon on the tracker to join a group", mapNameEn="" },
        { text="右键团长头像选「访问」→ 进屋立刻完成", mapName="", mapIds={}, x=nil, y=nil, textEn="Right-click the leader's portrait, Visit → completes as you enter", mapNameEn="" },
      } },
    { id="w0923-raid-buff", period="week", tag="团本", title="进团本先跟最左侧 NPC 对话，领 2% Buff", summary="本周进团本别忘了先跟入口最左侧的 NPC 对话，领一个 2% 的 Buff。",
      tagEn="Raid", titleEn="In the raid, talk to the leftmost NPC first for a 2% buff", summaryEn="Before pulling in the raid this week, talk to the leftmost NPC at the entrance for a 2% buff.",
      fromDay="2026-09-23", untilDay="2026-09-29",
      steps={
        { text="团本入口：对话最左侧 NPC，领 2% Buff", mapName="", mapIds={}, x=nil, y=nil, textEn="Raid entrance: talk to the leftmost NPC for the 2% buff", mapNameEn="" },
      } },
    { id="w0922-hunt-double", period="day", tag="周常", title="追猎 6 倍今日双地图（限时返场）：追猎大厅传送 → 永歌森林 46 / 55 站几秒拉满 → 回大厅接第二站 虚影风暴 43 / 69", summary="今天追猎 6 倍开双地图，限时返场，本周少见。从追猎大厅直接传送：第一站永歌森林 46 / 55，站住几秒进度就满；开完格子回大厅接第二站虚影风暴 43 / 69，手快两秒搞定。两站都刷完再走。",
      tagEn="Weekly", titleEn="Hunts x6 today, two maps (limited-time return): teleport from the Hunt Hall → Eversong Woods 46 / 55, stand a few seconds → back to the hall for the second one, Voidstorm 43 / 69", summaryEn="Hunts x6 runs on two maps today, a rare limited-time return. Teleport from the Hunt Hall: first stop Eversong Woods 46 / 55, stand a few seconds and the bar fills; open the cache, return to the hall and take the second one, Voidstorm 43 / 69, done in two seconds if you're quick. Clear both before leaving.",
      fromDay="2026-09-22", untilDay="2026-09-22",
      steps={
        { text="追猎大厅传送 → 永歌森林 46 / 55，站住几秒进度拉满，开格子", mapName="永歌森林", mapIds={2395,2567}, x=46, y=55, textEn="Hunt Hall teleport → Eversong Woods 46 / 55, stand a few seconds to fill the bar, open the cache", mapNameEn="Eversong Woods" },
        { text="回追猎大厅接第二站 → 虚影风暴 43 / 69，两秒完成", mapName="虚影风暴", mapIds={2405,2479,2444,2397,2506}, x=43, y=69, textEn="Back to the Hunt Hall, take the second hunt → Voidstorm 43 / 69, done in two seconds", mapNameEn="Voidstorm" },
      } },
    { id="w0922-delve-atalaman", period="day", tag="地下堡", title="丰裕「阿塔阿曼」（永歌森林 60 / 81）：撞泡泡召青蛙 + 拿笛子，双 Buff 输出拉满；带小号，门口对话一键传送", summary="今日丰裕是阿塔阿曼。进去别忘拿笛子；地上的泡泡一定去撞，召出青蛙公主一群青蛙冰伤极高，两个 Buff 叠着输出拉满。带小号也方便，门口对话 NPC 一键传送去拿奖励。",
      tagEn="Delve", titleEn="Bountiful Atal'Aman (Eversong 60 / 81): pop the bubbles for frogs + grab the flute, two buffs for max damage; bring an alt, talk at the entrance for a one-click teleport", summaryEn="Today's Bountiful delve is Atal'Aman. Don't forget the flute on the way in; always pop the bubbles on the ground to summon the frog princess's swarm (huge frost damage) - with both buffs up you melt everything. Alts are easy too: talk to the NPC at the entrance for a one-click teleport to the rewards.",
      fromDay="2026-09-22", untilDay="2026-09-22",
      steps={
        { text="永歌森林 60 / 81（祖阿曼交界）进「阿塔阿曼」（今日丰裕）", mapName="永歌森林", mapIds={2395,2567}, x=60, y=81, textEn="Enter Atal'Aman at Eversong Woods 60 / 81 (Zul'Aman border), Bountiful today", mapNameEn="Eversong Woods" },
        { text="别忘拿笛子；地上的泡泡一定去撞 → 召青蛙群冰伤极高，双 Buff 输出拉满", mapName="", mapIds={}, x=nil, y=nil, textEn="Grab the flute; always pop the bubbles → frog swarm with huge frost damage, both buffs = max output", mapNameEn="" },
        { text="带小号：门口对话 NPC 一键传送去拿奖励", mapName="", mapIds={}, x=nil, y=nil, textEn="Alts: talk to the NPC at the entrance for a one-click teleport to the rewards", mapNameEn="" },
      } },
    { id="w0921-delve-collegiate", period="day", tag="地下堡", title="丰裕「学府骚动」（银月城 40.7 / 53.7）：追踪栏出现斧头「揭示伪装的暴光之刃」必打——用它激活伪装者就能直接尾王，路线超短", summary="今天丰裕的学府骚动非常好刷（宏伟宝库栏位直接升级）。追踪栏出现斧头图标「揭示伪装的暴光之刃」就必打：只激活几波怪就能直接尾王。冒绿光的 NPC 别碰；把另外 4 个 NPC 解救出来，他们帮打，躺赢。",
      tagEn="Delve", titleEn="Bountiful Collegiate Calamity (Silvermoon 40.7 / 53.7): when the axe item 'Exposing Blade' shows up, always take it - reveal the impostors and go straight to the last boss, super short route", summaryEn="Today's Bountiful Collegiate Calamity is a free Great Vault upgrade. When the axe icon 'Exposing Blade' appears in the tracker, always take it: only a few packs to activate, then straight to the last boss. Don't touch the green-glowing NPCs; free the other 4 and they carry the fight.",
      fromDay="2026-09-21", untilDay="2026-09-21",
      steps={
        { text="银月城 40.7 / 53.7 进「学府骚动」（今日丰裕）", mapName="银月城", mapIds={2393,2443,2525}, x=40.7, y=53.7, textEn="Enter Collegiate Calamity (Bountiful today) at Silvermoon 40.7 / 53.7", mapNameEn="Silvermoon City" },
        { text="追踪栏出斧头「揭示伪装的暴光之刃」必打：激活几波怪即可直接尾王", mapName="", mapIds={}, x=nil, y=nil, textEn="Take the axe item 'Exposing Blade' when it appears: activate a few packs and go straight to the last boss", mapNameEn="" },
        { text="冒绿光的 NPC 别碰；解救其他 4 个 NPC 帮打躺赢", mapName="", mapIds={}, x=nil, y=nil, textEn="Don't touch green-glowing NPCs; free the other 4 NPCs and let them fight for you", mapNameEn="" },
      } },
    { id="w0921-valeera-ring-of-glory", period="day", tag="速通", title="瓦娘最快升 80 故事线：「荣耀之环」（盘卷蛇岛东 约 44.2 / 22.6），珍玩选「钝顿的青睐」，配 SilverDragon 一键开图，小 boss 全部吃晕", summary="今天带瓦娘刷等级最快的是荣耀之环的故事线。瓦莉拉效能珍玩选「钝顿的青睐」（打错放的奇珍召迷途精魂，每下 6 个易爆精魂）；配合 SilverDragon 一键开图找目标。怪非常少，小 boss 全部可以吃晕，切记控住；带上「盐击者」一路前进即可。",
      tagEn="Speedrun", titleEn="Fastest Valeera-to-80 story line today: The Ring of Glory (east Coiled Isles ~44.2 / 22.6), pick the Dunmore's Favor trinket, use SilverDragon to reveal the map, every mini boss is stunnable", summaryEn="Fastest Valeera leveling today is the Ring of Glory story line. Pick Dunmore's Favor for Valeera's utility trinket (misplaced curios spawn lost spirits, 6 volatile spirits per hit); use SilverDragon to reveal objectives. Very few mobs and every mini boss can be stunned - keep them locked down and push forward with the Saltstriker.",
      fromDay="2026-09-21", untilDay="2026-09-21",
      steps={
        { text="荣耀之环入口：盘卷蛇岛东侧 约 44.2 / 22.6", mapName="盘卷蛇岛", mapIds={2512}, x=44.2, y=22.6, textEn="Ring of Glory entrance: east Coiled Isles, ~44.2 / 22.6", mapNameEn="Coiling Isles" },
        { text="瓦莉拉效能珍玩选「钝顿的青睐」；SilverDragon 一键开图", mapName="", mapIds={}, x=nil, y=nil, textEn="Valeera utility trinket: Dunmore's Favor; SilverDragon to reveal the map", mapNameEn="" },
        { text="怪非常少，小 boss 全部吃晕；带盐击者前进即可", mapName="", mapIds={}, x=nil, y=nil, textEn="Very few mobs, stun every mini boss; push forward with the Saltstriker", mapNameEn="" },
      } },
    { id="w0920-weekly-toy", period="day", tag="周常", title="三条周常原地完成：紫球边放「海象人冰钓帐」玩具，坐上无脑点球，进度一直涨（还能蹭别人的）", summary="「干扰敌方基地的行动」那三条周常（异界决战 / 虚空侵袭 / 地下堡任务板各一）不用跑图：在紫色虚空球旁边放下玩具「海象人冰钓帐」，坐进去点球，人不动进度无限涨；有人放了帐篷直接蹭，十秒搞定。别忘了先在银月城 49 / 65 的任务板把「地下堡」那条接上，三条一起完成。",
      tagEn="Weekly", titleEn="Three weeklies without moving: drop the Tuskarr Ice Fishing Tent toy beside the purple orb, sit and spam-click the orb - progress keeps ticking (or use someone else's tent)", summaryEn="The three 'disrupt the enemy base' weeklies (Otherworld / Void Incursion / Delve board) need no running: put the Tuskarr Ice Fishing Tent toy next to a purple void orb, sit in it and click the orb - progress keeps rising while you stand still; if someone already placed a tent just use it, ten seconds. Take the Delve weekly from the Silvermoon quest board at 49 / 65 first so all three complete together.",
      fromDay="2026-09-20", untilDay="2026-09-20",
      steps={
        { text="先在银月城任务板 49 / 65 接「地下堡」周常（和另外两条一起完成）", mapName="银月城", mapIds={2393,2443}, x=49, y=65, textEn="Take the Delve weekly from the Silvermoon quest board at 49 / 65 first (completes together with the other two)", mapNameEn="Silvermoon City" },
        { text="找一个紫色虚空球，旁边放下玩具「海象人冰钓帐」（1 小时冷却），坐进去无脑点球，进度自己涨；有别人的帐篷直接蹭", mapName="", mapIds={}, x=nil, y=nil, textEn="Find a purple void orb, drop the Tuskarr Ice Fishing Tent toy (1h cooldown) beside it, sit in and spam-click the orb - progress keeps ticking; someone else's tent works too", mapNameEn="" },
      } },
    { id="w0917-timewalking", period="week", tag="时光漫游", title="本周大灾变时光漫游：每号 5 分钟一把，周常摸勇士 / 英雄轨道装", summary="4.0 时光漫游周，随机本极快；银月城 48 / 64 找大法师艾萨斯·逐日者接周常「穿越时光的翱翔之路」，打满 5 把交任务开「奎尔萨拉斯宝藏」——勇士或英雄轨道一件（S2 勇士 295–308 · 英雄 308–321），小号一起过一遍。",
      tagEn="Timewalking", titleEn="Cataclysm Timewalking this week: ~5 minutes per run, weekly gives a Champion / Hero track piece", summaryEn="Cataclysm Timewalking week, random dungeons are very fast. In Silvermoon (48 / 64) talk to Archmage Aethas Sunreaver for the weekly \"A Timely Flight Through Time\"; after 5 runs turn it in for the Cache of Quel'Thalas treasures — one Champion or Hero track piece (S2 Champion 295–308 · Hero 308–321). Run alts through too.",
      fromDay="2026-09-17", untilDay="2026-09-22",
      steps={
        { text="银月城 48 / 64 找大法师艾萨斯·逐日者，接周常「穿越时光的翱翔之路」", mapName="银月城", mapIds={2393,2443}, x=48, y=64, textEn="Silvermoon 48 / 64: talk to Archmage Aethas Sunreaver and take the weekly \"A Timely Flight Through Time\"", mapNameEn="Silvermoon City" },
        { text="随机时光漫游本 ×5（每把约 5 分钟）", mapName="", mapIds={}, x=nil, y=nil, textEn="Random Timewalking dungeon ×5 (about 5 minutes each)", mapNameEn="" },
        { text="回 48 / 64 交任务，开箱 = 勇士轨道 295–308 或英雄轨道 308–321 一件（按拾取专精）", mapName="银月城", mapIds={2393,2443}, x=48, y=64, textEn="Return to 48 / 64, turn in, open the cache = one Champion track 295–308 or Hero track 308–321 piece (by loot spec)", mapNameEn="Silvermoon City" },
      } },
  },
  sources={
    { platform="B站", author="魔兽阿落", title="本周限时福利 符文石超级新巅峰白送 超简单每号灰岩货币全部直接领 每日地下堡逃课推荐见置顶", url="https://www.bilibili.com/video/BV1KYaD6vEFc/", date="2026-10-03" },
    { platform="B站", author="会圣盾术的打工人", title="10月3日逃课指南！荣耀之环领养大会！阿塔阿曼蛙全不同！", url="https://www.bilibili.com/video/BV1f2aD6REgg/", date="2026-10-03" },
    { platform="B站", author="祢豆子小七", title="魔兽世界10.3丰裕地下堡，豪华逃课快出去，一路爽刷，每日地下堡狩猎逃课推荐", url="https://www.bilibili.com/video/BV1KQHh6sELx/", date="2026-10-03" },
    { platform="Wowprimer", author="Wowprimer", title="Twilight Crypts Delve Guide（south-western curve of Zul'Aman, small cave）", url="https://wowprimer.com/twilight-crypts-delve-guide", date="2026-10-03" },
    { platform="B站", author="魔兽阿落", title="蛇怪闪击猎人特殊驯服刷新 超级芳糖三福利 丰裕急速通关 每日地下堡狩猎逃课推荐", url="https://www.bilibili.com/video/BV1M1a46uExo/", date="2026-09-27" },
    { platform="抖音", author="遗忘的檰糀餹", title="本周福利双芳糖 超级6倍刷新 战龟全秒丰裕爽刷 笛子白送英雄", url="https://v.douyin.com/mGZgOiMVWks/", date="2026-09-26" },
    { platform="B站", author="魔兽阿落", title="超级中秋芳糖3秒吃完 丰裕S级速刷 每日地下堡狩猎逃课推荐9.25中秋快乐~", url="https://www.bilibili.com/video/BV1wWaM6rE3e/", date="2026-09-25" },
    { platform="视频号", author="魔兽阿落", title="超级中秋芳糖3秒吃完 丰裕S级速刷", url="https://weixin.qq.com/sph/A1tQKm0kvC", date="2026-09-25" },
    { platform="B站", author="魔兽阿落", title="小号随时开启芳糖镜 本周指南保姆全路线 周常快速完成 虚空银月城背景", url="https://www.bilibili.com/video/BV1qwhb6pEsH/", date="2026-09-23" },
    { platform="视频号", author="魔兽阿落", title="本周指南 小号随时开启芳糖镜 周常快速完成 虚空银月城背景", url="https://weixin.qq.com/sph/Atcjgy23hZ", date="2026-09-23" },
    { platform="B站", author="魔兽阿落", title="超级福利双芳糖 本周罕见狩猎新地图 永歌风暴丰裕刷爆限时返场 每日地下堡狩猎逃课推荐", url="https://www.bilibili.com/video/BV1JBh66tEAT/", date="2026-09-22" },
    { platform="B站", author="魔兽阿落", title="超级弹簧符文 无限大跳玩具 丰裕爽刷白送 瓦娘80最快满级 每日地下堡逃课推荐", url="https://www.bilibili.com/video/BV1Cchv67Esa/", date="2026-09-21" },
    { platform="Icy Veins", author="Icy Veins", title="The Ring of Glory Delve Guide（east Coiled Isle ~44.15/22.60）", url="https://www.icy-veins.com/wow/the-ring-of-glory-delve-guide", date="2026-09-21" },
    { platform="Wowhead", author="Wowhead", title="Delves in Midnight - Locations（Collegiate Calamity 40.6/53.7）", url="https://www.wowhead.com/guide/midnight/delves-season-companion-nemesis-rewards-locations", date="2026-09-17" },
    { platform="Icy Veins", author="Icy Veins", title="Atal'Aman Delve Guide（west Zul'Aman, Eversong border）", url="https://www.icy-veins.com/wow/atal-aman-delve-guide", date="2026-09-19" },
  } }
