-- 由 build_enchant_names_lua.py 生成，⛔别手改。附魔 id → 各语言名（去掉部位前缀）。
GearInsight = GearInsight or {}
GearInsight.EnchantNames = {
    [1704] = { deDE = "Thoriumstachel", enUS = "Thorium Spike", esES = "Punta de torio", frFR = "Pointe en thorium", itIT = "Chiodatura di Torio", koKR = "토륨 쐐기", ptBR = "Espigão de Tório", ruRU = "Ториевый шип", zhCN = "瑟银盾刺", zhTW = "瑟銀盾刺" },
    [2603] = { deDE = "Angeln", enUS = "Fishing", esES = "pesca", frFR = "en Pêche", itIT = "Pesca", koKR = "낚시 숙련도", ptBR = "de Pesca", ruRU = "к навыку рыбной ловли", zhCN = "钓鱼", zhTW = "釣魚" },
    [2841] = { deDE = "Ausdauer", enUS = "Stamina", esES = "aguante", frFR = "à l’Endurance", itIT = "Tempra", koKR = "체력", ptBR = "de Vigor", ruRU = "к выносливости", zhCN = "耐力", zhTW = "耐力" },
    [3238] = { deDE = "Sammler", enUS = "Gatherer", esES = "Recolector", frFR = "Récolteur", itIT = "Raccolta", koKR = "채집가", ptBR = "Coletador", ruRU = "Собиратель", zhCN = "采集", zhTW = "採集者" },
    [3368] = { deDE = "Rune des gefallenen Kreuzfahrers", enUS = "Rune of the Fallen Crusader", esES = "Runa del cruzado caído", frFR = "Rune du Croisé déchu", itIT = "Runa del Crociato Caduto", koKR = "타락한 성전사의 룬", ptBR = "Runa do Cruzado Caído", ruRU = "Руна павшего рыцаря", zhCN = "堕落十字军符文", zhTW = "墮落十字軍符文" },
    [3847] = { deDE = "Rune des Steinhautgargoyles", enUS = "Rune of the Stoneskin Gargoyle", esES = "Runa de la gárgola piel de piedra", frFR = "Rune de la gargouille peau de pierre", itIT = "Runa del Gargoyle Pellepietrosa", koKR = "돌가죽 가고일의 룬", ptBR = "Runa da Gárgula Litopele", ruRU = "Руна каменной горгульи", zhCN = "岩肤石像鬼符文", zhTW = "石膚石像鬼符文" },
    [4216] = { deDE = "Pyriumstachel", enUS = "Pyrium Spike", esES = "Punta de pirium", frFR = "Pointe en pyrium", itIT = "Chiodatura di Pirio", koKR = "황철 쐐기", ptBR = "Espigão de Pírio", ruRU = "Колчедановый шип", zhCN = "燃钢盾刺", zhTW = "黃鐵盾刺" },
    [5447] = { deDE = "Vermessung der Verheerten Inseln", enUS = "Legion Surveying", esES = "Topografía de Legion", frFR = "Levé de la Légion", itIT = "Rilevamento di Legion", koKR = "군단 조사", ptBR = "Sondagem de Legion", ruRU = "Археология Legion", zhCN = "军团勘测", zhTW = "軍團勘察" },
    [5932] = { deDE = "Kräuterkunde von Kul Tiras", enUS = "Kul Tiran Herbalism", esES = "Herboristería de Kul Tiras", frFR = "Herboristerie de Kul Tiras", itIT = "Erbalismo di Kul Tiras", koKR = "쿨 티란 약초채집", ptBR = "Herborismo de Kul Tiraz", ruRU = "Кул-тирасское травничество", zhCN = "库尔提拉斯草药学", zhTW = "庫爾提拉斯草藥學" },
    [5935] = { deDE = "Vermessung von Kul Tiras", enUS = "Kul Tiran Surveying", esES = "Topografía de Kul Tiras", frFR = "Archéologie de Kul Tiras", itIT = "Rilevamento di Kul Tiras", koKR = "쿨 티란 조사", ptBR = "Sondagem de Kul Tiraz", ruRU = "Кул-тирасская археология", zhCN = "库尔提拉斯勘测", zhTW = "庫爾提拉斯勘察" },
    [5937] = { deDE = "Handwerkskunst von Kul Tiras", enUS = "Kul Tiran Crafting", esES = "Artesanía de Kul Tiras", frFR = "Artisanat de Kul Tiras", itIT = "Artigianato di Kul Tiras", koKR = "쿨 티란 제작", ptBR = "Criação de Kul Tiraz", ruRU = "Кул-тирасское ремесло", zhCN = "库尔提拉斯工艺", zhTW = "庫爾提拉斯製作" },
    [6205] = { deDE = "Sammeln der Schattenlande", enUS = "Shadowlands Gathering", esES = "Recolección de las Tierras Sombrías", frFR = "Récolte d’Ombreterre", itIT = "Raccolta di Shadowlands", koKR = "어둠땅 채집", ptBR = "Coleta nas Terras Sombrias", ruRU = "Сбор ресурсов в Темных Землях", zhCN = "暗影界采集", zhTW = "暗影之境採集" },
    [6241] = { deDE = "Rune der Sanguination", enUS = "Rune of Sanguination", esES = "Runa de desangramiento", frFR = "Rune d’exsanguination", itIT = "Runa del Dissanguamento", koKR = "혈기의 룬", ptBR = "Runa da Sangradura", ruRU = "Руна полнокровия", zhCN = "鲜红符文", zhTW = "淌血符文" },
    [6245] = { deDE = "Rune der Apokalypse", enUS = "Rune of the Apocalypse", esES = "Runa del Apocalipsis", frFR = "Rune de l’apocalypse", itIT = "Runa dell'Apocalisse", koKR = "대재앙의 룬", ptBR = "Runa do Apocalipse", ruRU = "Руна апокалипсиса", zhCN = "天启符文", zhTW = "天啟符文" },
    [7935] = { deDE = "Intelligenz und Ausdauer", enUS = "Intellect & Stamina", esES = "p. de intelecto y p. de aguante", frFR = "à l’intelligence et à l’endurance", itIT = "Intelletto e Tempra", koKR = "지능 / 체력", ptBR = "de Intelecto e de Vigor", ruRU = "к интеллекту и к выносливости", zhCN = "智力和耐力", zhTW = "點智力和點耐力" },
    [7937] = { deDE = "Intelligenz und Mana", enUS = "Intellect & Mana", esES = "p. de intelecto y de maná", frFR = "à l’intelligence et % de mana", itIT = "Intelletto e Mana", koKR = "지능 / 마나", ptBR = "de Intelecto e de Mana", ruRU = "к интеллекту и маны", zhCN = "智力和法力值", zhTW = "點智力和法力" },
    [7957] = { deDE = "Zeichen von Nalorakk", enUS = "Mark of Nalorakk", esES = "Marca de Nalorakk", frFR = "marque de Nalorakk", itIT = "Marchio di Nalorakk", koKR = "날로라크의 징표", ptBR = "Torso", ruRU = "метка Налоракка", zhCN = "纳洛拉克印记", zhTW = "納羅拉克印記" },
    [7959] = { enUS = "Hex of Leeching", zhCN = "吸血妖术", zhTW = "汲取妖術", deDE = "Lebensraubzauber", frFR = "maléfice de sangsue", esES = "Maleficio de parasitismo", itIT = "Maleficio dell'Assorbimento", koKR = "생기흡수의 사술", ptBR = "Elmo", ruRU = "сглаз самоисцеления" },
    [7961] = { deDE = "Ermächtigter Lebensraubzauber", enUS = "Empowered Hex of Leeching", esES = "Maleficio de parasitismo potenciado", frFR = "maléfice de sangsue renforcé", itIT = "Maleficio dell'Assorbimento Potenziato", koKR = "강화된 생기흡수의 사술", ptBR = "Encantamento de Bagata Sorvedora Potencializada - Elmo", ruRU = "усиленный сглаз самоисцеления", zhCN = "强化吸血妖术", zhTW = "強化汲取妖術" },
    [7963] = { deDE = "Gewandtheit des Luchses", enUS = "Lynx's Dexterity", esES = "Destreza de lince", frFR = "dextérité du lynx", itIT = "Destrezza della Lince", koKR = "스라소니의 기민함", ptBR = "Botas", ruRU = "рысья стремительность", zhCN = "山猫之敏", zhTW = "山貓迅敏" },
    [7965] = { enUS = "Amani Mastery", zhCN = "阿曼尼精通", zhTW = "阿曼尼精通", deDE = "Amanimeisterschaft", frFR = "maîtrise amani", esES = "Maestría Amani", itIT = "Maestria degli Amani", koKR = "아마니의 특화", ptBR = "Anel", ruRU = "аманийская искусность" },
    [7967] = { deDE = "Augen des Adlers", enUS = "Eyes of the Eagle", esES = "Ojos del águila", frFR = "yeux de l’aigle", itIT = "Occhi dell'Aquila", koKR = "독수리의 눈", ptBR = "Anel", ruRU = "глаза орла", zhCN = "鹰眼神视", zhTW = "老鷹之眼" },
    [7969] = { deDE = "Zul'jins Meisterschaft", enUS = "Zul'jin's Mastery", esES = "Maestría de Zul'jin", frFR = "maîtrise de Zul’jin", itIT = "Maestria di Zul'jin", koKR = "줄진의 특화", ptBR = "Anel", ruRU = "искусность Зул'джина", zhCN = "祖尔金的精通", zhTW = "祖爾金精通" },
    [7971] = { enUS = "Flight of the Eagle", zhCN = "鹰翔长空", zhTW = "老鷹之翔", deDE = "Flug des Adlers", frFR = "Vol de l’aigle", esES = "Vuelo del águila", itIT = "Volo dell'Aquila", koKR = "독수리의 비행", ptBR = "Ombros", ruRU = "полет орла" },
    [7972] = { enUS = "Akil'zon's Swiftness", zhCN = "埃基尔松的迅捷", zhTW = "阿奇爾森的迅捷", deDE = "Akil'zons Schnelligkeit", frFR = "Rapidité d’Akil’zon", esES = "Presteza de Akil'zon", itIT = "Rapidità di Akil'zon", koKR = "아킬존의 신속함", ptBR = "Ombros", ruRU = "стремительность Акил'зон" },
    [7973] = { deDE = "Akil'zons Schnelligkeit", enUS = "Akil'zon's Swiftness", esES = "Presteza de Akil'zon", frFR = "Rapidité d’Akil’zon", itIT = "Rapidità di Akil'zon", koKR = "아킬존의 신속함", ptBR = "Ombros", ruRU = "стремительность Акил'зон", zhCN = "埃基尔松的迅捷", zhTW = "阿奇爾森的迅捷" },
    [7981] = { deDE = "Jan'alais Präzision", enUS = "Jan'alai's Precision", esES = "Precisión de Jan'alai", frFR = "précision de Jan’alai", itIT = "Precisione di Jan'alai", koKR = "잔알라이의 정밀함", ptBR = "Arma", ruRU = "точность Джан'алай", zhCN = "加亚莱的精准", zhTW = "賈納雷的精準" },
    [7983] = { deDE = "Berserkerwut", enUS = "Berserker's Rage", esES = "Ira de rabioso", frFR = "rage du berserker", itIT = "Rabbia del Berserker", koKR = "광전사의 분노", ptBR = "Arma", ruRU = "ярость берсерка", zhCN = "狂战士之怒", zhTW = "狂戰士之怒" },
    [7984] = { enUS = "Mark of the Rootwarden", zhCN = "护根者印记", zhTW = "根莖守望者印記", deDE = "Zeichen des Wurzelhüters", frFR = "marque de garde-racines", esES = "Marca del celador de raíces", itIT = "Marchio del Guardaradici", koKR = "뿌리감시관의 징표", ptBR = "Torso", ruRU = "метка корнестража" },
    [7985] = { enUS = "Mark of the Rootwarden", zhCN = "护根者印记", zhTW = "根莖守望者印記", deDE = "Zeichen des Wurzelhüters", frFR = "marque de garde-racines", esES = "Marca del celador de raíces", itIT = "Marchio del Guardaradici", koKR = "뿌리감시관의 징표", ptBR = "Torso", ruRU = "метка корнестража" },
    [7987] = { deDE = "Zeichen der Weltenseele", enUS = "Mark of the Worldsoul", esES = "Marca del alma-mundo", frFR = "marque de l’Âme-monde", itIT = "Marchio dell'Anima del Mondo", koKR = "세계혼의 징표", ptBR = "Torso", ruRU = "метка души мира", zhCN = "世界之魂印记", zhTW = "世界之魂印記" },
    [7989] = { enUS = "Blessing of Speed", zhCN = "加速祝福", zhTW = "速度祝福", deDE = "Segen der Geschwindigkeit", frFR = "bénédiction de vitesse", esES = "Bendición de velocidad", itIT = "Benedizione della Velocità", koKR = "속도의 축복", ptBR = "Elmo", ruRU = "благословение скорости" },
    [7991] = { deDE = "Ermächtigter Segen der Geschwindigkeit", enUS = "Empowered Blessing of Speed", esES = "Bendición de velocidad potenciada", frFR = "bénédiction de vitesse renforcée", itIT = "Benedizione della Velocità Potenziata", koKR = "강화된 속도의 축복", ptBR = "Encantamento da Bênção da Velocidade Potencializada - Elmo", ruRU = "усиленное благословение скорости", zhCN = "强化加速祝福", zhTW = "強化速度祝福" },
    [7993] = { deDE = "Shaladrassils Wurzeln", enUS = "Shaladrassil's Roots", esES = "Raíces de Shaladrassil", frFR = "racines de Shaladrassil", itIT = "Radici di Shaladrassil", koKR = "샬라드라실의 뿌리", ptBR = "Botas", ruRU = "корни Шаладрассила", zhCN = "莎拉达希尔之根", zhTW = "夏達希爾之根" },
    [7997] = { deDE = "Furor der Natur", enUS = "Nature's Fury", esES = "Furia de la Naturaleza", frFR = "fureur de la nature", itIT = "Furia della Natura", koKR = "자연의 격노", ptBR = "Anel", ruRU = "гнев природы", zhCN = "自然之怒", zhTW = "自然之怒" },
    [8001] = { deDE = "Amirdrassils Anmut", enUS = "Amirdrassil's Grace", esES = "Gracia de Amirdrassil", frFR = "grâce d’Amirdrassil", itIT = "Grazia di Amirdrassil", koKR = "아미드랏실의 은혜", ptBR = "Ombros", ruRU = "милость Амирдрассила", zhCN = "阿梅达希尔之赐", zhTW = "埃達希爾之賜" },
    [8011] = { enUS = "Worldsoul Tenacity", zhCN = "世界之魂的坚韧", zhTW = "世界之魂堅毅", deDE = "Weltenseelenhartnäckigkeit", frFR = "ténacité d’Âme-monde", esES = "Tenacidad del alma-mundo", itIT = "Tenacia dell'Anima del Mondo", koKR = "세계혼의 끈기", ptBR = "Encantamento de Tenacidade da Alma do Mundo - Arma", ruRU = "упорство души мира" },
    [8013] = { deDE = "Mal des Magisters", enUS = "Mark of the Magister", esES = "Marca del magister", frFR = "marque de magistère", itIT = "Marchio del Magistro", koKR = "마법학자의 징표", ptBR = "Torso", ruRU = "метка магистра", zhCN = "魔导师印记", zhTW = "博學者印記" },
    [8017] = { deDE = "Ermächtigte Rune der Vermeidung", enUS = "Empowered Rune of Avoidance", esES = "Runa de evasión potenciada", frFR = "rune d’évitement renforcée", itIT = "Runa dell'Elusione Potenziata", koKR = "강화된 광역회피의 룬", ptBR = "Encantamento da Runa da Evasão Potencializada - Elmo", ruRU = "усиленная руна избежания", zhCN = "强化闪避符文", zhTW = "強化迴避符文" },
    [8018] = { enUS = "Farstrider's Hunt", zhCN = "远行者的狩猎", zhTW = "遠行者之狩", deDE = "Jagd des Weltenwanderers", frFR = "chasse de pérégrin", esES = "Cacería de errante", itIT = "Caccia dei Lungopasso", koKR = "원정순찰대의 추적", ptBR = "Botas", ruRU = "охота Странника" },
    [8019] = { deDE = "Jagd des Weltenwanderers", enUS = "Farstrider's Hunt", esES = "Cacería de errante", frFR = "chasse de pérégrin", itIT = "Caccia dei Lungopasso", koKR = "원정순찰대의 추적", ptBR = "Botas", ruRU = "охота Странника", zhCN = "远行者的狩猎", zhTW = "遠行者之狩" },
    [8025] = { deDE = "Inbrunst von Silbermond", enUS = "Silvermoon's Alacrity", esES = "Prontitud de Lunargenta", frFR = "empressement de Lune-d’Argent", itIT = "Alacrità di Lunargenta", koKR = "실버문의 기민함", ptBR = "Anel", ruRU = "луносветская расторопность", zhCN = "银月城之捷", zhTW = "銀月城的矯捷" },
    [8027] = { deDE = "Hartnäckigkeit von Silbermond", enUS = "Silvermoon's Tenacity", esES = "Tenacidad de Lunargenta", frFR = "ténacité de Lune-d’Argent", itIT = "Tenacia di Lunargenta", koKR = "실버문의 끈기", ptBR = "Anel", ruRU = "луносветское упорство", zhCN = "银月城之韧", zhTW = "銀月城的堅毅" },
    [8031] = { deDE = "Heilung von Silbermond", enUS = "Silvermoon's Mending", esES = "Alivio de Lunargenta", frFR = "Guérison de Lune-d’Argent", itIT = "Guarigione di Lunargenta", koKR = "실버문의 치유", ptBR = "Ombros", ruRU = "луносветское исцеление", zhCN = "银月城治愈", zhTW = "銀月城的癒合" },
    [8038] = { enUS = "Acuity of the Ren'dorei", zhCN = "朗多雷之锐", zhTW = "刃多雷的敏銳", deDE = "Scharfsinn der Ren'dorei", frFR = "acuité des Ren’dorei", esES = "Agudeza de los ren'dorei", itIT = "Acutezza dei Ren'dorei", koKR = "렌도레이의 명민함", ptBR = "Arma", ruRU = "проницательность рен'дорай" },
    [8039] = { deDE = "Scharfsinn der Ren'dorei", enUS = "Acuity of the Ren'dorei", esES = "Agudeza de los ren'dorei", frFR = "acuité des Ren’dorei", itIT = "Acutezza dei Ren'dorei", koKR = "렌도레이의 명민함", ptBR = "Arma", ruRU = "проницательность рен'дорай", zhCN = "朗多雷之锐", zhTW = "刃多雷的敏銳" },
    [8041] = { deDE = "Arkane Meisterschaft", enUS = "Arcane Mastery", esES = "Maestría Arcana", frFR = "maîtrise des arcanes", itIT = "Maestria Arcana", koKR = "비전 숙련", ptBR = "Arma", ruRU = "чародейская искусность", zhCN = "奥术精通", zhTW = "秘法專精" },
    [8159] = { deDE = "Beweglichkeit/Stärke und Ausdauer", enUS = "Agility/Strength & Stamina", esES = "p. de agilidad/fuerza y p. de aguante", frFR = "à l’agilité/force et à l’endurance", itIT = "Agilità/Forza e Tempra", koKR = "민첩성/힘 / 체력", ptBR = "de Agilidade/Força e de Vigor", ruRU = "к ловкости/силе и к выносливости", zhCN = "敏捷/力量 & 耐力", zhTW = "點敏捷/力量和點耐力" },
    [8163] = { deDE = "Beweglichkeit/Stärke und Rüstung", enUS = "Agility/Strength & Armor", esES = "p. de agilidad/fuerza y p. de armadura", frFR = "à l’agilité/force et à l’armure", itIT = "Agilità/Forza e Armatura", koKR = "민첩성/힘 / 방어도", ptBR = "de Agilidade/Força e de Armadura", ruRU = "к ловкости/силе и к броне", zhCN = "敏捷/力量和护甲", zhTW = "點敏捷/力量和點護甲值" },
    [8689] = { deDE = "Ritual der Hash'ey", enUS = "Rite of the Hash'ey", esES = "Ritual del hash'ey", frFR = "Rite des hash’ey", itIT = "Rito degli Hash'ey", koKR = "하셰이의 의례", ptBR = "Rito dos Hash'ey", ruRU = "Обряд хаш'эй", zhCN = "哈谢仪式", zhTW = "哈謝之儀" },
}

-- 取当前客户端语言的附魔名：zhCN 优先烤制的 nameCn（口径最熟），其它语言查表，再退到配方物品名，再退 nameCn。
function GearInsight.EnchName(e, fallback)
    if not e then return fallback or "" end
    local loc = GearInsight.LOCALE or (GetLocale and GetLocale()) or "enUS"
    if loc == "esMX" then loc = "esES" elseif loc == "enGB" then loc = "enUS" end
    if loc == "zhCN" and e.nameCn and e.nameCn ~= "" then return e.nameCn end
    local t = e.id and GearInsight.EnchantNames[e.id]
    if t then
        local n = t[loc] or t.enUS
        if n and n ~= "" then return n end
    end
    if e.item and C_Item and C_Item.GetItemNameByID then
        local n = C_Item.GetItemNameByID(e.item)
        if n and n ~= "" then return n end
    end
    if e.nameCn and e.nameCn ~= "" then return e.nameCn end
    return fallback or ""
end
