-- 由 build_enchant_names_lua.py 生成，⛔别手改。附魔 id → 各语言名（去掉部位前缀）。
GearInsight = GearInsight or {}
GearInsight.EnchantNames = {
    [844] = { deDE = "+Bergbau", esES = "+minería", frFR = "+Minage", itIT = "+Estrazione", koKR = "채광 +", ptBR = "+de Mineração", ruRU = "+к навыку горного дела", zhCN = "+采矿", zhTW = "+採礦" },
    [1704] = { deDE = "Thoriumstachel", esES = "Punta de torio", frFR = "Pointe en thorium", itIT = "Chiodatura di Torio", koKR = "토륨 쐐기", ptBR = "Espigão de Tório", ruRU = "Ториевый шип", zhCN = "瑟银盾刺", zhTW = "瑟銀盾刺" },
    [2603] = { deDE = "+2 Angeln", esES = "+2 pesca", frFR = "+2 en Pêche", itIT = "+2 Pesca", koKR = "낚시 숙련도 +2", ptBR = "+2 de Pesca", ruRU = "+2 к навыку рыбной ловли", zhCN = "+2 钓鱼", zhTW = "+2釣魚", enUS = "+2 Fishing" },
    [2841] = { deDE = "+3 Ausdauer", esES = "+3 aguante", frFR = "+3 à l’Endurance", itIT = "+3 Tempra", koKR = "체력 +3", ptBR = "+3 de Vigor", ruRU = "+3 к выносливости", zhCN = "+3 耐力", zhTW = "+3耐力", enUS = "+3 Stamina" },
    [3238] = { deDE = "Sammler", esES = "Recolector", frFR = "Récolteur", itIT = "Raccolta", koKR = "채집가", ptBR = "Coletador", ruRU = "Собиратель", zhCN = "采集", zhTW = "採集者" },
    [3368] = { deDE = "Rune des gefallenen Kreuzfahrers", esES = "Runa del cruzado caído", frFR = "Rune du Croisé déchu", itIT = "Runa del Crociato Caduto", koKR = "타락한 성전사의 룬", ptBR = "Runa do Cruzado Caído", ruRU = "Руна павшего рыцаря", zhCN = "堕落十字军符文", zhTW = "墮落十字軍符文" },
    [3847] = { deDE = "Rune des Steinhautgargoyles", esES = "Runa de la gárgola piel de piedra", frFR = "Rune de la gargouille peau de pierre", itIT = "Runa del Gargoyle Pellepietrosa", koKR = "돌가죽 가고일의 룬", ptBR = "Runa da Gárgula Litopele", ruRU = "Руна каменной горгульи", zhCN = "岩肤石像鬼符文", zhTW = "石膚石像鬼符文" },
    [4216] = { deDE = "Pyriumstachel", esES = "Punta de pirium", frFR = "Pointe en pyrium", itIT = "Chiodatura di Pirio", koKR = "황철 쐐기", ptBR = "Espigão de Pírio", ruRU = "Колчедановый шип", zhCN = "燃钢盾刺", zhTW = "黃鐵盾刺" },
    [5447] = { deDE = "Vermessung der Verheerten Inseln", esES = "Topografía de Legion", frFR = "Levé de la Légion", itIT = "Rilevamento di Legion", koKR = "군단 조사", ptBR = "Sondagem de Legion", ruRU = "Археология Legion", zhCN = "军团勘测", zhTW = "軍團勘察" },
    [5932] = { deDE = "Kräuterkunde von Kul Tiras", esES = "Herboristería de Kul Tiras", frFR = "Herboristerie de Kul Tiras", itIT = "Erbalismo di Kul Tiras", koKR = "쿨 티란 약초채집", ptBR = "Herborismo de Kul Tiraz", ruRU = "Кул-тирасское травничество", zhCN = "库尔提拉斯草药学", zhTW = "庫爾提拉斯草藥學" },
    [5933] = { deDE = "Bergbau von Kul Tiras", esES = "Minería de Kul Tiras", frFR = "Minage de Kul Tiras", itIT = "Estrazione di Kul Tiras", koKR = "쿨 티란 채광", ptBR = "Mineração de Kul Tiraz", ruRU = "Кул-тирасское горное дело", zhCN = "库尔提拉斯采矿", zhTW = "庫爾提拉斯採礦" },
    [5935] = { deDE = "Vermessung von Kul Tiras", esES = "Topografía de Kul Tiras", frFR = "Archéologie de Kul Tiras", itIT = "Rilevamento di Kul Tiras", koKR = "쿨 티란 조사", ptBR = "Sondagem de Kul Tiraz", ruRU = "Кул-тирасская археология", zhCN = "库尔提拉斯勘测", zhTW = "庫爾提拉斯勘察" },
    [5937] = { deDE = "Handwerkskunst von Kul Tiras", esES = "Artesanía de Kul Tiras", frFR = "Artisanat de Kul Tiras", itIT = "Artigianato di Kul Tiras", koKR = "쿨 티란 제작", ptBR = "Criação de Kul Tiraz", ruRU = "Кул-тирасское ремесло", zhCN = "库尔提拉斯工艺", zhTW = "庫爾提拉斯製作" },
    [6205] = { deDE = "Sammeln der Schattenlande", esES = "Recolección de las Tierras Sombrías", frFR = "Récolte d’Ombreterre", itIT = "Raccolta di Shadowlands", koKR = "어둠땅 채집", ptBR = "Coleta nas Terras Sombrias", ruRU = "Сбор ресурсов в Темных Землях", zhCN = "暗影界采集", zhTW = "暗影之境採集" },
    [6241] = { deDE = "Rune der Sanguination", esES = "Runa de desangramiento", frFR = "Rune d’exsanguination", itIT = "Runa del Dissanguamento", koKR = "혈기의 룬", ptBR = "Runa da Sangradura", ruRU = "Руна полнокровия", zhCN = "鲜红符文", zhTW = "淌血符文" },
    [6245] = { deDE = "Rune der Apokalypse", esES = "Runa del Apocalipsis", frFR = "Rune de l’apocalypse", itIT = "Runa dell'Apocalisse", koKR = "대재앙의 룬", ptBR = "Runa do Apocalipse", ruRU = "Руна апокалипсиса", zhCN = "天启符文", zhTW = "天啟符文" },
    [7935] = { deDE = "+41 Intelligenz und +115 Ausdauer", esES = "+41 p. de intelecto y +115 p. de aguante", frFR = "+41 à l’intelligence et +115 à l’endurance", itIT = "+41 Intelletto e +115 Tempra", koKR = "지능 +41 / 체력 +115", ptBR = "+41 de Intelecto e +115 de Vigor", ruRU = "+41 к интеллекту и +115 к выносливости", zhCN = "+41 智力和+115 耐力", zhTW = "+41點智力和+115點耐力", enUS = "+41 Intellect & +115 Stamina" },
    [7937] = { deDE = "+41 Intelligenz und +4% Mana", esES = "+41 p. de intelecto y +4% de maná", frFR = "+41 à l’intelligence et +4 % de mana", itIT = "+41 Intelletto e +4% Mana", koKR = "지능 +41 / 마나 +4%", ptBR = "+41 de Intelecto e +4% de Mana", ruRU = "+41 к интеллекту и +4% маны", zhCN = "+41 智力和+4% 法力值", zhTW = "+41點智力和+4%法力", enUS = "+41 Intellect & +4% Mana" },
    [7957] = { deDE = "Zeichen von Nalorakk", esES = "Marca de Nalorakk", frFR = "marque de Nalorakk", itIT = "Marchio di Nalorakk", koKR = "날로라크의 징표", ptBR = "Torso", ruRU = "метка Налоракка", zhCN = "纳洛拉克印记", zhTW = "納羅拉克印記" },
    [7959] = { enUS = "Hex of Leeching", zhCN = "吸血妖术", zhTW = "汲取妖術", deDE = "Lebensraubzauber", frFR = "maléfice de sangsue", esES = "Maleficio de parasitismo", itIT = "Maleficio dell'Assorbimento", koKR = "생기흡수의 사술", ptBR = "Elmo", ruRU = "сглаз самоисцеления" },
    [7961] = { deDE = "Ermächtigter Lebensraubzauber", esES = "Maleficio de parasitismo potenciado", frFR = "maléfice de sangsue renforcé", itIT = "Maleficio dell'Assorbimento Potenziato", koKR = "강화된 생기흡수의 사술", ptBR = "Encantamento de Bagata Sorvedora Potencializada - Elmo", ruRU = "усиленный сглаз самоисцеления", zhCN = "强化吸血妖术", zhTW = "強化汲取妖術" },
    [7963] = { deDE = "Gewandtheit des Luchses", esES = "Destreza de lince", frFR = "dextérité du lynx", itIT = "Destrezza della Lince", koKR = "스라소니의 기민함", ptBR = "Botas", ruRU = "рысья стремительность", zhCN = "山猫之敏", zhTW = "山貓迅敏" },
    [7965] = { enUS = "Amani Mastery", zhCN = "阿曼尼精通", zhTW = "阿曼尼精通", deDE = "Amanimeisterschaft", frFR = "maîtrise amani", esES = "Maestría Amani", itIT = "Maestria degli Amani", koKR = "아마니의 특화", ptBR = "Anel", ruRU = "аманийская искусность" },
    [7967] = { deDE = "Augen des Adlers", esES = "Ojos del águila", frFR = "yeux de l’aigle", itIT = "Occhi dell'Aquila", koKR = "독수리의 눈", ptBR = "Anel", ruRU = "глаза орла", zhCN = "鹰眼神视", zhTW = "老鷹之眼" },
    [7969] = { deDE = "Zul'jins Meisterschaft", esES = "Maestría de Zul'jin", frFR = "maîtrise de Zul’jin", itIT = "Maestria di Zul'jin", koKR = "줄진의 특화", ptBR = "Anel", ruRU = "искусность Зул'джина", zhCN = "祖尔金的精通", zhTW = "祖爾金精通" },
    [7970] = { enUS = "Flight of the Eagle", zhCN = "鹰翔长空", zhTW = "老鷹之翔", deDE = "Flug des Adlers", frFR = "Vol de l’aigle", esES = "Vuelo del águila", itIT = "Volo dell'Aquila", koKR = "독수리의 비행", ptBR = "Ombros", ruRU = "полет орла" },
    [7971] = { enUS = "Flight of the Eagle", zhCN = "鹰翔长空", zhTW = "老鷹之翔", deDE = "Flug des Adlers", frFR = "Vol de l’aigle", esES = "Vuelo del águila", itIT = "Volo dell'Aquila", koKR = "독수리의 비행", ptBR = "Ombros", ruRU = "полет орла" },
    [7972] = { enUS = "Akil'zon's Swiftness", zhCN = "埃基尔松的迅捷", zhTW = "阿奇爾森的迅捷", deDE = "Akil'zons Schnelligkeit", frFR = "Rapidité d’Akil’zon", esES = "Presteza de Akil'zon", itIT = "Rapidità di Akil'zon", koKR = "아킬존의 신속함", ptBR = "Ombros", ruRU = "стремительность Акил'зон" },
    [7973] = { deDE = "Akil'zons Schnelligkeit", esES = "Presteza de Akil'zon", frFR = "Rapidité d’Akil’zon", itIT = "Rapidità di Akil'zon", koKR = "아킬존의 신속함", ptBR = "Ombros", ruRU = "стремительность Акил'зон", zhCN = "埃基尔松的迅捷", zhTW = "阿奇爾森的迅捷" },
    [7981] = { deDE = "Jan'alais Präzision", esES = "Precisión de Jan'alai", frFR = "précision de Jan’alai", itIT = "Precisione di Jan'alai", koKR = "잔알라이의 정밀함", ptBR = "Arma", ruRU = "точность Джан'алай", zhCN = "加亚莱的精准", zhTW = "賈納雷的精準" },
    [7983] = { deDE = "Berserkerwut", esES = "Ira de rabioso", frFR = "rage du berserker", itIT = "Rabbia del Berserker", koKR = "광전사의 분노", ptBR = "Arma", ruRU = "ярость берсерка", zhCN = "狂战士之怒", zhTW = "狂戰士之怒" },
    [7984] = { enUS = "Mark of the Rootwarden", zhCN = "护根者印记", zhTW = "根莖守望者印記", deDE = "Zeichen des Wurzelhüters", frFR = "marque de garde-racines", esES = "Marca del celador de raíces", itIT = "Marchio del Guardaradici", koKR = "뿌리감시관의 징표", ptBR = "Torso", ruRU = "метка корнестража" },
    [7985] = { enUS = "Mark of the Rootwarden", zhCN = "护根者印记", zhTW = "根莖守望者印記", deDE = "Zeichen des Wurzelhüters", frFR = "marque de garde-racines", esES = "Marca del celador de raíces", itIT = "Marchio del Guardaradici", koKR = "뿌리감시관의 징표", ptBR = "Torso", ruRU = "метка корнестража" },
    [7986] = { enUS = "Mark of the Worldsoul", zhCN = "世界之魂印记", zhTW = "世界之魂印記", deDE = "Zeichen der Weltenseele", frFR = "marque de l’Âme-monde", esES = "Marca del alma-mundo", itIT = "Marchio dell'Anima del Mondo", koKR = "세계혼의 징표", ptBR = "Torso", ruRU = "метка души мира" },
    [7987] = { deDE = "Zeichen der Weltenseele", esES = "Marca del alma-mundo", frFR = "marque de l’Âme-monde", itIT = "Marchio dell'Anima del Mondo", koKR = "세계혼의 징표", ptBR = "Torso", ruRU = "метка души мира", zhCN = "世界之魂印记", zhTW = "世界之魂印記" },
    [7989] = { enUS = "Blessing of Speed", zhCN = "加速祝福", zhTW = "速度祝福", deDE = "Segen der Geschwindigkeit", frFR = "bénédiction de vitesse", esES = "Bendición de velocidad", itIT = "Benedizione della Velocità", koKR = "속도의 축복", ptBR = "Elmo", ruRU = "благословение скорости" },
    [7991] = { deDE = "Ermächtigter Segen der Geschwindigkeit", esES = "Bendición de velocidad potenciada", frFR = "bénédiction de vitesse renforcée", itIT = "Benedizione della Velocità Potenziata", koKR = "강화된 속도의 축복", ptBR = "Encantamento da Bênção da Velocidade Potencializada - Elmo", ruRU = "усиленное благословение скорости", zhCN = "强化加速祝福", zhTW = "強化速度祝福" },
    [7993] = { deDE = "Shaladrassils Wurzeln", esES = "Raíces de Shaladrassil", frFR = "racines de Shaladrassil", itIT = "Radici di Shaladrassil", koKR = "샬라드라실의 뿌리", ptBR = "Botas", ruRU = "корни Шаладрассила", zhCN = "莎拉达希尔之根", zhTW = "夏達希爾之根" },
    [7997] = { deDE = "Furor der Natur", esES = "Furia de la Naturaleza", frFR = "fureur de la nature", itIT = "Furia della Natura", koKR = "자연의 격노", ptBR = "Anel", ruRU = "гнев природы", zhCN = "自然之怒", zhTW = "自然之怒" },
    [8001] = { deDE = "Amirdrassils Anmut", esES = "Gracia de Amirdrassil", frFR = "grâce d’Amirdrassil", itIT = "Grazia di Amirdrassil", koKR = "아미드랏실의 은혜", ptBR = "Ombros", ruRU = "милость Амирдрассила", zhCN = "阿梅达希尔之赐", zhTW = "埃達希爾之賜" },
    [8011] = { enUS = "Worldsoul Tenacity", zhCN = "世界之魂的坚韧", zhTW = "世界之魂堅毅", deDE = "Weltenseelenhartnäckigkeit", frFR = "ténacité d’Âme-monde", esES = "Tenacidad del alma-mundo", itIT = "Tenacia dell'Anima del Mondo", koKR = "세계혼의 끈기", ptBR = "Encantamento de Tenacidade da Alma do Mundo - Arma", ruRU = "упорство души мира" },
    [8012] = { enUS = "Mark of the Magister", zhCN = "魔导师印记", zhTW = "博學者印記", deDE = "Mal des Magisters", frFR = "marque de magistère", esES = "Marca del magister", itIT = "Marchio del Magistro", koKR = "마법학자의 징표", ptBR = "Torso", ruRU = "метка магистра" },
    [8013] = { deDE = "Mal des Magisters", esES = "Marca del magister", frFR = "marque de magistère", itIT = "Marchio del Magistro", koKR = "마법학자의 징표", ptBR = "Torso", ruRU = "метка магистра", zhCN = "魔导师印记", zhTW = "博學者印記" },
    [8017] = { deDE = "Ermächtigte Rune der Vermeidung", esES = "Runa de evasión potenciada", frFR = "rune d’évitement renforcée", itIT = "Runa dell'Elusione Potenziata", koKR = "강화된 광역회피의 룬", ptBR = "Encantamento da Runa da Evasão Potencializada - Elmo", ruRU = "усиленная руна избежания", zhCN = "强化闪避符文", zhTW = "強化迴避符文" },
    [8018] = { enUS = "Farstrider's Hunt", zhCN = "远行者的狩猎", zhTW = "遠行者之狩", deDE = "Jagd des Weltenwanderers", frFR = "chasse de pérégrin", esES = "Cacería de errante", itIT = "Caccia dei Lungopasso", koKR = "원정순찰대의 추적", ptBR = "Botas", ruRU = "охота Странника" },
    [8019] = { deDE = "Jagd des Weltenwanderers", esES = "Cacería de errante", frFR = "chasse de pérégrin", itIT = "Caccia dei Lungopasso", koKR = "원정순찰대의 추적", ptBR = "Botas", ruRU = "охота Странника", zhCN = "远行者的狩猎", zhTW = "遠行者之狩" },
    [8025] = { deDE = "Inbrunst von Silbermond", esES = "Prontitud de Lunargenta", frFR = "empressement de Lune-d’Argent", itIT = "Alacrità di Lunargenta", koKR = "실버문의 기민함", ptBR = "Anel", ruRU = "луносветская расторопность", zhCN = "银月城之捷", zhTW = "銀月城的矯捷" },
    [8027] = { deDE = "Hartnäckigkeit von Silbermond", esES = "Tenacidad de Lunargenta", frFR = "ténacité de Lune-d’Argent", itIT = "Tenacia di Lunargenta", koKR = "실버문의 끈기", ptBR = "Anel", ruRU = "луносветское упорство", zhCN = "银月城之韧", zhTW = "銀月城的堅毅" },
    [8029] = { enUS = "Thalassian Recovery", zhCN = "萨拉斯复原", zhTW = "薩拉斯恢復", deDE = "Thalassische Erholung", frFR = "Récupération thalassienne", esES = "Recuperación thalassiana", itIT = "Recupero Thalassiano", koKR = "탈라시안 회복", ptBR = "Ombros", ruRU = "талассийское восстановление" },
    [8031] = { deDE = "Heilung von Silbermond", esES = "Alivio de Lunargenta", frFR = "Guérison de Lune-d’Argent", itIT = "Guarigione di Lunargenta", koKR = "실버문의 치유", ptBR = "Ombros", ruRU = "луносветское исцеление", zhCN = "银月城治愈", zhTW = "銀月城的癒合" },
    [8038] = { enUS = "Acuity of the Ren'dorei", zhCN = "朗多雷之锐", zhTW = "刃多雷的敏銳", deDE = "Scharfsinn der Ren'dorei", frFR = "acuité des Ren’dorei", esES = "Agudeza de los ren'dorei", itIT = "Acutezza dei Ren'dorei", koKR = "렌도레이의 명민함", ptBR = "Arma", ruRU = "проницательность рен'дорай" },
    [8039] = { deDE = "Scharfsinn der Ren'dorei", esES = "Agudeza de los ren'dorei", frFR = "acuité des Ren’dorei", itIT = "Acutezza dei Ren'dorei", koKR = "렌도레이의 명민함", ptBR = "Arma", ruRU = "проницательность рен'дорай", zhCN = "朗多雷之锐", zhTW = "刃多雷的敏銳" },
    [8041] = { deDE = "Arkane Meisterschaft", esES = "Maestría Arcana", frFR = "maîtrise des arcanes", itIT = "Maestria Arcana", koKR = "비전 숙련", ptBR = "Arma", ruRU = "чародейская искусность", zhCN = "奥术精通", zhTW = "秘法專精" },
    [8159] = { deDE = "+41 Beweglichkeit/Stärke und +115 Ausdauer", esES = "+41 p. de agilidad/fuerza y +115 p. de aguante", frFR = "+41 à l’agilité/force et +115 à l’endurance", itIT = "+41 Agilità/Forza e +115 Tempra", koKR = "민첩성/힘 +41 / 체력 +115", ptBR = "+41 de Agilidade/Força e +115 de Vigor", ruRU = "+41 к ловкости/силе и +115 к выносливости", zhCN = "+41 敏捷/力量 &+115 耐力", zhTW = "+41點敏捷/力量和+115點耐力", enUS = "+41 Agility/Strength & +115 Stamina" },
    [8163] = { deDE = "+41 Beweglichkeit/Stärke und +27 Rüstung", esES = "+41 p. de agilidad/fuerza y +27 p. de armadura", frFR = "+41 à l’agilité/force et +27 à l’armure", itIT = "+41 Agilità/Forza e +27 Armatura", koKR = "민첩성/힘 +41 / 방어도 +27", ptBR = "+41 de Agilidade/Força e +27 de Armadura", ruRU = "+41 к ловкости/силе и +27 к броне", zhCN = "+41 敏捷/力量和+27 护甲", zhTW = "+41點敏捷/力量和+27點護甲值", enUS = "+41 Agility/Strength & +27 Armor" },
    [8689] = { deDE = "Ritual der Hash'ey", esES = "Ritual del hash'ey", frFR = "Rite des hash’ey", itIT = "Rito degli Hash'ey", koKR = "하셰이의 의례", ptBR = "Rito dos Hash'ey", ruRU = "Обряд хаш'эй", zhCN = "哈谢仪式", zhTW = "哈謝之儀" },
}

-- 取当前客户端语言的附魔名：zhCN 优先烤制的 nameCn（口径最熟），其它语言查表，再退到配方物品名，再退 nameCn。
function GearInsight.EnchName(e, fallback)
    if not e then return fallback or "" end
    local loc = GearInsight.LOCALE or (GetLocale and GetLocale()) or "enUS"
    if loc == "esMX" then loc = "esES" elseif loc == "enGB" then loc = "enUS" end
    if loc == "zhCN" and e.nameCn and e.nameCn ~= "" then return e.nameCn end
    local t = e.id and GearInsight.EnchantNames[e.id]
    if t then
        local n = t[loc] or t.enUS
        if n and n ~= "" then return n end
    end
    if e.item and C_Item and C_Item.GetItemNameByID then
        local n = C_Item.GetItemNameByID(e.item)
        if n and n ~= "" then return n end
    end
    if e.nameCn and e.nameCn ~= "" then return e.nameCn end
    return fallback or ""
end
