-- 自动生成(generate_news_lua.py)，勿手改。插件「资讯」页数据：更新日志(最新3版)/游戏版本/强度榜/关注/频道。
GearInsightNews = {
  builtAt="2026-09-19",
  releases={
    { version="0.91.3", date="2026-09-19", items={
      { zh="插件内「资讯」页的更新日志停在 0.90.10，补上 0.91.0 → 0.91.2 三条。", en="The in-addon News page's changelog was stuck at 0.90.10; 0.91.0 → 0.91.2 entries added.", tw="插件內「資訊」頁的更新日誌停在 0.90.10，補上 0.91.0 → 0.91.2。", kind="fixed" },
    } },
    { version="0.91.2", date="2026-09-19", items={
      { zh="智能键位+宏：修复打开页签 / 点重置时游戏「没有足够的内存」死机（读宏格时不再拾取放回，改用 GetActionText；动作条事件刷新合并为每帧一次）。", en="Smart Keybinds + Macros: fixed the client running out of memory (crash) when opening the tab or resetting keys — macro slots are read via GetActionText instead of pick-up/place, and action-bar refreshes are coalesced to once per frame.", tw="智慧鍵位+巨集：修復打開頁籤 / 重置時遊戲「記憶體不足」當機。", kind="fixed" },
      { zh="改一格键位只动这一格：冲突的那格置为无快捷键，不再连锁重排其他格；智能推荐键按专精记住，刷新 / 重载不漂移。", en="Editing one slot's key only touches that slot: the conflicting slot is left unbound instead of everything else being reshuffled; smart recommendations are remembered per spec and no longer drift on refresh / reload.", tw="改一格鍵位只動這一格：衝突的那格置為無快捷鍵，不再連鎖重排；智慧推薦鍵按專精記住。", kind="fixed" },
      { zh="「存储当前键位快照」不再清掉面板上的手动改键，记的是面板当前显示的这套。", en="\"Save current key snapshot\" no longer wipes your manual key edits; it stores exactly what the panel shows.", tw="「儲存當前鍵位快照」不再清掉手動改鍵。", kind="fixed" },
      { zh="MySlot 导出串补上宏定义：之前导入后所有宏格都是空的。", en="MySlot export now includes macro definitions — previously every macro slot came back empty after import.", tw="MySlot 匯出串補上巨集定義：之前匯入後巨集格全空。", kind="fixed" },
    } },
    { version="0.91.1", date="2026-09-18", items={
      { zh="智能键位+宏：撞键被替换的格不再变「不绑」，刷新时自动补一个空闲键；宏格左键 = 改键（Shift+左键才建宏放格），格子底部直接显示宏名。", en="Smart Keybinds + Macros: a slot whose key gets taken is re-assigned a free key on refresh instead of going unbound; left-click on a macro cell now rebinds (Shift+click creates and places the macro); macro cells show the macro name.", tw="智慧鍵位+巨集：撞鍵被替換的格自動補一個空閒鍵；巨集格左鍵 = 改鍵（Shift+左鍵建巨集放格），格子顯示巨集名。", kind="fixed" },
      { zh="支持者名单更新。", en="Supporter list updated.", tw="支持者名單更新。", kind="data" },
    } },
  },
  patch={ title="12.1 至暗之夜 · 赛季 2 · 热修记录", titleEn="Patch 12.1 Midnight · Season 2 · Hotfixes", source="", hotfixes={
    { date="2026-09-15", lines={ "斯索拉克：风暴伤害英雄/史诗 -20%；英雄难度腐蚀利爪不再生成腐蚀残渣", "双子毒牙：腐蚀唾液史诗 -20%；唤醒子嗣召唤的小怪降至 10 只；脏腑爆裂读条 +0.5 秒", "盘卷祭坛：毒液爆裂英雄/史诗 -10%，诱变毒液 -15%；恐惧哀嚎读条英雄 12 秒 / 史诗 10 秒；恐惧行军目标数不再随阶段增加；打断后小怪额外可见 3 秒；史诗转场碎片 -25%", "乌拉特克史诗：腐臭薄膜 1 小时→30 秒；一阶段每波小怪 13→8、二阶段每侧 14→12、转场蛋 14→8；岩石剧毒伤害全难度下调", "乌拉特克随机团：漏站蛇母之怒只叠 1 层岩石剧毒；恶意读条 1.5→5 秒且伤害下调；二阶段小怪降至 6；无羁之怒、响尾猛击伤害下调", "射击猎：修复枪/弩的瞄准射击施法动画；防骑：奉献首跳吃到套装暴击加成；神牧：二件套「活力」不再超过 3 层", "潮汐火花补发：火花尘多于背包+装备内火花的角色，登录直接补入缺失的火花", "任务：「仍在敌后传送门」被劫持的传送门传送位置修复；地下堡重新计入「至暗角落的希望」进度；盘蛇岛诅咒涌动轮换 45→30 分钟" }, linesEn={ "Sszorak: Tempest -20% on Heroic/Mythic; Caustic Claws no longer leaves Caustic Residue on Heroic", "Twin Fangs: Corrosive Spit -20% on Mythic; Rouse the Brood spawns 10 Broodlings; Visceral Burst cast +0.5s", "Coiled Altar: Venom Rupture -10% (H/M), Mutagenic Venom -15%; Wail of Terror cast 12s (H) / 10s (M); Dreadmarch target count no longer grows; revealed adds visible +3s; Mythic intermission Fragments -25%", "Ula'tek Mythic: Putrid Membrane 1h→30s; Stage 1 adds per wave 13→8, Stage 2 per side 14→12, intermission eggs 14→8; Stone Venom damage reduced on all difficulties", "Ula'tek LFR: missing Mother's Wrath only applies 1 Stone Venom stack; Malice cast 1.5→5s and damage reduced; Stage 2 adds reduced to 6; Unchecked Rage / Rattler Slam damage reduced", "MM Hunter: Aimed Shot animation with guns/crossbows fixed; Prot Paladin: Consecration first tick gets the tier crit bonus; Holy Priest: 2pc Renewed Vigor caps at 3 stacks", "Spark of Tides catch-up: characters with more Spark Dust than sparks receive missing sparks on login", "Quests: Hijacked Portal for \"Still Behind Enemy Portals\" fixed; Delves count for \"Hope in the Darkest Corners\" again; Curse Surges rotate every 30 min (was 45)" }, refs={ { { t="spell", id=1287072, zh="风暴", en="Tempest" }, { t="spell", id=1305998, zh="腐蚀利爪", en="Caustic Claws" }, { t="spell", id=1296602, zh="腐蚀残渣", en="Caustic Residue" } }, { { t="spell", id=1291478, zh="腐蚀唾液", en="Corrosive Spit" }, { t="spell", id=1308356, zh="唤醒子嗣", en="Rouse the Brood" }, { t="spell", id=1308385, zh="脏腑爆裂", en="Visceral Burst" } }, { { t="spell", id=1299838, zh="毒液爆裂", en="Venom Rupture" }, { t="spell", id=1310498, zh="诱变毒液", en="Mutagenic Venom" }, { t="spell", id=1286399, zh="恐惧哀嚎", en="Wail of Terror" }, { t="spell", id=1285643, zh="恐惧行军", en="Dreadmarch" } }, { { t="spell", id=1301268, zh="腐臭薄膜", en="Putrid Membrane" }, { t="spell", id=1298417, zh="岩石剧毒", en="Stone Venom" } }, { { t="spell", id=1298367, zh="蛇母之怒", en="Mother's Wrath" }, { t="spell", id=1290779, zh="恶意", en="Malice" }, { t="spell", id=1286945, zh="无羁之怒", en="Unchecked Rage" }, { t="spell", id=1299206, zh="响尾猛击", en="Rattler Slam" } }, { { t="spell", id=19434, zh="瞄准射击", en="Aimed Shot" }, { t="spell", id=26573, zh="奉献", en="Consecration" } }, { { t="item", id=274476, zh="潮汐火花", en="Spark of Tides" } }, {  } } },
    { date="2026-09-10", lines={ "邪恶 DK：修复亡者魔导师偶尔生成在极端高低差位置的问题", "生存猎人：修复野火炸弹伤害与「合而为一」和控制效果的交互", "神圣骑士：修复选光铸时天堂回响不生效", "恢复萨满：宁静之雨现在正确缩短治疗之雨 0.5 秒施法", "地下堡：暮光墓穴「脱缰的洛阿」变体加入探险者协会补给" }, linesEn={ "Unholy DK: Magus of the Dead no longer spawns at extreme vertical offsets", "Survival Hunter: Wildfire Bomb damage / Strike As One crowd-control interactions fixed", "Holy Paladin: Ringing of the Heavens now works as Lightsmith", "Resto Shaman: Soothing Rain properly reduces Healing Rain cast time by 0.5s", "Delves: Explorer's League Supplies added to Twilight Crypts 'Loosed Loa'" }, refs={ { { t="spell", id=390196, zh="亡者魔导师", en="Magus of the Dead" } }, { { t="spell", id=259495, zh="野火炸弹", en="Wildfire Bomb" } }, { { t="spell", id=1241542, zh="天堂回响", en="Ringing of the Heavens" } }, { { t="spell", id=1252874, zh="宁静之雨", en="Soothing Rain" }, { t="spell", id=73920, zh="治疗之雨", en="Healing Rain" } }, {  } } },
    { date="2026-09-09", lines={ "鲜血 DK：修复死亡凋零的亡者之握永久生效", "守护德鲁伊：修复荒野守护者未选 3 级也提高痛击 / 裂伤伤害", "防护骑士：修复先锋军荣耀对远处目标的伤害", "牧师：快速治疗可在冷却管理器里追踪（多专精）", "地下堡：丰饶宝箱正确给予祖尔加拉部众声望" }, linesEn={ "Blood DK: Grip of the Dead from Death and Decay no longer permanently active", "Guardian Druid: Wild Guardian no longer boosts Thrash / Mangle without Rank 3", "Protection Paladin: Glory of the Vanguard damage fixed for distant targets", "Priest: Flash Heal trackable in Cooldown Manager for multiple specs", "Delves: Bountiful Coffers properly grant Zul'jarra's Forces reputation" }, refs={ { { t="spell", id=43265, zh="死亡凋零", en="Death and Decay" }, { t="spell", id=273952, zh="亡者之握", en="Grip of the Dead" } }, { { t="spell", id=1269614, zh="荒野守护者", en="Wild Guardian" }, { t="spell", id=77758, zh="痛击", en="Thrash" }, { t="spell", id=33917, zh="裂伤", en="Mangle" } }, { { t="spell", id=1267203, zh="先锋军荣耀", en="Glory of the Vanguard" } }, { { t="spell", id=2061, zh="快速治疗", en="Flash Heal" } }, {  } } },
  } },
  tier={ updatedAt="2026-09-17", basis="mplus", groups={
    { role="dps", roleCn="输出", specs={
      { tier="S", cls="WARLOCK", specCn="恶魔", spec="DEMONOLOGY", hex="8788EE", delta=0, specID=266 },
      { tier="S", cls="SHAMAN", specCn="元素", spec="ELEMENTAL", hex="0070DD", delta=0, specID=262 },
      { tier="S", cls="MAGE", specCn="奥术", spec="ARCANE", hex="3FC7EB", delta=0, specID=62 },
      { tier="S", cls="ROGUE", specCn="刺杀", spec="ASSASSINATION", hex="FFF468", delta=1, specID=259 },
      { tier="S", cls="MONK", specCn="踏风", spec="WINDWALKER", hex="00FF98", delta=1, specID=269 },
      { tier="S", cls="WARRIOR", specCn="武器", spec="ARMS", hex="C69B3A", delta=-2, specID=71 },
      { tier="S", cls="DRUID", specCn="野性", spec="FERAL", hex="FF7C0A", delta=0, specID=103 },
      { tier="A", cls="HUNTER", specCn="兽王", spec="BEASTMASTERY", hex="AAD372", delta=0, specID=253 },
      { tier="A", cls="PALADIN", specCn="惩戒", spec="RETRIBUTION", hex="F48CBA", delta=0, specID=70 },
      { tier="A", cls="ROGUE", specCn="狂徒", spec="OUTLAW", hex="FFF468", delta=0, specID=260 },
      { tier="B", cls="DEATHKNIGHT", specCn="邪恶", spec="UNHOLY", hex="C41E3A", delta=0, specID=252 },
      { tier="B", cls="DEMONHUNTER", specCn="噬灭", spec="DEVAURER", hex="A330C9", delta=1, specID=1480 },
      { tier="B", cls="DEATHKNIGHT", specCn="冰霜", spec="FROST", hex="C41E3A", delta=3, specID=251 },
      { tier="B", cls="ROGUE", specCn="敏锐", spec="SUBTLETY", hex="FFF468", delta=-2, specID=261 },
      { tier="B", cls="DEMONHUNTER", specCn="浩劫", spec="HAVOC", hex="A330C9", delta=-1, specID=577 },
      { tier="B", cls="DRUID", specCn="平衡", spec="BALANCE", hex="FF7C0A", delta=-1, specID=102 },
      { tier="C", cls="SHAMAN", specCn="增强", spec="ENHANCEMENT", hex="0070DD", delta=0, specID=263 },
      { tier="C", cls="WARRIOR", specCn="狂怒", spec="FURY", hex="C69B3A", delta=0, specID=72 },
      { tier="C", cls="PRIEST", specCn="暗影", spec="SHADOW", hex="FFFFFF", delta=0, specID=258 },
      { tier="C", cls="WARLOCK", specCn="痛苦", spec="AFFLICTION", hex="8788EE", delta=0, specID=265 },
      { tier="D", cls="EVOKER", specCn="湮灭", spec="DEVASTATION", hex="33937F", delta=0, specID=1467 },
      { tier="D", cls="WARLOCK", specCn="毁灭", spec="DESTRUCTION", hex="8788EE", delta=1, specID=267 },
      { tier="D", cls="HUNTER", specCn="生存", spec="SURVIVAL", hex="AAD372", delta=1, specID=255 },
      { tier="D", cls="HUNTER", specCn="射击", spec="MARKSMANSHIP", hex="AAD372", delta=-2, specID=254 },
      { tier="F", cls="MAGE", specCn="火焰", spec="FIRE", hex="3FC7EB", delta=0, specID=63 },
      { tier="F", cls="MAGE", specCn="冰霜", spec="FROST", hex="3FC7EB", delta=0, specID=64 },
      { tier="F", cls="EVOKER", specCn="增辉", spec="AUGMENTATION", hex="33937F", delta=0, specID=1473 },
    } },
    { role="healer", roleCn="治疗", specs={
      { tier="S", cls="PRIEST", specCn="神圣", spec="HOLY", hex="FFFFFF", delta=0, specID=257 },
      { tier="S", cls="PALADIN", specCn="神圣", spec="HOLY", hex="F48CBA", delta=0, specID=65 },
      { tier="S", cls="MONK", specCn="织雾", spec="MISTWEAVER", hex="00FF98", delta=0, specID=270 },
      { tier="A", cls="SHAMAN", specCn="恢复", spec="RESTORATION", hex="0070DD", delta=0, specID=264 },
      { tier="A", cls="EVOKER", specCn="恩护", spec="PRESERVATION", hex="33937F", delta=1, specID=1468 },
      { tier="A", cls="DRUID", specCn="恢复", spec="RESTORATION", hex="FF7C0A", delta=-1, specID=105 },
      { tier="C", cls="PRIEST", specCn="戒律", spec="DISCIPLINE", hex="FFFFFF", delta=0, specID=256 },
    } },
    { role="tank", roleCn="坦克", specs={
      { tier="S", cls="DEATHKNIGHT", specCn="鲜血", spec="BLOOD", hex="C41E3A", delta=0, specID=250 },
      { tier="D", cls="DRUID", specCn="守护", spec="GUARDIAN", hex="FF7C0A", delta=0, specID=104 },
      { tier="D", cls="DEMONHUNTER", specCn="复仇", spec="VENGEANCE", hex="A330C9", delta=2, specID=581 },
      { tier="D", cls="WARRIOR", specCn="防护", spec="PROTECTION", hex="C69B3A", delta=0, specID=73 },
      { tier="D", cls="MONK", specCn="酒仙", spec="BREWMASTER", hex="00FF98", delta=-2, specID=268 },
      { tier="D", cls="PALADIN", specCn="防护", spec="PROTECTION", hex="F48CBA", delta=0, specID=66 },
    } },
  } },
  channels={
    follow_cn={ { "公众号", "gear魔兽装备", "微信搜「gear魔兽装备」", "wechat" } },
    follow_en={ { "X", "@GearInsightApp", "x.com/GearInsightApp", "x" }, { "YouTube", "@GearInsightWoW", "youtube.com/@GearInsightWoW", "youtube" } },
    cn={ { "微信小程序", "GearInsight", "微信搜「GearInsight」小程序：BiS / 掉落 / 天赋 / 万奥宝典，手机随时查", "mp" }, { "抖音", "魔兽装备管家·GearInsight", "抖音搜「GearInsight」", "douyin" }, { "小红书", "GearInsight", "小红书搜「GearInsight」", "xhs" }, { "B站", "GearInsight", "B站搜「GearInsight」", "bili" }, { "QQ群", "954673901", "954673901", "qq" } },
    en={ { "Telegram", "t.me/gearInsight", "t.me/gearInsight", "tg" } },
  },
}
