-- 自动生成(generate_news_lua.py)，勿手改。插件「资讯」页数据：更新日志(最新3版)/游戏版本/强度榜/关注/频道。
GearInsightNews = {
  builtAt="2026-09-14",
  releases={
    { version="0.90.0", date="2026-09-14", items={
      { zh="资讯页：海外关注账号改为 X @GearInsightApp；致谢数据刷新（27 位支持者）。", en="News tab: overseas follow handle is now X @GearInsightApp; supporters wall refreshed (27 supporters).", tw="資訊頁：海外關注帳號改為 X @GearInsightApp；致謝資料刷新（27 位支持者）。", kind="changed" },
      { zh="资讯页强度榜：全部专精 S–D，带专精图标与较上周升降。", en="Talents/News tabs: tier list rows show every spec S-D with spec icons and rank change vs last week.", tw="資訊頁強度榜：全部專精 S–D，帶專精圖示與較上週升降。", kind="changed" },
      { zh="热修行里每个技能 / 天赋各自可悬浮看说明，带图标。", en="Hotfix lines: each spell / talent name is its own hoverable link with icon.", tw="熱修行裡每個技能 / 天賦各自可懸浮看說明，帶圖示。", kind="fixed" },
      { zh="刷本规划「套装」组补齐 5 个部位：团本 BOSS 直掉的两件本体也归进套装组（从团本组移出，不重复算缺）。", en="Farm plan tier-set block now lists all five tier slots, including the two that drop directly from raid bosses (moved out of the raid group so they are not counted twice).", tw="刷本規劃「套裝」組補齊 5 個部位：團本 BOSS 直掉的兩件本體也歸進套裝組（從團本組移出，不重複算缺）。", kind="fixed" },
    } },
    { version="0.9.0", date="2026-09-14", items={
      { zh="天赋页签新增「万奥宝典」：按游戏宝典树画五行符文，标出顶尖玩家每行怎么选（团本 / 大秘境）、你当前选的，一键换成推荐，打开宝典按钮和解锁攻略。", en="Omnium Folio guide under the Talents tab: five rune rows like the in-game tree, top-player picks per row (raid / Mythic+), your current pick, one-click apply recommended, open-Folio button and unlock guide.", tw="天賦頁籤新增「萬奧寶典」：按遊戲寶典樹畫五行符文，標出頂尖玩家每行怎麼選（團本 / 傳奇鑰石）、你目前選的，一鍵換成推薦，打開寶典按鈕和解鎖攻略。", kind="added" },
      { zh="新增「资讯」页签：插件最新 3 版更新、支持榜、最近 3 次游戏热修（技能可悬浮）、全部专精 S–D 强度榜（较上周升降）、可复制的关注 / 频道账号。", en="News tab: latest 3 addon updates, supporters wall, latest 3 game hotfixes with hoverable spells, full S-D tier list with rank change vs last week, copyable follow / channel handles.", tw="新增「資訊」頁籤：外掛最新 3 版更新、支持榜、最近 3 次遊戲熱修（技能可懸浮）、全部專精 S–D 強度榜（較上週升降）、可複製的關注 / 頻道帳號。", kind="added" },
      { zh="刷本规划「套装」组固定列 5 个部位并写 4 件套进度；顶尖多用散件的部位标「可选」不计缺件。", en="Farm plan tier-set block lists all five slots with 4-piece progress; off-set slots marked optional.", tw="刷本規劃「套裝」組固定列 5 個部位並寫 4 件套進度；頂尖多用散件的部位標「可選」不計缺件。", kind="added" },
      { zh="页签改名：刷本助手 → 刷本规划，实用工具 → 攻略；致谢墙搬到资讯页。", en="Tabs renamed: Farm helper -> Farm plan, Tools -> Guides; supporters wall moved to News.", tw="頁籤改名：刷本助手 → 刷本規劃，實用工具 → 攻略；致謝牆搬到資訊頁。", kind="changed" },
    } },
    { version="0.81.7", date="2026-09-14", items={
      { zh="坯子排序全局统一：物品悬浮 / 角色面板图标 / 掉落提醒都按本专精属性契合度排。感谢 虔诚。", en="One filler ranking everywhere: tooltips / character-sheet icon / loot alerts all use your spec's stat fit. Thanks 虔诚.", tw="坯子排序全域統一：物品懸浮 / 角色面板圖示 / 掉落提醒都按本專精屬性契合度排。感謝 虔誠。", kind="fixed" },
      { zh="角色面板 BiS 图标不再对封顶的低装等套装件打「已收集」——跟总览的结论。", en="Character-sheet BiS icon no longer shows 'collected' for a capped low-ilvl tier piece - follows the Overview verdict.", tw="角色面板 BiS 圖示不再對封頂的低裝等套裝件打「已收集」——跟總覽的結論。", kind="fixed" },
      { zh="装备总览新增「参照档」按钮（史诗 / 英雄 / 普通）。", en="'Ref. tier' button on the Overview (Mythic / Heroic / Normal).", tw="裝備總覽新增「參照檔」按鈕（傳奇 / 英雄 / 普通）。", kind="added" },
      { zh="套装部位不再显示「前 5」按钮，保留「套装坯子」弹窗。", en="Tier-set slots no longer show a 'Top 5' button; the tier-filler popup stays.", tw="套裝部位不再顯示「前 5」按鈕，保留「套裝坯子」彈窗。", kind="added" },
    } },
  },
  patch={ title="12.1 至暗之夜 · 赛季 2 · 热修记录", titleEn="Patch 12.1 Midnight · Season 2 · Hotfixes", source="", hotfixes={
    { date="2026-09-10", lines={ "邪恶 DK：修复亡者魔导师偶尔生成在极端高低差位置的问题", "生存猎人：修复野火炸弹伤害与「合而为一」和控制效果的交互", "神圣骑士：修复选光铸时天堂回响不生效", "恢复萨满：宁静之雨现在正确缩短治疗之雨 0.5 秒施法", "地下堡：暮光墓穴「脱缰的洛阿」变体加入探险者协会补给" }, linesEn={ "Unholy DK: Magus of the Dead no longer spawns at extreme vertical offsets", "Survival Hunter: Wildfire Bomb damage / Strike As One crowd-control interactions fixed", "Holy Paladin: Ringing of the Heavens now works as Lightsmith", "Resto Shaman: Soothing Rain properly reduces Healing Rain cast time by 0.5s", "Delves: Explorer's League Supplies added to Twilight Crypts 'Loosed Loa'" }, refs={ { { t="spell", id=390196, zh="亡者魔导师", en="Magus of the Dead" } }, { { t="spell", id=259495, zh="野火炸弹", en="Wildfire Bomb" } }, { { t="spell", id=1241542, zh="天堂回响", en="Ringing of the Heavens" } }, { { t="spell", id=1252874, zh="宁静之雨", en="Soothing Rain" }, { t="spell", id=73920, zh="治疗之雨", en="Healing Rain" } }, {  } } },
    { date="2026-09-09", lines={ "鲜血 DK：修复死亡凋零的亡者之握永久生效", "守护德鲁伊：修复荒野守护者未选 3 级也提高痛击 / 裂伤伤害", "防护骑士：修复先锋军荣耀对远处目标的伤害", "牧师：快速治疗可在冷却管理器里追踪（多专精）", "地下堡：丰饶宝箱正确给予祖尔加拉部众声望" }, linesEn={ "Blood DK: Grip of the Dead from Death and Decay no longer permanently active", "Guardian Druid: Wild Guardian no longer boosts Thrash / Mangle without Rank 3", "Protection Paladin: Glory of the Vanguard damage fixed for distant targets", "Priest: Flash Heal trackable in Cooldown Manager for multiple specs", "Delves: Bountiful Coffers properly grant Zul'jarra's Forces reputation" }, refs={ { { t="spell", id=43265, zh="死亡凋零", en="Death and Decay" }, { t="spell", id=273952, zh="亡者之握", en="Grip of the Dead" } }, { { t="spell", id=1269614, zh="荒野守护者", en="Wild Guardian" }, { t="spell", id=77758, zh="痛击", en="Thrash" }, { t="spell", id=33917, zh="裂伤", en="Mangle" } }, { { t="spell", id=1267203, zh="先锋军荣耀", en="Glory of the Vanguard" } }, { { t="spell", id=2061, zh="快速治疗", en="Flash Heal" } }, {  } } },
    { date="2026-09-04", lines={ "平衡德鲁伊：星辰强化可追踪；双月射程随目标体型增大", "增强萨满：烈毒之渊 4 件套对闪电鞭笞的前置伤害修复", "团本 乌拉特克：修复毒蛇噬咬施加「吞噬之毒」的问题", "家园：秘密纪念品成就补发", "物品：超凡抗毒剂的吸收上限与治疗百分比修正" }, linesEn={ "Balance Druid: Stellar Amplification trackable; Twin Moons range scales with target size", "Enhancement Shaman: Venomous Abyss 4-set upfront damage fixed for Crash Lightning", "Raid Ula'tek: Ingested Venom application from Serpent's Bite resolved", "Housing: Secret Souvenir achievement credit fixed retroactively", "Items: Preternatural Antivenom absorb cap and healing percentage corrected" }, refs={ { { t="spell", id=450212, zh="星辰强化", en="Stellar Amplification" }, { t="spell", id=279620, zh="双月", en="Twin Moons" } }, { { t="spell", id=187874, zh="闪电鞭笞", en="Crash Lightning" } }, { { t="spell", id=1295840, zh="毒蛇噬咬", en="Serpent's Bite" } }, {  }, { { t="item", id=270171, zh="超凡抗毒剂", en="Preternatural Antivenom" } } } },
  } },
  tier={ updatedAt="2026-09-09", basis="mplus", groups={
    { role="dps", roleCn="输出", specs={
      { tier="S", cls="WARLOCK", specCn="恶魔", spec="DEMONOLOGY", hex="8788EE", delta=0, specID=266 },
      { tier="S", cls="SHAMAN", specCn="元素", spec="ELEMENTAL", hex="0070DD", delta=0, specID=262 },
      { tier="S", cls="MAGE", specCn="奥术", spec="ARCANE", hex="3FC7EB", delta=0, specID=62 },
      { tier="S", cls="WARRIOR", specCn="武器", spec="ARMS", hex="C69B3A", delta=0, specID=71 },
      { tier="A", cls="ROGUE", specCn="刺杀", spec="ASSASSINATION", hex="FFF468", delta=0, specID=259 },
      { tier="A", cls="MONK", specCn="踏风", spec="WINDWALKER", hex="00FF98", delta=0, specID=269 },
      { tier="A", cls="DRUID", specCn="野性", spec="FERAL", hex="FF7C0A", delta=1, specID=103 },
      { tier="A", cls="HUNTER", specCn="兽王", spec="BEASTMASTERY", hex="AAD372", delta=-1, specID=253 },
      { tier="A", cls="PALADIN", specCn="惩戒", spec="RETRIBUTION", hex="F48CBA", delta=0, specID=70 },
      { tier="A", cls="ROGUE", specCn="狂徒", spec="OUTLAW", hex="FFF468", delta=0, specID=260 },
      { tier="B", cls="DEATHKNIGHT", specCn="邪恶", spec="UNHOLY", hex="C41E3A", delta=0, specID=252 },
      { tier="B", cls="ROGUE", specCn="敏锐", spec="SUBTLETY", hex="FFF468", delta=1, specID=261 },
      { tier="B", cls="DEMONHUNTER", specCn="噬灭", spec="DEVAURER", hex="A330C9", delta=-1, specID=1480 },
      { tier="C", cls="DEMONHUNTER", specCn="浩劫", spec="HAVOC", hex="A330C9", delta=0, specID=577 },
      { tier="C", cls="DRUID", specCn="平衡", spec="BALANCE", hex="FF7C0A", delta=0, specID=102 },
      { tier="C", cls="DEATHKNIGHT", specCn="冰霜", spec="FROST", hex="C41E3A", delta=0, specID=251 },
      { tier="C", cls="SHAMAN", specCn="增强", spec="ENHANCEMENT", hex="0070DD", delta=0, specID=263 },
      { tier="C", cls="WARRIOR", specCn="狂怒", spec="FURY", hex="C69B3A", delta=0, specID=72 },
      { tier="C", cls="PRIEST", specCn="暗影", spec="SHADOW", hex="FFFFFF", delta=0, specID=258 },
      { tier="D", cls="WARLOCK", specCn="痛苦", spec="AFFLICTION", hex="8788EE", delta=0, specID=265 },
      { tier="D", cls="EVOKER", specCn="湮灭", spec="DEVASTATION", hex="33937F", delta=0, specID=1467 },
      { tier="D", cls="HUNTER", specCn="射击", spec="MARKSMANSHIP", hex="AAD372", delta=1, specID=254 },
      { tier="D", cls="WARLOCK", specCn="毁灭", spec="DESTRUCTION", hex="8788EE", delta=-1, specID=267 },
      { tier="D", cls="HUNTER", specCn="生存", spec="SURVIVAL", hex="AAD372", delta=0, specID=255 },
      { tier="F", cls="MAGE", specCn="火焰", spec="FIRE", hex="3FC7EB", delta=0, specID=63 },
      { tier="F", cls="MAGE", specCn="冰霜", spec="FROST", hex="3FC7EB", delta=0, specID=64 },
      { tier="F", cls="EVOKER", specCn="增辉", spec="AUGMENTATION", hex="33937F", delta=0, specID=1473 },
    } },
    { role="healer", roleCn="治疗", specs={
      { tier="S", cls="PRIEST", specCn="神圣", spec="HOLY", hex="FFFFFF", delta=0, specID=257 },
      { tier="S", cls="PALADIN", specCn="神圣", spec="HOLY", hex="F48CBA", delta=0, specID=65 },
      { tier="A", cls="MONK", specCn="织雾", spec="MISTWEAVER", hex="00FF98", delta=0, specID=270 },
      { tier="A", cls="SHAMAN", specCn="恢复", spec="RESTORATION", hex="0070DD", delta=0, specID=264 },
      { tier="A", cls="DRUID", specCn="恢复", spec="RESTORATION", hex="FF7C0A", delta=1, specID=105 },
      { tier="A", cls="EVOKER", specCn="恩护", spec="PRESERVATION", hex="33937F", delta=-1, specID=1468 },
      { tier="C", cls="PRIEST", specCn="戒律", spec="DISCIPLINE", hex="FFFFFF", delta=0, specID=256 },
    } },
    { role="tank", roleCn="坦克", specs={
      { tier="S", cls="DEATHKNIGHT", specCn="鲜血", spec="BLOOD", hex="C41E3A", delta=0, specID=250 },
      { tier="D", cls="DRUID", specCn="守护", spec="GUARDIAN", hex="FF7C0A", delta=0, specID=104 },
      { tier="D", cls="MONK", specCn="酒仙", spec="BREWMASTER", hex="00FF98", delta=0, specID=268 },
      { tier="D", cls="WARRIOR", specCn="防护", spec="PROTECTION", hex="C69B3A", delta=0, specID=73 },
      { tier="D", cls="DEMONHUNTER", specCn="复仇", spec="VENGEANCE", hex="A330C9", delta=0, specID=581 },
      { tier="F", cls="PALADIN", specCn="防护", spec="PROTECTION", hex="F48CBA", delta=0, specID=66 },
    } },
  } },
  channels={
    follow_cn={ { "公众号", "gear魔兽装备", "微信搜「gear魔兽装备」", "wechat" } },
    follow_en={ { "X", "@GearInsightApp", "x.com/GearInsightApp", "x" }, { "YouTube", "@GearInsightWoW", "youtube.com/@GearInsightWoW", "youtube" } },
    cn={ { "微信小程序", "GearInsight", "微信搜「GearInsight」小程序：BiS / 掉落 / 天赋 / 万奥宝典，手机随时查", "mp" }, { "抖音", "魔兽装备管家·GearInsight", "抖音搜「GearInsight」", "douyin" }, { "小红书", "GearInsight", "小红书搜「GearInsight」", "xhs" }, { "B站", "GearInsight", "B站搜「GearInsight」", "bili" }, { "QQ群", "954673901", "954673901", "qq" } },
    en={ { "YouTube", "@GearInsightWoW", "youtube.com/@GearInsightWoW", "youtube" }, { "X", "@GearInsightApp", "x.com/GearInsightApp", "x" }, { "Telegram", "t.me/gearInsight", "t.me/gearInsight", "tg" } },
  },
}
