-- 自动生成(generate_news_lua.py)，勿手改。插件「资讯」页数据：更新日志(最新3版)/游戏版本/强度榜/关注/频道。
GearInsightNews = {
  builtAt="2026-09-16",
  releases={
    { version="0.90.4", date="2026-09-16", items={
      { zh="修复战斗中窗口无法拖动、关闭，副本传送仍可在脱战后使用。", en="Fixed moving and closing the window in combat; dungeon teleports remain available out of combat.", tw="修復戰鬥中視窗無法拖動、關閉，副本傳送仍可在脫戰後使用。", kind="fixed" },
      { zh="恢复团本天赋 H1–H9，排在 M 档之后，并恢复英雄天赋数据更新。", en="Restored H1–H9 raid talent builds after Mythic entries and restored Heroic talent data updates.", tw="恢復團本天賦 H1–H9，排在 M 檔之後，並恢復英雄天賦資料更新。", kind="fixed" },
    } },
    { version="0.90.3", date="2026-09-16", items={
      { zh="修复战斗中窗口无法拖动、关闭，副本传送仍可在脱战后使用。", en="Fixed moving and closing the window in combat; dungeon teleports remain available out of combat.", tw="修復戰鬥中視窗無法拖動、關閉，副本傳送仍可在脫戰後使用。", kind="fixed" },
      { zh="恢复团本天赋 H1–H9，排在 M 档之后，并恢复英雄天赋数据更新。", en="Restored H1–H9 raid talent builds after Mythic entries and restored Heroic talent data updates.", tw="恢復團本天賦 H1–H9，排在 M 檔之後，並恢復英雄天賦資料更新。", kind="fixed" },
    } },
    { version="0.90.2", date="2026-09-15", items={
      { zh="刷本规划：4 专精职业（德鲁伊）的第 4 个专精芯片被「复制需求单文本」按钮盖住点不到（我的椰子呀c 报）。芯片按可用宽度自适应：先去「当前」后缀，再放不下缩成只图标、名字进提示。", en="Farm plan: on 4-spec classes (Druid) the fourth spec chip was hidden under the 'Copy need sheet' button and could not be clicked (reported by 我的椰子呀c). Chips now shrink to fit: suffix dropped first, then icon-only with the name in the tooltip.", tw="刷本規劃：4 專精職業（德魯伊）的第 4 個專精籌碼被「複製需求單文字」按鈕蓋住點不到（我的椰子呀c 報）。籌碼按可用寬度自適應：先去「當前」後綴，再放不下縮成只圖示、名字進提示。", kind="fixed" },
      { zh="资讯页（简体客户端）：新增「微信群」一行，点击在游戏内弹出群二维码（群码 7 天一换，随周更数据刷新，过期自动隐藏）。", en="News tab (Simplified Chinese client): a 'WeChat group' row that pops the group QR code in game (7-day code, refreshed with weekly data; hidden automatically after expiry).", tw="資訊頁（簡體客戶端）：新增「微信群」一行，點擊在遊戲內彈出群 QR code（群碼 7 天一換，隨週更資料刷新，過期自動隱藏）。", kind="added" },
    } },
  },
  patch={ title="12.1 至暗之夜 · 赛季 2 · 热修记录", titleEn="Patch 12.1 Midnight · Season 2 · Hotfixes", source="", hotfixes={
    { date="2026-09-10", lines={ "邪恶 DK：修复亡者魔导师偶尔生成在极端高低差位置的问题", "生存猎人：修复野火炸弹伤害与「合而为一」和控制效果的交互", "神圣骑士：修复选光铸时天堂回响不生效", "恢复萨满：宁静之雨现在正确缩短治疗之雨 0.5 秒施法", "地下堡：暮光墓穴「脱缰的洛阿」变体加入探险者协会补给" }, linesEn={ "Unholy DK: Magus of the Dead no longer spawns at extreme vertical offsets", "Survival Hunter: Wildfire Bomb damage / Strike As One crowd-control interactions fixed", "Holy Paladin: Ringing of the Heavens now works as Lightsmith", "Resto Shaman: Soothing Rain properly reduces Healing Rain cast time by 0.5s", "Delves: Explorer's League Supplies added to Twilight Crypts 'Loosed Loa'" }, refs={ { { t="spell", id=390196, zh="亡者魔导师", en="Magus of the Dead" } }, { { t="spell", id=259495, zh="野火炸弹", en="Wildfire Bomb" } }, { { t="spell", id=1241542, zh="天堂回响", en="Ringing of the Heavens" } }, { { t="spell", id=1252874, zh="宁静之雨", en="Soothing Rain" }, { t="spell", id=73920, zh="治疗之雨", en="Healing Rain" } }, {  } } },
    { date="2026-09-09", lines={ "鲜血 DK：修复死亡凋零的亡者之握永久生效", "守护德鲁伊：修复荒野守护者未选 3 级也提高痛击 / 裂伤伤害", "防护骑士：修复先锋军荣耀对远处目标的伤害", "牧师：快速治疗可在冷却管理器里追踪（多专精）", "地下堡：丰饶宝箱正确给予祖尔加拉部众声望" }, linesEn={ "Blood DK: Grip of the Dead from Death and Decay no longer permanently active", "Guardian Druid: Wild Guardian no longer boosts Thrash / Mangle without Rank 3", "Protection Paladin: Glory of the Vanguard damage fixed for distant targets", "Priest: Flash Heal trackable in Cooldown Manager for multiple specs", "Delves: Bountiful Coffers properly grant Zul'jarra's Forces reputation" }, refs={ { { t="spell", id=43265, zh="死亡凋零", en="Death and Decay" }, { t="spell", id=273952, zh="亡者之握", en="Grip of the Dead" } }, { { t="spell", id=1269614, zh="荒野守护者", en="Wild Guardian" }, { t="spell", id=77758, zh="痛击", en="Thrash" }, { t="spell", id=33917, zh="裂伤", en="Mangle" } }, { { t="spell", id=1267203, zh="先锋军荣耀", en="Glory of the Vanguard" } }, { { t="spell", id=2061, zh="快速治疗", en="Flash Heal" } }, {  } } },
    { date="2026-09-04", lines={ "平衡德鲁伊：星辰强化可追踪；双月射程随目标体型增大", "增强萨满：烈毒之渊 4 件套对闪电鞭笞的前置伤害修复", "团本 乌拉特克：修复毒蛇噬咬施加「吞噬之毒」的问题", "家园：秘密纪念品成就补发", "物品：超凡抗毒剂的吸收上限与治疗百分比修正" }, linesEn={ "Balance Druid: Stellar Amplification trackable; Twin Moons range scales with target size", "Enhancement Shaman: Venomous Abyss 4-set upfront damage fixed for Crash Lightning", "Raid Ula'tek: Ingested Venom application from Serpent's Bite resolved", "Housing: Secret Souvenir achievement credit fixed retroactively", "Items: Preternatural Antivenom absorb cap and healing percentage corrected" }, refs={ { { t="spell", id=450212, zh="星辰强化", en="Stellar Amplification" }, { t="spell", id=279620, zh="双月", en="Twin Moons" } }, { { t="spell", id=187874, zh="闪电鞭笞", en="Crash Lightning" } }, { { t="spell", id=1295840, zh="毒蛇噬咬", en="Serpent's Bite" } }, {  }, { { t="item", id=270171, zh="超凡抗毒剂", en="Preternatural Antivenom" } } } },
  } },
  tier={ updatedAt="2026-09-09", basis="mplus", groups={
    { role="dps", roleCn="输出", specs={
      { tier="S", cls="WARLOCK", specCn="恶魔", spec="DEMONOLOGY", hex="8788EE", delta=0, specID=266 },
      { tier="S", cls="SHAMAN", specCn="元素", spec="ELEMENTAL", hex="0070DD", delta=0, specID=262 },
      { tier="S", cls="MAGE", specCn="奥术", spec="ARCANE", hex="3FC7EB", delta=0, specID=62 },
      { tier="S", cls="WARRIOR", specCn="武器", spec="ARMS", hex="C69B3A", delta=0, specID=71 },
      { tier="A", cls="ROGUE", specCn="刺杀", spec="ASSASSINATION", hex="FFF468", delta=0, specID=259 },
      { tier="A", cls="MONK", specCn="踏风", spec="WINDWALKER", hex="00FF98", delta=0, specID=269 },
      { tier="A", cls="DRUID", specCn="野性", spec="FERAL", hex="FF7C0A", delta=1, specID=103 },
      { tier="A", cls="HUNTER", specCn="兽王", spec="BEASTMASTERY", hex="AAD372", delta=-1, specID=253 },
      { tier="A", cls="PALADIN", specCn="惩戒", spec="RETRIBUTION", hex="F48CBA", delta=0, specID=70 },
      { tier="A", cls="ROGUE", specCn="狂徒", spec="OUTLAW", hex="FFF468", delta=0, specID=260 },
      { tier="B", cls="DEATHKNIGHT", specCn="邪恶", spec="UNHOLY", hex="C41E3A", delta=0, specID=252 },
      { tier="B", cls="ROGUE", specCn="敏锐", spec="SUBTLETY", hex="FFF468", delta=1, specID=261 },
      { tier="B", cls="DEMONHUNTER", specCn="噬灭", spec="DEVAURER", hex="A330C9", delta=-1, specID=1480 },
      { tier="C", cls="DEMONHUNTER", specCn="浩劫", spec="HAVOC", hex="A330C9", delta=0, specID=577 },
      { tier="C", cls="DRUID", specCn="平衡", spec="BALANCE", hex="FF7C0A", delta=0, specID=102 },
      { tier="C", cls="DEATHKNIGHT", specCn="冰霜", spec="FROST", hex="C41E3A", delta=0, specID=251 },
      { tier="C", cls="SHAMAN", specCn="增强", spec="ENHANCEMENT", hex="0070DD", delta=0, specID=263 },
      { tier="C", cls="WARRIOR", specCn="狂怒", spec="FURY", hex="C69B3A", delta=0, specID=72 },
      { tier="C", cls="PRIEST", specCn="暗影", spec="SHADOW", hex="FFFFFF", delta=0, specID=258 },
      { tier="D", cls="WARLOCK", specCn="痛苦", spec="AFFLICTION", hex="8788EE", delta=0, specID=265 },
      { tier="D", cls="EVOKER", specCn="湮灭", spec="DEVASTATION", hex="33937F", delta=0, specID=1467 },
      { tier="D", cls="HUNTER", specCn="射击", spec="MARKSMANSHIP", hex="AAD372", delta=1, specID=254 },
      { tier="D", cls="WARLOCK", specCn="毁灭", spec="DESTRUCTION", hex="8788EE", delta=-1, specID=267 },
      { tier="D", cls="HUNTER", specCn="生存", spec="SURVIVAL", hex="AAD372", delta=0, specID=255 },
      { tier="F", cls="MAGE", specCn="火焰", spec="FIRE", hex="3FC7EB", delta=0, specID=63 },
      { tier="F", cls="MAGE", specCn="冰霜", spec="FROST", hex="3FC7EB", delta=0, specID=64 },
      { tier="F", cls="EVOKER", specCn="增辉", spec="AUGMENTATION", hex="33937F", delta=0, specID=1473 },
    } },
    { role="healer", roleCn="治疗", specs={
      { tier="S", cls="PRIEST", specCn="神圣", spec="HOLY", hex="FFFFFF", delta=0, specID=257 },
      { tier="S", cls="PALADIN", specCn="神圣", spec="HOLY", hex="F48CBA", delta=0, specID=65 },
      { tier="A", cls="MONK", specCn="织雾", spec="MISTWEAVER", hex="00FF98", delta=0, specID=270 },
      { tier="A", cls="SHAMAN", specCn="恢复", spec="RESTORATION", hex="0070DD", delta=0, specID=264 },
      { tier="A", cls="DRUID", specCn="恢复", spec="RESTORATION", hex="FF7C0A", delta=1, specID=105 },
      { tier="A", cls="EVOKER", specCn="恩护", spec="PRESERVATION", hex="33937F", delta=-1, specID=1468 },
      { tier="C", cls="PRIEST", specCn="戒律", spec="DISCIPLINE", hex="FFFFFF", delta=0, specID=256 },
    } },
    { role="tank", roleCn="坦克", specs={
      { tier="S", cls="DEATHKNIGHT", specCn="鲜血", spec="BLOOD", hex="C41E3A", delta=0, specID=250 },
      { tier="D", cls="DRUID", specCn="守护", spec="GUARDIAN", hex="FF7C0A", delta=0, specID=104 },
      { tier="D", cls="MONK", specCn="酒仙", spec="BREWMASTER", hex="00FF98", delta=0, specID=268 },
      { tier="D", cls="WARRIOR", specCn="防护", spec="PROTECTION", hex="C69B3A", delta=0, specID=73 },
      { tier="D", cls="DEMONHUNTER", specCn="复仇", spec="VENGEANCE", hex="A330C9", delta=0, specID=581 },
      { tier="F", cls="PALADIN", specCn="防护", spec="PROTECTION", hex="F48CBA", delta=0, specID=66 },
    } },
  } },
  channels={
    follow_cn={ { "公众号", "gear魔兽装备", "微信搜「gear魔兽装备」", "wechat" } },
    follow_en={ { "X", "@GearInsightApp", "x.com/GearInsightApp", "x" }, { "YouTube", "@GearInsightWoW", "youtube.com/@GearInsightWoW", "youtube" } },
    cn={ { "微信小程序", "GearInsight", "微信搜「GearInsight」小程序：BiS / 掉落 / 天赋 / 万奥宝典，手机随时查", "mp" }, { "抖音", "魔兽装备管家·GearInsight", "抖音搜「GearInsight」", "douyin" }, { "小红书", "GearInsight", "小红书搜「GearInsight」", "xhs" }, { "B站", "GearInsight", "B站搜「GearInsight」", "bili" }, { "QQ群", "954673901", "954673901", "qq" } },
    en={ { "YouTube", "@GearInsightWoW", "youtube.com/@GearInsightWoW", "youtube" }, { "X", "@GearInsightApp", "x.com/GearInsightApp", "x" }, { "Telegram", "t.me/gearInsight", "t.me/gearInsight", "tg" } },
  },
}
