-- 由 clawhub services/wow-agent/export_pvp_meta.py 生成，⛔别手改（随 PvP 榜数据刷新）。
-- ⛔ 全局表：与 GearInsightPopularTalents 同款，主插件 ShowTalentPicker 直接读。
GearInsightPvpTalents = {
    season = 42,
    mode = "shuffle",
    top = 30,
    region = "US",
    date = "2026-09-09",
    [250] = { key = "DEATHKNIGHT/BLOOD", n = 30, pvp = {
        { id=608, name="Last Dance", cn="最终之舞", pct=90.0 },
        { id=3441, name="Decomposing Aura", cn="腐烂光环", pct=66.7 },
        { id=5592, name="Spellwarden", cn="咒术防护", pct=43.3 },
        { id=5587, name="Bloodforged Armor", cn="血锻盔甲", pct=40.0 },
        { id=609, name="Death Chain", cn="死亡锁链", pct=20.0 },
        { id=841, name="Murderous Intent", cn="杀戮意图", pct=16.7 },
        { id=206, name="Strangulate", cn="绞袭", pct=13.3 },
    }, builds = {
        { rank=1, rating=1601, player="Ttvflarkness", realm="dawnbringer", hero="Vampiric Speed", heroCn="吸血鬼之速", code="CoPAkXBWxkyfx9CbGaHonEAhLxYWmZmxMGzMMLjZGsMjxMzYGAAAAYmZmZGzMjZmBAMmZmZAAAmZ2GDjZssYsssMMsNMsNAzYGAAmZmZAjB", pvp={ { id=609, name="Death Chain", cn="死亡锁链" }, { id=608, name="Last Dance", cn="最终之舞" }, { id=3441, name="Decomposing Aura", cn="腐烂光环" } } },
        { rank=2, rating=1437, player="Horrorz", realm="tichondrius", hero="Vampiric Strike", heroCn="吸血鬼打击", code="CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmZmhZZMz0MLzMjZmBAAAAwMMzMzMjZGDAYmZmZGAAgZmtxwYGLLNW2WGmsNMsBYGDAAmZmZAjB", pvp={ { id=5592, name="Spellwarden", cn="咒术防护" }, { id=608, name="Last Dance", cn="最终之舞" }, { id=841, name="Murderous Intent", cn="杀戮意图" } } },
        { rank=3, rating=1417, player="Bloodiousosa", realm="dalaran", hero="Reaper's Mark", heroCn="死神印记", code="CoPAkXBWxkyfx9CbGaHonEAhLxY2mZGmZmZmhZxMzELzYMzMmBAAAAmZmZGmZGzMDAYMzMzMAAgZmtxwYGLLNWW2GmsNMsMAzYGAAmZmZAMA", pvp={ { id=3441, name="Decomposing Aura", cn="腐烂光环" }, { id=608, name="Last Dance", cn="最终之舞" }, { id=5592, name="Spellwarden", cn="咒术防护" } } },
    } },
    [103] = { key = "DRUID/FERAL", n = 30, pvp = {
        { id=620, name="Wicked Claws", cn="邪恶之爪", pct=93.3 },
        { id=5647, name="Tireless Pursuit", cn="不息追猎", pct=66.7 },
        { id=5384, name="High Winds", cn="高天狂风", pct=46.7 },
        { id=3053, name="Strength of the Wild", cn="野性力量", pct=43.3 },
        { id=820, name="Savage Momentum", cn="狂野冲撞", pct=40.0 },
    }, builds = {
        { rank=1, rating=2501, player="Semvetax", realm="alleria", hero="Thriving Growth", heroCn="兴荣生长", code="CcGADBD3hSPCL9Y9gz68WcKvMAAAAAAAjZWwYmZGz2yYZmlZmZMzMAAAAsEMbGYmZqZMbmZmZWGzYGAAAAAAgBAAAQzsMbzMzMLzs0sNzyGMzMALMYAAMzgZ2wA", pvp={ { id=5647, name="Tireless Pursuit", cn="不息追猎" }, { id=5384, name="High Winds", cn="高天狂风" }, { id=620, name="Wicked Claws", cn="邪恶之爪" } } },
        { rank=2, rating=2359, player="Borkdru", realm="area-52", hero="Thriving Growth", heroCn="兴荣生长", code="CcGADBD3hSPCL9Y9gz68WcKvMAAAAAAwYMzCDzMzY2WYZmlZmZMzMAAAAsEMbGYmZqZMbmZmZ2GzYGAAAAAAgBAAAQzsMbzMzMbzs0sNzyGMzMALMYAAMzgZ2wA", pvp={ { id=3053, name="Strength of the Wild", cn="野性力量" }, { id=5647, name="Tireless Pursuit", cn="不息追猎" }, { id=620, name="Wicked Claws", cn="邪恶之爪" } } },
        { rank=3, rating=2353, player="Riverside", realm="sargeras", hero="Ravage", heroCn="毁灭", code="CcGADBD3hSPCL9Y9gz68WcKvMAAAAAAgZmZ2MzMzMGzmx2YbGzMmZAAAAYJY2M8AmZUzYWMzMzsMmhBAAAAAwADAAAgmZZWmZmZ2mZpZZmlFwMDwCzwAAYmBzshB", pvp={ { id=620, name="Wicked Claws", cn="邪恶之爪" }, { id=5384, name="High Winds", cn="高天狂风" }, { id=3053, name="Strength of the Wild", cn="野性力量" } } },
    } },
    [105] = { key = "DRUID/RESTORATION", n = 30, pvp = {
        { id=5687, name="Forest Guardian", cn="森林守护者", pct=100.0 },
        { id=1215, name="Early Spring", cn="万物复苏", pct=100.0 },
        { id=5668, name="Call of Ohn'ahra", cn="欧恩哈拉的召唤", pct=80.0 },
        { id=59, name="Disentanglement", cn="解缠", pct=13.3 },
    }, builds = {
        { rank=1, rating=2790, player="Habibieu", realm="area-52", hero="Thriving Growth", heroCn="兴荣生长", code="CkGADBD3hSPCL9Y9gz68WcKvMMMmZBjxMzsMmZMmNmNLDAAAAAAAAAAsMDZzMmmZmZwsZmZmZzgZAAAAAMAgxA22GLYamZZAAMbzs0sNziNGzYYGbgmBAzMzMAMA", pvp={ { id=59, name="Disentanglement", cn="解缠" }, { id=5687, name="Forest Guardian", cn="森林守护者" }, { id=1215, name="Early Spring", cn="万物复苏" } } },
        { rank=2, rating=2763, player="Alphawolf", realm="kilrogg", hero="Dream Surge", heroCn="梦境涌现", code="CkGADBD3hSPCL9Y9gz68WcKvMMMmZBjxMzsMmZMmNmNLzAAAAAAAAAAglZIbmx0MzMwsZmZmZxgZAAAAAMAAGw22YBTzMLDAgZbmlmtZWsAzMDzYD0MAYmZmBgB", pvp={ { id=838, name="High Winds", cn="高天狂风" }, { id=5687, name="Forest Guardian", cn="森林守护者" }, { id=1215, name="Early Spring", cn="万物复苏" } } },
        { rank=3, rating=2654, player="Babzy", realm="jaedenar", hero="Dream Surge", heroCn="梦境涌现", code="CkGADBD3hSPCL9Y9gz68WcKvMMMmZDjxMzsMmZMmNmNbzAAAAAAAAAAglZILmx0MzMwsZmZmZxwDMAAAAAMAAGw22YBTzMLDAgZZmlmtZWsAzMDzYD0MAYmZmBgB", pvp={ { id=5668, name="Call of Ohn'ahra", cn="欧恩哈拉的召唤" }, { id=5687, name="Forest Guardian", cn="森林守护者" }, { id=1215, name="Early Spring", cn="万物复苏" } } },
    } },
    [62] = { key = "MAGE/ARCANE", n = 30, pvp = {
        { id=5707, name="Overpowered Barrier", cn="超强能量屏障", pct=93.3 },
        { id=637, name="Improved Mass Invisibility", cn="强化群体隐形", pct=93.3 },
        { id=5661, name="Chrono Shift", cn="时空转移", pct=90.0 },
        { id=5397, name="Arcanosphere", cn="奥能之球", pct=13.3 },
    }, builds = {
        { rank=1, rating=2587, player="Numbing", realm="sargeras", hero="Spellfire Spheres", heroCn="法术火焰宝珠", code="C4DAche08tHz49KSVf7iKFnyuNstMzyMzMbYG0MjZAAAMAgZmpZZZZmZmZWWmZiNAAWwMzMsZZmZmlZMmHwMzwCzMzMzAAMAAAzMLYmBYAwwYG", pvp={ { id=5707, name="Overpowered Barrier", cn="超强能量屏障" }, { id=637, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5661, name="Chrono Shift", cn="时空转移" } } },
        { rank=2, rating=2562, player="Austin", realm="sargeras", hero="Spellfire Spheres", heroCn="法术火焰宝珠", code="C4DAche08tHz49KSVf7iKFnyuNmtlZWmZegZDzgmZMDAAgBAMzMNLLbzMzMzyyMTsBAwCmZmhNLzMzsMjx8AzMDWYGzMzAAMAAAzMLYmBGDAGGzA", pvp={ { id=5491, name="Ring of Fire", cn="火焰之环" }, { id=637, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5707, name="Overpowered Barrier", cn="超强能量屏障" } } },
        { rank=3, rating=2434, player="Showmaker", realm="sargeras", hero="Mana Cascade", heroCn="法力涌流", code="C4DAche08tHz49KSVf7iKFnyuNzwMLzMmFMzgZmZAAAYAAzMjZZZZGAAbAAsxYmZYzyMmZZGjZMzMswMzMzMAADAAwAMzAMAYYmZA", pvp={ { id=5707, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5661, name="Chrono Shift", cn="时空转移" }, { id=637, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
    } },
    [268] = { key = "MONK/BREWMASTER", n = 30, pvp = {
        { id=667, name="Hot Trub", cn="热酿", pct=90.0 },
        { id=672, name="Double Barrel", cn="醉上加醉", pct=80.0 },
        { id=843, name="Admonishment", cn="劝诫", pct=56.7 },
        { id=666, name="Microbrew", cn="私家陈酿", pct=23.3 },
        { id=669, name="Avert Harm", cn="斗转星移", pct=13.3 },
        { id=673, name="Mighty Ox Kick", cn="蛮牛踢", pct=10.0 },
        { id=765, name="Eerie Fermentation", cn="怪味发酵", pct=10.0 },
    }, builds = {
        { rank=1, rating=1893, player="Droguex", realm="tichondrius", hero="Manifestation", heroCn="化气凝形", code="CwQAQnG51S19isUJoJoTeJ/IKDAAAgZZzYGGzyMzGzMjBAAAAAAYZBzgZGYGGbwYmZmhZjZGjlhltHYbb2wsAAALzyYZ2mZZAAAAMsxwMDYMGAAwA", pvp={ { id=667, name="Hot Trub", cn="热酿" }, { id=672, name="Double Barrel", cn="醉上加醉" }, { id=843, name="Admonishment", cn="劝诫" } } },
        { rank=2, rating=1551, player="Artam", realm="thrall", hero="Flurry Strikes", heroCn="疾风乱打", code="CwQAQnG51S19isUJoJoTeJ/IKDAAAgZbzYGGzyM2YmZAAAAAAAYZBjYmBmhxmZMmZmZmZWGMmZ7BYZ7B22mtZMLAAw2sMtMbzsMAAz2s0MzMLMsBmZmZYaMAAgB", pvp={ { id=843, name="Admonishment", cn="劝诫" }, { id=667, name="Hot Trub", cn="热酿" }, { id=672, name="Double Barrel", cn="醉上加醉" } } },
        { rank=3, rating=1426, player="Worldpvp", realm="nerzhul", hero="Aspect of Harmony", heroCn="和谐化身", code="CwQAQnG51S19isUJoJoTeJ/IKDAAAwMbbGzYmx2M2wMDAAAAAAALLYEzMzGzYmBwMzMDzCMmZZYZz22sNMLAAwysMtMbzsMAAz2s0MzMLMsxwMzMDTjBYAgB", pvp={ { id=667, name="Hot Trub", cn="热酿" }, { id=843, name="Admonishment", cn="劝诫" }, { id=672, name="Double Barrel", cn="醉上加醉" } } },
    } },
    [270] = { key = "MONK/MISTWEAVER", n = 30, pvp = {
        { id=5395, name="Peaceweaver", cn="静心织魂", pct=100.0 },
        { id=5603, name="Zen Spheres", cn="禅意法球", pct=100.0 },
        { id=70, name="Eminence", cn="龙威显赫", pct=70.0 },
        { id=1928, name="Zen Focus Tea", cn="禅意聚神茶", pct=16.7 },
        { id=679, name="Counteract Magic", cn="法术中和", pct=13.3 },
    }, builds = {
        { rank=1, rating=2676, player="Crazydogwoez", realm="kelthuzad", hero="Aspect of Harmony", heroCn="和谐化身", code="C4QAQnG51S19isUJoJoTeJ/IKDAAAAAAAghZWmZZMbWMmZwYZbZGs9AzsZbmxCzoZMDYwwwsNzMzwsNLgZbmAAAAAzy02sNzysZbmlZZmBEAMYMzMYGwAQGzA", pvp={ { id=70, name="Eminence", cn="龙威显赫" }, { id=5395, name="Peaceweaver", cn="静心织魂" }, { id=5603, name="Zen Spheres", cn="禅意法球" } } },
        { rank=2, rating=2385, player="Jadestørmz", realm="illidan", hero="Celestial Conduit", heroCn="天神御身", code="C4QAQnG51S19isUJoJoTeJ/IKDAAAAAAAghx2YZYzixMzyyM2wYGmZZZbmxCzoZMDYwgxsNzYGmtxYwiJAAAAACwilZWmtZGQAwAGgZAjhxiMmBA", pvp={ { id=5603, name="Zen Spheres", cn="禅意法球" }, { id=679, name="Counteract Magic", cn="法术中和" }, { id=5395, name="Peaceweaver", cn="静心织魂" } } },
        { rank=3, rating=2368, player="Garbagemonk", realm="scilla", hero="Aspect of Harmony", heroCn="和谐化身", code="C4QAQnG51S19isUJoJoTeJ/IKDAAAAAAAghZWmZZMbWMmZwYZbZGsNzsZbmxGGNjZADGMmtZmZGmtZBMbzEAAAAYWmWmtZWmNbzsMLzMgAgBjPYmBzAGYQGzA", pvp={ { id=5395, name="Peaceweaver", cn="静心织魂" }, { id=5603, name="Zen Spheres", cn="禅意法球" }, { id=679, name="Counteract Magic", cn="法术中和" } } },
    } },
    [269] = { key = "MONK/WINDWALKER", n = 30, pvp = {
        { id=3745, name="Turbo Fists", cn="怒雷叶轮", pct=100.0 },
        { id=3052, name="Grapple Weapon", cn="抓钩武器", pct=76.7 },
        { id=77, name="Ride the Wind", cn="驭风而行", pct=60.0 },
        { id=3737, name="Wind Waker", cn="唤风者", pct=53.3 },
    }, builds = {
        { rank=1, rating=2620, player="Stepdro", realm="tichondrius", hero="Invoke Xuen, the White Tiger", heroCn="白虎下凡", code="C0QAQnG51S19isUJoJoTeJ/IKPzYMgxYbmZ2mBAAAAAAAAAAAYZYmGmhhBMMjZmZGmNmZwyMBAswsxMmZmZgAYxMLz2YaWmlmZmZBYGDMzMDwYZAMzMbG", pvp={ { id=3052, name="Grapple Weapon", cn="抓钩武器" }, { id=3737, name="Wind Waker", cn="唤风者" }, { id=3745, name="Turbo Fists", cn="怒雷叶轮" } } },
        { rank=2, rating=2619, player="Droguex", realm="tichondrius", hero="Flurry Strikes", heroCn="疾风乱打", code="C0QAQnG51S19isUJoJoTeJ/IKbmZMgZYbmZ2mxAAAAAAAAAAAALDjwMz2wAwMmZmZY2mFGmlZCAYzMbzMMzMzABwmZwYa2mlmZmZBYYgZmZAYhxgZmZzHA", pvp={ { id=3052, name="Grapple Weapon", cn="抓钩武器" }, { id=5643, name="Rising Dragon Sweep", cn="升龙扫" }, { id=3745, name="Turbo Fists", cn="怒雷叶轮" } } },
        { rank=3, rating=2615, player="Divergent", realm="demon-soul", hero="Flurry Strikes", heroCn="疾风乱打", code="C0QAQnG51S19isUJoJoTeJ/IKbmZMYMDbzMz2MAAAAAAAAAAAALDjwMzGGwwMmZMzYWmFGmlZCAYzMLzMMzMzABwmZWmlx0sNLNzMzCwwAzMzAwyYAzMzmPA", pvp={ { id=3745, name="Turbo Fists", cn="怒雷叶轮" }, { id=77, name="Ride the Wind", cn="驭风而行" }, { id=3052, name="Grapple Weapon", cn="抓钩武器" } } },
    } },
    [256] = { key = "PRIEST/DISCIPLINE", n = 30, pvp = {
        { id=123, name="Inner Light", cn="心灵之光", pct=96.7 },
        { id=114, name="Ultimate Radiance", cn="极致光辉", pct=90.0 },
        { id=5570, name="Phase Shift", cn="相位变换", pct=73.3 },
        { id=109, name="Trinity", cn="三位一体", pct=20.0 },
        { id=126, name="Dark Archangel", cn="黑暗天使长", pct=16.7 },
    }, builds = {
        { rank=1, rating=2653, player="Smíght", realm="thrall", hero="Guiding Light", heroCn="指引之光", code="CAQAR03Gt7xPmcDNOjs2Zlb3yCDsMDWmZMzMwMbzYmZGjZGAAAAAAAAAAzMzyAjZGLzMzMssYamYwMzMbYIMmlZWmtFjxYxAAwYGGDGYmZmZmgZA", pvp={ { id=123, name="Inner Light", cn="心灵之光" }, { id=5570, name="Phase Shift", cn="相位变换" }, { id=114, name="Ultimate Radiance", cn="极致光辉" } } },
        { rank=2, rating=2651, player="Faschism", realm="illidan", hero="Guiding Light", heroCn="指引之光", code="CAQAR03Gt7xPmcDNOjs2Zlb3yCDsMGWmZMzMwMbzYmZGjZGAAAAAAAAAAzMzyMYMGLzMzMssYamYwMzMbYIMmtZ2mlFjxYxAAwYGGDGYmZmZmgB", pvp={ { id=114, name="Ultimate Radiance", cn="极致光辉" }, { id=123, name="Inner Light", cn="心灵之光" }, { id=5570, name="Phase Shift", cn="相位变换" } } },
        { rank=3, rating=2650, player="Challengerz", realm="suramar", hero="Guiding Light", heroCn="指引之光", code="CAQAR03Gt7xPmcDNOjs2Zlb3yCDsMGWmZMPwMwMbzYmZmZMzAAAAAAAAAAYmZWGYmxYZmZmhlFTzEDmZmZDDhxsNzystYMGLGAAGzwYwAYmZmgB", pvp={ { id=114, name="Ultimate Radiance", cn="极致光辉" }, { id=5570, name="Phase Shift", cn="相位变换" }, { id=123, name="Inner Light", cn="心灵之光" } } },
    } },
    [258] = { key = "PRIEST/SHADOW", n = 30, pvp = {
        { id=106, name="Driven to Madness", cn="堕入疯狂", pct=96.7 },
        { id=5568, name="Phase Shift", cn="相位变换", pct=93.3 },
        { id=763, name="Psyfiend", cn="灵能魔", pct=80.0 },
        { id=5447, name="Cascading Horrors", cn="倾泻恐怖", pct=20.0 },
    }, builds = {
        { rank=1, rating=2593, player="Envyion", realm="sargeras", hero="Halo", heroCn="光晕", code="CIQAR03Gt7xPmcDNOjs2Zlb3yOMDDAAAAAAAAAAAAmZxMmZbmxMzyMGjx2MzYmZGbIzYxMNAzMzgZ2MjmNDmtZbLjZWYAmZAjZmZMbMz2yMzgZwA", pvp={ { id=106, name="Driven to Madness", cn="堕入疯狂" }, { id=763, name="Psyfiend", cn="灵能魔" }, { id=5568, name="Phase Shift", cn="相位变换" } } },
        { rank=2, rating=2452, player="Ñótlìkëthîs", realm="kelthuzad", hero="Void Torrent", heroCn="虚空洪流", code="CIQAR03Gt7xPmcDNOjs2Zlb3yaYMAAAAAAAAAAAAYMLzMGbzMmZ2mZYMz2YGzMzYZMZYZx0AMzMDmZxMa2MY2mtlMmZjBYMzgxMjxsMmZbZmZwMYA", pvp={ { id=106, name="Driven to Madness", cn="堕入疯狂" }, { id=763, name="Psyfiend", cn="灵能魔" }, { id=5568, name="Phase Shift", cn="相位变换" } } },
        { rank=3, rating=2450, player="Ruberhosex", realm="kelthuzad", hero="Void Torrent", heroCn="虚空洪流", code="CIQAR03Gt7xPmcDNOjs2Zlb3yaYMAAAAAAAAAAAAYMLzMGbzMmZ2mZYMz2YGzMzYZMZYZx0AMzMDmZxMa2MY2mtlMmZjBYMzgxMjxsMzYbZmZwMYA", pvp={ { id=106, name="Driven to Madness", cn="堕入疯狂" }, { id=5447, name="Cascading Horrors", cn="倾泻恐怖" }, { id=5568, name="Phase Shift", cn="相位变换" } } },
    } },
    [263] = { key = "SHAMAN/ENHANCEMENT", n = 30, pvp = {
        { id=722, name="Shamanism", cn="萨满之道", pct=96.7 },
        { id=5575, name="Burrow", cn="掘地三尺", pct=86.7 },
        { id=3622, name="Grounding Totem", cn="根基图腾", pct=83.3 },
        { id=3489, name="Counterstrike Totem", cn="反击图腾", pct=13.3 },
        { id=5438, name="Static Field Totem", cn="静电力场图腾", pct=13.3 },
    }, builds = {
        { rank=1, rating=2587, player="Resetmmr", realm="stormrage", hero="Tempest", heroCn="狂风怒号", code="CcQALMl7AwW51MWzGneuHE3tPOzMDMzMzMzMMzMDAAAAAAAAwGWw2yMmZWW0ssNMDzMNYBgZZwYmtlZsMGz2MbGzMMz2YGAgZYmZGzMxMzMDGMGA", pvp={ { id=3622, name="Grounding Totem", cn="根基图腾" }, { id=5575, name="Burrow", cn="掘地三尺" }, { id=722, name="Shamanism", cn="萨满之道" } } },
        { rank=2, rating=2555, player="Madeofpaper", realm="stormrage", hero="Tempest", heroCn="狂风怒号", code="CcQALMl7AwW51MWzGneuHE3tPOzMDMzMzMzMMzMDAAAAAAAAwGWw2yMmZWW0ssNMDzMNYBgZZwYmtlZswY2MbmZmhZ2GzAAMDzMzYmJmZmZwgxA", pvp={ { id=3622, name="Grounding Totem", cn="根基图腾" }, { id=5575, name="Burrow", cn="掘地三尺" }, { id=722, name="Shamanism", cn="萨满之道" } } },
        { rank=3, rating=2482, player="Laabuubuu", realm="malganis", hero="Tempest", heroCn="狂风怒号", code="CcQALMl7AwW51MWzGneuHE3tPOzMDMzMzMzMMzMDAAAAAAAAwGWw2yMmZ2W0ssNMDzMNYBgZbwYmllZsYmZ2YxMzMM2GzAAMDzMzYmJmZmZwgxA", pvp={ { id=5575, name="Burrow", cn="掘地三尺" }, { id=722, name="Shamanism", cn="萨满之道" }, { id=3622, name="Grounding Totem", cn="根基图腾" } } },
    } },
    [264] = { key = "SHAMAN/RESTORATION", n = 30, pvp = {
        { id=715, name="Grounding Totem", cn="根基图腾", pct=93.3 },
        { id=5723, name="Lightning Lasso", cn="闪电磁索", pct=63.3 },
        { id=5437, name="Master of the Elements", cn="元素宗师", pct=60.0 },
        { id=5567, name="Static Field Totem", cn="静电力场图腾", pct=43.3 },
        { id=3755, name="Rain Dance", cn="祈雨舞", pct=20.0 },
        { id=5705, name="Totem of Wrath", cn="天怒图腾", pct=10.0 },
    }, builds = {
        { rank=1, rating=2613, player="Koksammy", realm="tichondrius", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CgQALMl7AwW51MWzGneuHE3tPCAAAgBAAAAzMzYbbGmZmZmxMzYssMzmNGzYZasNzCTmhxCmZwsNGjmllZmFzAzi5BmZMzsNbGAAAYmBzMYmhZgB", pvp={ { id=5723, name="Lightning Lasso", cn="闪电磁索" }, { id=5437, name="Master of the Elements", cn="元素宗师" }, { id=715, name="Grounding Totem", cn="根基图腾" } } },
        { rank=2, rating=2555, player="Mjölnîr", realm="aggramar", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CgQALMl7AwW51MWzGneuHE3tPCAAAgBAAAAzMzYbZGmZmZmxMzYstMziNGzYZasNzCTmhxCmZws8AGjmtFzsMGDWMmZmZmtZzAAAAzMYmBzMMzgB", pvp={ { id=5437, name="Master of the Elements", cn="元素宗师" }, { id=5723, name="Lightning Lasso", cn="闪电磁索" }, { id=715, name="Grounding Totem", cn="根基图腾" } } },
        { rank=3, rating=2439, player="Illixx", realm="area-52", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CgQALMl7AwW51MWzGneuHE3tPCAAAgBAAAAzMzYbZGmZmZmxMzYssMzmNGzYZasNzGTmhxCmZwsMGz0ssMzsYGwixMjZmtZzAAAAzMYmBzMMzgB", pvp={ { id=5567, name="Static Field Totem", cn="静电力场图腾" }, { id=5437, name="Master of the Elements", cn="元素宗师" }, { id=715, name="Grounding Totem", cn="根基图腾" } } },
    } },
    [265] = { key = "WARLOCK/AFFLICTION", n = 30, pvp = {
        { id=5386, name="Jinx", cn="祸不单行", pct=100.0 },
        { id=5579, name="Impish Instincts", cn="小鬼本能", pct=73.3 },
        { id=18, name="Nether Ward", cn="虚空守卫", pct=50.0 },
        { id=15, name="Gateway Mastery", cn="传送门大师", pct=36.7 },
        { id=16, name="Rot and Decay", cn="腐化枯萎", pct=33.3 },
    }, builds = {
        { rank=1, rating=2561, player="Stinkie", realm="nerzhul", hero="Wither", heroCn="枯萎", code="CkQAMrNP5kak+EBqLfUa3dMm+uMm5BmZ0sxYhZmZZAAAmZWmtZmZbMAwsssMGGziZaMzMslZjhlBAAgZAAgZmZmZmZGjZMMjZmZmBzMmBAMgB", pvp={ { id=18, name="Nether Ward", cn="虚空守卫" }, { id=16, name="Rot and Decay", cn="腐化枯萎" }, { id=5386, name="Jinx", cn="祸不单行" } } },
        { rank=2, rating=2530, player="Skide", realm="sargeras", hero="Demonic Soul", heroCn="恶魔之魂", code="CkQAMrNP5kak+EBqLfUa3dMm+uMGmZ0sNzYhZmZZAAAmZWsZmZxMAwsssMGGziZaMzMslZjhtBAAgZAAgZmZmZmZmZMzMMjZmZmBzYGAgBMA", pvp={ { id=5386, name="Jinx", cn="祸不单行" }, { id=5579, name="Impish Instincts", cn="小鬼本能" }, { id=18, name="Nether Ward", cn="虚空守卫" } } },
        { rank=3, rating=2526, player="Bronzerl", realm="stormrage", hero="Necrolyte Teachings", heroCn="通灵教义", code="CkQAMrNP5kak+EBqLfUa3dMm+uMGmZY2mZswMzsMAAAzML2MzsYGAYWWWGDjZxMwMDbMLMsNAAAMDAAYmZmZmZmZMzMMjZmZmBzYGAgBMA", pvp={ { id=16, name="Rot and Decay", cn="腐化枯萎" }, { id=5579, name="Impish Instincts", cn="小鬼本能" }, { id=5386, name="Jinx", cn="祸不单行" } } },
    } },
    [267] = { key = "WARLOCK/DESTRUCTION", n = 30, pvp = {
        { id=157, name="Fel Fissure", cn="邪能裂痕", pct=86.7 },
        { id=3508, name="Nether Ward", cn="虚空守卫", pct=80.0 },
        { id=5580, name="Impish Instincts", cn="小鬼本能", pct=63.3 },
        { id=5607, name="Soul Rip", cn="夺魂", pct=36.7 },
        { id=5382, name="Gateway Mastery", cn="传送门大师", pct=30.0 },
    }, builds = {
        { rank=1, rating=2594, player="Diábolical", realm="sargeras", hero="Wither", heroCn="枯萎", code="CsQAMrNP5kak+EBqLfUa3dMm+uMGzMjmtZGLMzMLzCzYWMmtFzAAgZmxMzsYDzMjZWWGNzMsMsMbN2YAAgxAzsBgZmZGMzMzYAAAYGDAAGDD", pvp={ { id=5382, name="Gateway Mastery", cn="传送门大师" }, { id=3508, name="Nether Ward", cn="虚空守卫" }, { id=5580, name="Impish Instincts", cn="小鬼本能" } } },
        { rank=2, rating=2545, player="Papajohns", realm="illidan", hero="Wither", heroCn="枯萎", code="CsQAMrNP5kak+EBqLfUa3dMm+uMGPwMjmtZGLMzMLjxMmlZMLLmBAAzMjZmZxCmZGzssNamZYbYZ2asxAAADAbAYmZmBzMzMGAAAmxMAAMzwA", pvp={ { id=3508, name="Nether Ward", cn="虚空守卫" }, { id=5580, name="Impish Instincts", cn="小鬼本能" }, { id=157, name="Fel Fissure", cn="邪能裂痕" } } },
        { rank=3, rating=2535, player="Stinkie", realm="nerzhul", hero="Diabolic Ritual", heroCn="敬魔仪式", code="CsQAMrNP5kak+EBqLfUa3dMm+uMGPwMz0sNzYjZmZZMmxsYMLLmBAAzMjZmZxCmZGzssMamZYZYZ2aswAAAjBYDAzMzMYmZMGAAAmZMAAMzwA", pvp={ { id=5607, name="Soul Rip", cn="夺魂" }, { id=3508, name="Nether Ward", cn="虚空守卫" }, { id=157, name="Fel Fissure", cn="邪能裂痕" } } },
    } },
    [71] = { key = "WARRIOR/ARMS", n = 30, pvp = {
        { id=33, name="Sharpen Blade", cn="打磨利刃", pct=100.0 },
        { id=3534, name="Disarm", cn="缴械", pct=66.7 },
        { id=5625, name="Safeguard", cn="捍卫", pct=53.3 },
        { id=31, name="Storm of Destruction", cn="毁灭风暴", pct=43.3 },
        { id=5701, name="Berserker Roar", cn="狂战士咆哮", pct=26.7 },
    }, builds = {
        { rank=1, rating=2539, player="Xingming", realm="blackrock", hero="Slayer's Dominance", heroCn="屠戮之霸", code="CcEASWsDSHNyPDXnbxuIhH3ZdjZmZmFz8AmZGAAAghphZGzYhZmZGGzMDAAAAgxyMDMhxy2sYmthNDDzMz0CNzgNgZsYWmBLzsNYmZmBgZGGA", pvp={ { id=33, name="Sharpen Blade", cn="打磨利刃" }, { id=5625, name="Safeguard", cn="捍卫" }, { id=3534, name="Disarm", cn="缴械" } } },
        { rank=2, rating=2510, player="Magnusz", realm="zuljin", hero="Slayer's Dominance", heroCn="屠戮之霸", code="CcEASWsDSHNyPDXnbxuIhH3ZdjZmZmFzMmZGAAAghJMzMzMbbmZmBDzMAAAAAGLzMgwYZbWMz2wmhhZmZajmZwGYmxyYZGsMz2gZmZGAMDDA", pvp={ { id=33, name="Sharpen Blade", cn="打磨利刃" }, { id=5625, name="Safeguard", cn="捍卫" }, { id=31, name="Storm of Destruction", cn="毁灭风暴" } } },
        { rank=3, rating=2495, player="Xenrai", realm="blackrock", hero="Imminent Demise", heroCn="殒命在即", code="CcEASWsDSHNyPDXnbxuIhH3ZdjZmZmFzMmZAAAAMMGmZMjFmZmZYMzMAAAAAGLzMwAjlthZ2G2MgZmZAzMYDYGLmlZwyMbDmZmZAYmhBA", pvp={ { id=33, name="Sharpen Blade", cn="打磨利刃" }, { id=5625, name="Safeguard", cn="捍卫" }, { id=3534, name="Disarm", cn="缴械" } } },
    } },
    [73] = { key = "WARRIOR/PROTECTION", n = 30, pvp = {
        { id=171, name="Morale Killer", cn="士气重挫", pct=70.0 },
        { id=175, name="Thunderstruck", cn="雷霆打击", pct=46.7 },
        { id=5715, name="Power Through Adversity", cn="逆势奋发", pct=36.7 },
        { id=831, name="Dragon Charge", cn="巨龙冲锋", pct=23.3 },
        { id=24, name="Disarm", cn="缴械", pct=20.0 },
        { id=5627, name="Storm of Destruction", cn="毁灭风暴", pct=20.0 },
        { id=168, name="Bodyguard", cn="护卫", pct=16.7 },
        { id=173, name="Shield Bash", cn="盾击", pct=16.7 },
    }, builds = {
        { rank=1, rating=1515, player="Megasmilax", realm="tichondrius", hero="Crashing Thunder", heroCn="崩解闪电", code="CkEASWsDSHNyPDXnbxuIhH3ZdbZAAgxMjZmZGjZzMzyADjxMzYZzMzMYMzMAAAAYZmBYGDwAbwyihxMAmFMzGmhZGmZBAmZAAYGYMA", pvp={ { id=24, name="Disarm", cn="缴械" }, { id=168, name="Bodyguard", cn="护卫" }, { id=171, name="Morale Killer", cn="士气重挫" } } },
        { rank=2, rating=1304, player="Smirm", realm="thrall", hero="Lightning Strikes", heroCn="闪电打击", code="CkEASWsDSHNyPDXnbxuIhH3ZdnBAAGzwMzMzMmNzMLzYMGNmxwyMzMzYGmZAAAAwyMDwMGgB2glFjGzAYWiZ2gxMDMbAwMDAAzAjB", pvp={ { id=5626, name="Safeguard", cn="捍卫" }, { id=171, name="Morale Killer", cn="士气重挫" }, { id=175, name="Thunderstruck", cn="雷霆打击" } } },
        { rank=3, rating=1196, player="Zelail", realm="vashj", hero="Martial Expert", heroCn="武艺专家", code="CkEASWsDSHNyPDXnbxuIhH3ZdbbAAgZmxMzMzYmZzMzywYMjZmxMbmZMDzMzMDAAAAWmBwMAMYbbGzy2ywMzwMsNLGzsgxwAzCAMzMzAAGwYA", pvp={ { id=171, name="Morale Killer", cn="士气重挫" }, { id=5715, name="Power Through Adversity", cn="逆势奋发" }, { id=173, name="Shield Bash", cn="盾击" } } },
    } },
    [1480] = { key = "DEMONHUNTER/DEVOURER", n = 29, pvp = {
        { id=5735, name="Beckon", cn="召唤", pct=100.0 },
        { id=5734, name="Glimpse", cn="转瞬即逝", pct=72.4 },
        { id=5729, name="Armor of Souls", cn="灵魂护甲", pct=72.4 },
        { id=5738, name="Reverse Magic", cn="反转魔法", pct=24.1 },
        { id=5730, name="Surrender to the Void", cn="向虚空屈服", pct=17.2 },
    }, builds = {
        { rank=1, rating=2704, player="Mvqx", realm="illidan", hero="Demonsurge", heroCn="魔涌", code="CgcBp/epaxe7D0A403L+Tvk0iCAMjZmZmxMjhZAAAAAAAYMGzMDAAAAAAAAzYGmZmZmxMzMMz2Mjxm2WAQADwMmZmlZmpZZmlZmxwA", pvp={ { id=5735, name="Beckon", cn="召唤" }, { id=5734, name="Glimpse", cn="转瞬即逝" }, { id=5729, name="Armor of Souls", cn="灵魂护甲" } } },
        { rank=2, rating=2635, player="Akumma", realm="tichondrius", hero="Voidfall", heroCn="虚落", code="CgcBp/epaxe7D0A403L+Tvk0iCAMjZmZMzMjhBAAAAAAAjZZMzMAAAAAAAAMjZYeAzMzYmZmZmZxMzYRLLMzMzs12MzMAmxMzsMzMNLzsMDDMfA", pvp={ { id=5729, name="Armor of Souls", cn="灵魂护甲" }, { id=5734, name="Glimpse", cn="转瞬即逝" }, { id=5735, name="Beckon", cn="召唤" } } },
        { rank=3, rating=2595, player="Ttndh", realm="proudmoore", hero="Voidfall", heroCn="虚落", code="CgcBp/epaxe7D0A403L+Tvk0iCAMjZmZMmZMMDAAAAAAgHYMGzMDAAAAAAAAzYGmxMzMmZmZmZWMjxiWWYmZmZrtZmZAMjZmZZmZaWmZZGGY+AA", pvp={ { id=5729, name="Armor of Souls", cn="灵魂护甲" }, { id=5735, name="Beckon", cn="召唤" }, { id=5730, name="Surrender to the Void", cn="向虚空屈服" } } },
    } },
    [577] = { key = "DEMONHUNTER/HAVOC", n = 29, pvp = {
        { id=5433, name="Blood Moon", cn="鲜血之月", pct=100.0 },
        { id=813, name="Glimpse", cn="转瞬即逝", pct=89.7 },
        { id=806, name="Reverse Magic", cn="反转魔法", pct=58.6 },
        { id=811, name="Rain from Above", cn="从天而降", pct=34.5 },
        { id=812, name="Detainment", cn="拘押", pct=17.2 },
    }, builds = {
        { rank=1, rating=2770, player="Natooeasy", realm="area-52", hero="Art of the Glaive", heroCn="战刃绝技", code="CEkAp/epaxe7D0A403L+Tvk0iygZmZMjxMjZmJDzAAAAAAAmFjxMzMzMbzMjlZGzYZmhZ2mZZmlZZmZmltZZaaGzMmxCAAAAAACwMzMDGACAAM", pvp={ { id=813, name="Glimpse", cn="转瞬即逝" }, { id=5433, name="Blood Moon", cn="鲜血之月" }, { id=806, name="Reverse Magic", cn="反转魔法" } } },
        { rank=2, rating=2653, player="Golrathx", realm="thrall", hero="Art of the Glaive", heroCn="战刃绝技", code="CEkAp/epaxe7D0A403L+Tvk0iygZmZYMzMjZmJDDAAAAAAwsMjxYmZmZbmZmlZGzYbYbmZbmlZ2mlZmZW2mtppZMzYGLAAAAAAIAzMzMYAIAAwA", pvp={ { id=813, name="Glimpse", cn="转瞬即逝" }, { id=811, name="Rain from Above", cn="从天而降" }, { id=5433, name="Blood Moon", cn="鲜血之月" } } },
        { rank=3, rating=2626, player="Arandom", realm="thrall", hero="Demonsurge", heroCn="魔涌", code="CEkAp/epaxe7D0A403L+Tvk0iygZmZYMmZMzMNDDAAAAAAwsMjxYmZmZbmZsMzYGbzMMz2MLzsMLzMzssNLTTzYmxM2AAAAAAQAmZmZwAQAAgB", pvp={ { id=811, name="Rain from Above", cn="从天而降" }, { id=806, name="Reverse Magic", cn="反转魔法" }, { id=5433, name="Blood Moon", cn="鲜血之月" } } },
    } },
    [104] = { key = "DRUID/GUARDIAN", n = 29, pvp = {
        { id=51, name="Den Mother", cn="兽穴之母", pct=86.2 },
        { id=196, name="Overrun", cn="蛮力冲锋", pct=65.5 },
        { id=52, name="Demoralizing Roar", cn="挫志咆哮", pct=55.2 },
        { id=194, name="Charging Bash", cn="横冲直撞", pct=20.7 },
        { id=842, name="Alpha Challenge", cn="头号挑战", pct=17.2 },
        { id=1237, name="Malorne's Swiftness", cn="玛洛恩的迅捷", pct=17.2 },
        { id=5410, name="Grove Protection", cn="林地守护", pct=13.8 },
        { id=3750, name="Freedom of the Herd", cn="兽群的自由", pct=10.3 },
    }, builds = {
        { rank=1, rating=1887, player="Zyhsul", realm="emerald-dream", hero="Boundless Moonlight", heroCn="天涯共银辉", code="CgGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAgZmxsYmZMzmZz4BMWGwmhRTz0MzsZmZmZZMzDYAAAAAAzYxMw22MDGzyAYqZWmlZmZAAsZMDgFDMgFLbAmZmZDG", pvp={ { id=52, name="Demoralizing Roar", cn="挫志咆哮" }, { id=51, name="Den Mother", cn="兽穴之母" }, { id=196, name="Overrun", cn="蛮力冲锋" } } },
        { rank=2, rating=1462, player="Bigpredator", realm="drakkari", hero="Moon Guardian", heroCn="辉月卫士", code="CgGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAgZmxsYmZMzmZz4BMWGwmZMMmxMzsZmZmZZMDAAAAAAzMLzA2WmZwYWGADzsMLzMzAAYzYGALGYALW2AMzMzGMA", pvp={ { id=51, name="Den Mother", cn="兽穴之母" }, { id=842, name="Alpha Challenge", cn="头号挑战" }, { id=196, name="Overrun", cn="蛮力冲锋" } } },
        { rank=3, rating=1304, player="Ironaddlct", realm="frostmourne", hero="Boundless Moonlight", heroCn="天涯共银辉", code="CgGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAgZmZmFzYMzyMLGjZZZgZzMGNRGz2YmZmlxMPAAAAAAAmlZALbzMYMLDgpmZZWmZmBAwmxMDwmBGMYZDwMzMbwHA", pvp={ { id=196, name="Overrun", cn="蛮力冲锋" }, { id=52, name="Demoralizing Roar", cn="挫志咆哮" }, { id=51, name="Den Mother", cn="兽穴之母" } } },
    } },
    [1473] = { key = "EVOKER/AUGMENTATION", n = 29, pvp = {
        { id=5563, name="Obsidian Mettle", cn="黑曜之勇", pct=93.1 },
        { id=5560, name="Unburdened Flight", cn="轻驰飞翔", pct=75.9 },
        { id=5561, name="Scouring Flame", cn="冲刷之焰", pct=65.5 },
        { id=5619, name="Time Stop", cn="时间停止", pct=27.6 },
        { id=5558, name="Nullifying Shroud", cn="废灵遮罩", pct=17.2 },
    }, builds = {
        { rank=1, rating=2117, player="Youginong", realm="tichondrius", hero="Mass Eruption", heroCn="大规模喷发", code="CEcBPJc41CfcseY0baneJ1IHrNMzMbzMzMWmBzsNMzMmBAAAAAGAAwMMzwYM1YmZGAAAAYmZGmZWGzMwMLGDzyMWWmlhZ2GmhZmGxGGDMzAYA", pvp={ { id=5561, name="Scouring Flame", cn="冲刷之焰" }, { id=5560, name="Unburdened Flight", cn="轻驰飞翔" }, { id=5563, name="Obsidian Mettle", cn="黑曜之勇" } } },
        { rank=2, rating=2026, player="Augdog", realm="darkspear", hero="Mass Eruption", heroCn="大规模喷发", code="CEcBPJc41CfcseY0baneJ1IHrhZmZbmZmhZwMbDzMjZWAAAAAAAAwMjZmxYomZmZGAAAAYGDmZ2GzMwMLzYYWmx2ysMMz2wMMz0I2wYgZGYYA", pvp={ { id=5619, name="Time Stop", cn="时间停止" }, { id=5563, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5560, name="Unburdened Flight", cn="轻驰飞翔" } } },
        { rank=3, rating=1881, player="Evoketage", realm="malganis", hero="Chrono Flame", heroCn="时序烈焰", code="CEcBPJc41CfcseY0baneJ1IHrhZGbzMzM2mxMzsMMzMmZBAAAAADAAMzMMzYMUzYmZAAAAwMzMYmZZMDwsYMMbzYbbWGmZbYGmZaELYMmZAgB", pvp={ { id=5563, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5560, name="Unburdened Flight", cn="轻驰飞翔" }, { id=5561, name="Scouring Flame", cn="冲刷之焰" } } },
    } },
    [1468] = { key = "EVOKER/PRESERVATION", n = 29, pvp = {
        { id=5468, name="Nullifying Shroud", cn="废灵遮罩", pct=100.0 },
        { id=5718, name="Emerald Communion", cn="翡翠交融", pct=100.0 },
        { id=5461, name="Scouring Flame", cn="冲刷之焰", pct=72.4 },
        { id=5459, name="Obsidian Mettle", cn="黑曜之勇", pct=17.2 },
        { id=5470, name="Unburdened Flight", cn="轻驰飞翔", pct=10.3 },
    }, builds = {
        { rank=1, rating=2571, player="Trantis", realm="tichondrius", hero="Legacy of the Lifebinder", heroCn="生命缚誓者的传承", code="CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZwMwsNMAAwMMzMGDz0YmZAAAgtZmZaGMzMLjZAgxMjZW2YxCDzMz0QzmZsZYMzgZGGA", pvp={ { id=5461, name="Scouring Flame", cn="冲刷之焰" }, { id=5468, name="Nullifying Shroud", cn="废灵遮罩" }, { id=5718, name="Emerald Communion", cn="翡翠交融" } } },
        { rank=2, rating=2541, player="Mackthëknife", realm="tichondrius", hero="Legacy of the Lifebinder", heroCn="生命缚誓者的传承", code="CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZYGGsNMAAwMMzMGDzEzMDAAAsNzMTzYMzMLjZAgxMjZW2YxCDzMz0QzmhNDjZGMzwA", pvp={ { id=5718, name="Emerald Communion", cn="翡翠交融" }, { id=5468, name="Nullifying Shroud", cn="废灵遮罩" }, { id=5461, name="Scouring Flame", cn="冲刷之焰" } } },
        { rank=3, rating=2467, player="Romancer", realm="llane", hero="Legacy of the Lifebinder", heroCn="生命缚誓者的传承", code="CwbBPJc41CfcseY0baneJ1IHrBAAAAAegZmZ22GYYmZYmxDwsNMAAwMMzMGDzEzMDAAAsNzMTzYMzMLjZAgxMjZW2YxCDzMz0QzmhNDjZGMzwA", pvp={ { id=5468, name="Nullifying Shroud", cn="废灵遮罩" }, { id=5461, name="Scouring Flame", cn="冲刷之焰" }, { id=5718, name="Emerald Communion", cn="翡翠交融" } } },
    } },
    [254] = { key = "HUNTER/MARKSMANSHIP", n = 29, pvp = {
        { id=5745, name="Scatter Shot", cn="驱散射击", pct=100.0 },
        { id=651, name="Survival Tactics", cn="生存战术", pct=100.0 },
        { id=653, name="Chimaeral Sting", cn="奇美拉钉刺", pct=75.9 },
        { id=659, name="Ranger's Finesse", cn="游侠的灵巧", pct=13.8 },
    }, builds = {
        { rank=1, rating=2594, player="Ilidariban", realm="stormrage", hero="Sentinel", heroCn="警戒", code="C4PAD57yiELKEty14ekTDtZEqYbZWGDjZMTjlZG2yMMbAAAAAAAAgZgZsYMzMzMYGNjZmZ2W2mZYmhZmtxYZYmBAAMzYmhZGMjtFMDwCzsMjB", pvp={ { id=659, name="Ranger's Finesse", cn="游侠的灵巧" }, { id=5745, name="Scatter Shot", cn="驱散射击" }, { id=651, name="Survival Tactics", cn="生存战术" } } },
        { rank=2, rating=2587, player="Pvpdevsuc", realm="stormrage", hero="Sentinel", heroCn="警戒", code="C4PAD57yiELKEty14ekTDtZEqYbZWGDjZMTjlZG2yMMbAAAAAAAAgZgZsYMzMzMYGNjZmZ2WWmZYmhZmtxYZYmBAAMzYmhZGMjtFMDwCzsMjB", pvp={ { id=651, name="Survival Tactics", cn="生存战术" }, { id=5745, name="Scatter Shot", cn="驱散射击" }, { id=659, name="Ranger's Finesse", cn="游侠的灵巧" } } },
        { rank=3, rating=2554, player="Kanlaomei", realm="tichondrius", hero="Sentinel", heroCn="警戒", code="C4PAD57yiELKEty14ekTDtZEqYbZWGDjZMTjlZG2yMMbAAAAAAAAgZYMzyyMmxMzAjmxMzMbWmBmZmZmlxMLDzAAAMzYmhZGMjtFMDwCzsMjB", pvp={ { id=651, name="Survival Tactics", cn="生存战术" }, { id=5745, name="Scatter Shot", cn="驱散射击" }, { id=653, name="Chimaeral Sting", cn="奇美拉钉刺" } } },
    } },
    [64] = { key = "MAGE/FROST", n = 29, pvp = {
        { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形", pct=100.0 },
        { id=5708, name="Overpowered Barrier", cn="超强能量屏障", pct=82.8 },
        { id=5581, name="Master Shepherd", cn="牧羊大师", pct=48.3 },
        { id=5497, name="Snowdrift", cn="积雪", pct=37.9 },
        { id=5390, name="Ice Wall", cn="冰墙", pct=27.6 },
    }, builds = {
        { rank=1, rating=2481, player="Polynike", realm="tichondrius", hero="Augury Abounds", heroCn="满目征兆", code="CAEAche08tHz49KSVf7iKFnyuZGGLzMzsMmZGMzMjZmZmZxMzMmxMAAAwMzMLLzM2AAAAAAgNA2WGzMzgZbYMDbAAAMzGwMwAmBDD", pvp={ { id=5581, name="Master Shepherd", cn="牧羊大师" }, { id=5708, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
        { rank=2, rating=2454, player="Goküü", realm="emerald-dream", hero="Augury Abounds", heroCn="满目征兆", code="CAEAche08tHz49KSVf7iKFnyuNmtlZWmZmZDzMYGmZmZmZWMzMjZMzsMjZmlZBAMzMzyyMjNAAYBAAAsBw2yYmZALGjZmtFAAAmZZmBzwYGAMA", pvp={ { id=5708, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5497, name="Snowdrift", cn="积雪" } } },
        { rank=3, rating=2419, player="Adachisakura", realm="tichondrius", hero="Augury Abounds", heroCn="满目征兆", code="CAEAche08tHz49KSVf7iKFnyuNmtlZWmZmZDzMYGmZmZmZWMzMjZMDAAAMzMzyyMjNAAYBAAAsBw2yYmZALzDYMzYBAAgZWAmhxMgBDA", pvp={ { id=5708, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5581, name="Master Shepherd", cn="牧羊大师" } } },
    } },
    [65] = { key = "PALADIN/HOLY", n = 29, pvp = {
        { id=640, name="Divine Vision", cn="神圣视野", pct=96.6 },
        { id=5692, name="Blessing of Spellwarding", cn="破咒祝福", pct=62.1 },
        { id=87, name="Spreading the Word", cn="广布圣言", pct=51.7 },
        { id=642, name="Cleanse the Weak", cn="净化虚弱", pct=48.3 },
        { id=5583, name="Searing Glare", cn="灼热凝视", pct=20.7 },
        { id=5663, name="Divine Plea", cn="神圣恳求", pct=13.8 },
    }, builds = {
        { rank=1, rating=2525, player="Miswalkpally", realm="ragnaros", hero="Dawnlight", heroCn="晨光", code="CEEAzbn3egSOtoSwvPw1U1vTLAAAALAwMAAD2GzMzMjZmZBmZYZsZmFjmYYMzMMmtMAMAsB2YbmZmlZbmZ2aAAD2WsNwCwgNDMjZYGAAzMMjxoB", pvp={ { id=5663, name="Divine Plea", cn="神圣恳求" }, { id=640, name="Divine Vision", cn="神圣视野" }, { id=5692, name="Blessing of Spellwarding", cn="破咒祝福" } } },
        { rank=2, rating=2514, player="Juicedaddy", realm="blackhand", hero="Holy Armaments", heroCn="神圣军备", code="CEEAzbn3egSOtoSwvPw1U1vTLAAAAbAwMAADWGGMzyMzsMjZMsN2MziZaiZZGmZYYLDADAbgNzmZGAEAwMzy2itZG2YDM2YYmxMjZAMzAYMY0A", pvp={ { id=5692, name="Blessing of Spellwarding", cn="破咒祝福" }, { id=640, name="Divine Vision", cn="神圣视野" }, { id=5583, name="Searing Glare", cn="灼热凝视" } } },
        { rank=3, rating=2477, player="Ànotherx", realm="illidan", hero="Holy Armaments", heroCn="神圣军备", code="CEEAzbn3egSOtoSwvPw1U1vTLAAAAbAwMAADWGGMz2MzsMDjhtx2MziZaiZZGzMzYYJDADAbgNziZmZZ2mZmlGAwMzy2ilZG2YjHA2YGzMbGmBwMDAGQDA", pvp={ { id=5692, name="Blessing of Spellwarding", cn="破咒祝福" }, { id=642, name="Cleanse the Weak", cn="净化虚弱" }, { id=640, name="Divine Vision", cn="神圣视野" } } },
    } },
    [70] = { key = "PALADIN/RETRIBUTION", n = 29, pvp = {
        { id=752, name="Blessing of Sanctuary", cn="庇护祝福", pct=96.6 },
        { id=5535, name="Hallowed Ground", cn="神圣之地", pct=79.3 },
        { id=5573, name="Blessing of Spellwarding", cn="破咒祝福", pct=58.6 },
        { id=5584, name="Searing Glare", cn="灼热凝视", pct=34.5 },
        { id=81, name="Luminescence", cn="明光", pct=17.2 },
    }, builds = {
        { rank=1, rating=2702, player="Claudiogodtv", realm="nemesis", hero="Dawnlight", heroCn="晨光", code="CYEAzbn3egSOtoSwvPw1U1vTLAAAAAANLbzMzywMjBAAAAAYmysMDzw2w2wMbzYMmZYGLsNAMLz2Mzs1Mz02Mz2MAgFADDMmZmNDMjhNsNzMzwYYwA", pvp={ { id=5573, name="Blessing of Spellwarding", cn="破咒祝福" }, { id=81, name="Luminescence", cn="明光" }, { id=752, name="Blessing of Sanctuary", cn="庇护祝福" } } },
        { rank=2, rating=2685, player="Dentabilis", realm="area-52", hero="Dawnlight", heroCn="晨光", code="CYEAzbn3egSOtoSwvPw1U1vTLAAAAAANLbzMzyYmZMAAAAAAzUmlZYG2G2GmZZGPgxMDzYhtBgZZWmZmtmZmWMjZAALAGAzMmxMDmxwGMzMzwYYwA", pvp={ { id=752, name="Blessing of Sanctuary", cn="庇护祝福" }, { id=5573, name="Blessing of Spellwarding", cn="破咒祝福" }, { id=5535, name="Hallowed Ground", cn="神圣之地" } } },
        { rank=3, rating=2611, player="Deathboundtv", realm="sargeras", hero="Dawnlight", heroCn="晨光", code="CYEAzbn3egSOtoSwvPw1U1vTLAAAAAANLbzMzywYMAAAAAAzUGzwMzsMsNMz2MGjZGmxCbDDYWmlZmZrZmptZmtZAALAGAzMmhBmxwGWmZmZGjhBD", pvp={ { id=752, name="Blessing of Sanctuary", cn="庇护祝福" }, { id=5535, name="Hallowed Ground", cn="神圣之地" }, { id=5584, name="Searing Glare", cn="灼热凝视" } } },
    } },
    [257] = { key = "PRIEST/HOLY", n = 29, pvp = {
        { id=124, name="Spirit of the Redeemer", cn="救赎者之魂", pct=100.0 },
        { id=5569, name="Phase Shift", cn="相位变换", pct=100.0 },
        { id=101, name="Psychic Shroud", cn="心灵帷幕", pct=41.4 },
        { id=108, name="Sanctified Ground", cn="神圣之地", pct=37.9 },
        { id=5479, name="Purification", cn="纯净御罪", pct=20.7 },
    }, builds = {
        { rank=1, rating=2656, player="Peat", realm="hyjal", hero="Guiding Light", heroCn="指引之光", code="CEQAR03Gt7xPmcDNOjs2Zlb3yCDAAAAAAYxwMz2YmxMjhZglZmZGAAAAzYWmBzMzwMjZAMTBwMLzsMzkZbmZZAmZGsYmZWA0MmZMGMz2ygZmZgB", pvp={ { id=124, name="Spirit of the Redeemer", cn="救赎者之魂" }, { id=101, name="Psychic Shroud", cn="心灵帷幕" }, { id=5569, name="Phase Shift", cn="相位变换" } } },
        { rank=2, rating=2595, player="Lovelike", realm="tichondrius", hero="Guiding Light", heroCn="指引之光", code="CEQAR03Gt7xPmcDNOjs2Zlb3yyYAAAAAAAmZmxsNzMmZGDzgZbmZmBAAAwMzsMwYMWmxMDLLGzUAMz2MLzMZWmZ2GgZmBLGDAaGzYGDGbLDmZmB+AA", pvp={ { id=5569, name="Phase Shift", cn="相位变换" }, { id=124, name="Spirit of the Redeemer", cn="救赎者之魂" }, { id=5479, name="Purification", cn="纯净御罪" } } },
        { rank=3, rating=2556, player="Bholebender", realm="tichondrius", hero="Preventive Measures", heroCn="防微杜渐", code="CEQAR03Gt7xPmcDNOjs2Zlb3yCDAAAAAAwMzDMzsNzMmZGDzgZbmZmBAAAwMzsMDGjxyMmZYZxYGAYmlZWmZY2mZ2GgZmBLGDAMjZYMYstNYmZG4DA", pvp={ { id=5569, name="Phase Shift", cn="相位变换" }, { id=5479, name="Purification", cn="纯净御罪" }, { id=124, name="Spirit of the Redeemer", cn="救赎者之魂" } } },
    } },
    [259] = { key = "ROGUE/ASSASSINATION", n = 29, pvp = {
        { id=5697, name="Preemptive Maneuver", cn="先觉机动", pct=96.6 },
        { id=3480, name="Smoke Bomb", cn="烟雾弹", pct=93.1 },
        { id=5405, name="Dismantle", cn="卸除武装", pct=62.1 },
        { id=830, name="Hemotoxin", cn="血毒素", pct=24.1 },
        { id=5408, name="Thick as Thieves", cn="偷天换日", pct=13.8 },
        { id=5530, name="Control is King", cn="制者为王", pct=10.3 },
    }, builds = {
        { rank=1, rating=2711, player="Hecklebury", realm="malganis", hero="Hand of Fate", heroCn="命运之手", code="CMQA5HmDzx68KWyrW/8Y781L7bmlxsZGAAAAAAz2MmtZAAAAAAtsMMDzMGLzMzsNzyMzYmZmZwMmxMGGYgFYGjGzCIbDYbG2AmZGMA", pvp={ { id=3480, name="Smoke Bomb", cn="烟雾弹" }, { id=5405, name="Dismantle", cn="卸除武装" }, { id=5697, name="Preemptive Maneuver", cn="先觉机动" } } },
        { rank=1, rating=2711, player="Wildcard", realm="laughing-skull", hero="Hand of Fate", heroCn="命运之手", code="CMQA5HmDzx68KWyrW/8Y781L7bmlxsZGAAAAAAz2MmtZAAAAAAtsMmBzMGLzMzsNzyMjZmZMDmxMmxAsNz2YhxMmlGzy2wkthhtZYbmBzMjxA", pvp={ { id=5697, name="Preemptive Maneuver", cn="先觉机动" }, { id=830, name="Hemotoxin", cn="血毒素" }, { id=3480, name="Smoke Bomb", cn="烟雾弹" } } },
        { rank=3, rating=2647, player="Røbinhooe", realm="malganis", hero="Hand of Fate", heroCn="命运之手", code="CMQA5HmDzx68KWyrW/8Y781L7bmlxsZGAAAAAAzyMmtZAAAAAAtsMMDzMGLzMzsNzyMzMzMMDmxMmxAsNz2YhxMmlGzy2wkthhtZYbmBzMjxA", pvp={ { id=5408, name="Thick as Thieves", cn="偷天换日" }, { id=3480, name="Smoke Bomb", cn="烟雾弹" }, { id=5697, name="Preemptive Maneuver", cn="先觉机动" } } },
    } },
    [261] = { key = "ROGUE/SUBTLETY", n = 29, pvp = {
        { id=1209, name="Smoke Bomb", cn="烟雾弹", pct=100.0 },
        { id=5698, name="Preemptive Maneuver", cn="先觉机动", pct=93.1 },
        { id=5406, name="Dismantle", cn="卸除武装", pct=79.3 },
        { id=5409, name="Thick as Thieves", cn="偷天换日", pct=17.2 },
    }, builds = {
        { rank=1, rating=2368, player="Bornfilthy", realm="daggerspine", hero="Clear the Witnesses", heroCn="见者尽灭", code="CUQA5HmDzx68KWyrW/8Y781L7DgZ2mBAAAAAmtZmZZwssNzYmxMwMzMzyY2mxMzyywgZGDYGDAAAgZYG2MLzYWmhxCDbzsNWwyswYYmZmBzMDA", pvp={ { id=5698, name="Preemptive Maneuver", cn="先觉机动" }, { id=1209, name="Smoke Bomb", cn="烟雾弹" }, { id=3462, name="Death from Above", cn="天降杀机" } } },
        { rank=2, rating=2352, player="Másvidal", realm="area-52", hero="Deathstalker's Mark", heroCn="死亡猎手标记", code="CUQA5HmDzx68KWyrW/8Y781L7DgZ2mBAAAAAmtZmZZiZZbmxMjZgZmZmlxsNmZmllxMYmxAmxAAAAwghFzyMmlZYswwyMbTL0yswMDzMzMYmZA", pvp={ { id=5698, name="Preemptive Maneuver", cn="先觉机动" }, { id=5406, name="Dismantle", cn="卸除武装" }, { id=1209, name="Smoke Bomb", cn="烟雾弹" } } },
        { rank=3, rating=2335, player="Robinhoe", realm="malganis", hero="Surprising Strikes", heroCn="出其不意", code="CUQA5HmDzx68KWyrW/8Y781L7DgZ2mBAAAAAmlxMLDmltZGzMmBPwMjZWGz2YmZWWGGzMzYAzYAAAAYYGWMLzYWmhxCDbzsNWwyshZYmZmBzMDA", pvp={ { id=5409, name="Thick as Thieves", cn="偷天换日" }, { id=1209, name="Smoke Bomb", cn="烟雾弹" }, { id=5698, name="Preemptive Maneuver", cn="先觉机动" } } },
    } },
    [262] = { key = "SHAMAN/ELEMENTAL", n = 29, pvp = {
        { id=5660, name="Shamanism", cn="萨满之道", pct=100.0 },
        { id=3620, name="Grounding Totem", cn="根基图腾", pct=93.1 },
        { id=5574, name="Burrow", cn="掘地三尺", pct=79.3 },
        { id=3488, name="Totem of Wrath", cn="天怒图腾", pct=17.2 },
    }, builds = {
        { rank=1, rating=2611, player="Meatbeaterx", realm="aggramar", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CYQALMl7AwW51MWzGneuHE3tPCAAAAzMLbzMGjZZZhxMMDAAAAsYmtNzMDbGWY2mZaoZWAgZbMGzstYaxMzYsYMzYmZb2MzyMYmZZAgZGgZmZGDz4DA", pvp={ { id=5574, name="Burrow", cn="掘地三尺" }, { id=3620, name="Grounding Totem", cn="根基图腾" }, { id=5660, name="Shamanism", cn="萨满之道" } } },
        { rank=2, rating=2564, player="Meatbeaterx", realm="bleeding-hollow", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CYQALMl7AwW51MWzGneuHE3tPCAAAAzMLbzMGjZZZhxMMDAAAAsYmtNzMDbGWY2mZaoZWAgZbMGzstYaxMzYsYMzYmZb2MzyMYmZZAgZGAMzYYGfA", pvp={ { id=5660, name="Shamanism", cn="萨满之道" }, { id=5574, name="Burrow", cn="掘地三尺" }, { id=3620, name="Grounding Totem", cn="根基图腾" } } },
        { rank=3, rating=2525, player="Gelex", realm="tichondrius", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CYQALMl7AwW51MWzGneuHE3tPCAAAAzMLbzMGjZZZhxMMDAAAAsYmtNzMDbGWY2mZaoZWAgZbMGzstYaxMzYsYMzYmZb2MzyMYmZZAgZGgZmZGDz4DA", pvp={ { id=5660, name="Shamanism", cn="萨满之道" }, { id=5574, name="Burrow", cn="掘地三尺" }, { id=3620, name="Grounding Totem", cn="根基图腾" } } },
    } },
    [251] = { key = "DEATHKNIGHT/FROST", n = 28, pvp = {
        { id=5429, name="Strangulate", cn="绞袭", pct=96.4 },
        { id=5591, name="Spellwarden", cn="咒术防护", pct=75.0 },
        { id=702, name="Delirium", cn="神智不清", pct=71.4 },
        { id=5586, name="Bloodforged Armor", cn="血锻盔甲", pct=32.1 },
        { id=701, name="Deathchill", cn="死亡之寒", pct=10.7 },
    }, builds = {
        { rank=1, rating=2332, player="Üuü", realm="barthilas", hero="Wave of Souls", heroCn="灵魂浪潮", code="CsPAkXBWxkyfx9CbGaHonEAhLNDYmBjZGDzyMzMDbzMDzMmZmhZMjZmZwMzMmBAAAAAAAAgxsNwAWALDDwYxYmhZGwAYYmBgBD", pvp={ { id=702, name="Delirium", cn="神智不清" }, { id=5429, name="Strangulate", cn="绞袭" }, { id=5591, name="Spellwarden", cn="咒术防护" } } },
        { rank=2, rating=2327, player="Ttvflarkness", realm="dawnbringer", hero="Wave of Souls", heroCn="灵魂浪潮", code="CsPAkXBWxkyfx9CbGaHonEAhLNDYmBjZGDzyMzMDLzYGzMmZmhZYMzMDmZmZmBAAAAAAAAgxsMbmtZYswwyMbjBzYxYmhZGwAYYmBzMMYA", pvp={ { id=702, name="Delirium", cn="神智不清" }, { id=5429, name="Strangulate", cn="绞袭" }, { id=5591, name="Spellwarden", cn="咒术防护" } } },
        { rank=3, rating=2321, player="Flarkness", realm="dawnbringer", hero="Reaper's Mark", heroCn="死神印记", code="CsPAkXBWxkyfx9CbGaHonEAhLNDYmBjZGDzyMzMDLzYmmZMzMDzwYmZGMzMzMDAAAAAAAAAjZZ2MLzwYhhlZ2mGaGLGzMMzAGADzMYmhBD", pvp={ { id=702, name="Delirium", cn="神智不清" }, { id=5591, name="Spellwarden", cn="咒术防护" }, { id=5429, name="Strangulate", cn="绞袭" } } },
    } },
    [252] = { key = "DEATHKNIGHT/UNHOLY", n = 28, pvp = {
        { id=149, name="Necrotic Wounds", cn="死疽伤口", pct=100.0 },
        { id=5430, name="Strangulate", cn="绞袭", pct=82.1 },
        { id=5590, name="Spellwarden", cn="咒术防护", pct=67.9 },
        { id=5585, name="Bloodforged Armor", cn="血锻盔甲", pct=32.1 },
        { id=41, name="Dark Simulacrum", cn="黑暗模拟", pct=10.7 },
    }, builds = {
        { rank=1, rating=2567, player="Royjones", realm="sargeras", hero="Rider's Champion", heroCn="冠军骑士", code="CwPAkXBWxkyfx9CbGaHonEAhLBYmBjZmZYWGzMTz2MGjhZAAAAAAAAMzYmZAwyMmZYmxMzYw2MbmZmNNz2CzGz20YhBYGAGzMjZwMzMzYGD", pvp={ { id=5585, name="Bloodforged Armor", cn="血锻盔甲" }, { id=149, name="Necrotic Wounds", cn="死疽伤口" }, { id=5430, name="Strangulate", cn="绞袭" } } },
        { rank=2, rating=2554, player="Slackjawed", realm="dalvengyr", hero="Rider's Champion", heroCn="冠军骑士", code="CwPAkXBWxkyfx9CbGaHonEAhLBYmBjZMDzyYmZa2mxYmhZAAAAAAAAMzYmZAwyMmZYmxMzYw2MbmZmFNz2CzGz20YhBYGAGzMjZwMzMzYGD", pvp={ { id=41, name="Dark Simulacrum", cn="黑暗模拟" }, { id=149, name="Necrotic Wounds", cn="死疽伤口" }, { id=5590, name="Spellwarden", cn="咒术防护" } } },
        { rank=3, rating=2543, player="Cerséï", realm="tichondrius", hero="Rider's Champion", heroCn="冠军骑士", code="CwPAkXBWxkyfx9CbGaHonEAhLBYmBjZMDzyYmZa2mxYMjZAAAAAAAAMzYmZAwyMmZYmxMzYw2MbmZmNNz2CzGz20YhBYGAGzMjZwMzMzYGD", pvp={ { id=149, name="Necrotic Wounds", cn="死疽伤口" }, { id=5430, name="Strangulate", cn="绞袭" }, { id=5585, name="Bloodforged Armor", cn="血锻盔甲" } } },
    } },
    [255] = { key = "HUNTER/SURVIVAL", n = 28, pvp = {
        { id=3607, name="Survival Tactics", cn="生存战术", pct=89.3 },
        { id=5744, name="Scatter Shot", cn="驱散射击", pct=67.9 },
        { id=3609, name="Chimaeral Sting", cn="奇美拉钉刺", pct=50.0 },
        { id=664, name="Sticky Tar Bomb", cn="粘稠焦油炸弹", pct=50.0 },
        { id=662, name="Mending Bandage", cn="治疗绷带", pct=28.6 },
    }, builds = {
        { rank=1, rating=2571, player="Elyberia", realm="uther", hero="Sentinel", heroCn="警戒", code="C8PAD57yiELKEty14ekTDtZEqM2wMzYmZb0stMMDzMNYbGzMMmtZAAAAAAMzYMjFjxMMGzoZAAAAGAgltZMLmZmZmZMzAmZbGbLYGjZmFDA", pvp={ { id=3607, name="Survival Tactics", cn="生存战术" }, { id=3609, name="Chimaeral Sting", cn="奇美拉钉刺" }, { id=662, name="Mending Bandage", cn="治疗绷带" } } },
        { rank=2, rating=2536, player="Yahwéh", realm="area-52", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C8PAD57yiELKEty14ekTDtZEqMWwMzYmZb0stMMDzMNYxYmZMeglBAAAAAgZYMsYMmZmxYGNDAAAwAghllZmZxMzMmZMzAmZbGbLYGjZGGAA", pvp={ { id=3607, name="Survival Tactics", cn="生存战术" }, { id=5744, name="Scatter Shot", cn="驱散射击" }, { id=662, name="Mending Bandage", cn="治疗绷带" } } },
        { rank=3, rating=2521, player="Jaywaz", realm="tichondrius", hero="Sentinel", heroCn="警戒", code="C8PAD57yiELKEty14ekTDtZEqM2wMzYmZb0ssMMDzMNYbGzMMmtZAAAAAAMzYMjFjxMeghlZ0MAAAADAwy2MmFzMzMzwMDYmtZstgZMmZWMAA", pvp={ { id=665, name="Tracker's Net", cn="追踪者之网" }, { id=5744, name="Scatter Shot", cn="驱散射击" }, { id=3607, name="Survival Tactics", cn="生存战术" } } },
    } },
    [63] = { key = "MAGE/FIRE", n = 28, pvp = {
        { id=5706, name="Overpowered Barrier", cn="超强能量屏障", pct=100.0 },
        { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形", pct=100.0 },
        { id=5588, name="Master Shepherd", cn="牧羊大师", pct=82.1 },
        { id=5489, name="Ice Wall", cn="冰墙", pct=17.9 },
    }, builds = {
        { rank=1, rating=2691, player="Edrees", realm="kelthuzad", hero="Spellfire Spheres", heroCn="法术火焰宝珠", code="C8DAche08tHz49KSVf7iKFnyuNmtlZWmZegZBzMyMMDAAgZWmxMzysMzMNbLbzAAsZmZmtZMmZWAAAAAwiZmZGAAYGjZwwMLzAzMzMkxYAzwYA", pvp={ { id=5706, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5588, name="Master Shepherd", cn="牧羊大师" }, { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
        { rank=2, rating=2688, player="Goküü", realm="emerald-dream", hero="Frostfire Bolt", heroCn="霜火之箭", code="C8DAche08tHz49KSVf7iKFnyuNmtlZWmxMbYmRmhZAAAMzyMmZWmlZmpZbZbGAgFzMmtZmZmxCAAAAAWMzMzAAAzYMzwYmZZGYmZmhMmBYGGA", pvp={ { id=5706, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5588, name="Master Shepherd", cn="牧羊大师" }, { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
        { rank=3, rating=2675, player="Contx", realm="kelthuzad", hero="Spellfire Spheres", heroCn="法术火焰宝珠", code="C8DAche08tHz49KSVf7iKFnyuNmtlZWmZmZBzMyMMDAAgZWmxMz2sMzMNbLLzAAsZmxsNjxMzCAAAAAWMzMzAAAzYMDGzMLzAzMzMkxYAzwA", pvp={ { id=5588, name="Master Shepherd", cn="牧羊大师" }, { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5706, name="Overpowered Barrier", cn="超强能量屏障" } } },
    } },
    [266] = { key = "WARLOCK/DEMONOLOGY", n = 28, pvp = {
        { id=5577, name="Impish Instincts", cn="小鬼本能", pct=75.0 },
        { id=3624, name="Nether Ward", cn="虚空守卫", pct=64.3 },
        { id=3506, name="Gateway Mastery", cn="传送门大师", pct=64.3 },
        { id=5606, name="Soul Rip", cn="夺魂", pct=60.7 },
        { id=162, name="Call Fel Lord", cn="召唤邪能领主", pct=32.1 },
    }, builds = {
        { rank=1, rating=2506, player="Stinkie", realm="nerzhul", hero="Diabolic Ritual", heroCn="敬魔仪式", code="CoQAMrNP5kak+EBqLfUa3dMm+uMGPwMz0sNzYhZmZZAAAAAAAGLLzYmZYzwwMLzWL0MWMYsMmZmZmBAMmZMzMDmZmZGjBAAYmZGjZmhlZGgB", pvp={ { id=162, name="Call Fel Lord", cn="召唤邪能领主" }, { id=3624, name="Nether Ward", cn="虚空守卫" }, { id=5606, name="Soul Rip", cn="夺魂" } } },
        { rank=2, rating=2457, player="Fëlmäxxîng", realm="thrall", hero="Diabolic Ritual", heroCn="敬魔仪式", code="CoQAMrNP5kak+EBqLfUa3dMm+uMGzMjmlZGLMzMLDAAAAAAwYZZGzMDbGGmZb2ahmxiZGjlZZmZGzAAzMmZmZmBzMzMjxAAAMmxMGzYWmxAeAA", pvp={ { id=5606, name="Soul Rip", cn="夺魂" }, { id=5577, name="Impish Instincts", cn="小鬼本能" }, { id=3506, name="Gateway Mastery", cn="传送门大师" } } },
        { rank=3, rating=2437, player="Woopzyy", realm="tichondrius", hero="Diabolic Ritual", heroCn="敬魔仪式", code="CoQAMrNP5kak+EBqLfUa3dMm+uMGzMz0sMzYhZmZZAAAAAAAGLLzYmZYzwwMbzWL0MWMzYsMLzMzYGAYmxMzMzMYmZmZwAAAMmxMGzYWmxAeAA", pvp={ { id=162, name="Call Fel Lord", cn="召唤邪能领主" }, { id=3624, name="Nether Ward", cn="虚空守卫" }, { id=3506, name="Gateway Mastery", cn="传送门大师" } } },
    } },
    [72] = { key = "WARRIOR/FURY", n = 28, pvp = {
        { id=3735, name="Slaughterhouse", cn="屠宰场", pct=100.0 },
        { id=177, name="Enduring Rage", cn="无尽之怒", pct=85.7 },
        { id=3533, name="Disarm", cn="缴械", pct=53.6 },
        { id=5702, name="Berserker Roar", cn="狂战士咆哮", pct=21.4 },
        { id=5624, name="Safeguard", cn="捍卫", pct=17.9 },
        { id=179, name="Death Wish", cn="死亡之愿", pct=14.3 },
    }, builds = {
        { rank=1, rating=2655, player="Kenstlols", realm="tichondrius", hero="Lightning Strikes", heroCn="闪电打击", code="CgEASWsDSHNyPDXnbxuIhH3ZdDAAAAAAgGDjZMzCzMzYmxMzMzYmZmlhxMzMLmZmBAAiZW2GbsZZzMNmZGmMbMzYBwMLGLAwMDAjxwYGGD", pvp={ { id=3533, name="Disarm", cn="缴械" }, { id=177, name="Enduring Rage", cn="无尽之怒" }, { id=3735, name="Slaughterhouse", cn="屠宰场" } } },
        { rank=2, rating=2641, player="Isnlonely", realm="tichondrius", hero="Lightning Strikes", heroCn="闪电打击", code="CgEASWsDSHNyPDXnbxuIhH3ZdDAAAAAAgGDzMjZWYmZGjxMzMzYmZmlhxMzMLmZmBAAiZW2GbsZZzMNmZGmMbMzYBwMLGLAwMDAjxwYGGD", pvp={ { id=5702, name="Berserker Roar", cn="狂战士咆哮" }, { id=3735, name="Slaughterhouse", cn="屠宰场" }, { id=177, name="Enduring Rage", cn="无尽之怒" } } },
        { rank=3, rating=2587, player="Xenrai", realm="blackrock", hero="Lightning Strikes", heroCn="闪电打击", code="CgEASWsDSHNyPDXnbxuIhH3ZdDAAAAAAgGDzMzMzCzMzYwMzMzYmZmlhxMzMLmZmBAAiZW2GbsZZzMNmZGmMbMzYBwMLGLAwMDAjxwYGGD", pvp={ { id=3735, name="Slaughterhouse", cn="屠宰场" }, { id=177, name="Enduring Rage", cn="无尽之怒" }, { id=3533, name="Disarm", cn="缴械" } } },
    } },
    [102] = { key = "DRUID/BALANCE", n = 27, pvp = {
        { id=185, name="Moonkin Aura", cn="枭兽光环", pct=85.2 },
        { id=5407, name="Owlkin Adept", cn="枭兽专家", pct=81.5 },
        { id=5383, name="High Winds", cn="高天狂风", pct=59.3 },
        { id=836, name="Faerie Swarm", cn="精灵虫群", pct=51.9 },
        { id=3058, name="Star Burst", cn="星辰迸发", pct=11.1 },
    }, builds = {
        { rank=2, rating=2575, player="Wakeenfiendx", realm="tichondrius", hero="Dream Surge", heroCn="梦境涌现", code="CYGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAAAAAAWoMLNjxMDwsZmZmZjxDMegZbsMjZMDmlZMzMDzGGAM22mZ22mZbWmpZmlZCAAAwmZmZmBbGGjZAMzgZGYA", pvp={ { id=5383, name="High Winds", cn="高天狂风" }, { id=836, name="Faerie Swarm", cn="精灵虫群" }, { id=185, name="Moonkin Aura", cn="枭兽光环" } } },
        { rank=3, rating=2549, player="Fredagn", realm="illidan", hero="Dream Surge", heroCn="梦境涌现", code="CYGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAAAAAAWoMLNjxMDwsNzMzMbMeAzMLjlZMjZGmlZMzMD2wAgx22Mz22MbzyMNzsMTAAAA2YmZMYzwYMDgZGMzADA", pvp={ { id=836, name="Faerie Swarm", cn="精灵虫群" }, { id=5646, name="Tireless Pursuit", cn="不息追猎" }, { id=5407, name="Owlkin Adept", cn="枭兽专家" } } },
        { rank=4, rating=2546, player="Gspx", realm="dalaran", hero="Dream Surge", heroCn="梦境涌现", code="CYGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAAAAAAWGlZpZMmZAmNzMzMbmxYmZZmlxyMmBWmxMzMYBDAGLbzMbbzsNLz0MzyMBAAAYjZegZGsZgxMAmZwMDMA", pvp={ { id=3058, name="Star Burst", cn="星辰迸发" }, { id=836, name="Faerie Swarm", cn="精灵虫群" }, { id=5383, name="High Winds", cn="高天狂风" } } },
    } },
    [1467] = { key = "EVOKER/DEVASTATION", n = 27, pvp = {
        { id=5462, name="Scouring Flame", cn="冲刷之焰", pct=85.2 },
        { id=5469, name="Unburdened Flight", cn="轻驰飞翔", pct=85.2 },
        { id=5460, name="Obsidian Mettle", cn="黑曜之勇", pct=81.5 },
        { id=5464, name="Time Stop", cn="时间停止", pct=48.1 },
    }, builds = {
        { rank=1, rating=2648, player="Gloomie", realm="tichondrius", hero="Mass Disintegrate", heroCn="群体裂解", code="CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAwYMDMDzwMMzwYMTjZmpZmx2MMzMzMzMzAMzMDzMLjZgBGD2glxox2AyMBYDDMzAMA", pvp={ { id=5460, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5462, name="Scouring Flame", cn="冲刷之焰" }, { id=5469, name="Unburdened Flight", cn="轻驰飞翔" } } },
        { rank=2, rating=2460, player="Resurecty", realm="lightbringer", hero="Mass Disintegrate", heroCn="群体裂解", code="CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAwMjZgZYGzMMzwYMTjZmpZmxyMMzMzMzMzAMDDzMLjZgBYwGsMGN2GQmJAbYgZGYMA", pvp={ { id=5462, name="Scouring Flame", cn="冲刷之焰" }, { id=5464, name="Time Stop", cn="时间停止" }, { id=5469, name="Unburdened Flight", cn="轻驰飞翔" } } },
        { rank=4, rating=2400, player="Bluechewer", realm="stonemaul", hero="Mass Disintegrate", heroCn="群体裂解", code="CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAwYmZgZYmxMMz8AGDTjZmpZmxyMMzMz8AzMzAMzMDzMLjZgBGD2glxox2AyMBYDDMzAMA", pvp={ { id=5469, name="Unburdened Flight", cn="轻驰飞翔" }, { id=5460, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5462, name="Scouring Flame", cn="冲刷之焰" } } },
    } },
    [253] = { key = "HUNTER/BEASTMASTERY", n = 27, pvp = {
        { id=3599, name="Survival Tactics", cn="生存战术", pct=100.0 },
        { id=5746, name="Scatter Shot", cn="驱散射击", pct=77.8 },
        { id=5444, name="Kindred Beasts", cn="野兽亲和", pct=51.9 },
        { id=3604, name="Chimaeral Sting", cn="奇美拉钉刺", pct=51.9 },
        { id=693, name="The Beast Within", cn="野兽之心", pct=11.1 },
    }, builds = {
        { rank=1, rating=2725, player="Shadeh", realm="tichondrius", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C0PAD57yiELKEty14ekTDtZEqAMmxwCsAzwQDbAAYGzYmFzwMmZY8AzMGmxMzMGzYxMjZmZMMaGAAAAwMAAAMDzMgZ2ILYmFwyAwA", pvp={ { id=3599, name="Survival Tactics", cn="生存战术" }, { id=5746, name="Scatter Shot", cn="驱散射击" }, { id=5444, name="Kindred Beasts", cn="野兽亲和" } } },
        { rank=2, rating=2546, player="Nashi", realm="burning-blade", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C0PAD57yiELKEty14ekTDtZEqYzsNjZmhFDbMzMbGaGbAAYGzYmFzwMmZY8AzMGmxMzMmZGLmZMzYwMaGAAAAwMAAAMDzMMzMzGZBzsAWGAG", pvp={ { id=3599, name="Survival Tactics", cn="生存战术" }, { id=5444, name="Kindred Beasts", cn="野兽亲和" }, { id=5746, name="Scatter Shot", cn="驱散射击" } } },
        { rank=3, rating=2530, player="Ggbruh", realm="illidan", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C0PAD57yiELKEty14ekTDtZEqAMmxwCsAzwQDbAAYGzMzs8AzYmZmZMzgZGzMMzYmZGbzMjZMDLjpZAAAAAAAAgHYMGwMbEwsA2GAA", pvp={ { id=3604, name="Chimaeral Sting", cn="奇美拉钉刺" }, { id=5746, name="Scatter Shot", cn="驱散射击" }, { id=3599, name="Survival Tactics", cn="生存战术" } } },
    } },
    [66] = { key = "PALADIN/PROTECTION", n = 26, pvp = {
        { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫", pct=96.2 },
        { id=861, name="Shield of Virtue", cn="美德之盾", pct=80.8 },
        { id=5664, name="Bear the Burden", cn="当承其重", pct=50.0 },
        { id=860, name="Warrior of Light", cn="光明战士", pct=23.1 },
        { id=5582, name="Searing Glare", cn="灼热凝视", pct=23.1 },
        { id=91, name="Steed of Glory", cn="荣耀战马", pct=11.5 },
    }, builds = {
        { rank=1, rating=2526, player="Aluvia", realm="malygos", hero="Light's Guidance", heroCn="圣光指引", code="CIEAzbn3egSOtoSwvPw1U1vTLsNDzyMzYmZmZswYWmFGGAgBAAAAAANNzsMzYmZMjt2AwAADsNAAwMTLzMbzMzsst0yMjNLbMDDMYGDDAmZ2mBGzAM2A", pvp={ { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫" }, { id=861, name="Shield of Virtue", cn="美德之盾" }, { id=5664, name="Bear the Burden", cn="当承其重" } } },
        { rank=2, rating=2467, player="Wheyprot", realm="gorefiend", hero="Holy Bulwark", heroCn="神圣壁垒", code="CIEAzbn3egSOtoSwvPw1U1vTLsZYWmZGzMzMjNMz2sYZYAAGAAAAAA00MzyMjZGG2aDADAMD2AAAIAzMLbLtMzYx2CGGYmxMmZGAMzAgZAGL", pvp={ { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫" }, { id=5664, name="Bear the Burden", cn="当承其重" }, { id=861, name="Shield of Virtue", cn="美德之盾" } } },
        { rank=3, rating=2450, player="Holytren", realm="gorefiend", hero="Holy Bulwark", heroCn="神圣壁垒", code="CIEAzbn3egSOtoSwvPw1U1vTLsZYWmZGzMzMjFMz2sYZYAAGAAAAAA00MzyMjZGG2aDADAMD2GAAABYmZZbplZGL22wwAzMmxYGAMzAgZAGL", pvp={ { id=861, name="Shield of Virtue", cn="美德之盾" }, { id=5664, name="Bear the Burden", cn="当承其重" }, { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫" } } },
    } },
    [260] = { key = "ROGUE/OUTLAW", n = 25, pvp = {
        { id=3483, name="Smoke Bomb", cn="烟雾弹", pct=92.0 },
        { id=5699, name="Preemptive Maneuver", cn="先觉机动", pct=76.0 },
        { id=145, name="Dismantle", cn="卸除武装", pct=68.0 },
        { id=3421, name="Turn the Tables", cn="局势逆转", pct=40.0 },
        { id=1208, name="Thick as Thieves", cn="偷天换日", pct=12.0 },
    }, builds = {
        { rank=1, rating=2340, player="Bootyguru", realm="bonechewer", hero="Hand of Fate", heroCn="命运之手", code="CQQA5HmDzx68KWyrW/8Y781L7DgZAGDmZbmZmZGjZZxMzMbTbzY2mBAAAAAYZZmZGmZmZWMzMGAAAAzAYwsNLmZmRzMbMbssNtwiZAmZmZGYA", pvp={ { id=5699, name="Preemptive Maneuver", cn="先觉机动" }, { id=3483, name="Smoke Bomb", cn="烟雾弹" }, { id=145, name="Dismantle", cn="卸除武装" } } },
        { rank=2, rating=2121, player="Bodymasage", realm="tichondrius", hero="Unseen Blade", heroCn="隐秘之刃", code="CQQA5HmDzx68KWyrW/8Y781L7DgZ8ADzYMmZbmZmZGjZZzMzMbTLD2mBAAAAAMLLjZYmZMziZmxAAAAYGGYwsNLmZmRzMbMbssNtwGDwMzMzAfA", pvp={ { id=3421, name="Turn the Tables", cn="局势逆转" }, { id=3483, name="Smoke Bomb", cn="烟雾弹" }, { id=1208, name="Thick as Thieves", cn="偷天换日" } } },
        { rank=3, rating=2068, player="Ghoste", realm="zuljin", hero="Hand of Fate", heroCn="命运之手", code="CQQA5HmDzx68KWyrW/8Y781L7DgZwwYGmZzMzYGjZbbmZmZbabGz2MAAAAAgZZZMDmZMziZmxAAAAYGADmtZxMzMamZjZjltpFWMDwMzMzYYA", pvp={ { id=3483, name="Smoke Bomb", cn="烟雾弹" }, { id=145, name="Dismantle", cn="卸除武装" }, { id=5699, name="Preemptive Maneuver", cn="先觉机动" } } },
    } },
    [581] = { key = "DEMONHUNTER/VENGEANCE", n = 22, pvp = {
        { id=819, name="Illidan's Grasp", cn="伊利丹之握", pct=68.2 },
        { id=5716, name="Lay In Wait", cn="以逸待劳", pct=40.9 },
        { id=1948, name="Sigil Mastery", cn="咒符掌握", pct=40.9 },
        { id=814, name="Cleansed by Flame", cn="烈焰净化", pct=27.3 },
        { id=816, name="Jagged Spikes", cn="锯齿尖刺", pct=27.3 },
        { id=5521, name="Rain from Above", cn="从天而降", pct=22.7 },
        { id=3430, name="Detainment", cn="拘押", pct=18.2 },
        { id=1220, name="Tormentor", cn="酷刑折磨", pct=13.6 },
    }, builds = {
        { rank=1, rating=1174, player="Yumo", realm="frostmourne", hero="Voidfall", heroCn="虚落", code="CUkAp/epaxe7D0A403L+Tvk0iCAMjZmZMMzkZmBDzMzYMzYmxMmZmxgZmZs9AzMGjZAAAAAAAEwMzYDAAAADMzMzMLtNzMDAAAAAwA", pvp={ { id=819, name="Illidan's Grasp", cn="伊利丹之握" }, { id=5716, name="Lay In Wait", cn="以逸待劳" }, { id=814, name="Cleansed by Flame", cn="烈焰净化" } } },
        { rank=2, rating=952, player="Rumikpop", realm="malganis", hero="Art of the Glaive", heroCn="战刃绝技", code="CUkAp/epaxe7D0A403L+Tvk0iCAYMzMjZmZmYMY2MzMzMMjZGzYGzYYmZmxixsMmZGAAAAmtZwwYZjJMMjZWAAAAwADgAMzAMAAAA+A", pvp={ { id=5716, name="Lay In Wait", cn="以逸待劳" }, { id=819, name="Illidan's Grasp", cn="伊利丹之握" }, { id=1948, name="Sigil Mastery", cn="咒符掌握" } } },
        { rank=3, rating=845, player="Washedfr", realm="moon-guard", hero="Art of the Glaive", heroCn="战刃绝技", code="CUkAp/epaxe7D0A403L+Tvk0iCAMjZmZMzMzEjxY2mxMzgZMDzMzYmBmZmxyDMGjxMAAAAMbzghxyGTYYGzsAAAAgBzMzMzs02MzMmZAAAAA4DA", pvp={ { id=819, name="Illidan's Grasp", cn="伊利丹之握" }, { id=5716, name="Lay In Wait", cn="以逸待劳" }, { id=3430, name="Detainment", cn="拘押" } } },
    } },
}
