-- 由 clawhub services/wow-agent/export_pvp_meta.py 生成，⛔别手改（随 PvP 榜数据刷新）。
-- ⛔ 全局表：与 GearInsightPopularTalents 同款，主插件 ShowTalentPicker 直接读。
GearInsightPvpTalents = {
    season = 42,
    mode = "shuffle",
    top = 30,
    region = "US",
    date = "2026-09-16",
    [250] = { key = "DEATHKNIGHT/BLOOD", n = 30, pvp = {
        { id=608, name="Last Dance", cn="最终之舞", pct=96.7 },
        { id=3441, name="Decomposing Aura", cn="腐烂光环", pct=63.3 },
        { id=5592, name="Spellwarden", cn="咒术防护", pct=60.0 },
        { id=5587, name="Bloodforged Armor", cn="血锻盔甲", pct=30.0 },
        { id=609, name="Death Chain", cn="死亡锁链", pct=16.7 },
        { id=841, name="Murderous Intent", cn="杀戮意图", pct=13.3 },
        { id=206, name="Strangulate", cn="绞袭", pct=10.0 },
    }, builds = {
        { rank=1, rating=1601, player="Ttvflarkness", realm="dawnbringer", hero="Vampiric Speed", heroCn="吸血鬼之速", code="CoPAkXBWxkyfx9CbGaHonEAhLxYWmZmxMGzMMLjZGsMjxMzYGAAAAYmZmZGzMjZmBAMmZmZAAAmZ2GDjZssYsssMMsNMsNAzYGAAmZmZAjB", pvp={ { id=609, name="Death Chain", cn="死亡锁链" }, { id=608, name="Last Dance", cn="最终之舞" }, { id=3441, name="Decomposing Aura", cn="腐烂光环" } } },
        { rank=2, rating=1437, player="Horrorz", realm="tichondrius", hero="Vampiric Strike", heroCn="吸血鬼打击", code="CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmZmhZZMz0MLzMjZmBAAAAwMMzMzMjZGDAYmZmZGAAgZmtxwYGLLNW2WGmsNMsBYGDAAmZmZAjB", pvp={ { id=5592, name="Spellwarden", cn="咒术防护" }, { id=608, name="Last Dance", cn="最终之舞" }, { id=841, name="Murderous Intent", cn="杀戮意图" } } },
        { rank=3, rating=1417, player="Bloodiousosa", realm="dalaran", hero="Reaper's Mark", heroCn="死神印记", code="CoPAkXBWxkyfx9CbGaHonEAhLxY2mZGmZmZmhZxMzELzYMzMmBAAAAmZmZGmZGzMDAYMzMzMAAgZmtxwYGLLNWW2GmsNMsMAzYGAAmZmZAMA", pvp={ { id=3441, name="Decomposing Aura", cn="腐烂光环" }, { id=608, name="Last Dance", cn="最终之舞" }, { id=5592, name="Spellwarden", cn="咒术防护" } } },
    } },
    [103] = { key = "DRUID/FERAL", n = 30, pvp = {
        { id=620, name="Wicked Claws", cn="邪恶之爪", pct=93.3 },
        { id=5647, name="Tireless Pursuit", cn="不息追猎", pct=70.0 },
        { id=5384, name="High Winds", cn="高天狂风", pct=46.7 },
        { id=3053, name="Strength of the Wild", cn="野性力量", pct=36.7 },
        { id=820, name="Savage Momentum", cn="狂野冲撞", pct=33.3 },
        { id=611, name="Ferocious Wound", cn="凶猛伤痕", pct=13.3 },
    }, builds = {
        { rank=1, rating=2501, player="Semvetax", realm="alleria", hero="Thriving Growth", heroCn="兴荣生长", code="CcGADBD3hSPCL9Y9gz68WcKvMAAAAAAAjZWwYmZGz2yYZmlZmZMzMAAAAsEMbGYmZqZMbmZmZWGzYGAAAAAAgBAAAQzsMbzMzMLzs0sNzyGMzMALMYAAMzgZ2wA", pvp={ { id=5647, name="Tireless Pursuit", cn="不息追猎" }, { id=5384, name="High Winds", cn="高天狂风" }, { id=620, name="Wicked Claws", cn="邪恶之爪" } } },
        { rank=2, rating=2383, player="Benchpress", realm="bloodscalp", hero="Thriving Growth", heroCn="兴荣生长", code="CcGADBD3hSPCL9Y9gz68WcKvMAAAAAAwYMzCDzMzY2WYZmlZmZMzMAAAAsEMbGYmZqZMbmZmZWGzMGAAAAAAgBAAAQAwsNzSz2MLbgZGgFGMAAmZAwA", pvp={ { id=620, name="Wicked Claws", cn="邪恶之爪" }, { id=5384, name="High Winds", cn="高天狂风" }, { id=5647, name="Tireless Pursuit", cn="不息追猎" } } },
        { rank=3, rating=2359, player="Borkdru", realm="area-52", hero="Thriving Growth", heroCn="兴荣生长", code="CcGADBD3hSPCL9Y9gz68WcKvMAAAAAAwYMzCDzMzY2WYZmlZmZMzMAAAAsEMbGYmZqZMbmZmZ2GzYGAAAAAAgBAAAQzsMbzMzMbzs0sNzyGMzMALMYAAMzgZ2wA", pvp={ { id=3053, name="Strength of the Wild", cn="野性力量" }, { id=5647, name="Tireless Pursuit", cn="不息追猎" }, { id=620, name="Wicked Claws", cn="邪恶之爪" } } },
    } },
    [105] = { key = "DRUID/RESTORATION", n = 30, pvp = {
        { id=1215, name="Early Spring", cn="万物复苏", pct=100.0 },
        { id=5687, name="Forest Guardian", cn="森林守护者", pct=96.7 },
        { id=5668, name="Call of Ohn'ahra", cn="欧恩哈拉的召唤", pct=66.7 },
        { id=838, name="High Winds", cn="高天狂风", pct=20.0 },
        { id=59, name="Disentanglement", cn="解缠", pct=10.0 },
    }, builds = {
        { rank=1, rating=2790, player="Habibieu", realm="area-52", hero="Thriving Growth", heroCn="兴荣生长", code="CkGADBD3hSPCL9Y9gz68WcKvMMMmZBjxMzsMmZMmNmNLDAAAAAAAAAAsMDZzMmmZmZwsZmZmZzgZAAAAAMAgxA22GLYamZZAAMbzs0sNziNGzYYGbgmBAzMzMAMA", pvp={ { id=838, name="High Winds", cn="高天狂风" }, { id=5687, name="Forest Guardian", cn="森林守护者" }, { id=1215, name="Early Spring", cn="万物复苏" } } },
        { rank=2, rating=2763, player="Alphawolf", realm="kilrogg", hero="Dream Surge", heroCn="梦境涌现", code="CkGADBD3hSPCL9Y9gz68WcKvMMMmZBjxMzsMmZMmNmNLzAAAAAAAAAAglZIbmx0MzMwsZmZmZxgZAAAAAMAAGw22YBTzMLDAgZbmlmtZWsAzMDzYD0MAYmZmBgB", pvp={ { id=838, name="High Winds", cn="高天狂风" }, { id=5687, name="Forest Guardian", cn="森林守护者" }, { id=1215, name="Early Spring", cn="万物复苏" } } },
        { rank=3, rating=2699, player="Creamyfresh", realm="tichondrius", hero="Thriving Growth", heroCn="兴荣生长", code="CkGADBD3hSPCL9Y9gz68WcKvMMMmZjZMzMzsMmZMmNmNLzAAAAAAAAAAglZoZjx0MzMwsZmZmZxgZAAAAAMAAAYsgJDAAMbzs0sNziNGz8ADGbgmBAYmBgB", pvp={ { id=5687, name="Forest Guardian", cn="森林守护者" }, { id=1215, name="Early Spring", cn="万物复苏" }, { id=5668, name="Call of Ohn'ahra", cn="欧恩哈拉的召唤" } } },
    } },
    [62] = { key = "MAGE/ARCANE", n = 30, pvp = {
        { id=637, name="Improved Mass Invisibility", cn="强化群体隐形", pct=93.3 },
        { id=5661, name="Chrono Shift", cn="时空转移", pct=90.0 },
        { id=5707, name="Overpowered Barrier", cn="超强能量屏障", pct=86.7 },
        { id=5397, name="Arcanosphere", cn="奥能之球", pct=13.3 },
        { id=5488, name="Ice Wall", cn="冰墙", pct=13.3 },
    }, builds = {
        { rank=1, rating=2587, player="Numbing", realm="sargeras", hero="Spellfire Spheres", heroCn="法术火焰宝珠", code="C4DAche08tHz49KSVf7iKFnyuNzwYZmZmFMDamxAAAwAAmZmmlltZmZmZZZmJ2AAYDmZG2sMjZWmxYmZmZYhZmZmZAAGAAgZmFMzAmBADzMD", pvp={ { id=5707, name="Overpowered Barrier", cn="超强能量屏障" }, { id=637, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5661, name="Chrono Shift", cn="时空转移" } } },
        { rank=2, rating=2562, player="Austin", realm="sargeras", hero="Spellfire Spheres", heroCn="法术火焰宝珠", code="C4DAche08tHz49KSVf7iKFnyuNmtlZWmZegZDzgmZMDAAgBAMzMNLLbzMzMzyyMTsBAwCmZmhNLzMzsMjx8AzMDWYGzMzAAMAAAzMLYmBGDAGGzA", pvp={ { id=5491, name="Ring of Fire", cn="火焰之环" }, { id=637, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5707, name="Overpowered Barrier", cn="超强能量屏障" } } },
        { rank=3, rating=2453, player="Adachisakura", realm="tichondrius", hero="Mana Cascade", heroCn="法力涌流", code="C4DAche08tHz49KSVf7iKFnyuNstMzyMzMbYmBzMmBAAwAAmZGzyyyMAA2AAYBmZG2sMzMzyMGzYmZYhZMjZAAGAAgBYmBGzAwwYG", pvp={ { id=5707, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5661, name="Chrono Shift", cn="时空转移" }, { id=637, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
    } },
    [64] = { key = "MAGE/FROST", n = 30, pvp = {
        { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形", pct=93.3 },
        { id=5708, name="Overpowered Barrier", cn="超强能量屏障", pct=83.3 },
        { id=5581, name="Master Shepherd", cn="牧羊大师", pct=56.7 },
        { id=5497, name="Snowdrift", cn="积雪", pct=40.0 },
        { id=5390, name="Ice Wall", cn="冰墙", pct=23.3 },
    }, builds = {
        { rank=1, rating=2588, player="Polynike", realm="tichondrius", hero="Splintering Sorcery", heroCn="裂解巫术", code="CAEAche08tHz49KSVf7iKFnyuNmtFzyMzMbDzMxMMzMzMzsYmZGzYmZZmmZ2mFAwMzMLLzMtBAALAAAgNA2WGzMDYZeAjZGLAAAMzCwMMmBMYA", pvp={ { id=5581, name="Master Shepherd", cn="牧羊大师" }, { id=5708, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
        { rank=2, rating=2533, player="Gotenkss", realm="emerald-dream", hero="Augury Abounds", heroCn="满目征兆", code="CAEAche08tHz49KSVf7iKFnyuNmtlZWmxMLYmBzwMzMzMziZmhZMzsMjZmlZBAMzMzyyMjNAAYBAAAsBw2yYmZGYZGjZmtFAAAmZZmBzwYGAMA", pvp={ { id=5708, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5497, name="Snowdrift", cn="积雪" } } },
        { rank=3, rating=2494, player="Goküü", realm="emerald-dream", hero="Splintering Sorcery", heroCn="裂解巫术", code="CAEAche08tHz49KSVf7iKFnyuNmtlZWmZmZBzMxMMzMzMzsYmZYGzMLz0MzysAAmZmZZZmpNAAYBAAAsBw2yYmZALzYMzstAAAwMLzMYGGzAgBA", pvp={ { id=5708, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5581, name="Master Shepherd", cn="牧羊大师" } } },
    } },
    [268] = { key = "MONK/BREWMASTER", n = 30, pvp = {
        { id=672, name="Double Barrel", cn="醉上加醉", pct=86.7 },
        { id=667, name="Hot Trub", cn="热酿", pct=80.0 },
        { id=843, name="Admonishment", cn="劝诫", pct=50.0 },
        { id=666, name="Microbrew", cn="私家陈酿", pct=36.7 },
        { id=669, name="Avert Harm", cn="斗转星移", pct=20.0 },
        { id=1958, name="Niuzao's Essence", cn="砮皂的精华", pct=13.3 },
        { id=670, name="Nimble Brew", cn="逍遥酒", pct=10.0 },
    }, builds = {
        { rank=1, rating=1893, player="Droguex", realm="tichondrius", hero="Manifestation", heroCn="化气凝形", code="CwQAQnG51S19isUJoJoTeJ/IKDAAAgZZzYGGzyMzGzMjBAAAAAAYZBzgZGYGGbwYmZmhZjZGjlhltHYbb2wsAAALzyYZ2mZZAAAAMsxwMDYMGAAwA", pvp={ { id=667, name="Hot Trub", cn="热酿" }, { id=672, name="Double Barrel", cn="醉上加醉" }, { id=843, name="Admonishment", cn="劝诫" } } },
        { rank=2, rating=1551, player="Artam", realm="thrall", hero="Pride of Pandaria", heroCn="潘达利亚之豪", code="CwQAQnG51S19isUJoJoTeJ/IKDAAAwMLbGzYGWmxGmZMAAAAAAALLYgZGYGGMjxMzMjZ2GmxYZYZz22sNjZBAA2AAAAz2sYmZmFG2AYmhxYAAAD", pvp={ { id=843, name="Admonishment", cn="劝诫" }, { id=667, name="Hot Trub", cn="热酿" }, { id=672, name="Double Barrel", cn="醉上加醉" } } },
        { rank=3, rating=1426, player="Worldpvp", realm="nerzhul", hero="Aspect of Harmony", heroCn="和谐化身", code="CwQAQnG51S19isUJoJoTeJ/IKDAAAwMLbGzYmx2M2wMDAAAAAAALLYEzMzGzYmBwMzMDzCMmZZYZz22sNMLAAwysMtMbzsMAAz2s0MzMLMsxwMzMDTjBYAgB", pvp={ { id=667, name="Hot Trub", cn="热酿" }, { id=666, name="Microbrew", cn="私家陈酿" }, { id=672, name="Double Barrel", cn="醉上加醉" } } },
    } },
    [269] = { key = "MONK/WINDWALKER", n = 30, pvp = {
        { id=3745, name="Turbo Fists", cn="怒雷叶轮", pct=100.0 },
        { id=3052, name="Grapple Weapon", cn="抓钩武器", pct=73.3 },
        { id=77, name="Ride the Wind", cn="驭风而行", pct=60.0 },
        { id=3737, name="Wind Waker", cn="唤风者", pct=56.7 },
        { id=5643, name="Rising Dragon Sweep", cn="升龙扫", pct=10.0 },
    }, builds = {
        { rank=1, rating=2664, player="Droguex", realm="tichondrius", hero="Flurry Strikes", heroCn="疾风乱打", code="C0QAQnG51S19isUJoJoTeJ/IKbmZMgZYbmZ2mxAAAAAAAAAAAALDjwMzGGwwMmZmZYWmFGmlZCAYzMbzMMzMzABwmZwYa2mlmZmZBYYgZmZAYZMgZmZzHA", pvp={ { id=5643, name="Rising Dragon Sweep", cn="升龙扫" }, { id=3052, name="Grapple Weapon", cn="抓钩武器" }, { id=3745, name="Turbo Fists", cn="怒雷叶轮" } } },
        { rank=2, rating=2620, player="Stepdro", realm="tichondrius", hero="Flurry Strikes", heroCn="疾风乱打", code="C0QAQnG51S19isUJoJoTeJ/IKbmZMgZYbmZ2mxAAAAAAAAAAAAbDjwMz2wAwMmZmZY2mFGmlZCAYzMbzMMzMzABwmZWmlx0sNLNzMzCwwAzMzAwCjBzMzmPA", pvp={ { id=3052, name="Grapple Weapon", cn="抓钩武器" }, { id=5643, name="Rising Dragon Sweep", cn="升龙扫" }, { id=3745, name="Turbo Fists", cn="怒雷叶轮" } } },
        { rank=3, rating=2615, player="Divergentww", realm="sargeras", hero="Flurry Strikes", heroCn="疾风乱打", code="C0QAQnG51S19isUJoJoTeJ/IKbmZMYMDbzMz2MAAAAAAAAAAAALDjwMz2wAwMmZMzYWmFGmlZCAYzMLzMMzMzABwmZWmlx0sNLNzMzCwwAzMzAwCjBzMzmPA", pvp={ { id=3745, name="Turbo Fists", cn="怒雷叶轮" }, { id=77, name="Ride the Wind", cn="驭风而行" }, { id=3052, name="Grapple Weapon", cn="抓钩武器" } } },
    } },
    [256] = { key = "PRIEST/DISCIPLINE", n = 30, pvp = {
        { id=123, name="Inner Light", cn="心灵之光", pct=96.7 },
        { id=114, name="Ultimate Radiance", cn="极致光辉", pct=86.7 },
        { id=5570, name="Phase Shift", cn="相位变换", pct=83.3 },
        { id=109, name="Trinity", cn="三位一体", pct=16.7 },
        { id=126, name="Dark Archangel", cn="黑暗天使长", pct=10.0 },
    }, builds = {
        { rank=1, rating=2653, player="Smíght", realm="thrall", hero="Guiding Light", heroCn="指引之光", code="CAQAR03Gt7xPmcDNOjs2Zlb3yCDsMDWmZMzMwMbzYmZGjZGAAAAAAAAAAzMzyAjZGLzMzMssYamYwMzMbYIMmlZWmtFjxYxAAwYGGDGYmZmZmgZA", pvp={ { id=123, name="Inner Light", cn="心灵之光" }, { id=5570, name="Phase Shift", cn="相位变换" }, { id=114, name="Ultimate Radiance", cn="极致光辉" } } },
        { rank=2, rating=2651, player="Faschism", realm="illidan", hero="Guiding Light", heroCn="指引之光", code="CAQAR03Gt7xPmcDNOjs2Zlb3yCDsMGWmZMzMwMbzYmZGjZGAAAAAAAAAAzMzyMYMGLzMzMssYamYwMzMbYIMmtZ2mlFjxYxAAwYGGDGYmZmZmgB", pvp={ { id=114, name="Ultimate Radiance", cn="极致光辉" }, { id=123, name="Inner Light", cn="心灵之光" }, { id=5570, name="Phase Shift", cn="相位变换" } } },
        { rank=3, rating=2650, player="Challengerz", realm="suramar", hero="Guiding Light", heroCn="指引之光", code="CAQAR03Gt7xPmcDNOjs2Zlb3yCDsMGWmZMPwMwMbzYmZmZMzAAAAAAAAAAYmZWGYmxYZmZmhlFTzEDmZmZDDhxsNzystYMGLGAAGzwYwAYmZmgB", pvp={ { id=114, name="Ultimate Radiance", cn="极致光辉" }, { id=5570, name="Phase Shift", cn="相位变换" }, { id=123, name="Inner Light", cn="心灵之光" } } },
    } },
    [258] = { key = "PRIEST/SHADOW", n = 30, pvp = {
        { id=106, name="Driven to Madness", cn="堕入疯狂", pct=93.3 },
        { id=763, name="Psyfiend", cn="灵能魔", pct=93.3 },
        { id=5568, name="Phase Shift", cn="相位变换", pct=90.0 },
        { id=5447, name="Cascading Horrors", cn="倾泻恐怖", pct=20.0 },
    }, builds = {
        { rank=1, rating=2593, player="Envyion", realm="sargeras", hero="Halo", heroCn="光晕", code="CIQAR03Gt7xPmcDNOjs2Zlb3yOMDDAAAAAAAAAAAAmZxMmZbmxMz2MGjx2MzYmZGbIzYxMNAzMzgZ2MjmNDmtZbLjZWYAmZAjZmZMbMz2yMzgZwA", pvp={ { id=106, name="Driven to Madness", cn="堕入疯狂" }, { id=763, name="Psyfiend", cn="灵能魔" }, { id=5568, name="Phase Shift", cn="相位变换" } } },
        { rank=2, rating=2507, player="Nothinglasts", realm="alleria", hero="Void Torrent", heroCn="虚空洪流", code="CIQAR03Gt7xPmcDNOjs2Zlb3yaYMAAAAAAAAAAAAYMLzMmZbmxMz2MzYMz2MzYmZGLMZYZx0AMzMDmZxMa2MY2mtlMmZjBAzgxMjxsMzYbZmZwMYA", pvp={ { id=5447, name="Cascading Horrors", cn="倾泻恐怖" }, { id=763, name="Psyfiend", cn="灵能魔" }, { id=106, name="Driven to Madness", cn="堕入疯狂" } } },
        { rank=3, rating=2475, player="Rhx", realm="kelthuzad", hero="Void Torrent", heroCn="虚空洪流", code="CIQAR03Gt7xPmcDNOjs2Zlb3yaYMAAAAAAAAAAAAYMLzMGbzMmZ2mZYMz2YGzMzYZMZYZx0AMzMDmZxMa2MY2mtlMmZjBYMzgxMjxsMzYbZmZwMYA", pvp={ { id=763, name="Psyfiend", cn="灵能魔" }, { id=106, name="Driven to Madness", cn="堕入疯狂" }, { id=5568, name="Phase Shift", cn="相位变换" } } },
    } },
    [259] = { key = "ROGUE/ASSASSINATION", n = 30, pvp = {
        { id=5697, name="Preemptive Maneuver", cn="先觉机动", pct=93.3 },
        { id=3480, name="Smoke Bomb", cn="烟雾弹", pct=93.3 },
        { id=5405, name="Dismantle", cn="卸除武装", pct=63.3 },
        { id=5408, name="Thick as Thieves", cn="偷天换日", pct=20.0 },
        { id=830, name="Hemotoxin", cn="血毒素", pct=13.3 },
    }, builds = {
        { rank=1, rating=2740, player="Ozzthegreat", realm="illidan", hero="Hand of Fate", heroCn="命运之手", code="CMQA5HmDzx68KWyrW/8Y781L7bmlxsNzAAAAAAY2mxsNDAAAAAollhZYmxYbmZmtZWmZYmZmZwMmxMGGsNz2YhxMmlGzy2wkthhtZYbmBzMDGA", pvp={ { id=5697, name="Preemptive Maneuver", cn="先觉机动" }, { id=3480, name="Smoke Bomb", cn="烟雾弹" }, { id=3448, name="Maneuverability", cn="动若脱兔" } } },
        { rank=2, rating=2711, player="Hecklebury", realm="malganis", hero="Hand of Fate", heroCn="命运之手", code="CMQA5HmDzx68KWyrW/8Y781L7bmlxsZGAAAAAAz2MmtZAAAAAAtsMMDzMGLzMzsNzyMzYmZmZwMmxMGGYgFYGjGzCIbDYbG2AmZGMA", pvp={ { id=3480, name="Smoke Bomb", cn="烟雾弹" }, { id=5405, name="Dismantle", cn="卸除武装" }, { id=5697, name="Preemptive Maneuver", cn="先觉机动" } } },
        { rank=2, rating=2711, player="Wildcard", realm="laughing-skull", hero="Hand of Fate", heroCn="命运之手", code="CMQA5HmDzx68KWyrW/8Y781L7bmlxsZGAAAAAAz2MmtZAAAAAAtsMmBzMGLzMzsNzyMjZmZMDmxMmxAsNz2YhxMmlGzy2wkthhtZYbmBzMjxA", pvp={ { id=5697, name="Preemptive Maneuver", cn="先觉机动" }, { id=5405, name="Dismantle", cn="卸除武装" }, { id=3480, name="Smoke Bomb", cn="烟雾弹" } } },
    } },
    [261] = { key = "ROGUE/SUBTLETY", n = 30, pvp = {
        { id=1209, name="Smoke Bomb", cn="烟雾弹", pct=100.0 },
        { id=5698, name="Preemptive Maneuver", cn="先觉机动", pct=96.7 },
        { id=5406, name="Dismantle", cn="卸除武装", pct=76.7 },
        { id=5409, name="Thick as Thieves", cn="偷天换日", pct=23.3 },
    }, builds = {
        { rank=1, rating=2368, player="Bornfilthy", realm="daggerspine", hero="Deathstalker's Mark", heroCn="死亡猎手标记", code="CUQA5HmDzx68KWyrW/8Y781L7DgZ2mBAAAAAmtZmZZiZZbmxMjZgZmZmlxsNjZmllhBzMGwMGAAAAzwMsZWmxsMDjFG2mZbahWmFGDzMzMYmZA", pvp={ { id=5698, name="Preemptive Maneuver", cn="先觉机动" }, { id=1209, name="Smoke Bomb", cn="烟雾弹" }, { id=3462, name="Death from Above", cn="天降杀机" } } },
        { rank=2, rating=2352, player="Másvidal", realm="area-52", hero="Unseen Blade", heroCn="隐秘之刃", code="CUQA5HmDzx68KWyrW/8Y781L7DgZ2mBAAAAAmtZmZZiZZbmxMjZgZGzsMmtZmZmllhBzMGwMGAAAAGmhNz2MmlZYsww2MbTL0ysxMDzMzMYmZA", pvp={ { id=5698, name="Preemptive Maneuver", cn="先觉机动" }, { id=5406, name="Dismantle", cn="卸除武装" }, { id=1209, name="Smoke Bomb", cn="烟雾弹" } } },
        { rank=3, rating=2335, player="Robinhoe", realm="malganis", hero="Surprising Strikes", heroCn="出其不意", code="CUQA5HmDzx68KWyrW/8Y781L7DgZ2mBAAAAAmlxMLDmltZGzMmBPwMjZWGz2YmZWWGGzMzYAzYAAAAYYGWMLzYWmhxCDbzsNWwyshZYmZmBzMDA", pvp={ { id=5409, name="Thick as Thieves", cn="偷天换日" }, { id=1209, name="Smoke Bomb", cn="烟雾弹" }, { id=5698, name="Preemptive Maneuver", cn="先觉机动" } } },
    } },
    [262] = { key = "SHAMAN/ELEMENTAL", n = 30, pvp = {
        { id=5660, name="Shamanism", cn="萨满之道", pct=100.0 },
        { id=5574, name="Burrow", cn="掘地三尺", pct=90.0 },
        { id=3620, name="Grounding Totem", cn="根基图腾", pct=90.0 },
        { id=3488, name="Totem of Wrath", cn="天怒图腾", pct=13.3 },
    }, builds = {
        { rank=1, rating=2661, player="Meatbeaterx", realm="aggramar", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CYQALMl7AwW51MWzGneuHE3tPCAAAAzMLbzMGjZZZhxMMDAAAAsYmtNzMDbGWY2mZaoZWAgZbMzYmtFTLMzYsYMz8AzMbzGzyMYmZZAgZGgZmZGDz4DA", pvp={ { id=5574, name="Burrow", cn="掘地三尺" }, { id=3620, name="Grounding Totem", cn="根基图腾" }, { id=5660, name="Shamanism", cn="萨满之道" } } },
        { rank=2, rating=2616, player="Meatbeaterx", realm="bleeding-hollow", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CYQALMl7AwW51MWzGneuHE3tPCAAAAzMLbzMGjZZZhxMMDAAAAsYmtNzMDbGWY2mZaoZWAgZbMGzstYaxMzYsYMzYmZb2MzyMYmZZAgZGAMzYYGfA", pvp={ { id=5660, name="Shamanism", cn="萨满之道" }, { id=5574, name="Burrow", cn="掘地三尺" }, { id=3620, name="Grounding Totem", cn="根基图腾" } } },
        { rank=3, rating=2540, player="Gelex", realm="tichondrius", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CYQALMl7AwW51MWzGneuHE3tPCAAAAzMLbzMGjZZZhxMMDAAAAsYmtNzMDbGWY2mZaoZWAgZbMzYmtFTLjZGjFjZGzMb2MzyMYmZZAgZGgZmZGDz4DA", pvp={ { id=5660, name="Shamanism", cn="萨满之道" }, { id=5574, name="Burrow", cn="掘地三尺" }, { id=3620, name="Grounding Totem", cn="根基图腾" } } },
    } },
    [263] = { key = "SHAMAN/ENHANCEMENT", n = 30, pvp = {
        { id=722, name="Shamanism", cn="萨满之道", pct=100.0 },
        { id=3622, name="Grounding Totem", cn="根基图腾", pct=96.7 },
        { id=5575, name="Burrow", cn="掘地三尺", pct=93.3 },
    }, builds = {
        { rank=1, rating=2587, player="Resetmmr", realm="stormrage", hero="Tempest", heroCn="狂风怒号", code="CcQALMl7AwW51MWzGneuHE3tPOzMDMzMzMzMMzMDAAAAAAAAwGWw2yMmZWW0ssNMDzMNYBgZZwYmtlZsMGz2MbGzMMz2YGAgZYmZGzMxMzMDGMGA", pvp={ { id=3622, name="Grounding Totem", cn="根基图腾" }, { id=5575, name="Burrow", cn="掘地三尺" }, { id=722, name="Shamanism", cn="萨满之道" } } },
        { rank=2, rating=2555, player="Madeofpaper", realm="stormrage", hero="Tempest", heroCn="狂风怒号", code="CcQALMl7AwW51MWzGneuHE3tPOzMDMzMzMzMMzMDAAAAAAAAwGWw2yMmZWW0ssNMDzMNYBgZZwYmtlZswY2MbmZmhZ2GzAAMDzMzYmJmZmZwgxA", pvp={ { id=3622, name="Grounding Totem", cn="根基图腾" }, { id=5575, name="Burrow", cn="掘地三尺" }, { id=722, name="Shamanism", cn="萨满之道" } } },
        { rank=3, rating=2553, player="Zözösh", realm="zuljin", hero="Tempest", heroCn="狂风怒号", code="CcQALMl7AwW51MWzGneuHE3tPOzMDMzMzMzMMzMDAAAAAAAAwGWw2yMmZ2W0ssNMDzMNYBgZbwYstMjlxMzGLmZmhZ2GzAAMDzMzYmJmZmZwgxA", pvp={ { id=5575, name="Burrow", cn="掘地三尺" }, { id=722, name="Shamanism", cn="萨满之道" }, { id=3622, name="Grounding Totem", cn="根基图腾" } } },
    } },
    [264] = { key = "SHAMAN/RESTORATION", n = 30, pvp = {
        { id=715, name="Grounding Totem", cn="根基图腾", pct=96.7 },
        { id=5723, name="Lightning Lasso", cn="闪电磁索", pct=60.0 },
        { id=5437, name="Master of the Elements", cn="元素宗师", pct=56.7 },
        { id=5567, name="Static Field Totem", cn="静电力场图腾", pct=53.3 },
        { id=3755, name="Rain Dance", cn="祈雨舞", pct=26.7 },
    }, builds = {
        { rank=1, rating=2613, player="Koksammy", realm="tichondrius", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CgQALMl7AwW51MWzGneuHE3tPCAAAgBAAAAzMzYbbGmZmZmxMzYssMzmNGzYZasNzCTmhxCmZwsNGjmllZmFzAzi5BmZMzsNbGAAAYmBzMYmhZgB", pvp={ { id=5723, name="Lightning Lasso", cn="闪电磁索" }, { id=5437, name="Master of the Elements", cn="元素宗师" }, { id=715, name="Grounding Totem", cn="根基图腾" } } },
        { rank=2, rating=2555, player="Mjölnîr", realm="aggramar", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CgQALMl7AwW51MWzGneuHE3tPCAAAgBAAAAzMzYbZGmZmZmxMzYstMziNGzYZasNzCTmhxCmZws8AGjmtFzsMGDWMmZmZmtZzAAAAzMYmBzMMzgB", pvp={ { id=5437, name="Master of the Elements", cn="元素宗师" }, { id=5723, name="Lightning Lasso", cn="闪电磁索" }, { id=715, name="Grounding Totem", cn="根基图腾" } } },
        { rank=3, rating=2537, player="Bobbywittjr", realm="blood-furnace", hero="Surging Totem", heroCn="涌动图腾", code="CgQALMl7AwW51MWzGneuHE3tPCAAAgBAAAAzMmltlhZmZmZmZmZMWWmZzGjZsMN2mZjJzwYDzMY2GjRzyiZWGjBLGzMPwMz2sZAAAgZGMzAzwYwA", pvp={ { id=3755, name="Rain Dance", cn="祈雨舞" }, { id=715, name="Grounding Totem", cn="根基图腾" }, { id=5723, name="Lightning Lasso", cn="闪电磁索" } } },
    } },
    [265] = { key = "WARLOCK/AFFLICTION", n = 30, pvp = {
        { id=5386, name="Jinx", cn="祸不单行", pct=96.7 },
        { id=5579, name="Impish Instincts", cn="小鬼本能", pct=80.0 },
        { id=16, name="Rot and Decay", cn="腐化枯萎", pct=40.0 },
        { id=15, name="Gateway Mastery", cn="传送门大师", pct=36.7 },
        { id=18, name="Nether Ward", cn="虚空守卫", pct=30.0 },
        { id=5608, name="Soul Rip", cn="夺魂", pct=10.0 },
    }, builds = {
        { rank=1, rating=2618, player="Filese", realm="tichondrius", hero="Demonic Soul", heroCn="恶魔之魂", code="CkQAMrNP5kak+EBqLfUa3dMm+uMGzMjmNzYhZmZZAAAmZWsZmZxMAwsssMGGziZaMzMslZjhtBAAgZAAAMzMzMzMjZmhZMzMzMYGDAgBMA", pvp={ { id=5386, name="Jinx", cn="祸不单行" }, { id=5579, name="Impish Instincts", cn="小鬼本能" }, { id=18, name="Nether Ward", cn="虚空守卫" } } },
        { rank=2, rating=2565, player="Stinkie", realm="nerzhul", hero="Wither", heroCn="枯萎", code="CkQAMrNP5kak+EBqLfUa3dMm+uMmZmZ0sxYhZmZZAAAmZWmtZmZbMAwsssMGGziZaMzMslZjhlBAAgZAAgZmZmZmZGjZMMzYmZmBzMGAgBMA", pvp={ { id=18, name="Nether Ward", cn="虚空守卫" }, { id=16, name="Rot and Decay", cn="腐化枯萎" }, { id=5386, name="Jinx", cn="祸不单行" } } },
        { rank=3, rating=2530, player="Skide", realm="sargeras", hero="Wither", heroCn="枯萎", code="CkQAMrNP5kak+EBqLfUa3dMm+yMMzoZxMz2MzYWGAAgZmlZZmZWGDAMLbbjhxsYmGzMDbZWYYZAAAYGAAYmZmZmZMmNzMMzYmZMYmZGAgZgB", pvp={ { id=5386, name="Jinx", cn="祸不单行" }, { id=5579, name="Impish Instincts", cn="小鬼本能" }, { id=16, name="Rot and Decay", cn="腐化枯萎" } } },
    } },
    [267] = { key = "WARLOCK/DESTRUCTION", n = 30, pvp = {
        { id=5580, name="Impish Instincts", cn="小鬼本能", pct=83.3 },
        { id=157, name="Fel Fissure", cn="邪能裂痕", pct=70.0 },
        { id=3508, name="Nether Ward", cn="虚空守卫", pct=60.0 },
        { id=5382, name="Gateway Mastery", cn="传送门大师", pct=43.3 },
        { id=5607, name="Soul Rip", cn="夺魂", pct=40.0 },
    }, builds = {
        { rank=1, rating=2745, player="Níenarýa", realm="skullcrusher", hero="Wither", heroCn="枯萎", code="CsQAMrNP5kak+EBqLfUa3dMm+uMGPwMjmtZGLMzMLDmxsMjZbxMAAYmZYmZxGmZGzssMamZYZYZ2asxAAAjBmZDAzMzMYmZmxAAAwMmBAAzwA", pvp={ { id=3508, name="Nether Ward", cn="虚空守卫" }, { id=157, name="Fel Fissure", cn="邪能裂痕" }, { id=5580, name="Impish Instincts", cn="小鬼本能" } } },
        { rank=2, rating=2638, player="Papajohns", realm="illidan", hero="Wither", heroCn="枯萎", code="CsQAMrNP5kak+EBqLfUa3dMm+uMGPwMjmtZGLMzMLjxMmlZMLLmBAAzMDzMLWwMzYmltRzMDbDLzWjNGAAYAGbAYmZmBzMzMGAAAmxMAAMzwA", pvp={ { id=3508, name="Nether Ward", cn="虚空守卫" }, { id=5580, name="Impish Instincts", cn="小鬼本能" }, { id=157, name="Fel Fissure", cn="邪能裂痕" } } },
        { rank=3, rating=2594, player="Diábolical", realm="sargeras", hero="Wither", heroCn="枯萎", code="CsQAMrNP5kak+EBqLfUa3dMm+uMmxMjmtZGLMzMLjxMmlZMLLmBAAzMDzMLWgBmFjGzAY2iNGAAYMwYDAYmBzMzMGAAAmxMAAMPwwA", pvp={ { id=5382, name="Gateway Mastery", cn="传送门大师" }, { id=3508, name="Nether Ward", cn="虚空守卫" }, { id=5580, name="Impish Instincts", cn="小鬼本能" } } },
    } },
    [71] = { key = "WARRIOR/ARMS", n = 30, pvp = {
        { id=33, name="Sharpen Blade", cn="打磨利刃", pct=100.0 },
        { id=3534, name="Disarm", cn="缴械", pct=60.0 },
        { id=5625, name="Safeguard", cn="捍卫", pct=56.7 },
        { id=31, name="Storm of Destruction", cn="毁灭风暴", pct=43.3 },
        { id=5701, name="Berserker Roar", cn="狂战士咆哮", pct=30.0 },
    }, builds = {
        { rank=1, rating=2637, player="Ilh", realm="sargeras", hero="Slayer's Dominance", heroCn="屠戮之霸", code="CcEASWsDSHNyPDXnbxuIhH3ZdDzMzsMzwMDAAAghphZGzYZxMzMDjZmBAAAAwMLzMgsYssNLmZZYzwwMzMtRzMYDYGMLzMsMz2gZmZGAmZYA", pvp={ { id=33, name="Sharpen Blade", cn="打磨利刃" }, { id=5701, name="Berserker Roar", cn="狂战士咆哮" }, { id=31, name="Storm of Destruction", cn="毁灭风暴" } } },
        { rank=2, rating=2622, player="Gummi", realm="tichondrius", hero="Slayer's Dominance", heroCn="屠戮之霸", code="CcEASWsDSHNyPDXnbxuIhH3ZdjZmZmFzYmZGAAAghphxwMLLzMzMjZGzMAAAAAGLzMwEGLbDsAGwMMhMD2AzMMMYWmZbAmZAwMMA", pvp={ { id=31, name="Storm of Destruction", cn="毁灭风暴" }, { id=3534, name="Disarm", cn="缴械" }, { id=33, name="Sharpen Blade", cn="打磨利刃" } } },
        { rank=3, rating=2545, player="Urdem", realm="moon-guard", hero="Slayer's Dominance", heroCn="屠戮之霸", code="CcEASWsDSHNyPDXnbxuIhH3ZdjZmZmFzMmZGAAAghphxYGLMzMzYGzMDAAAAgxyMDIMW2mFzsNsZYYmZm2oZGsBMjFzyMYZmtBzMzMAMzwA", pvp={ { id=31, name="Storm of Destruction", cn="毁灭风暴" }, { id=3534, name="Disarm", cn="缴械" }, { id=33, name="Sharpen Blade", cn="打磨利刃" } } },
    } },
    [73] = { key = "WARRIOR/PROTECTION", n = 30, pvp = {
        { id=171, name="Morale Killer", cn="士气重挫", pct=63.3 },
        { id=175, name="Thunderstruck", cn="雷霆打击", pct=50.0 },
        { id=5715, name="Power Through Adversity", cn="逆势奋发", pct=43.3 },
        { id=5627, name="Storm of Destruction", cn="毁灭风暴", pct=33.3 },
        { id=5626, name="Safeguard", cn="捍卫", pct=23.3 },
        { id=24, name="Disarm", cn="缴械", pct=20.0 },
        { id=831, name="Dragon Charge", cn="巨龙冲锋", pct=16.7 },
        { id=168, name="Bodyguard", cn="护卫", pct=13.3 },
    }, builds = {
        { rank=1, rating=1903, player="Humanlog", realm="proudmoore", hero="Demolish", heroCn="崩摧", code="CkEASWsDSHNyPDXnbxuIhH3Zd32AAAzMDmZmZmZ2mxsMMGmGzMjlFzMzwMmZGAAAAsMAMjBAWMjhNyAzwCNmZhxMMDjFAAzMAgBMG", pvp={ { id=175, name="Thunderstruck", cn="雷霆打击" }, { id=5626, name="Safeguard", cn="捍卫" }, { id=171, name="Morale Killer", cn="士气重挫" } } },
        { rank=2, rating=1884, player="Orclog", realm="proudmoore", hero="Demolish", heroCn="崩摧", code="CkEASWsDSHNyPDXnbxuIhH3Zd32AAAzMzwMzYmZ2mxsMMGmGzMjFmZmhZMzMAAAAYZAYGDAsYGDbkBmhFaMzCjZYGMLAAmZAAzAjB", pvp={ { id=168, name="Bodyguard", cn="护卫" }, { id=5626, name="Safeguard", cn="捍卫" }, { id=171, name="Morale Killer", cn="士气重挫" } } },
        { rank=3, rating=1783, player="Loglogn", realm="tichondrius", hero="Demolish", heroCn="崩摧", code="CkEASWsDSHNyPDXnbxuIhH3Zd32AAAzMzwMzYmZ2mxsMMGz0YmZswMzMMjZmBAAAALDAzYAgFzYYjMwMsQjZWYMDzwYBAwMDAYAjB", pvp={ { id=5626, name="Safeguard", cn="捍卫" }, { id=5703, name="Berserker Roar", cn="狂战士咆哮" }, { id=171, name="Morale Killer", cn="士气重挫" } } },
    } },
    [251] = { key = "DEATHKNIGHT/FROST", n = 29, pvp = {
        { id=5429, name="Strangulate", cn="绞袭", pct=93.1 },
        { id=5591, name="Spellwarden", cn="咒术防护", pct=93.1 },
        { id=702, name="Delirium", cn="神智不清", pct=65.5 },
        { id=701, name="Deathchill", cn="死亡之寒", pct=24.1 },
        { id=5586, name="Bloodforged Armor", cn="血锻盔甲", pct=20.7 },
    }, builds = {
        { rank=1, rating=2344, player="Swapzz", realm="stormrage", hero="Reaper's Mark", heroCn="死神印记", code="CsPAkXBWxkyfx9CbGaHonEAhLNDYmhZMzMDzyMzMDbmZ0MjZmZYGzYmZGMzMjZAAAAAAAAAYMbDMgFwywEyYxYmhZGwAYYmBAYA", pvp={ { id=5586, name="Bloodforged Armor", cn="血锻盔甲" }, { id=701, name="Deathchill", cn="死亡之寒" }, { id=5429, name="Strangulate", cn="绞袭" } } },
        { rank=2, rating=2332, player="Üuü", realm="barthilas", hero="Reaper's Mark", heroCn="死神印记", code="CsPAkXBWxkyfx9CbGaHonEAhLNDYmBjZGDzyMzMDbzMjmZMzMDzYGzMzgZmZMDAAAAAAAAAjZbgBsAWGmQGLGzMMzAGADzMAMYA", pvp={ { id=702, name="Delirium", cn="神智不清" }, { id=5429, name="Strangulate", cn="绞袭" }, { id=5591, name="Spellwarden", cn="咒术防护" } } },
        { rank=3, rating=2327, player="Ttvflarkness", realm="dawnbringer", hero="Reaper's Mark", heroCn="死神印记", code="CsPAkXBWxkyfx9CbGaHonEAhLNDYmBjZGDzyMzMDLzYmmZMzMDzwYmZGMzMzMDAAAAAAAAAjZZ2MbzwYhhlZ2mGaGLGzMMzAGADzMYmhBD", pvp={ { id=702, name="Delirium", cn="神智不清" }, { id=5429, name="Strangulate", cn="绞袭" }, { id=5591, name="Spellwarden", cn="咒术防护" } } },
    } },
    [1480] = { key = "DEMONHUNTER/DEVOURER", n = 29, pvp = {
        { id=5735, name="Beckon", cn="召唤", pct=100.0 },
        { id=5734, name="Glimpse", cn="转瞬即逝", pct=75.9 },
        { id=5729, name="Armor of Souls", cn="灵魂护甲", pct=65.5 },
        { id=5738, name="Reverse Magic", cn="反转魔法", pct=24.1 },
        { id=5730, name="Surrender to the Void", cn="向虚空屈服", pct=17.2 },
        { id=5733, name="Detainment", cn="拘押", pct=10.3 },
    }, builds = {
        { rank=1, rating=2704, player="Mvqx", realm="illidan", hero="Demonsurge", heroCn="魔涌", code="CgcBp/epaxe7D0A403L+Tvk0iCAMjZmZmxMjhZAAAAAAAYMGzMDAAAAAAAAzYGmZmZmxMzMMz2Mjxm2WAQADwMmZmlZmpZZmlZmxwA", pvp={ { id=5735, name="Beckon", cn="召唤" }, { id=5734, name="Glimpse", cn="转瞬即逝" }, { id=5729, name="Armor of Souls", cn="灵魂护甲" } } },
        { rank=2, rating=2635, player="Akumma", realm="tichondrius", hero="Voidfall", heroCn="虚落", code="CgcBp/epaxe7D0A403L+Tvk0iCAMjZmZMzMjhBAAAAAAAjZZMzMAAAAAAAAMjZYeAzMzYmZmZmZxMzYRLLMzMzs12MzMAmxMzsMzMNLzsMDDMfA", pvp={ { id=5729, name="Armor of Souls", cn="灵魂护甲" }, { id=5734, name="Glimpse", cn="转瞬即逝" }, { id=5735, name="Beckon", cn="召唤" } } },
        { rank=3, rating=2598, player="Ttndhtwo", realm="proudmoore", hero="Voidfall", heroCn="虚落", code="CgcBp/epaxe7D0A403L+Tvk0iCAMjZmZMmZMMDAAAAAAgHYMGzMDAAAAAAAAzYGmxMzMmZmZmZWMjxiWWYmZmZrtZmZAMjZmZZmZaWmZbGGY+AA", pvp={ { id=5729, name="Armor of Souls", cn="灵魂护甲" }, { id=5735, name="Beckon", cn="召唤" }, { id=5730, name="Surrender to the Void", cn="向虚空屈服" } } },
    } },
    [577] = { key = "DEMONHUNTER/HAVOC", n = 29, pvp = {
        { id=5433, name="Blood Moon", cn="鲜血之月", pct=100.0 },
        { id=813, name="Glimpse", cn="转瞬即逝", pct=93.1 },
        { id=806, name="Reverse Magic", cn="反转魔法", pct=48.3 },
        { id=811, name="Rain from Above", cn="从天而降", pct=31.0 },
        { id=812, name="Detainment", cn="拘押", pct=27.6 },
    }, builds = {
        { rank=1, rating=2770, player="Natooeasy", realm="area-52", hero="Art of the Glaive", heroCn="战刃绝技", code="CEkAp/epaxe7D0A403L+Tvk0iygZmZMjxMjZmJDzAAAAAAAmFjxMzMzMbzMjlZGzYZmhZ2mZZmlZZmZmltZZaaGzMmxCAAAAAACwMzMDGACAAM", pvp={ { id=813, name="Glimpse", cn="转瞬即逝" }, { id=5433, name="Blood Moon", cn="鲜血之月" }, { id=806, name="Reverse Magic", cn="反转魔法" } } },
        { rank=2, rating=2660, player="Golx", realm="thrall", hero="Demonsurge", heroCn="魔涌", code="CEkAp/epaxe7D0A403L+Tvk0iamZMzMDjxMjZmpZMDAAAAAAwsMjxYMzgZGLzMmx2MDmtBWmFzYYW00YmZMjNAAAAAAEAMzgBgAAAD", pvp={ { id=5433, name="Blood Moon", cn="鲜血之月" }, { id=813, name="Glimpse", cn="转瞬即逝" }, { id=812, name="Detainment", cn="拘押" } } },
        { rank=3, rating=2653, player="Golrathx", realm="thrall", hero="Art of the Glaive", heroCn="战刃绝技", code="CEkAp/epaxe7D0A403L+Tvk0iygZmZYMzMjZmJDDAAAAAAwsMjxYmZmZbmZmlZGzYbYbmZbmlZ2mlZmZW2mtppZMzYGLAAAAAAIAzMzMYAIAAwA", pvp={ { id=813, name="Glimpse", cn="转瞬即逝" }, { id=811, name="Rain from Above", cn="从天而降" }, { id=5433, name="Blood Moon", cn="鲜血之月" } } },
    } },
    [1473] = { key = "EVOKER/AUGMENTATION", n = 29, pvp = {
        { id=5563, name="Obsidian Mettle", cn="黑曜之勇", pct=100.0 },
        { id=5560, name="Unburdened Flight", cn="轻驰飞翔", pct=82.8 },
        { id=5561, name="Scouring Flame", cn="冲刷之焰", pct=62.1 },
        { id=5619, name="Time Stop", cn="时间停止", pct=31.0 },
    }, builds = {
        { rank=1, rating=2126, player="Gloomie", realm="tichondrius", hero="Might of the Black Dragonflight", heroCn="黑龙军团之力", code="CEcBPJc41CfcseY0baneJ1IHrNMzMbjZmx2MYmtZMzMmBAAAAAAAAmhZmxYMMmZmBAAAAmZGMzsMmZgZ2MGmlZssMLDzsNMDzMGYDjxMzMDgB", pvp={ { id=5563, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5560, name="Unburdened Flight", cn="轻驰飞翔" }, { id=5561, name="Scouring Flame", cn="冲刷之焰" } } },
        { rank=2, rating=2117, player="Youginong", realm="tichondrius", hero="Mass Eruption", heroCn="大规模喷发", code="CEcBPJc41CfcseY0baneJ1IHrNMzMbzMzMWmBzsNMzMmBAAAAAGAAwMMzwYM1YmZGAAAAYmZGmZWGzMwMLGDzyMWWmlhZ2GmhZmGxGGDMzAYA", pvp={ { id=5561, name="Scouring Flame", cn="冲刷之焰" }, { id=5560, name="Unburdened Flight", cn="轻驰飞翔" }, { id=5563, name="Obsidian Mettle", cn="黑曜之勇" } } },
        { rank=3, rating=2026, player="Augdog", realm="darkspear", hero="Mass Eruption", heroCn="大规模喷发", code="CEcBPJc41CfcseY0baneJ1IHrhZmZbmZmhZwMbDzMjZWAAAAAAAAwMjZmxYomZmZGAAAAYGDmZ2GzMwMLzYYWmx2ysMMz2wMMz0I2wYgZGYYA", pvp={ { id=5619, name="Time Stop", cn="时间停止" }, { id=5563, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5560, name="Unburdened Flight", cn="轻驰飞翔" } } },
    } },
    [1468] = { key = "EVOKER/PRESERVATION", n = 29, pvp = {
        { id=5718, name="Emerald Communion", cn="翡翠交融", pct=100.0 },
        { id=5468, name="Nullifying Shroud", cn="废灵遮罩", pct=100.0 },
        { id=5461, name="Scouring Flame", cn="冲刷之焰", pct=75.9 },
        { id=5459, name="Obsidian Mettle", cn="黑曜之勇", pct=13.8 },
    }, builds = {
        { rank=1, rating=2611, player="Resurecty", realm="lightbringer", hero="Legacy of the Lifebinder", heroCn="生命缚誓者的传承", code="CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZYmBmthBAAzMjZmxYMzEMDAAAsNzMTzgZmZZMDAMmZMzyGLWYYmZmGa2MsZYAMzwA", pvp={ { id=5461, name="Scouring Flame", cn="冲刷之焰" }, { id=5718, name="Emerald Communion", cn="翡翠交融" }, { id=5468, name="Nullifying Shroud", cn="废灵遮罩" } } },
        { rank=2, rating=2571, player="Trantis", realm="tichondrius", hero="Legacy of the Lifebinder", heroCn="生命缚誓者的传承", code="CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZwMeAmthBAAmhZmxYYmYmZAAAgtZmZaGjZmZZMDAMmZMzyGLWYYmZmGa2MsZYMzgZGGA", pvp={ { id=5461, name="Scouring Flame", cn="冲刷之焰" }, { id=5468, name="Nullifying Shroud", cn="废灵遮罩" }, { id=5718, name="Emerald Communion", cn="翡翠交融" } } },
        { rank=3, rating=2541, player="Mackthëknife", realm="tichondrius", hero="Legacy of the Lifebinder", heroCn="生命缚誓者的传承", code="CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZYGGsNMAAwMMzMGDzEzMDAAAsNzMTzYMzMLjZAgxMjZW2YxCDzMz0QzmhNDjZGMzwA", pvp={ { id=5718, name="Emerald Communion", cn="翡翠交融" }, { id=5468, name="Nullifying Shroud", cn="废灵遮罩" }, { id=5461, name="Scouring Flame", cn="冲刷之焰" } } },
    } },
    [254] = { key = "HUNTER/MARKSMANSHIP", n = 29, pvp = {
        { id=651, name="Survival Tactics", cn="生存战术", pct=100.0 },
        { id=5745, name="Scatter Shot", cn="驱散射击", pct=96.6 },
        { id=653, name="Chimaeral Sting", cn="奇美拉钉刺", pct=86.2 },
    }, builds = {
        { rank=1, rating=2670, player="Tokyosdrippn", realm="area-52", hero="Sentinel", heroCn="警戒", code="C4PAD57yiELKEty14ekTDtZEqYbZWGDjZMTjlZG2yMMbAAAAAAAAAjZMjFjZmZMYGNjZGzmtZwMzMzMbjZWGmBAAYmxMYmBzYbhtZAWYmlZMA", pvp={ { id=651, name="Survival Tactics", cn="生存战术" }, { id=660, name="Sniper's Advantage", cn="狙击优势" }, { id=653, name="Chimaeral Sting", cn="奇美拉钉刺" } } },
        { rank=2, rating=2606, player="Omegaotaku", realm="tichondrius", hero="Sentinel", heroCn="警戒", code="C4PAD57yiELKEty14ekTDtZEqYbZWGDjZMTjlZG2yMMbAAAAAAAAgZYMjFjZmZmxwoZMzMzmtZwMzMjZbMzywMAAAzMmZYmBzYbBzAswMLzYA", pvp={ { id=5745, name="Scatter Shot", cn="驱散射击" }, { id=5440, name="Consecutive Concussion", cn="连续震荡" }, { id=651, name="Survival Tactics", cn="生存战术" } } },
        { rank=3, rating=2594, player="Ilidariban", realm="stormrage", hero="Sentinel", heroCn="警戒", code="C4PAD57yiELKEty14ekTDtZEqYbZWGDjZMTjlZG2yMMbAAAAAAAAgZgZsYMzMzMYGNjZmZ2W2mZYmhZmtxYZYmBAAMzYmhZGMjtFMDwCzsMjB", pvp={ { id=5533, name="Diamond Ice", cn="寒冰钻石" }, { id=5745, name="Scatter Shot", cn="驱散射击" }, { id=651, name="Survival Tactics", cn="生存战术" } } },
    } },
    [255] = { key = "HUNTER/SURVIVAL", n = 29, pvp = {
        { id=3607, name="Survival Tactics", cn="生存战术", pct=93.1 },
        { id=5744, name="Scatter Shot", cn="驱散射击", pct=82.8 },
        { id=664, name="Sticky Tar Bomb", cn="粘稠焦油炸弹", pct=44.8 },
        { id=662, name="Mending Bandage", cn="治疗绷带", pct=37.9 },
        { id=3609, name="Chimaeral Sting", cn="奇美拉钉刺", pct=34.5 },
    }, builds = {
        { rank=1, rating=2631, player="Yahwéh", realm="area-52", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C8PAD57yiELKEty14ekTDtZEqMWwMzYmZZ0ssMMDzMNYxYmZMjlBAAAAAgZMzMjtZMMmhlxkBAAAYAwwyyMzswMzMzDMGDYmtZshFjxMzmBA", pvp={ { id=3607, name="Survival Tactics", cn="生存战术" }, { id=664, name="Sticky Tar Bomb", cn="粘稠焦油炸弹" }, { id=5744, name="Scatter Shot", cn="驱散射击" } } },
        { rank=2, rating=2613, player="Jaywaz", realm="tichondrius", hero="Sentinel", heroCn="警戒", code="C8PAD57yiELKEty14ekTDtZEqM2wMzYmZb0ssMMDzMNYbGzMMmtZAAAAAAMDjZsYMmxDMsMjmBAAAYAAW2mxsYmZmZmxMDYmtZstgZMmZWMAA", pvp={ { id=664, name="Sticky Tar Bomb", cn="粘稠焦油炸弹" }, { id=5744, name="Scatter Shot", cn="驱散射击" }, { id=3607, name="Survival Tactics", cn="生存战术" } } },
        { rank=3, rating=2586, player="Anielaingrid", realm="aegwynn", hero="Sentinel", heroCn="警戒", code="C8PAD57yiELKEty14ekTDtZEqM2wMzYmZb0stMMDzMNYbGzMMmtZAAAAAAMDjZsYMmhxsMjmBAAAYAAW2mxsYmZmZmxMDYmtZstgZMmZWMAA", pvp={ { id=3607, name="Survival Tactics", cn="生存战术" }, { id=5744, name="Scatter Shot", cn="驱散射击" }, { id=3609, name="Chimaeral Sting", cn="奇美拉钉刺" } } },
    } },
    [270] = { key = "MONK/MISTWEAVER", n = 29, pvp = {
        { id=5395, name="Peaceweaver", cn="静心织魂", pct=100.0 },
        { id=5603, name="Zen Spheres", cn="禅意法球", pct=100.0 },
        { id=70, name="Eminence", cn="龙威显赫", pct=82.8 },
        { id=1928, name="Zen Focus Tea", cn="禅意聚神茶", pct=10.3 },
    }, builds = {
        { rank=1, rating=2676, player="Crazydogwoez", realm="kelthuzad", hero="Aspect of Harmony", heroCn="和谐化身", code="C4QAQnG51S19isUJoJoTeJ/IKDAAAAAAAghZWmZZMbWMmZwYZbZGs9AzsZbmxCzoZMDYwwwsNzMzwsNLgZbmAAAAAzy02sNzysZbmlZZmBEAMYMzMYGwAQGzA", pvp={ { id=70, name="Eminence", cn="龙威显赫" }, { id=5395, name="Peaceweaver", cn="静心织魂" }, { id=5603, name="Zen Spheres", cn="禅意法球" } } },
        { rank=2, rating=2444, player="Vaen", realm="kelthuzad", hero="Aspect of Harmony", heroCn="和谐化身", code="C4QAQnG51S19isUJoJoTeJ/IKDAAAAAAAghZWmZZMbzixMDGLbLzgNzsZbmxCGNjZADmFY2mZmZY2mFwsNTAAAAgZZab2mZZ2sNzysMzACAGMmZGMDYgBZMDA", pvp={ { id=70, name="Eminence", cn="龙威显赫" }, { id=5395, name="Peaceweaver", cn="静心织魂" }, { id=5603, name="Zen Spheres", cn="禅意法球" } } },
        { rank=3, rating=2420, player="Drmw", realm="dalaran", hero="Aspect of Harmony", heroCn="和谐化身", code="C4QAQnG51S19isUJoJoTeJ/IKDAAAAAAAgxMzyMLjZzixMjNDbLzgtHYmNbzMWwoZMjNMYYGz2MzMDz2sAmlZCAAAAMLTbz2MLzmtZWmlZGQAAM+gZGMDYMAhZA", pvp={ { id=5603, name="Zen Spheres", cn="禅意法球" }, { id=5395, name="Peaceweaver", cn="静心织魂" }, { id=70, name="Eminence", cn="龙威显赫" } } },
    } },
    [65] = { key = "PALADIN/HOLY", n = 29, pvp = {
        { id=640, name="Divine Vision", cn="神圣视野", pct=93.1 },
        { id=5692, name="Blessing of Spellwarding", cn="破咒祝福", pct=58.6 },
        { id=87, name="Spreading the Word", cn="广布圣言", pct=58.6 },
        { id=642, name="Cleanse the Weak", cn="净化虚弱", pct=48.3 },
        { id=5583, name="Searing Glare", cn="灼热凝视", pct=24.1 },
        { id=5663, name="Divine Plea", cn="神圣恳求", pct=10.3 },
    }, builds = {
        { rank=1, rating=2616, player="Miswalkpally", realm="ragnaros", hero="Dawnlight", heroCn="晨光", code="CEEAzbn3egSOtoSwvPw1U1vTLAAAALAwMAAD2GzMzMjZmZBmZYZsZmFjmYYMzMMmtMAMAsB2YbmZmlZbmZ2aAAD2WsNwCwgNDMjZYGAAzMMjxoB", pvp={ { id=5663, name="Divine Plea", cn="神圣恳求" }, { id=640, name="Divine Vision", cn="神圣视野" }, { id=5692, name="Blessing of Spellwarding", cn="破咒祝福" } } },
        { rank=2, rating=2572, player="Juicedaddy", realm="blackhand", hero="Holy Armaments", heroCn="神圣军备", code="CEEAzbn3egSOtoSwvPw1U1vTLAAAALAwMAADWGGMzyMzsMjZMsN2MziZaiZZGmZYYJDADAbgNziZGAEAwMzy2itZG2YjHgxGDzMmhZAMzAYMY0A", pvp={ { id=5692, name="Blessing of Spellwarding", cn="破咒祝福" }, { id=640, name="Divine Vision", cn="神圣视野" }, { id=86, name="Darkest before the Dawn", cn="拂晓的黑暗" } } },
        { rank=3, rating=2485, player="Ánother", realm="illidan", hero="Holy Armaments", heroCn="神圣军备", code="CEEAzbn3egSOtoSwvPw1U1vTLAAAALAwMAADWGGMz2MzsYMjhtx2MziZaiZZGzMDDbZAYAYDsZWMzAgAAmZW2WsMzwGbMM2YGzMMMDgZGAMgGA", pvp={ { id=642, name="Cleanse the Weak", cn="净化虚弱" }, { id=5692, name="Blessing of Spellwarding", cn="破咒祝福" }, { id=640, name="Divine Vision", cn="神圣视野" } } },
    } },
    [70] = { key = "PALADIN/RETRIBUTION", n = 29, pvp = {
        { id=752, name="Blessing of Sanctuary", cn="庇护祝福", pct=96.6 },
        { id=5535, name="Hallowed Ground", cn="神圣之地", pct=86.2 },
        { id=5573, name="Blessing of Spellwarding", cn="破咒祝福", pct=51.7 },
        { id=5584, name="Searing Glare", cn="灼热凝视", pct=31.0 },
        { id=81, name="Luminescence", cn="明光", pct=17.2 },
    }, builds = {
        { rank=1, rating=2731, player="Dentabilis", realm="area-52", hero="Dawnlight", heroCn="晨光", code="CYEAzbn3egSOtoSwvPw1U1vTLAAAAAANLbzMzyYmZMAAAAAAzUmlZYmx2w2wMLz4BMmZYGLsNAMLzyMzs1Mz0iZMDAYBwAYmxMGDmxwGMzMzwYYwA", pvp={ { id=752, name="Blessing of Sanctuary", cn="庇护祝福" }, { id=5584, name="Searing Glare", cn="灼热凝视" }, { id=5535, name="Hallowed Ground", cn="神圣之地" } } },
        { rank=2, rating=2714, player="Hammyr", realm="tichondrius", hero="Dawnlight", heroCn="晨光", code="CYEAzbn3egSOtoSwvPw1U1vTLAAAAAANLbzMzyYmZAAAAAAYmysMDzMz2w2wMbzYMmZYGLsNAMLzyMzs0Mz02Mz2MAgFADgxYGjBzYYDbzMzMMGGMA", pvp={ { id=5573, name="Blessing of Spellwarding", cn="破咒祝福" }, { id=5535, name="Hallowed Ground", cn="神圣之地" }, { id=5584, name="Searing Glare", cn="灼热凝视" } } },
        { rank=3, rating=2702, player="Claudiogodtv", realm="nemesis", hero="Dawnlight", heroCn="晨光", code="CYEAzbn3egSOtoSwvPw1U1vTLAAAAAANLbzMzywMjBAAAAAYmysMDzw2M2GmZbGjxMDzYhtBgZZ2mZmtmZm2mZ2mBAsAYYgxMzwAzYYDbzMzMMGGMA", pvp={ { id=5573, name="Blessing of Spellwarding", cn="破咒祝福" }, { id=5666, name="Spellbreaker", cn="破法者" }, { id=752, name="Blessing of Sanctuary", cn="庇护祝福" } } },
    } },
    [257] = { key = "PRIEST/HOLY", n = 29, pvp = {
        { id=124, name="Spirit of the Redeemer", cn="救赎者之魂", pct=100.0 },
        { id=5569, name="Phase Shift", cn="相位变换", pct=100.0 },
        { id=108, name="Sanctified Ground", cn="神圣之地", pct=37.9 },
        { id=101, name="Psychic Shroud", cn="心灵帷幕", pct=34.5 },
        { id=5479, name="Purification", cn="纯净御罪", pct=27.6 },
    }, builds = {
        { rank=1, rating=2656, player="Peat", realm="hyjal", hero="Guiding Light", heroCn="指引之光", code="CEQAR03Gt7xPmcDNOjs2Zlb3yCDAAAAAAYxwMz2YmxMjhZglZmZGAAAAzYWmBzMzwMjZAMTBwMLzsMzkZbmZZAmZGsYmZWA0MmZMGMz2ygZmZgB", pvp={ { id=124, name="Spirit of the Redeemer", cn="救赎者之魂" }, { id=101, name="Psychic Shroud", cn="心灵帷幕" }, { id=5569, name="Phase Shift", cn="相位变换" } } },
        { rank=2, rating=2595, player="Lovelike", realm="tichondrius", hero="Guiding Light", heroCn="指引之光", code="CEQAR03Gt7xPmcDNOjs2Zlb3yyYAAAAAAAmZmxsNzMmZGDzgZbmZmBAAAwMzsMwYMWmxMDLLGzUAMzyMLzMZWmZ2GgZmBLGDAaGzYGDGbLDmZmB+AA", pvp={ { id=5569, name="Phase Shift", cn="相位变换" }, { id=124, name="Spirit of the Redeemer", cn="救赎者之魂" }, { id=5479, name="Purification", cn="纯净御罪" } } },
        { rank=3, rating=2556, player="Bholebender", realm="tichondrius", hero="Preventive Measures", heroCn="防微杜渐", code="CEQAR03Gt7xPmcDNOjs2Zlb3yCDAAAAAAwMzDMzsNzMmZGDzgZbmZmBAAAwMzsMDGjxyMmZYZxYGAYmlZWmZY2mZ2GgZmBLGDAMjZYMYstNYmZG4DA", pvp={ { id=5569, name="Phase Shift", cn="相位变换" }, { id=5479, name="Purification", cn="纯净御罪" }, { id=124, name="Spirit of the Redeemer", cn="救赎者之魂" } } },
    } },
    [266] = { key = "WARLOCK/DEMONOLOGY", n = 29, pvp = {
        { id=5577, name="Impish Instincts", cn="小鬼本能", pct=82.8 },
        { id=3506, name="Gateway Mastery", cn="传送门大师", pct=69.0 },
        { id=5606, name="Soul Rip", cn="夺魂", pct=51.7 },
        { id=3624, name="Nether Ward", cn="虚空守卫", pct=44.8 },
        { id=162, name="Call Fel Lord", cn="召唤邪能领主", pct=44.8 },
    }, builds = {
        { rank=1, rating=2552, player="Woopzyy", realm="tichondrius", hero="Diabolic Ritual", heroCn="敬魔仪式", code="CoQAMrNP5kak+EBqLfUa3dMm+uMGzMjmlZGLMzMLDAAAAAAwYZZGzMDbGGmZb2ahmxiZGjlZZmZGzAAzMmZmZmBzMzMjxAAAMmxMGzYWmxAeAA", pvp={ { id=5394, name="Shadow Rift", cn="暗影裂隙" }, { id=5577, name="Impish Instincts", cn="小鬼本能" }, { id=3506, name="Gateway Mastery", cn="传送门大师" } } },
        { rank=2, rating=2530, player="Stinkie", realm="nerzhul", hero="Demonic Soul", heroCn="恶魔之魂", code="CoQAMrNP5kak+EBqLfUa3dMm+uMz4BmZ0sNzYZmZMLDAAAAAAwYZZGzMDbGGmZZ2ahmxmBjlxMzMzMAgxMjZmZwMzMzYMAAAzMDjZmhlZGgB", pvp={ { id=3506, name="Gateway Mastery", cn="传送门大师" }, { id=3624, name="Nether Ward", cn="虚空守卫" }, { id=162, name="Call Fel Lord", cn="召唤邪能领主" } } },
        { rank=3, rating=2457, player="Fëlmäxxîng", realm="thrall", hero="Diabolic Ritual", heroCn="敬魔仪式", code="CoQAMrNP5kak+EBqLfUa3dMm+uMGzMjmlZGLMzMLDAAAAAAwYZZGzMDbGGmZb2ahmxiZGjlZZmZGzAAzMmZmZmBzMzMjxAAAMmxMGzYWmxAeAA", pvp={ { id=162, name="Call Fel Lord", cn="召唤邪能领主" }, { id=5577, name="Impish Instincts", cn="小鬼本能" }, { id=3506, name="Gateway Mastery", cn="传送门大师" } } },
    } },
    [252] = { key = "DEATHKNIGHT/UNHOLY", n = 28, pvp = {
        { id=149, name="Necrotic Wounds", cn="死疽伤口", pct=100.0 },
        { id=5430, name="Strangulate", cn="绞袭", pct=85.7 },
        { id=5590, name="Spellwarden", cn="咒术防护", pct=82.1 },
        { id=5585, name="Bloodforged Armor", cn="血锻盔甲", pct=21.4 },
    }, builds = {
        { rank=1, rating=2633, player="Royjones", realm="sargeras", hero="Rider's Champion", heroCn="冠军骑士", code="CwPAkXBWxkyfx9CbGaHonEAhLBYmBjZMDzyYmZa2mxYmhZAAAAAAAAMzYmZAwyMmZYmxMzYw2MbmZmNNz2CzGz20YhBYGAGzMjZwMzMzYGD", pvp={ { id=5590, name="Spellwarden", cn="咒术防护" }, { id=149, name="Necrotic Wounds", cn="死疽伤口" }, { id=5430, name="Strangulate", cn="绞袭" } } },
        { rank=2, rating=2554, player="Slackjawed", realm="dalvengyr", hero="Rider's Champion", heroCn="冠军骑士", code="CwPAkXBWxkyfx9CbGaHonEAhLBYmBjZMDzyYmZa2mxYmhZAAAAAAAAMzYmZAwyMmZYmxMzYw2MbmZmFNz2CzGz20YhBYGAGzMjZwMzMzYGD", pvp={ { id=41, name="Dark Simulacrum", cn="黑暗模拟" }, { id=149, name="Necrotic Wounds", cn="死疽伤口" }, { id=5590, name="Spellwarden", cn="咒术防护" } } },
        { rank=3, rating=2543, player="Cerséï", realm="tichondrius", hero="Rider's Champion", heroCn="冠军骑士", code="CwPAkXBWxkyfx9CbGaHonEAhLBYmBjZMDzyYmZa2mxYMjZAAAAAAAAMzYmZAwyMmZYmxMzYw2MbmZmNNz2CzGz20YhBYGAGzMjZwMzMzYGD", pvp={ { id=149, name="Necrotic Wounds", cn="死疽伤口" }, { id=5430, name="Strangulate", cn="绞袭" }, { id=5590, name="Spellwarden", cn="咒术防护" } } },
    } },
    [581] = { key = "DEMONHUNTER/VENGEANCE", n = 28, pvp = {
        { id=1948, name="Sigil Mastery", cn="咒符掌握", pct=53.6 },
        { id=819, name="Illidan's Grasp", cn="伊利丹之握", pct=53.6 },
        { id=5716, name="Lay In Wait", cn="以逸待劳", pct=46.4 },
        { id=814, name="Cleansed by Flame", cn="烈焰净化", pct=25.0 },
        { id=5521, name="Rain from Above", cn="从天而降", pct=25.0 },
        { id=816, name="Jagged Spikes", cn="锯齿尖刺", pct=21.4 },
        { id=3430, name="Detainment", cn="拘押", pct=14.3 },
        { id=1220, name="Tormentor", cn="酷刑折磨", pct=14.3 },
    }, builds = {
        { rank=1, rating=1276, player="Rumikpop", realm="malganis", hero="Art of the Glaive", heroCn="战刃绝技", code="CUkAp/epaxe7D0A403L+Tvk0iCAYMzMjZmZmYMY2MzMzMMjZGzYGzYYmZmxixsMmZGAAAAmtZwwYZjJMMjZWAAAAwADgAMzAMAAAA+A", pvp={ { id=5716, name="Lay In Wait", cn="以逸待劳" }, { id=3430, name="Detainment", cn="拘押" }, { id=1948, name="Sigil Mastery", cn="咒符掌握" } } },
        { rank=2, rating=1174, player="Yumo", realm="frostmourne", hero="Voidfall", heroCn="虚落", code="CUkAp/epaxe7D0A403L+Tvk0iCAMjZmZMMzkZmBDzMzYMzYmxMmZmxgZmZs9AzMGjZAAAAAAAEwMzYDAAAADMzMzMLtNzMDAAAAAwA", pvp={ { id=819, name="Illidan's Grasp", cn="伊利丹之握" }, { id=5716, name="Lay In Wait", cn="以逸待劳" }, { id=814, name="Cleansed by Flame", cn="烈焰净化" } } },
        { rank=3, rating=845, player="Washedfr", realm="moon-guard", hero="Art of the Glaive", heroCn="战刃绝技", code="CUkAp/epaxe7D0A403L+Tvk0iCAMjZmZMzMzEjxY2mxMzgZMDzMzYmBmZmxyDMGjxMAAAAMbzghxyGTYYGzsAAAAgBzMzMzs02MzMmZAAAAA4DA", pvp={ { id=819, name="Illidan's Grasp", cn="伊利丹之握" }, { id=5716, name="Lay In Wait", cn="以逸待劳" }, { id=3430, name="Detainment", cn="拘押" } } },
    } },
    [104] = { key = "DRUID/GUARDIAN", n = 28, pvp = {
        { id=51, name="Den Mother", cn="兽穴之母", pct=82.1 },
        { id=196, name="Overrun", cn="蛮力冲锋", pct=67.9 },
        { id=52, name="Demoralizing Roar", cn="挫志咆哮", pct=53.6 },
        { id=842, name="Alpha Challenge", cn="头号挑战", pct=25.0 },
        { id=194, name="Charging Bash", cn="横冲直撞", pct=17.9 },
        { id=1237, name="Malorne's Swiftness", cn="玛洛恩的迅捷", pct=17.9 },
        { id=5410, name="Grove Protection", cn="林地守护", pct=14.3 },
    }, builds = {
        { rank=1, rating=1744, player="Zyhsul", realm="emerald-dream", hero="Boundless Moonlight", heroCn="天涯共银辉", code="CgGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAgZmxsYmZMzmZz4BMWGwmhRTz0MzsZmZmZZMDDAAAAAYmZxMw22MDGzyAYqZWmlZmZAAsZMDgFDMgFLbAmZmZDG", pvp={ { id=52, name="Demoralizing Roar", cn="挫志咆哮" }, { id=51, name="Den Mother", cn="兽穴之母" }, { id=196, name="Overrun", cn="蛮力冲锋" } } },
        { rank=2, rating=1350, player="Ironaddlct", realm="frostmourne", hero="Moon Guardian", heroCn="辉月卫士", code="CgGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAgZmZmFzYMzyMLGjZZZgZxMGGwY2mZmZmlxMAAAAAAwsMDYZbmBjZZAMMzysMzMDAgNjZGgNDMYwyGgZmZ2gPA", pvp={ { id=196, name="Overrun", cn="蛮力冲锋" }, { id=3750, name="Freedom of the Herd", cn="兽群的自由" }, { id=51, name="Den Mother", cn="兽穴之母" } } },
        { rank=3, rating=1318, player="Bufferal", realm="malganis", hero="Fount of Strength", heroCn="力量源泉", code="CgGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAgZmxsMzMMzmZbYMWGYWMjhxMmxsZmZMLjZYAAAAAAzYbGwy2MDGz2AYYmlZZmZGAALGzAYxMYAbziBYmZmNYA", pvp={ { id=52, name="Demoralizing Roar", cn="挫志咆哮" }, { id=194, name="Charging Bash", cn="横冲直撞" }, { id=196, name="Overrun", cn="蛮力冲锋" } } },
    } },
    [1467] = { key = "EVOKER/DEVASTATION", n = 28, pvp = {
        { id=5460, name="Obsidian Mettle", cn="黑曜之勇", pct=82.1 },
        { id=5462, name="Scouring Flame", cn="冲刷之焰", pct=75.0 },
        { id=5469, name="Unburdened Flight", cn="轻驰飞翔", pct=75.0 },
        { id=5464, name="Time Stop", cn="时间停止", pct=64.3 },
    }, builds = {
        { rank=1, rating=2648, player="Gloomie", realm="tichondrius", hero="Mass Disintegrate", heroCn="群体裂解", code="CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAwYMzgZYGmhZGzYMTjZmJzM2mZmZGz8AzMzAMzMYmZZMDMwYwGsMGN2GQmJAbYgZGgB", pvp={ { id=5460, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5462, name="Scouring Flame", cn="冲刷之焰" }, { id=5464, name="Time Stop", cn="时间停止" } } },
        { rank=2, rating=2529, player="Iceddietcoke", realm="draktharon", hero="Mass Disintegrate", heroCn="群体裂解", code="CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMDYYmZmZMzMGDTjZmpZmxyMMzMzMzMzAMzYwMbjZgBMzM2YzyYWasNzwkZyCYbYgZGMMA", pvp={ { id=5464, name="Time Stop", cn="时间停止" }, { id=5462, name="Scouring Flame", cn="冲刷之焰" }, { id=5460, name="Obsidian Mettle", cn="黑曜之勇" } } },
        { rank=3, rating=2505, player="Resurecty", realm="lightbringer", hero="Might of the Black Dragonflight", heroCn="黑龙军团之力", code="CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAwMjZgZYGzMMzwYMjxMzYmZsMDzMzMzMzMAzwwMzyYGYAGsBLjhx2AYGA2wAzMwYA", pvp={ { id=5462, name="Scouring Flame", cn="冲刷之焰" }, { id=5464, name="Time Stop", cn="时间停止" }, { id=5469, name="Unburdened Flight", cn="轻驰飞翔" } } },
    } },
    [253] = { key = "HUNTER/BEASTMASTERY", n = 28, pvp = {
        { id=3599, name="Survival Tactics", cn="生存战术", pct=100.0 },
        { id=5746, name="Scatter Shot", cn="驱散射击", pct=82.1 },
        { id=3604, name="Chimaeral Sting", cn="奇美拉钉刺", pct=57.1 },
        { id=5444, name="Kindred Beasts", cn="野兽亲和", pct=50.0 },
        { id=693, name="The Beast Within", cn="野兽之心", pct=10.7 },
    }, builds = {
        { rank=1, rating=2725, player="Shadeh", realm="tichondrius", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C0PAD57yiELKEty14ekTDtZEqAMmxwCsAzwQDbAAYGzYmFzwMmZY8AzMGmxMzMGzYxMjZmZMMaGAAAAwMAAAMDzMgZ2ILYmFwyAwA", pvp={ { id=3599, name="Survival Tactics", cn="生存战术" }, { id=5746, name="Scatter Shot", cn="驱散射击" }, { id=5444, name="Kindred Beasts", cn="野兽亲和" } } },
        { rank=2, rating=2638, player="Mutations", realm="sargeras", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C0PAD57yiELKEty14ekTDtZEqAMmxwCsAzwQDbAAYGzYmFzwMmZY8AzMGmxMzMGzYxMjZmZMMaGAAAAwMAAAMDzMgZ2ILYmFwyAwA", pvp={ { id=3599, name="Survival Tactics", cn="生存战术" }, { id=3604, name="Chimaeral Sting", cn="奇美拉钉刺" }, { id=5746, name="Scatter Shot", cn="驱散射击" } } },
        { rank=3, rating=2628, player="Outz", realm="whisperwind", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C0PAD57yiELKEty14ekTDtZEqAMmxwCsAzwQDbAAYGzYmFzwMmZY8AzMGmxMzMGzYxMjZmZwQzAAAAAmBAAgZYmBMzGZBzsAWGAG", pvp={ { id=3604, name="Chimaeral Sting", cn="奇美拉钉刺" }, { id=3599, name="Survival Tactics", cn="生存战术" }, { id=5746, name="Scatter Shot", cn="驱散射击" } } },
    } },
    [260] = { key = "ROGUE/OUTLAW", n = 28, pvp = {
        { id=3483, name="Smoke Bomb", cn="烟雾弹", pct=89.3 },
        { id=145, name="Dismantle", cn="卸除武装", pct=75.0 },
        { id=5699, name="Preemptive Maneuver", cn="先觉机动", pct=71.4 },
        { id=3421, name="Turn the Tables", cn="局势逆转", pct=42.9 },
        { id=1208, name="Thick as Thieves", cn="偷天换日", pct=10.7 },
    }, builds = {
        { rank=1, rating=2373, player="Bootyguru", realm="bonechewer", hero="Hand of Fate", heroCn="命运之手", code="CQQA5HmDzx68KWyrW/8Y781L7DgZAGDmZbmZmZGjZZxMzMbTbzY2mBAAAAAYZZmZGmZmZWMzMGAAAAzAYwsNLmZmRzMbMbssNtwiZAmZmZGYA", pvp={ { id=5699, name="Preemptive Maneuver", cn="先觉机动" }, { id=3483, name="Smoke Bomb", cn="烟雾弹" }, { id=145, name="Dismantle", cn="卸除武装" } } },
        { rank=2, rating=2136, player="Exid", realm="stormrage", hero="Unseen Blade", heroCn="隐秘之刃", code="CQQA5HmDzx68KWyrW/8Y781L7DgZYwYGmZbmZmZGjZZxMzMbTbDWmBAAAAAYZZmZMzMjZWMzMGAAAAzwADmtZxMzMamZjZjltpF2YAmZmZGYA", pvp={ { id=5699, name="Preemptive Maneuver", cn="先觉机动" }, { id=3483, name="Smoke Bomb", cn="烟雾弹" }, { id=145, name="Dismantle", cn="卸除武装" } } },
        { rank=3, rating=2121, player="Bodymasage", realm="tichondrius", hero="Unseen Blade", heroCn="隐秘之刃", code="CQQA5HmDzx68KWyrW/8Y781L7DgZ8ADzYMmZbmZmZGjZZzMzMbTLD2mBAAAAAMLLjZYmZMziZmxAAAAYGGYwsNLmZmRzMbMbssNtwGDwMzMzAfA", pvp={ { id=3421, name="Turn the Tables", cn="局势逆转" }, { id=3483, name="Smoke Bomb", cn="烟雾弹" }, { id=1208, name="Thick as Thieves", cn="偷天换日" } } },
    } },
    [102] = { key = "DRUID/BALANCE", n = 27, pvp = {
        { id=185, name="Moonkin Aura", cn="枭兽光环", pct=81.5 },
        { id=5407, name="Owlkin Adept", cn="枭兽专家", pct=81.5 },
        { id=5383, name="High Winds", cn="高天狂风", pct=63.0 },
        { id=836, name="Faerie Swarm", cn="精灵虫群", pct=51.9 },
    }, builds = {
        { rank=2, rating=2576, player="Fanëto", realm="tichondrius", hero="Dream Surge", heroCn="梦境涌现", code="CYGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAAAAAAWoMLNjxMD8AmtxMzMLwwDMbjlZMjZwsMjZmZY2wAgx22Mz22MbzyMNzsMTAAAA2MzMzMYzwYMDgZGMzADA", pvp={ { id=5383, name="High Winds", cn="高天狂风" }, { id=185, name="Moonkin Aura", cn="枭兽光环" }, { id=836, name="Faerie Swarm", cn="精灵虫群" } } },
        { rank=3, rating=2575, player="Wakeenfiendx", realm="tichondrius", hero="Dream Surge", heroCn="梦境涌现", code="CYGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAAAAAAWoMLNjxMDwsZmZmZjxDMegZbsMjZMDmlZMzMDzGGAM22mZ22mZbWmpZmlZCAAAwmZmZmBbGGjZAMzgZGYA", pvp={ { id=5407, name="Owlkin Adept", cn="枭兽专家" }, { id=5383, name="High Winds", cn="高天狂风" }, { id=185, name="Moonkin Aura", cn="枭兽光环" } } },
        { rank=5, rating=2549, player="Fredagn", realm="illidan", hero="Dream Surge", heroCn="梦境涌现", code="CYGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAAAAAAWoMLNjxMDwsNzMzMbMeAzMbjlZMjZGmlZMzMD2wAgx22Mz22MbzyMNzsMTAAAA2YmZMYzwYMDgZGMzADA", pvp={ { id=836, name="Faerie Swarm", cn="精灵虫群" }, { id=5646, name="Tireless Pursuit", cn="不息追猎" }, { id=5407, name="Owlkin Adept", cn="枭兽专家" } } },
    } },
    [63] = { key = "MAGE/FIRE", n = 27, pvp = {
        { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形", pct=100.0 },
        { id=5706, name="Overpowered Barrier", cn="超强能量屏障", pct=96.3 },
        { id=5588, name="Master Shepherd", cn="牧羊大师", pct=70.4 },
        { id=5489, name="Ice Wall", cn="冰墙", pct=29.6 },
    }, builds = {
        { rank=1, rating=2742, player="Fujikaze", realm="kelthuzad", hero="Spellfire Spheres", heroCn="法术火焰宝珠", code="C8DAche08tHz49KSVf7iKFnyuNstMzyMzMb2MzIDmBAAwMLzYmZbWmZmmtllZAA2MzMz2wYmZBAAAAALmZmZAAghZmBDzsMDMzMzQGzMMMDjB", pvp={ { id=5588, name="Master Shepherd", cn="牧羊大师" }, { id=5706, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
        { rank=2, rating=2720, player="Polynike", realm="tichondrius", hero="Mana Cascade", heroCn="法力涌流", code="C8DAche08tHz49KSVf7iKFnyuNmtFzyMzMbYmBzYmBAAwMLzYmZZWmZGz2yyMAAbmZmZbGjZmFAAAAAsYmZGAAwMGzwMMzyMAmZgxMAzwA", pvp={ { id=5588, name="Master Shepherd", cn="牧羊大师" }, { id=5706, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
        { rank=3, rating=2691, player="Edrees", realm="kelthuzad", hero="Spellfire Spheres", heroCn="法术火焰宝珠", code="C8DAche08tHz49KSVf7iKFnyuNmtlZWmZegZBzMyMMDAAgZWmxMzysMzMNbLbzAAsZmZmtZMmZWAAAAAwiZmZGAAYGjZwwMLzAzMzMkxYAzwYA", pvp={ { id=5706, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5588, name="Master Shepherd", cn="牧羊大师" }, { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
    } },
    [66] = { key = "PALADIN/PROTECTION", n = 27, pvp = {
        { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫", pct=92.6 },
        { id=861, name="Shield of Virtue", cn="美德之盾", pct=77.8 },
        { id=5664, name="Bear the Burden", cn="当承其重", pct=51.9 },
        { id=860, name="Warrior of Light", cn="光明战士", pct=29.6 },
        { id=5582, name="Searing Glare", cn="灼热凝视", pct=18.5 },
        { id=91, name="Steed of Glory", cn="荣耀战马", pct=11.1 },
    }, builds = {
        { rank=1, rating=2526, player="Aluvia", realm="malygos", hero="Light's Guidance", heroCn="圣光指引", code="CIEAzbn3egSOtoSwvPw1U1vTLsZYWmZmZGzMjFGzyswwAAMAAAAAAopZmlZGzMjZs1GAGAYgtBAAmZaZmZbmZmltlWmZsZZBDDMYGzYAwMz2MwYGgxG", pvp={ { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫" }, { id=861, name="Shield of Virtue", cn="美德之盾" }, { id=5664, name="Bear the Burden", cn="当承其重" } } },
        { rank=2, rating=2467, player="Wheyprot", realm="gorefiend", hero="Holy Bulwark", heroCn="神圣壁垒", code="CIEAzbn3egSOtoSwvPw1U1vTLsZYWmZGzMzMjNMz2sYZYAAGAAAAAA00MzyMjZGG2aDADAMD2AAAIAzMLbLtMzYx2CGGYmxMmZGAMzAgZAGL", pvp={ { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫" }, { id=5664, name="Bear the Burden", cn="当承其重" }, { id=861, name="Shield of Virtue", cn="美德之盾" } } },
        { rank=3, rating=2459, player="Cloudx", realm="shattered-hand", hero="Light's Guidance", heroCn="圣光指引", code="CIEAzbn3egSOtoSwvPw1U1vTLsZegtZbmZMzMzwCjZbWsMMAADAAAAAAaamZZmxMDjHYLAYAgZwGAAYmptZmlZmZW2WabG2sthhBmZMjxMAYYbGgZAGL", pvp={ { id=860, name="Warrior of Light", cn="光明战士" }, { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫" }, { id=861, name="Shield of Virtue", cn="美德之盾" } } },
    } },
    [72] = { key = "WARRIOR/FURY", n = 26, pvp = {
        { id=3735, name="Slaughterhouse", cn="屠宰场", pct=100.0 },
        { id=177, name="Enduring Rage", cn="无尽之怒", pct=80.8 },
        { id=3533, name="Disarm", cn="缴械", pct=46.2 },
        { id=179, name="Death Wish", cn="死亡之愿", pct=23.1 },
        { id=5624, name="Safeguard", cn="捍卫", pct=19.2 },
        { id=5702, name="Berserker Roar", cn="狂战士咆哮", pct=19.2 },
    }, builds = {
        { rank=1, rating=2661, player="Isnlonely", realm="tichondrius", hero="Lightning Strikes", heroCn="闪电打击", code="CgEASWsDSHNyPDXnbxuIhH3ZdDAAAAAAgGDjZMz2mZmZMGzMzMjZmZWGGzMzsYmZGAAImZZbsxmlNz0YmZYysxMjFAzsYsAAzMAMGDjZYM", pvp={ { id=3533, name="Disarm", cn="缴械" }, { id=3735, name="Slaughterhouse", cn="屠宰场" }, { id=177, name="Enduring Rage", cn="无尽之怒" } } },
        { rank=2, rating=2655, player="Kenstlols", realm="tichondrius", hero="Lightning Strikes", heroCn="闪电打击", code="CgEASWsDSHNyPDXnbxuIhH3ZdDAAAAAAgGDjZMz2mZmZMGzMzMjZmZWGGzMzsYmZGAAImZZbsxmlNz0YmZYysxMjFAzsYsAAzMAMGDjZYM", pvp={ { id=3533, name="Disarm", cn="缴械" }, { id=177, name="Enduring Rage", cn="无尽之怒" }, { id=3735, name="Slaughterhouse", cn="屠宰场" } } },
        { rank=3, rating=2600, player="Syrtangx", realm="area-52", hero="Lightning Strikes", heroCn="闪电打击", code="CgEASWsDSHNyPDXnbxuIhH3ZdDAAAAAAgGDzMjZWYmZGjxMzMzMzMzsMjxMzMLmZmBAACDsBLLGNmBkZDzYBwMLGLAwMDAjBGDGD", pvp={ { id=3533, name="Disarm", cn="缴械" }, { id=3735, name="Slaughterhouse", cn="屠宰场" }, { id=177, name="Enduring Rage", cn="无尽之怒" } } },
    } },
}
