-- 由 clawhub services/wow-agent/export_pvp_meta.py 生成，⛔别手改（随 PvP 榜数据刷新）。
-- ⛔ 全局表：与 GearInsightPopularTalents 同款，主插件 ShowTalentPicker 直接读。
GearInsightPvpTalents = {
    season = 42,
    mode = "shuffle",
    top = 30,
    region = "US",
    date = "2026-09-23",
    [250] = { key = "DEATHKNIGHT/BLOOD", n = 30, pvp = {
        { id=608, name="Last Dance", cn="最终之舞", pct=100.0 },
        { id=3441, name="Decomposing Aura", cn="腐烂光环", pct=63.3 },
        { id=5592, name="Spellwarden", cn="咒术防护", pct=63.3 },
        { id=5587, name="Bloodforged Armor", cn="血锻盔甲", pct=30.0 },
        { id=609, name="Death Chain", cn="死亡锁链", pct=20.0 },
        { id=206, name="Strangulate", cn="绞袭", pct=10.0 },
    }, builds = {
        { rank=1, rating=1617, player="Gandoom", realm="illidan", hero="Vampiric Speed", heroCn="吸血鬼之速", code="CoPAkXBWxkyfx9CbGaHonEAhLxYWmZGmxMzMMLzMzYmNjxMzYAAAAAzMzMzMzMjZmBAMmZmZAAAmZ2GDjZstYsstMMsNMsNAzwAAwMzMDgB", pvp={ { id=3441, name="Decomposing Aura", cn="腐烂光环" }, { id=5592, name="Spellwarden", cn="咒术防护" }, { id=608, name="Last Dance", cn="最终之舞" } } },
        { rank=2, rating=1601, player="Ttvflarkness", realm="dawnbringer", hero="Vampiric Speed", heroCn="吸血鬼之速", code="CoPAkXBWxkyfx9CbGaHonEAhLxYWmZmxMGzMMLjZGsMjxMzYGAAAAYmZmZGzMjZmBAMmZmZAAAmZ2GDjZssYsssMMsNMsNAzYGAAmZmZAjB", pvp={ { id=609, name="Death Chain", cn="死亡锁链" }, { id=608, name="Last Dance", cn="最终之舞" }, { id=3441, name="Decomposing Aura", cn="腐烂光环" } } },
        { rank=3, rating=1590, player="Dibbons", realm="kul-tiras", hero="Reaper's Mark", heroCn="死神印记", code="CoPAkXBWxkyfx9CbGaHonEAhLxYWmZGmZmxMMLzMzEbmZMzMmBAAAAmZmZGzMDzMjBAjZmZGAAgZmtxwYGbLNW2WGmsNMsMAzYGAAmZmZAMA", pvp={ { id=3441, name="Decomposing Aura", cn="腐烂光环" }, { id=5592, name="Spellwarden", cn="咒术防护" }, { id=608, name="Last Dance", cn="最终之舞" } } },
    } },
    [251] = { key = "DEATHKNIGHT/FROST", n = 30, pvp = {
        { id=5429, name="Strangulate", cn="绞袭", pct=96.7 },
        { id=5591, name="Spellwarden", cn="咒术防护", pct=70.0 },
        { id=702, name="Delirium", cn="神智不清", pct=66.7 },
        { id=5586, name="Bloodforged Armor", cn="血锻盔甲", pct=36.7 },
        { id=701, name="Deathchill", cn="死亡之寒", pct=13.3 },
        { id=3512, name="Dark Simulacrum", cn="黑暗模拟", pct=10.0 },
    }, builds = {
        { rank=1, rating=2497, player="Asitawakito", realm="tichondrius", hero="Reaper's Mark", heroCn="死神印记", code="CsPAkXBWxkyfx9CbGaHonEAhLNAzMDjZmZYWmZmZYzYmmZMzMDzMGzMzgZmZMDAAAAAAAAAjZbgBsAWGmQGLGzMMzAzAYYmBAYA", pvp={ { id=5429, name="Strangulate", cn="绞袭" }, { id=5591, name="Spellwarden", cn="咒术防护" }, { id=702, name="Delirium", cn="神智不清" } } },
        { rank=2, rating=2466, player="Claudio", realm="tichondrius", hero="Wave of Souls", heroCn="灵魂浪潮", code="CsPAkXBWxkyfx9CbGaHonEAhLNDYmhZMzMDzyMzMDbmZYmxMzMMjZMzMDmZmxMAAAAAAAAAMmtBGwCYZYAGLGzMMzAGADzMAAD", pvp={ { id=702, name="Delirium", cn="神智不清" }, { id=5429, name="Strangulate", cn="绞袭" }, { id=701, name="Deathchill", cn="死亡之寒" } } },
        { rank=3, rating=2403, player="Üuü", realm="barthilas", hero="Reaper's Mark", heroCn="死神印记", code="CsPAkXBWxkyfx9CbGaHonEAhLNDYmBjZGDzyMzMDbzMjmZMzMDzYGzMzgZmZMDAAAAAAAAAjZbgBsAWGmQGLGzMMzAGADzMAMYA", pvp={ { id=702, name="Delirium", cn="神智不清" }, { id=5429, name="Strangulate", cn="绞袭" }, { id=5591, name="Spellwarden", cn="咒术防护" } } },
    } },
    [581] = { key = "DEMONHUNTER/VENGEANCE", n = 30, pvp = {
        { id=1948, name="Sigil Mastery", cn="咒符掌握", pct=60.0 },
        { id=5716, name="Lay In Wait", cn="以逸待劳", pct=50.0 },
        { id=819, name="Illidan's Grasp", cn="伊利丹之握", pct=43.3 },
        { id=816, name="Jagged Spikes", cn="锯齿尖刺", pct=26.7 },
        { id=5521, name="Rain from Above", cn="从天而降", pct=20.0 },
        { id=814, name="Cleansed by Flame", cn="烈焰净化", pct=16.7 },
        { id=1220, name="Tormentor", cn="酷刑折磨", pct=16.7 },
        { id=3429, name="Reverse Magic", cn="反转魔法", pct=13.3 },
    }, builds = {
        { rank=1, rating=1520, player="Zoeykpop", realm="malganis", hero="Art of the Glaive", heroCn="战刃绝技", code="CUkAp/epaxe7D0A403L+Tvk0iCAYMzMjZmZmYMY2MzMzMMjZGzYGzMDmZmxyDMmlxYGAAAAmtZwwYZjJMMjZWAAAAwADgAMzAMAAAA+A", pvp={ { id=5716, name="Lay In Wait", cn="以逸待劳" }, { id=3429, name="Reverse Magic", cn="反转魔法" }, { id=1948, name="Sigil Mastery", cn="咒符掌握" } } },
        { rank=2, rating=1400, player="Rumikpop", realm="malganis", hero="Fury of the Aldrachi", heroCn="奥达奇之怒", code="CUkAp/epaxe7D0A403L+Tvk0iCAYMzMjZmZGMGMbmZmZGmxMjZMjZmBzMzY5BGzyYMDAAAAz2MYYssxADzYmFAAAAMwAAgZGgBAAAwHA", pvp={ { id=5716, name="Lay In Wait", cn="以逸待劳" }, { id=819, name="Illidan's Grasp", cn="伊利丹之握" }, { id=1948, name="Sigil Mastery", cn="咒符掌握" } } },
        { rank=3, rating=1383, player="Vvhatdaf", realm="velen", hero="Art of the Glaive", heroCn="战刃绝技", code="CUkAp/epaxe7D0A403L+Tvk0iCAMjxMzMmZmMzMGzmZmZmhZMYmZGzYwYmxixYMmBAAAgZbGMMWWYCDzYmFAAAAMYmZmZml2mZmxMDAAAAAD", pvp={ { id=3429, name="Reverse Magic", cn="反转魔法" }, { id=5716, name="Lay In Wait", cn="以逸待劳" }, { id=1948, name="Sigil Mastery", cn="咒符掌握" } } },
    } },
    [103] = { key = "DRUID/FERAL", n = 30, pvp = {
        { id=620, name="Wicked Claws", cn="邪恶之爪", pct=96.7 },
        { id=5647, name="Tireless Pursuit", cn="不息追猎", pct=73.3 },
        { id=5384, name="High Winds", cn="高天狂风", pct=36.7 },
        { id=3053, name="Strength of the Wild", cn="野性力量", pct=36.7 },
        { id=820, name="Savage Momentum", cn="狂野冲撞", pct=33.3 },
        { id=611, name="Ferocious Wound", cn="凶猛伤痕", pct=16.7 },
    }, builds = {
        { rank=1, rating=2501, player="Semvetax", realm="alleria", hero="Thriving Growth", heroCn="兴荣生长", code="CcGADBD3hSPCL9Y9gz68WcKvMAAAAAAAjZWwYmZGz2yYZmlZmZMzMAAAAsEMbGYmZqZMbmZmZWGzYGAAAAAAgBAAAQzsMbzMzMLzs0sNzyGMzMALMYAAMzgZ2wA", pvp={ { id=5647, name="Tireless Pursuit", cn="不息追猎" }, { id=5384, name="High Winds", cn="高天狂风" }, { id=620, name="Wicked Claws", cn="邪恶之爪" } } },
        { rank=2, rating=2392, player="Riverside", realm="sargeras", hero="Thriving Growth", heroCn="兴荣生长", code="CcGADBD3hSPCL9Y9gz68WcKvMAAAAAAwYMzCDzMzY2WGLjlZmZMzMAAAAsEMbGYmZqZMbmZmZWGzMGAAAAAAgBAAAQzsMbzMzMLzs0sNzyGYmBYhBDAgZGMzGGA", pvp={ { id=620, name="Wicked Claws", cn="邪恶之爪" }, { id=5384, name="High Winds", cn="高天狂风" }, { id=5647, name="Tireless Pursuit", cn="不息追猎" } } },
        { rank=3, rating=2383, player="Benchpress", realm="bloodscalp", hero="Thriving Growth", heroCn="兴荣生长", code="CcGADBD3hSPCL9Y9gz68WcKvMAAAAAAwYMzCDzMzY2WYZmlZmZMzMAAAAsEMbGYmZqZMbmZmZWGz8AzAAAAAAAMAAAACAmtZWa2mZZDMzAswgBAwMDAGA", pvp={ { id=620, name="Wicked Claws", cn="邪恶之爪" }, { id=5384, name="High Winds", cn="高天狂风" }, { id=5647, name="Tireless Pursuit", cn="不息追猎" } } },
    } },
    [105] = { key = "DRUID/RESTORATION", n = 30, pvp = {
        { id=5687, name="Forest Guardian", cn="森林守护者", pct=100.0 },
        { id=1215, name="Early Spring", cn="万物复苏", pct=100.0 },
        { id=5668, name="Call of Ohn'ahra", cn="欧恩哈拉的召唤", pct=46.7 },
        { id=838, name="High Winds", cn="高天狂风", pct=26.7 },
        { id=59, name="Disentanglement", cn="解缠", pct=23.3 },
    }, builds = {
        { rank=1, rating=2790, player="Habibieu", realm="area-52", hero="Hunt Beneath the Open Skies", heroCn="茫野猎手", code="CkGADBD3hSPCL9Y9gz68WcKvMMMmZBjxMzsMmZMmNmNLDAAAAAAAAAAsMDsZGjZmZGMbmZmZ2MYGAAAAADAYMgttxCGzMLDAgZbmFz2ML2YMjhZsBMDAmZmZAYA", pvp={ { id=838, name="High Winds", cn="高天狂风" }, { id=5687, name="Forest Guardian", cn="森林守护者" }, { id=1215, name="Early Spring", cn="万物复苏" } } },
        { rank=2, rating=2781, player="Renner", realm="zuljin", hero="Thriving Growth", heroCn="兴荣生长", code="CkGADBD3hSPCL9Y9gz68WcKvMMMmZBjxMzsMmZMmNmNbzAAAAAAAAAAglZIbmx0MzMwsZmZmZxwMAAAAAMAAGw22YBTzMLDAgZbmlmtZWsBz8ADzYD0MAYmZmBgB", pvp={ { id=1215, name="Early Spring", cn="万物复苏" }, { id=5687, name="Forest Guardian", cn="森林守护者" }, { id=838, name="High Winds", cn="高天狂风" } } },
        { rank=3, rating=2763, player="Alphawolf", realm="kilrogg", hero="Thriving Growth", heroCn="兴荣生长", code="CkGADBD3hSPCL9Y9gz68WcKvMMMmZBjxMzsMmZMmNmNLzAAAAAAAAAAglZIbmx0MzMwsZmZmZxgZAAAAAMAAGw22YBTzMLDAgZbmlmtZWsxYmHYYGbgmBAzMzMAMA", pvp={ { id=838, name="High Winds", cn="高天狂风" }, { id=5687, name="Forest Guardian", cn="森林守护者" }, { id=1215, name="Early Spring", cn="万物复苏" } } },
    } },
    [254] = { key = "HUNTER/MARKSMANSHIP", n = 30, pvp = {
        { id=651, name="Survival Tactics", cn="生存战术", pct=100.0 },
        { id=5745, name="Scatter Shot", cn="驱散射击", pct=90.0 },
        { id=653, name="Chimaeral Sting", cn="奇美拉钉刺", pct=83.3 },
        { id=659, name="Ranger's Finesse", cn="游侠的灵巧", pct=23.3 },
    }, builds = {
        { rank=1, rating=2731, player="Tokyosdrippn", realm="area-52", hero="Sentinel", heroCn="警戒", code="C4PAD57yiELKEty14ekTDtZEqYbZWGDjZMTjlZG2yMMbAAAAAAAAAjZMjFjZmZMYGNjZGzmtZwMzMzMbjZWGmBAAYmxMYmBzYbhtZAWYmlZMA", pvp={ { id=651, name="Survival Tactics", cn="生存战术" }, { id=5745, name="Scatter Shot", cn="驱散射击" }, { id=653, name="Chimaeral Sting", cn="奇美拉钉刺" } } },
        { rank=2, rating=2703, player="Kanlaomei", realm="tichondrius", hero="Sentinel", heroCn="警戒", code="C4PAD57yiELKEty14ekTDtZEqYbZWGDjZMTjlZG2yMMbAAAAAAAAgZYMzyyMmZmZGY0MmZmZzyMwMzMzsMmZZYGAAgZYmhZGMjtFMDwCzsMjB", pvp={ { id=651, name="Survival Tactics", cn="生存战术" }, { id=5745, name="Scatter Shot", cn="驱散射击" }, { id=653, name="Chimaeral Sting", cn="奇美拉钉刺" } } },
        { rank=3, rating=2682, player="Ttcfivehunt", realm="proudmoore", hero="Black Arrow", heroCn="黑蚀箭", code="C4PAD57yiELKEty14ekTDtZEqYbZ2GDjZMTjlZG2yMMLAAAAAAAAgZMjZsYMzMmBGNjZGz2iZwMzMzYZMz2gBAAYmxMzMzMYGbLYGgN+gZZmZA", pvp={ { id=651, name="Survival Tactics", cn="生存战术" }, { id=5745, name="Scatter Shot", cn="驱散射击" }, { id=653, name="Chimaeral Sting", cn="奇美拉钉刺" } } },
    } },
    [255] = { key = "HUNTER/SURVIVAL", n = 30, pvp = {
        { id=3607, name="Survival Tactics", cn="生存战术", pct=93.3 },
        { id=5744, name="Scatter Shot", cn="驱散射击", pct=90.0 },
        { id=662, name="Mending Bandage", cn="治疗绷带", pct=40.0 },
        { id=3609, name="Chimaeral Sting", cn="奇美拉钉刺", pct=36.7 },
        { id=664, name="Sticky Tar Bomb", cn="粘稠焦油炸弹", pct=23.3 },
        { id=686, name="Diamond Ice", cn="寒冰钻石", pct=10.0 },
    }, builds = {
        { rank=1, rating=2745, player="Willyy", realm="area-52", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C8PAD57yiELKEty14ekTDtZEqMWwMzYmZb0ssMMDzMNYZGzMMmlZAAAAAAMDjhlZMmxMsMjmBAAAYAAWWmhlZmZmZmxMDYmtZssAjZmZ2MAA", pvp={ { id=3607, name="Survival Tactics", cn="生存战术" }, { id=3609, name="Chimaeral Sting", cn="奇美拉钉刺" }, { id=5744, name="Scatter Shot", cn="驱散射击" } } },
        { rank=2, rating=2719, player="Yahwéh", realm="area-52", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C8PAD57yiELKEty14ekTDtZEqMWwMzYmZZ0ssMMDzMNYxYmZMjlBAAAAAgZYMsYMmxMmlZ0MAAAADAGWWmZmFzMzYmxMDYmtZstgZMmZYAA", pvp={ { id=3607, name="Survival Tactics", cn="生存战术" }, { id=662, name="Mending Bandage", cn="治疗绷带" }, { id=5744, name="Scatter Shot", cn="驱散射击" } } },
        { rank=3, rating=2713, player="Jaywaz", realm="tichondrius", hero="Sentinel", heroCn="警戒", code="C8PAD57yiELKEty14ekTDtZEqM2wMzYmZb0ssMMDzMNYbGzMMmtZAAAAAAMzYMjFjxMeghlZ0MAAAADAwy2MmFzMzMzwMDYmtZstgZMmZWMAA", pvp={ { id=664, name="Sticky Tar Bomb", cn="粘稠焦油炸弹" }, { id=5744, name="Scatter Shot", cn="驱散射击" }, { id=3607, name="Survival Tactics", cn="生存战术" } } },
    } },
    [64] = { key = "MAGE/FROST", n = 30, pvp = {
        { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形", pct=96.7 },
        { id=5708, name="Overpowered Barrier", cn="超强能量屏障", pct=90.0 },
        { id=5497, name="Snowdrift", cn="积雪", pct=40.0 },
        { id=5581, name="Master Shepherd", cn="牧羊大师", pct=36.7 },
        { id=5390, name="Ice Wall", cn="冰墙", pct=36.7 },
    }, builds = {
        { rank=1, rating=2633, player="Gotenkss", realm="emerald-dream", hero="Splintering Sorcery", heroCn="裂解巫术", code="CAEAche08tHz49KSVf7iKFnyuNmtlZWmxMLYmJmhZmZmZmFzMDzYmZZmmZWmFAwMzMLLzMtBAALAAAgNA2WGzMzALzYMzstAAAwMLzMYGGzAgBA", pvp={ { id=5708, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5497, name="Snowdrift", cn="积雪" } } },
        { rank=2, rating=2615, player="Goküü", realm="emerald-dream", hero="Splintering Sorcery", heroCn="裂解巫术", code="CAEAche08tHz49KSVf7iKFnyuNmtlZWmZmZBzMxMMzMzMzsYmZYGzMLz0MzysAAmZmZZZmpNAAYBAAAsBw2yYmZALzYMzstAAAwMLzMYGGzAgBA", pvp={ { id=5708, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5581, name="Master Shepherd", cn="牧羊大师" } } },
        { rank=3, rating=2588, player="Polynike", realm="tichondrius", hero="Augury Abounds", heroCn="满目征兆", code="CAEAche08tHz49KSVf7iKFnyuNmtFzyMzMbDzMYGmZmZmZWMzMjZMzsMjZmtZBAMzMzyyMjNAAYBAAAsBw2yYmZALzDYMzYBAAgZWAmhxMgBDA", pvp={ { id=5581, name="Master Shepherd", cn="牧羊大师" }, { id=5708, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5622, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
    } },
    [268] = { key = "MONK/BREWMASTER", n = 30, pvp = {
        { id=672, name="Double Barrel", cn="醉上加醉", pct=83.3 },
        { id=667, name="Hot Trub", cn="热酿", pct=76.7 },
        { id=843, name="Admonishment", cn="劝诫", pct=50.0 },
        { id=666, name="Microbrew", cn="私家陈酿", pct=40.0 },
        { id=1958, name="Niuzao's Essence", cn="砮皂的精华", pct=20.0 },
        { id=669, name="Avert Harm", cn="斗转星移", pct=16.7 },
    }, builds = {
        { rank=1, rating=1893, player="Droguex", realm="tichondrius", hero="Manifestation", heroCn="化气凝形", code="CwQAQnG51S19isUJoJoTeJ/IKDAAAgZZzYGGzyMzGzMjBAAAAAAYZBzgZGYGGbwYmZmhZjZGjlhltHYbb2wsAAALzyYZ2mZZAAAAMsxwMDYMGAAwA", pvp={ { id=667, name="Hot Trub", cn="热酿" }, { id=672, name="Double Barrel", cn="醉上加醉" }, { id=843, name="Admonishment", cn="劝诫" } } },
        { rank=2, rating=1599, player="Worldpvp", realm="nerzhul", hero="Aspect of Harmony", heroCn="和谐化身", code="CwQAQnG51S19isUJoJoTeJ/IKDAAAgZZzYGzM2mxGmZAAAAAAAYZBjYmZ2YGzMAmZmZYWgxMLDLb22mthZBAAWmlplZbmlBAY2mlmZmZzMswwMzMDTjBYAgB", pvp={ { id=672, name="Double Barrel", cn="醉上加醉" }, { id=667, name="Hot Trub", cn="热酿" }, { id=666, name="Microbrew", cn="私家陈酿" } } },
        { rank=3, rating=1551, player="Artam", realm="thrall", hero="Aspect of Harmony", heroCn="和谐化身", code="CwQAQnG51S19isUJoJoTeJ/IKDAAAgZbzYGGzyMzGzMjBAAAAAAYZBmwMYmB2MMmZmZMzGzMmZZYZ7B22mNMLAAwysMtMbzsMAAQAMsBmZATjBAAMA", pvp={ { id=843, name="Admonishment", cn="劝诫" }, { id=667, name="Hot Trub", cn="热酿" }, { id=672, name="Double Barrel", cn="醉上加醉" } } },
    } },
    [270] = { key = "MONK/MISTWEAVER", n = 30, pvp = {
        { id=5395, name="Peaceweaver", cn="静心织魂", pct=100.0 },
        { id=5603, name="Zen Spheres", cn="禅意法球", pct=100.0 },
        { id=70, name="Eminence", cn="龙威显赫", pct=73.3 },
        { id=1928, name="Zen Focus Tea", cn="禅意聚神茶", pct=16.7 },
        { id=679, name="Counteract Magic", cn="法术中和", pct=10.0 },
    }, builds = {
        { rank=1, rating=2871, player="Meepsweep", realm="tichondrius", hero="Aspect of Harmony", heroCn="和谐化身", code="C4QAQnG51S19isUJoJoTeJ/IKDAAAAAAAghZWmZZMbzmxMjFDYY2egZ2sNzYBjmxMWwgZhxsNzMzwsNLgZbmAAAAAzy02sNzysZbmlZZmBEAAjZmBzAAsIjZA", pvp={ { id=70, name="Eminence", cn="龙威显赫" }, { id=5395, name="Peaceweaver", cn="静心织魂" }, { id=5603, name="Zen Spheres", cn="禅意法球" } } },
        { rank=2, rating=2676, player="Crazydogwoez", realm="kelthuzad", hero="Aspect of Harmony", heroCn="和谐化身", code="C4QAQnG51S19isUJoJoTeJ/IKDAAAAAAAghZWmZZMbWMmZwYZbZGs9AzsZbmxGzoZMDYwwwsNzMzwsNLgZbmAAAAAzy02sNzysZbmlZZmBEAMYMzMYGwAQGzA", pvp={ { id=70, name="Eminence", cn="龙威显赫" }, { id=5395, name="Peaceweaver", cn="静心织魂" }, { id=5603, name="Zen Spheres", cn="禅意法球" } } },
        { rank=3, rating=2664, player="Vaen", realm="kelthuzad", hero="Aspect of Harmony", heroCn="和谐化身", code="C4QAQnG51S19isUJoJoTeJ/IKDAAAAAAAgxMzyMLjZzixMDGLbLzgNzsZbmxCGNjZADmFDz2MzMDz2sAmtZCAAAAMLTbz2MLzmtZWmlZGQAwgxMzgZADAZMDA", pvp={ { id=70, name="Eminence", cn="龙威显赫" }, { id=5395, name="Peaceweaver", cn="静心织魂" }, { id=5603, name="Zen Spheres", cn="禅意法球" } } },
    } },
    [269] = { key = "MONK/WINDWALKER", n = 30, pvp = {
        { id=3745, name="Turbo Fists", cn="怒雷叶轮", pct=100.0 },
        { id=3737, name="Wind Waker", cn="唤风者", pct=76.7 },
        { id=3052, name="Grapple Weapon", cn="抓钩武器", pct=60.0 },
        { id=77, name="Ride the Wind", cn="驭风而行", pct=56.7 },
    }, builds = {
        { rank=1, rating=2680, player="Droguex", realm="tichondrius", hero="Flurry Strikes", heroCn="疾风乱打", code="C0QAQnG51S19isUJoJoTeJ/IKbmZMgZYbmZ2mxAAAAAAAAAAAALDjwMz2wAwMmZmZY2mFGmlZCAYzMLzMMzMzABwmZwYa2mlmZmZBYYgZmZAYhxgZmZzHA", pvp={ { id=3737, name="Wind Waker", cn="唤风者" }, { id=3052, name="Grapple Weapon", cn="抓钩武器" }, { id=3745, name="Turbo Fists", cn="怒雷叶轮" } } },
        { rank=2, rating=2653, player="Silentpalm", realm="sargeras", hero="Flurry Strikes", heroCn="疾风乱打", code="C0QAQnG51S19isUJoJoTeJ/IKbmZMYMDbzMz2MAAAAAAAAAAAALDjwMz2wAwMmZMzYWmFGmlZCAYzMLzMMzMzABwmZWmlx0sNLNzMzCwwAzMzAwCjBzMzmPA", pvp={ { id=77, name="Ride the Wind", cn="驭风而行" }, { id=3745, name="Turbo Fists", cn="怒雷叶轮" }, { id=3052, name="Grapple Weapon", cn="抓钩武器" } } },
        { rank=3, rating=2642, player="Gnoku", realm="tichondrius", hero="Flurry Strikes", heroCn="疾风乱打", code="C0QAQnG51S19isUJoJoTeJ/IKbmZMgZYbmZ2mxAAAAAAAAAAAALDjwMzGGwwMmZmZYWmFGmlZCAYzMbzMMzMzABwmZWmlx0sNLNzMzCwwAzMzAwyYAzMzmPA", pvp={ { id=3737, name="Wind Waker", cn="唤风者" }, { id=5643, name="Rising Dragon Sweep", cn="升龙扫" }, { id=3745, name="Turbo Fists", cn="怒雷叶轮" } } },
    } },
    [65] = { key = "PALADIN/HOLY", n = 30, pvp = {
        { id=640, name="Divine Vision", cn="神圣视野", pct=100.0 },
        { id=5692, name="Blessing of Spellwarding", cn="破咒祝福", pct=66.7 },
        { id=87, name="Spreading the Word", cn="广布圣言", pct=63.3 },
        { id=642, name="Cleanse the Weak", cn="净化虚弱", pct=30.0 },
        { id=5583, name="Searing Glare", cn="灼热凝视", pct=23.3 },
        { id=86, name="Darkest before the Dawn", cn="拂晓的黑暗", pct=10.0 },
    }, builds = {
        { rank=1, rating=2665, player="Miswalkpally", realm="ragnaros", hero="Dawnlight", heroCn="晨光", code="CEEAzbn3egSOtoSwvPw1U1vTLAAAALAwMAAD2GzMzMjZmZBmZYZsZmFjmYYMzMMmtMAMAsB2YbmZmlZbmZ2aAAD2WsNwCwgNDMjZYGAAzMMjxoB", pvp={ { id=5663, name="Divine Plea", cn="神圣恳求" }, { id=640, name="Divine Vision", cn="神圣视野" }, { id=5692, name="Blessing of Spellwarding", cn="破咒祝福" } } },
        { rank=2, rating=2656, player="Onryô", realm="illidan", hero="Dawnlight", heroCn="晨光", code="CEEAzbn3egSOtoSwvPw1U1vTLAAAALAwAAYwywMjZWmZmlBjhF2mZWMTTMLzwMY8AbZAYAYDsZ2mZmZZWmZmtGAAAgFWAjNzMmZMDGAAzMYwoB", pvp={ { id=640, name="Divine Vision", cn="神圣视野" }, { id=87, name="Spreading the Word", cn="广布圣言" }, { id=5692, name="Blessing of Spellwarding", cn="破咒祝福" } } },
        { rank=3, rating=2591, player="Airbusx", realm="tichondrius", hero="Holy Armaments", heroCn="神圣军备", code="CEEAzbn3egSOtoSwvPw1U1vTLAAAALAwMAADWGGMzyMzsYMjhtx2MziZaiZZGmBDbZAYAYDsZ2mZGAEAwMzy2itZG2YjhxmZGGbzgBwMDAGQDA", pvp={ { id=640, name="Divine Vision", cn="神圣视野" }, { id=642, name="Cleanse the Weak", cn="净化虚弱" }, { id=5692, name="Blessing of Spellwarding", cn="破咒祝福" } } },
    } },
    [70] = { key = "PALADIN/RETRIBUTION", n = 30, pvp = {
        { id=752, name="Blessing of Sanctuary", cn="庇护祝福", pct=96.7 },
        { id=5535, name="Hallowed Ground", cn="神圣之地", pct=76.7 },
        { id=5573, name="Blessing of Spellwarding", cn="破咒祝福", pct=56.7 },
        { id=5584, name="Searing Glare", cn="灼热凝视", pct=43.3 },
        { id=81, name="Luminescence", cn="明光", pct=16.7 },
        { id=5572, name="Spreading the Word", cn="广布圣言", pct=10.0 },
    }, builds = {
        { rank=1, rating=2748, player="Dentabilis", realm="area-52", hero="Dawnlight", heroCn="晨光", code="CYEAzbn3egSOtoSwvPw1U1vTLAAAAAANLbzMzyYmZMAAAAAAzUmlZYmx2w2wMLz4BMmZYGLsNAMLzyMzs1Mz0iZMDAYBwAYmxMGDmxwGMzMzwYYwA", pvp={ { id=752, name="Blessing of Sanctuary", cn="庇护祝福" }, { id=5584, name="Searing Glare", cn="灼热凝视" }, { id=5535, name="Hallowed Ground", cn="神圣之地" } } },
        { rank=2, rating=2714, player="Hammyr", realm="tichondrius", hero="Dawnlight", heroCn="晨光", code="CYEAzbn3egSOtoSwvPw1U1vTLAAAAAANLbzMzyYmZAAAAAAYmysMDzM2G2GmZbGjxMDzYhtBgZZWmZmlmZm2mZ2mBAsAYAMGzYmBzYYDbzMzMMGGMA", pvp={ { id=5573, name="Blessing of Spellwarding", cn="破咒祝福" }, { id=5584, name="Searing Glare", cn="灼热凝视" }, { id=5535, name="Hallowed Ground", cn="神圣之地" } } },
        { rank=3, rating=2702, player="Claudiogodtv", realm="nemesis", hero="Dawnlight", heroCn="晨光", code="CYEAzbn3egSOtoSwvPw1U1vTLAAAAAANLbzMzywMjBAAAAAYmysMDzw2w2wMbzYMmZYGLsNAMLzyMzs1Mz02Mz2MAgFADDMDzsNDMjhNsNzMzwYYwA", pvp={ { id=5573, name="Blessing of Spellwarding", cn="破咒祝福" }, { id=5584, name="Searing Glare", cn="灼热凝视" }, { id=752, name="Blessing of Sanctuary", cn="庇护祝福" } } },
    } },
    [256] = { key = "PRIEST/DISCIPLINE", n = 30, pvp = {
        { id=123, name="Inner Light", cn="心灵之光", pct=100.0 },
        { id=114, name="Ultimate Radiance", cn="极致光辉", pct=93.3 },
        { id=5570, name="Phase Shift", cn="相位变换", pct=86.7 },
        { id=109, name="Trinity", cn="三位一体", pct=10.0 },
    }, builds = {
        { rank=1, rating=2796, player="Trashdiscx", realm="thrall", hero="Guiding Light", heroCn="指引之光", code="CAQAR03Gt7xPmcDNOjs2Zlb3yCDsMDWmZMzMwMbzYmZGjZGAAAAAAAAAAzMzyAjZGLzMzMssYamYwMzMbYIMmlZWmtFjxYxAAwYGGDGYmZmZmgZA", pvp={ { id=123, name="Inner Light", cn="心灵之光" }, { id=5570, name="Phase Shift", cn="相位变换" }, { id=114, name="Ultimate Radiance", cn="极致光辉" } } },
        { rank=2, rating=2790, player="Jnglpriestx", realm="thrall", hero="Guiding Light", heroCn="指引之光", code="CAQAR03Gt7xPmcDNOjs2Zlb3yCDsMDWmZMzMwMbzYmZGjZGAAAAAAAAAAzMzyAjZGLzMzMssYamYAmZDDhxsMAjBLAAwYGGDGAzMzEMD", pvp={ { id=123, name="Inner Light", cn="心灵之光" }, { id=5570, name="Phase Shift", cn="相位变换" }, { id=114, name="Ultimate Radiance", cn="极致光辉" } } },
        { rank=3, rating=2751, player="Smíght", realm="thrall", hero="Guiding Light", heroCn="指引之光", code="CAQAR03Gt7xPmcDNOjs2Zlb3yCDsMDWmZMzMwMbzYmZGjZGAAAAAAAAAAzMzyAjZGLzMzMssYamYwMzMbYIMmlZWmtFjxYxAAwYGGDGYmZmZmgZA", pvp={ { id=123, name="Inner Light", cn="心灵之光" }, { id=5570, name="Phase Shift", cn="相位变换" }, { id=114, name="Ultimate Radiance", cn="极致光辉" } } },
    } },
    [257] = { key = "PRIEST/HOLY", n = 30, pvp = {
        { id=124, name="Spirit of the Redeemer", cn="救赎者之魂", pct=100.0 },
        { id=5569, name="Phase Shift", cn="相位变换", pct=100.0 },
        { id=108, name="Sanctified Ground", cn="神圣之地", pct=40.0 },
        { id=101, name="Psychic Shroud", cn="心灵帷幕", pct=33.3 },
        { id=5479, name="Purification", cn="纯净御罪", pct=26.7 },
    }, builds = {
        { rank=1, rating=2656, player="Peat", realm="hyjal", hero="Guiding Light", heroCn="指引之光", code="CEQAR03Gt7xPmcDNOjs2Zlb3yCDAAAAAAYxwMzyYmxMjhZglZmZGAAAAzYWmBzMzwMmZAMTBwMLzsMzkZbmZZAmZGsYmZWA0MmZMGMz2ygZmZgB", pvp={ { id=124, name="Spirit of the Redeemer", cn="救赎者之魂" }, { id=101, name="Psychic Shroud", cn="心灵帷幕" }, { id=5569, name="Phase Shift", cn="相位变换" } } },
        { rank=2, rating=2632, player="Mastutao", realm="azralon", hero="Guiding Light", heroCn="指引之光", code="CEQAR03Gt7xPmcDNOjs2Zlb3yCDAAAAAAwMzMmtZmhZGDzgZbmZmBAAAwMzsMwMjxyMmZYZxYmCgZ2wQYMLDwYgFjZAoZMDjBDgZmZgB", pvp={ { id=108, name="Sanctified Ground", cn="神圣之地" }, { id=5569, name="Phase Shift", cn="相位变换" }, { id=124, name="Spirit of the Redeemer", cn="救赎者之魂" } } },
        { rank=3, rating=2612, player="Tweeter", realm="trollbane", hero="Guiding Light", heroCn="指引之光", code="CEQAR03Gt7xPmcDNOjs2Zlb3yCDAAAAAAwMzMmtZmxMzYYGMbzMzMAAAAmZmlZwMzMWMGDLLGzUAMzyMbzMZ2mZ2GgZmBLGDAaGzwYwYZbwMzMwA", pvp={ { id=124, name="Spirit of the Redeemer", cn="救赎者之魂" }, { id=101, name="Psychic Shroud", cn="心灵帷幕" }, { id=5569, name="Phase Shift", cn="相位变换" } } },
    } },
    [260] = { key = "ROGUE/OUTLAW", n = 30, pvp = {
        { id=3483, name="Smoke Bomb", cn="烟雾弹", pct=93.3 },
        { id=5699, name="Preemptive Maneuver", cn="先觉机动", pct=80.0 },
        { id=145, name="Dismantle", cn="卸除武装", pct=73.3 },
        { id=3421, name="Turn the Tables", cn="局势逆转", pct=30.0 },
        { id=1208, name="Thick as Thieves", cn="偷天换日", pct=10.0 },
    }, builds = {
        { rank=1, rating=2454, player="Bootyguru", realm="bonechewer", hero="Hand of Fate", heroCn="命运之手", code="CQQA5HmDzx68KWyrW/8Y781L7DgZAGDmZbmZmZGjZZxMzMbTbzY2mBAAAAAYZZmZGmZmZWMzMGAAAAzAYwsNLmZmRzMbMbssNtwiZAmZmZGYA", pvp={ { id=5699, name="Preemptive Maneuver", cn="先觉机动" }, { id=3483, name="Smoke Bomb", cn="烟雾弹" }, { id=3421, name="Turn the Tables", cn="局势逆转" } } },
        { rank=2, rating=2219, player="Exid", realm="stormrage", hero="Unseen Blade", heroCn="隐秘之刃", code="CQQA5HmDzx68KWyrW/8Y781L7DgZYwYGmZbmZmZGjZZxMzMbTbDWmBAAAAAYZZmZMzMjZWMzMGAAAAzwADmtZxMzMamZjZjltpF2YAmZmZGYA", pvp={ { id=5699, name="Preemptive Maneuver", cn="先觉机动" }, { id=3483, name="Smoke Bomb", cn="烟雾弹" }, { id=145, name="Dismantle", cn="卸除武装" } } },
        { rank=3, rating=2146, player="Trelvareth", realm="velen", hero="Unseen Blade", heroCn="隐秘之刃", code="CQQA5HmDzx68KWyrW/8Y781L7DgZ2mhZMDzsNzMzMjxssYMzsNtMYbGAAAAAwssMmBzMmZxMzYAAAAMDDMY2mFzMzoZmNmNW2mWYjBYmZmZgB", pvp={ { id=3483, name="Smoke Bomb", cn="烟雾弹" }, { id=145, name="Dismantle", cn="卸除武装" }, { id=1208, name="Thick as Thieves", cn="偷天换日" } } },
    } },
    [262] = { key = "SHAMAN/ELEMENTAL", n = 30, pvp = {
        { id=5660, name="Shamanism", cn="萨满之道", pct=100.0 },
        { id=5574, name="Burrow", cn="掘地三尺", pct=93.3 },
        { id=3620, name="Grounding Totem", cn="根基图腾", pct=83.3 },
        { id=3488, name="Totem of Wrath", cn="天怒图腾", pct=20.0 },
    }, builds = {
        { rank=1, rating=2661, player="Meatbeaterx", realm="aggramar", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CYQALMl7AwW51MWzGneuHE3tPCAAAAzMLbzMGjZZZhxMMDAAAAsYmtNzMDbGWY2mZaoZWAgZbMzYmtFTLMzYsYMz8AzMbzGzyMYmZZAgZGgZmZGDz4DA", pvp={ { id=5574, name="Burrow", cn="掘地三尺" }, { id=3620, name="Grounding Totem", cn="根基图腾" }, { id=5660, name="Shamanism", cn="萨满之道" } } },
        { rank=2, rating=2579, player="Meatbeaterx", realm="bleeding-hollow", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CYQALMl7AwW51MWzGneuHE3tPCAAAAzMLbzMGjZZZhxMMDAAAAsYmtNzMDbGWY2mZaoZWAgZbMzYmtFTLjZGjFjZGzMbzGzyMYmZZAgZGAMzYYGfA", pvp={ { id=5660, name="Shamanism", cn="萨满之道" }, { id=5574, name="Burrow", cn="掘地三尺" }, { id=3620, name="Grounding Totem", cn="根基图腾" } } },
        { rank=3, rating=2551, player="Caserguy", realm="sargeras", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CYQALMl7AwW51MWzGneuHE3tPCAAAAzMLbzMGjZZbhxMMDAAAAsYmtNzMDLGWY2mZaoZWAgZbMGzstYaxMzYsYMzYmZb2MzyMYmZZAgZGgZmZGDz4DA", pvp={ { id=5574, name="Burrow", cn="掘地三尺" }, { id=5660, name="Shamanism", cn="萨满之道" }, { id=3620, name="Grounding Totem", cn="根基图腾" } } },
    } },
    [263] = { key = "SHAMAN/ENHANCEMENT", n = 30, pvp = {
        { id=722, name="Shamanism", cn="萨满之道", pct=100.0 },
        { id=5575, name="Burrow", cn="掘地三尺", pct=90.0 },
        { id=3622, name="Grounding Totem", cn="根基图腾", pct=83.3 },
        { id=3489, name="Counterstrike Totem", cn="反击图腾", pct=13.3 },
    }, builds = {
        { rank=1, rating=2587, player="Resetmmr", realm="stormrage", hero="Tempest", heroCn="狂风怒号", code="CcQALMl7AwW51MWzGneuHE3tPOzMDMzMzMzMMzMDAAAAAAAAwGWw2yMmZWW0ssNMDzMNYBgZZwYmtlZsMGz2MbGzMMz2YGAgZYmZGzMxMzMDGMGA", pvp={ { id=3622, name="Grounding Totem", cn="根基图腾" }, { id=5575, name="Burrow", cn="掘地三尺" }, { id=722, name="Shamanism", cn="萨满之道" } } },
        { rank=2, rating=2555, player="Madeofpaper", realm="stormrage", hero="Tempest", heroCn="狂风怒号", code="CcQALMl7AwW51MWzGneuHE3tPOzMDMzMzMzMMzMDAAAAAAAAwGWw2yMmZWW0ssNMDzMNYBgZbwYmtlZsMzY2GLGzMMz2YGAgZYmZGzMxMzMDGMGA", pvp={ { id=3622, name="Grounding Totem", cn="根基图腾" }, { id=5575, name="Burrow", cn="掘地三尺" }, { id=722, name="Shamanism", cn="萨满之道" } } },
        { rank=3, rating=2551, player="Ranton", realm="tichondrius", hero="Surging Totem", heroCn="涌动图腾", code="CcQALMl7AwW51MWzGneuHE3tPOzMjZmZmZmZmhZGzAAAAAAAAAgFstYMzstox2wMMz0gNAmlBjZWWmxyYmxMLGzMMz2YGAADzYGzMxMjZwgxHA", pvp={ { id=722, name="Shamanism", cn="萨满之道" }, { id=3489, name="Counterstrike Totem", cn="反击图腾" }, { id=5575, name="Burrow", cn="掘地三尺" } } },
    } },
    [264] = { key = "SHAMAN/RESTORATION", n = 30, pvp = {
        { id=715, name="Grounding Totem", cn="根基图腾", pct=90.0 },
        { id=5437, name="Master of the Elements", cn="元素宗师", pct=63.3 },
        { id=5723, name="Lightning Lasso", cn="闪电磁索", pct=50.0 },
        { id=5567, name="Static Field Totem", cn="静电力场图腾", pct=50.0 },
        { id=3755, name="Rain Dance", cn="祈雨舞", pct=26.7 },
        { id=5705, name="Totem of Wrath", cn="天怒图腾", pct=10.0 },
    }, builds = {
        { rank=1, rating=2613, player="Koksammy", realm="tichondrius", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CgQALMl7AwW51MWzGneuHE3tPCAAAgBAAAAzMzYbbGmZmZmxMzYssMzmNGzYZasNzCTmhxCmZwsNGjmllZmFzAzi5BmZMzsNbGAAAYmBzMYmhZgB", pvp={ { id=5723, name="Lightning Lasso", cn="闪电磁索" }, { id=5437, name="Master of the Elements", cn="元素宗师" }, { id=715, name="Grounding Totem", cn="根基图腾" } } },
        { rank=2, rating=2555, player="Mjölnîr", realm="aggramar", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CgQALMl7AwW51MWzGneuHE3tPCAAAgBAAAAzMzYbZGmZmZmxMzYstMziNGzYZasNzCTmhxCmZws8AGjmtFzsMGDWMmZmZmtZzAAAAzMYmBzMMzgB", pvp={ { id=5437, name="Master of the Elements", cn="元素宗师" }, { id=5723, name="Lightning Lasso", cn="闪电磁索" }, { id=715, name="Grounding Totem", cn="根基图腾" } } },
        { rank=3, rating=2495, player="Illiteratex", realm="area-52", hero="Call of the Ancestors", heroCn="先祖的召唤", code="CgQALMl7AwW51MWzGneuHE3tPCAAAgBAAAAzMGbLzwMzMzMmZYssMzmNGzYZasMzGTmhxiHwMDmlxY0ssMzsMzAWMmZMzsNbzAAAAzMYmBzMMzgB", pvp={ { id=5567, name="Static Field Totem", cn="静电力场图腾" }, { id=5437, name="Master of the Elements", cn="元素宗师" }, { id=715, name="Grounding Totem", cn="根基图腾" } } },
    } },
    [265] = { key = "WARLOCK/AFFLICTION", n = 30, pvp = {
        { id=5386, name="Jinx", cn="祸不单行", pct=96.7 },
        { id=5579, name="Impish Instincts", cn="小鬼本能", pct=76.7 },
        { id=18, name="Nether Ward", cn="虚空守卫", pct=46.7 },
        { id=16, name="Rot and Decay", cn="腐化枯萎", pct=36.7 },
        { id=15, name="Gateway Mastery", cn="传送门大师", pct=26.7 },
        { id=5608, name="Soul Rip", cn="夺魂", pct=13.3 },
    }, builds = {
        { rank=1, rating=2715, player="Filese", realm="tichondrius", hero="Demonic Soul", heroCn="恶魔之魂", code="CkQAMrNP5kak+EBqLfUa3dMm+uMGzMjmNzYhZmZZAAAmZWsZmZxMAwsssMGGziZaMzMslZjhtBAAgZAAAMzMzMzMjZmhZMzMzMYGDAgBMA", pvp={ { id=5386, name="Jinx", cn="祸不单行" }, { id=16, name="Rot and Decay", cn="腐化枯萎" }, { id=18, name="Nether Ward", cn="虚空守卫" } } },
        { rank=2, rating=2616, player="Diirtydawgg", realm="bleeding-hollow", hero="Demonic Soul", heroCn="恶魔之魂", code="CkQAMrNP5kak+EBqLfUa3dMm+uMGmZ0sNzYhZmZZAAAmZWsZmZxMAwsssMGGziZaMzMslZjhtBAAgZAAgZmZmZmZmZMzMMzYmZmBzYGAgBMA", pvp={ { id=5386, name="Jinx", cn="祸不单行" }, { id=16, name="Rot and Decay", cn="腐化枯萎" }, { id=5579, name="Impish Instincts", cn="小鬼本能" } } },
        { rank=3, rating=2589, player="Verminlordx", realm="sargeras", hero="Demonic Soul", heroCn="恶魔之魂", code="CkQAMrNP5kak+EBqLfUa3dMm+uMGPwMz0sNzYhZmZZAAAmZWsZmZxMAwsssMGGziZaMzMslZjhtBAAgZAAgZmZmZmxMjZGMzMzMzMYGDAgBMA", pvp={ { id=5579, name="Impish Instincts", cn="小鬼本能" }, { id=5608, name="Soul Rip", cn="夺魂" }, { id=5386, name="Jinx", cn="祸不单行" } } },
    } },
    [267] = { key = "WARLOCK/DESTRUCTION", n = 30, pvp = {
        { id=5580, name="Impish Instincts", cn="小鬼本能", pct=80.0 },
        { id=157, name="Fel Fissure", cn="邪能裂痕", pct=63.3 },
        { id=3508, name="Nether Ward", cn="虚空守卫", pct=60.0 },
        { id=5382, name="Gateway Mastery", cn="传送门大师", pct=50.0 },
        { id=5607, name="Soul Rip", cn="夺魂", pct=36.7 },
    }, builds = {
        { rank=1, rating=2778, player="Níenarýa", realm="skullcrusher", hero="Wither", heroCn="枯萎", code="CsQAMrNP5kak+EBqLfUa3dMm+uMGPwMjmtZGLMzMLjxMmlZMbLmBAAzMDzML2wMzYmllRzMDLDLzWjNGAAYMwMbAYmZmBzMzMGAAAmxMAA4BGG", pvp={ { id=5382, name="Gateway Mastery", cn="传送门大师" }, { id=3508, name="Nether Ward", cn="虚空守卫" }, { id=5580, name="Impish Instincts", cn="小鬼本能" } } },
        { rank=2, rating=2641, player="Stinkie", realm="nerzhul", hero="Cloven Souls", heroCn="溃解灵魂", code="CsQAMrNP5kak+EBqLfUa3dMm+uMGPwMzY2mZswMzsMGzYWMmlFzAAgZmxMzsYBzMjZW2GmZGWGWmNjFGAAYMAbAYmZmBzMjxAAAwMjBAgZGG", pvp={ { id=3508, name="Nether Ward", cn="虚空守卫" }, { id=5580, name="Impish Instincts", cn="小鬼本能" }, { id=157, name="Fel Fissure", cn="邪能裂痕" } } },
        { rank=3, rating=2639, player="Bigboomaj", realm="tichondrius", hero="Wither", heroCn="枯萎", code="CsQAMrNP5kak+EBqLfUa3dMm+aMjZGNbjxyMzMz2swMmlZMLLmBAAzMDzMbWwMzYmllRzMDbDLzWjNGAAYMwMbAYmZmBmZmxAAAwMjZAAMGG", pvp={ { id=157, name="Fel Fissure", cn="邪能裂痕" }, { id=5393, name="Shadow Rift", cn="暗影裂隙" }, { id=3508, name="Nether Ward", cn="虚空守卫" } } },
    } },
    [73] = { key = "WARRIOR/PROTECTION", n = 30, pvp = {
        { id=171, name="Morale Killer", cn="士气重挫", pct=66.7 },
        { id=175, name="Thunderstruck", cn="雷霆打击", pct=50.0 },
        { id=5715, name="Power Through Adversity", cn="逆势奋发", pct=40.0 },
        { id=5626, name="Safeguard", cn="捍卫", pct=26.7 },
        { id=24, name="Disarm", cn="缴械", pct=20.0 },
        { id=5627, name="Storm of Destruction", cn="毁灭风暴", pct=20.0 },
        { id=831, name="Dragon Charge", cn="巨龙冲锋", pct=20.0 },
        { id=168, name="Bodyguard", cn="护卫", pct=16.7 },
    }, builds = {
        { rank=1, rating=2051, player="Loglogn", realm="tichondrius", hero="Demolish", heroCn="崩摧", code="CkEASWsDSHNyPDXnbxuIhH3Zd32AAAzMDmZmZmZ2mxsMMGmGzMjlFzMzwMmZGAAAAsMAMjBAWMjhNyAzwCNmZhxMMDjFAAzMAgBMG", pvp={ { id=168, name="Bodyguard", cn="护卫" }, { id=5626, name="Safeguard", cn="捍卫" }, { id=171, name="Morale Killer", cn="士气重挫" } } },
        { rank=2, rating=2025, player="Humanlog", realm="proudmoore", hero="Demolish", heroCn="崩摧", code="CkEASWsDSHNyPDXnbxuIhH3Zd32AAAzMDmZmZmZ2mxsMMGmGzMjlFzMzwMmZGAAAAsMAMjBAWMjhNyAzwCNmZhxMMDjFAAzMAgBMG", pvp={ { id=24, name="Disarm", cn="缴械" }, { id=5626, name="Safeguard", cn="捍卫" }, { id=171, name="Morale Killer", cn="士气重挫" } } },
        { rank=3, rating=2020, player="Orclog", realm="proudmoore", hero="Demolish", heroCn="崩摧", code="CkEASWsDSHNyPDXnbxuIhH3Zd32AAAzMDmZmZmZ2mxsMMGmGzMjlFzMzwMmZGAAAAsMAMjBAWMjhNyAzwCNmZhxMMDjFAAzMAgBMG", pvp={ { id=24, name="Disarm", cn="缴械" }, { id=5626, name="Safeguard", cn="捍卫" }, { id=171, name="Morale Killer", cn="士气重挫" } } },
    } },
    [577] = { key = "DEMONHUNTER/HAVOC", n = 29, pvp = {
        { id=5433, name="Blood Moon", cn="鲜血之月", pct=96.6 },
        { id=813, name="Glimpse", cn="转瞬即逝", pct=93.1 },
        { id=812, name="Detainment", cn="拘押", pct=41.4 },
        { id=806, name="Reverse Magic", cn="反转魔法", pct=37.9 },
        { id=811, name="Rain from Above", cn="从天而降", pct=27.6 },
    }, builds = {
        { rank=1, rating=2817, player="Classfantasy", realm="bleeding-hollow", hero="Art of the Glaive", heroCn="战刃绝技", code="CEkAp/epaxe7D0A403L+Tvk0iaGMzMjZMmZMzMZYGAAAAAAwsYMmZmZmZbmZsMzYGLzMM2mZZmFLzMjltZZaaGzMmxCAAAAAACwMjZwAQAAgB", pvp={ { id=812, name="Detainment", cn="拘押" }, { id=813, name="Glimpse", cn="转瞬即逝" }, { id=5433, name="Blood Moon", cn="鲜血之月" } } },
        { rank=2, rating=2770, player="Natooeasy", realm="area-52", hero="Art of the Glaive", heroCn="战刃绝技", code="CEkAp/epaxe7D0A403L+Tvk0iygZmZMjxMjZmJDzAAAAAAAmFjxMzMzMbzMjlZGzYZmhZ2mZZmlZZmZmltZZaaGzMmxCAAAAAACwMzMDGACAAM", pvp={ { id=813, name="Glimpse", cn="转瞬即逝" }, { id=5433, name="Blood Moon", cn="鲜血之月" }, { id=806, name="Reverse Magic", cn="反转魔法" } } },
        { rank=3, rating=2660, player="Golx", realm="thrall", hero="Demonsurge", heroCn="魔涌", code="CEkAp/epaxe7D0A403L+Tvk0iamZMzMDjxMjZmpZMDAAAAAAwsMjxYMzgZGLzMmx2MDmlBWmFzYYW00YmZMjNAAAAAAEAMzgBgAAAD", pvp={ { id=5433, name="Blood Moon", cn="鲜血之月" }, { id=813, name="Glimpse", cn="转瞬即逝" }, { id=811, name="Rain from Above", cn="从天而降" } } },
    } },
    [1473] = { key = "EVOKER/AUGMENTATION", n = 29, pvp = {
        { id=5563, name="Obsidian Mettle", cn="黑曜之勇", pct=100.0 },
        { id=5560, name="Unburdened Flight", cn="轻驰飞翔", pct=79.3 },
        { id=5561, name="Scouring Flame", cn="冲刷之焰", pct=65.5 },
        { id=5619, name="Time Stop", cn="时间停止", pct=34.5 },
        { id=5557, name="Divide and Conquer", cn="各个击破", pct=10.3 },
    }, builds = {
        { rank=1, rating=2312, player="Gloomie", realm="tichondrius", hero="Mass Eruption", heroCn="大规模喷发", code="CEcBPJc41CfcseY0baneJ1IHrNMzMbzMzMWmBzsNjZmxMAAAAAAAAwMMzMGjpGzMzAAAAAzMDmZWGzMwMMGmlZstMLDzsNMDzMNiNMGYmBwA", pvp={ { id=5563, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5560, name="Unburdened Flight", cn="轻驰飞翔" }, { id=5561, name="Scouring Flame", cn="冲刷之焰" } } },
        { rank=2, rating=2249, player="Bigdicdragon", realm="stormrage", hero="Mass Eruption", heroCn="大规模喷发", code="CEcBPJc41CfcseY0baneJ1IHrNMzMbzMzMWmBzsNMzMmBAAAAAAAgxMMzwYM1MzMzAAAAAzYGmZMmZgZWMGmlZstMLDzsNMDzMNiNMGzMzMwwA", pvp={ { id=5561, name="Scouring Flame", cn="冲刷之焰" }, { id=5563, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5560, name="Unburdened Flight", cn="轻驰飞翔" } } },
        { rank=3, rating=2221, player="Augdog", realm="darkspear", hero="Mass Eruption", heroCn="大规模喷发", code="CEcBPJc41CfcseY0baneJ1IHrhZmZbmZmhZwMbzYmZMzCAAAAAMAAwMDzMGjpGzMzAAAAAzYwMz2YmBmxMGmlZstMLDzsNMDzMNiNMGYmBGG", pvp={ { id=5557, name="Divide and Conquer", cn="各个击破" }, { id=5563, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5619, name="Time Stop", cn="时间停止" } } },
    } },
    [1468] = { key = "EVOKER/PRESERVATION", n = 29, pvp = {
        { id=5468, name="Nullifying Shroud", cn="废灵遮罩", pct=100.0 },
        { id=5718, name="Emerald Communion", cn="翡翠交融", pct=100.0 },
        { id=5461, name="Scouring Flame", cn="冲刷之焰", pct=55.2 },
        { id=5459, name="Obsidian Mettle", cn="黑曜之勇", pct=20.7 },
        { id=5470, name="Unburdened Flight", cn="轻驰飞翔", pct=17.2 },
    }, builds = {
        { rank=1, rating=2765, player="Sleepiihead", realm="illidan", hero="Legacy of the Lifebinder", heroCn="生命缚誓者的传承", code="CwbBPJc41CfcseY0baneJ1IHrBAAAAAMzMDmZMYGzmhZmZbYAAgZMjZwYGNmZAAAAmZGZGzMmlZmBAzYmxMLbsYhhZmZaoZzwmhxMDmZGD", pvp={ { id=5468, name="Nullifying Shroud", cn="废灵遮罩" }, { id=5718, name="Emerald Communion", cn="翡翠交融" }, { id=5459, name="Obsidian Mettle", cn="黑曜之勇" } } },
        { rank=2, rating=2748, player="Waen", realm="kelthuzad", hero="Chrono Flame", heroCn="时序烈焰", code="CwbBPJc41CfcseY0baneJ1IHrBAAAAAegZmZ22GYYmZYmxgthBAAzMjZmxYMzEMDAAAsNzMaGjZmZZMDAMmZMzyGLWYYmZmGa2MsYYMzgZGGA", pvp={ { id=5459, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5468, name="Nullifying Shroud", cn="废灵遮罩" }, { id=5718, name="Emerald Communion", cn="翡翠交融" } } },
        { rank=3, rating=2689, player="Trantis", realm="tichondrius", hero="Legacy of the Lifebinder", heroCn="生命缚誓者的传承", code="CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZwMwsNMAAwMMzMGDzEzMDAAAsNzMTzYMzMLjZAgxMjZW2YxCDzMz0QzmZsZYMzgZGGA", pvp={ { id=5459, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5468, name="Nullifying Shroud", cn="废灵遮罩" }, { id=5718, name="Emerald Communion", cn="翡翠交融" } } },
    } },
    [253] = { key = "HUNTER/BEASTMASTERY", n = 29, pvp = {
        { id=3599, name="Survival Tactics", cn="生存战术", pct=93.1 },
        { id=5746, name="Scatter Shot", cn="驱散射击", pct=86.2 },
        { id=5444, name="Kindred Beasts", cn="野兽亲和", pct=69.0 },
        { id=3604, name="Chimaeral Sting", cn="奇美拉钉刺", pct=34.5 },
        { id=693, name="The Beast Within", cn="野兽之心", pct=17.2 },
    }, builds = {
        { rank=1, rating=2725, player="Shadeh", realm="tichondrius", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C0PAD57yiELKEty14ekTDtZEqAMmxwCsAzwQDbAAYGzYmFzwMmZY8AzMGmxMzMGzYxMjZmZMMaGAAAAwMAAAMDzMgZ2ILYmFwyAwA", pvp={ { id=3599, name="Survival Tactics", cn="生存战术" }, { id=5746, name="Scatter Shot", cn="驱散射击" }, { id=5444, name="Kindred Beasts", cn="野兽亲和" } } },
        { rank=2, rating=2638, player="Mutations", realm="sargeras", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C0PAD57yiELKEty14ekTDtZEqAMmxwCsAzwQDbAAYGzYmFzwMmZY8AzMGmxMzMGzYxMjZmZMMaGAAAAwMAAAMDzMgZ2ILYmFwyAwA", pvp={ { id=3599, name="Survival Tactics", cn="生存战术" }, { id=3604, name="Chimaeral Sting", cn="奇美拉钉刺" }, { id=5746, name="Scatter Shot", cn="驱散射击" } } },
        { rank=3, rating=2574, player="Zuunexx", realm="wildhammer", hero="Howl of the Pack Leader", heroCn="猎群领袖之嚎", code="C0PAD57yiELKEty14ekTDtZEqAMmxwCsAzwQDbAAYGzYmFzwMmZY8AzMGmxMzMGzYxMjZmZMMaGAAAAwMAAAMDzMgZ2ILYmFwyAwA", pvp={ { id=3604, name="Chimaeral Sting", cn="奇美拉钉刺" }, { id=3599, name="Survival Tactics", cn="生存战术" }, { id=5746, name="Scatter Shot", cn="驱散射击" } } },
    } },
    [62] = { key = "MAGE/ARCANE", n = 29, pvp = {
        { id=5661, name="Chrono Shift", cn="时空转移", pct=93.1 },
        { id=5707, name="Overpowered Barrier", cn="超强能量屏障", pct=89.7 },
        { id=637, name="Improved Mass Invisibility", cn="强化群体隐形", pct=82.8 },
        { id=5397, name="Arcanosphere", cn="奥能之球", pct=17.2 },
    }, builds = {
        { rank=1, rating=2587, player="Numbing", realm="sargeras", hero="Spellfire Spheres", heroCn="法术火焰宝珠", code="C4DAche08tHz49KSVf7iKFnyuNzwYZmZmFMDamxAAAwAAmZmmlltZmZmZZZmJ2AAYDmZG2sMjZWmxYmZmZYhZmZmZAAGAAgZmFMzAmBADzMD", pvp={ { id=5707, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5589, name="Master Shepherd", cn="牧羊大师" }, { id=5661, name="Chrono Shift", cn="时空转移" } } },
        { rank=2, rating=2562, player="Austin", realm="sargeras", hero="Spellfire Spheres", heroCn="法术火焰宝珠", code="C4DAche08tHz49KSVf7iKFnyuNstMzyMzMbDzM0YMDAAgBAMzMNLLLzMzMzyyMTsBAwCjZmhNLzMzsMjx8AmZGWYGzMzAAMAAAzMLYmBGDAGGzA", pvp={ { id=5661, name="Chrono Shift", cn="时空转移" }, { id=637, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5707, name="Overpowered Barrier", cn="超强能量屏障" } } },
        { rank=3, rating=2545, player="Oneschool", realm="sargeras", hero="Spellfire Spheres", heroCn="法术火焰宝珠", code="C4DAche08tHz49KSVf7iKFnyuNstMzyMzMbYmhmZMDAAgBAMzMNLLLzMzMzyyMTsBAwCmZmhNLzMzsMjx8AmZGWYGzMzAAMAAAzMLYmBYAwwYG", pvp={ { id=5707, name="Overpowered Barrier", cn="超强能量屏障" }, { id=637, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5661, name="Chrono Shift", cn="时空转移" } } },
    } },
    [63] = { key = "MAGE/FIRE", n = 29, pvp = {
        { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形", pct=100.0 },
        { id=5706, name="Overpowered Barrier", cn="超强能量屏障", pct=100.0 },
        { id=5588, name="Master Shepherd", cn="牧羊大师", pct=65.5 },
        { id=5489, name="Ice Wall", cn="冰墙", pct=34.5 },
    }, builds = {
        { rank=1, rating=2769, player="Cryptolord", realm="sargeras", hero="Mana Cascade", heroCn="法力涌流", code="C8DAche08tHz49KSVf7iKFnyuNmtlZWmZmZziZGMDzAAAYmlZMzsMLzMjZbbZGAgNzMzsNjxMzCAAAAAWMzMDAAYGjZYGmZZGAzMwYAMDDA", pvp={ { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形" }, { id=5706, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5588, name="Master Shepherd", cn="牧羊大师" } } },
        { rank=2, rating=2742, player="Fujikaze", realm="kelthuzad", hero="Mana Cascade", heroCn="法力涌流", code="C8DAche08tHz49KSVf7iKFnyuNmtlZWmZmZzmZGMPAzAAAYmlZMzsNLzMjZbZZGAgNzMzsNMmZWAAAAAwiZmZAAADzMDGmZZGYmZmBGzMMMDDA", pvp={ { id=5588, name="Master Shepherd", cn="牧羊大师" }, { id=5706, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
        { rank=3, rating=2720, player="Polynike", realm="tichondrius", hero="Frostfire Bolt", heroCn="霜火之箭", code="C8DAche08tHz49KSVf7iKFnyuNmtlZWmxDMb2MzIzwMAAAmZZGzMbzyMz0stsNDAwiZGz2MzMzYBAAAAALmZmZAAgZMmZYMzsMDMzMzQGzAMDDA", pvp={ { id=5489, name="Ice Wall", cn="冰墙" }, { id=5706, name="Overpowered Barrier", cn="超强能量屏障" }, { id=5621, name="Improved Mass Invisibility", cn="强化群体隐形" } } },
    } },
    [258] = { key = "PRIEST/SHADOW", n = 29, pvp = {
        { id=106, name="Driven to Madness", cn="堕入疯狂", pct=93.1 },
        { id=763, name="Psyfiend", cn="灵能魔", pct=86.2 },
        { id=5568, name="Phase Shift", cn="相位变换", pct=86.2 },
        { id=5447, name="Cascading Horrors", cn="倾泻恐怖", pct=24.1 },
        { id=5638, name="Mindgames", cn="控心术", pct=10.3 },
    }, builds = {
        { rank=1, rating=2612, player="Peterlongrod", realm="malganis", hero="Void Torrent", heroCn="虚空洪流", code="CIQAR03Gt7xPmcDNOjs2Zlb3yaYMAAAAAAAAAAAAYMLzMGLzMmZ2mZYMz2YGzMzYZMZYZx0AMzMDmZzMa2MY2mllMmZjBYMzgxMjxsMzYbZmZwMYA", pvp={ { id=106, name="Driven to Madness", cn="堕入疯狂" }, { id=763, name="Psyfiend", cn="灵能魔" }, { id=5447, name="Cascading Horrors", cn="倾泻恐怖" } } },
        { rank=2, rating=2593, player="Envyion", realm="sargeras", hero="Halo", heroCn="光晕", code="CIQAR03Gt7xPmcDNOjs2Zlb3yOMDDAAAAAAAAAAAAmZxMmZbmxMz2MGjx2MzYmZGbIzYxMNAzMzgZ2MjmNDmtZbLjZWYAmZAjZmZMbMz2yMzgZwA", pvp={ { id=106, name="Driven to Madness", cn="堕入疯狂" }, { id=5447, name="Cascading Horrors", cn="倾泻恐怖" }, { id=5568, name="Phase Shift", cn="相位变换" } } },
        { rank=3, rating=2554, player="Ruberhosex", realm="kelthuzad", hero="Void Torrent", heroCn="虚空洪流", code="CIQAR03Gt7xPmcDNOjs2Zlb3yaYMAAAAAAAAAAAAYMLzMGbzMmZ2mZYMz2YGzMzYZMZYZx0AMzMDmZxMa2MY2mtlMmZjBYMzgxMjxsMmZbZmZwMYA", pvp={ { id=763, name="Psyfiend", cn="灵能魔" }, { id=106, name="Driven to Madness", cn="堕入疯狂" }, { id=5568, name="Phase Shift", cn="相位变换" } } },
    } },
    [259] = { key = "ROGUE/ASSASSINATION", n = 29, pvp = {
        { id=5697, name="Preemptive Maneuver", cn="先觉机动", pct=93.1 },
        { id=3480, name="Smoke Bomb", cn="烟雾弹", pct=93.1 },
        { id=5405, name="Dismantle", cn="卸除武装", pct=82.8 },
        { id=5408, name="Thick as Thieves", cn="偷天换日", pct=13.8 },
        { id=3479, name="Death from Above", cn="天降杀机", pct=10.3 },
    }, builds = {
        { rank=1, rating=2800, player="Alaissaelsia", realm="tichondrius", hero="Hand of Fate", heroCn="命运之手", code="CMQA5HmDzx68KWyrW/8Y781L7bmlxsZGAAAAAAz2MmtZAAAAAAtsMmBzMGLzMzsNzyMjHYmZmZwMmZMGGsNz2YhxMmlGz22wkthhtZYbmBzMDGA", pvp={ { id=147, name="System Shock", cn="神经冲击" }, { id=3479, name="Death from Above", cn="天降杀机" }, { id=5697, name="Preemptive Maneuver", cn="先觉机动" } } },
        { rank=2, rating=2793, player="Ozzthegreat", realm="illidan", hero="Hand of Fate", heroCn="命运之手", code="CMQA5HmDzx68KWyrW/8Y781L7bmlxsNzAAAAAAY2mxsNDAAAAAollhZYmxYbmZmtZWmZYmZmZwMmxMzwgtZ2GLMmxs0YW2GmsNMsNYbmBzMDGA", pvp={ { id=5697, name="Preemptive Maneuver", cn="先觉机动" }, { id=3479, name="Death from Above", cn="天降杀机" }, { id=3480, name="Smoke Bomb", cn="烟雾弹" } } },
        { rank=3, rating=2788, player="Robinhoe", realm="malganis", hero="Hand of Fate", heroCn="命运之手", code="CMQA5HmDzx68KWyrW/8Y781L7bmlxsZGAAAAAAz2MmtZAAAAAAtsMMDzMGLzMzsNzyMjZmZMDmxMmxAsNz2YhxMmlGzy2wkthhtZYbmBzMjxA", pvp={ { id=5405, name="Dismantle", cn="卸除武装" }, { id=3480, name="Smoke Bomb", cn="烟雾弹" }, { id=5697, name="Preemptive Maneuver", cn="先觉机动" } } },
    } },
    [252] = { key = "DEATHKNIGHT/UNHOLY", n = 28, pvp = {
        { id=149, name="Necrotic Wounds", cn="死疽伤口", pct=100.0 },
        { id=5590, name="Spellwarden", cn="咒术防护", pct=92.9 },
        { id=5430, name="Strangulate", cn="绞袭", pct=64.3 },
        { id=5585, name="Bloodforged Armor", cn="血锻盔甲", pct=17.9 },
        { id=40, name="Life and Death", cn="生死攸关", pct=14.3 },
    }, builds = {
        { rank=1, rating=2747, player="Promisedland", realm="sargeras", hero="Vampiric Strike", heroCn="吸血鬼打击", code="CwPAkXBWxkyfx9CbGaHonEAhLBYmBjZMDzyYmZa2mxYmhZAAAAAAAAMzYmZAwyMmZYmxMzYw2MbmZmFNzyCzGz20YjBYGAGzMjZwMzMzYGD", pvp={ { id=5590, name="Spellwarden", cn="咒术防护" }, { id=149, name="Necrotic Wounds", cn="死疽伤口" }, { id=5430, name="Strangulate", cn="绞袭" } } },
        { rank=2, rating=2734, player="Actualplant", realm="sargeras", hero="Vampiric Strike", heroCn="吸血鬼打击", code="CwPAkXBWxkyfx9CbGaHonEAhLBYmBjZmZYWGzMTz2MGjhZAAAAAAAAMzYmZAwyMmZYmxMzYw2MbmZmNNzyCzGz20YjBYGAGzMjZwMzMzYGD", pvp={ { id=5590, name="Spellwarden", cn="咒术防护" }, { id=149, name="Necrotic Wounds", cn="死疽伤口" }, { id=40, name="Life and Death", cn="生死攸关" } } },
        { rank=3, rating=2699, player="Budgetsonyd", realm="sargeras", hero="Rider's Champion", heroCn="冠军骑士", code="CwPAkXBWxkyfx9CbGaHonEAhLBYmBjZGDzyYmZa2mxYmhZAAAAAAAAMzYmZAwyMmZYmxMzYw2MbmZmFNz2GzGz20YhBYGAGzMjZwMzMzYGD", pvp={ { id=5590, name="Spellwarden", cn="咒术防护" }, { id=149, name="Necrotic Wounds", cn="死疽伤口" }, { id=40, name="Life and Death", cn="生死攸关" } } },
    } },
    [261] = { key = "ROGUE/SUBTLETY", n = 28, pvp = {
        { id=1209, name="Smoke Bomb", cn="烟雾弹", pct=96.4 },
        { id=5698, name="Preemptive Maneuver", cn="先觉机动", pct=92.9 },
        { id=5406, name="Dismantle", cn="卸除武装", pct=75.0 },
        { id=5409, name="Thick as Thieves", cn="偷天换日", pct=14.3 },
    }, builds = {
        { rank=1, rating=2468, player="Røbinhooe", realm="malganis", hero="Unseen Blade", heroCn="隐秘之刃", code="CUQA5HmDzx68KWyrW/8Y781L7DgZ2mBAAAAAmtxMLTMLbzMmZMDegZGzsMmtxMzssMMmZmxAmxAAAAwwMsYWmxsMDjFG2mZbahWmNMDzMzMYmZA", pvp={ { id=5406, name="Dismantle", cn="卸除武装" }, { id=1209, name="Smoke Bomb", cn="烟雾弹" }, { id=5698, name="Preemptive Maneuver", cn="先觉机动" } } },
        { rank=2, rating=2446, player="Asensi", realm="stormrage", hero="Unseen Blade", heroCn="隐秘之刃", code="CUQA5HmDzx68KWyrW/8Y781L7DgZ2mBAAAAAmtZmZZiZZbMmZMDMzMzsMzsMjZmllhBzMGwMGAAAAGmhNzyMmlZYsww2MbTL0ysxMDzMzMYmZA", pvp={ { id=1209, name="Smoke Bomb", cn="烟雾弹" }, { id=5406, name="Dismantle", cn="卸除武装" }, { id=5698, name="Preemptive Maneuver", cn="先觉机动" } } },
        { rank=3, rating=2423, player="Robinhoe", realm="malganis", hero="Unseen Blade", heroCn="隐秘之刃", code="CUQA5HmDzx68KWyrW/8Y781L7DgZ2mBAAAAAmtxMLTMLbzMmZMDegZGzsMmtxMzssMMmZmxAmxAAAAwwMsYWmxsMDjFG2mZbahWmNMDzMzMYmZA", pvp={ { id=5406, name="Dismantle", cn="卸除武装" }, { id=1209, name="Smoke Bomb", cn="烟雾弹" }, { id=5698, name="Preemptive Maneuver", cn="先觉机动" } } },
    } },
    [266] = { key = "WARLOCK/DEMONOLOGY", n = 28, pvp = {
        { id=5577, name="Impish Instincts", cn="小鬼本能", pct=75.0 },
        { id=5606, name="Soul Rip", cn="夺魂", pct=60.7 },
        { id=3506, name="Gateway Mastery", cn="传送门大师", pct=57.1 },
        { id=3624, name="Nether Ward", cn="虚空守卫", pct=57.1 },
        { id=162, name="Call Fel Lord", cn="召唤邪能领主", pct=46.4 },
    }, builds = {
        { rank=1, rating=2585, player="Woopzyy", realm="tichondrius", hero="Diabolic Ritual", heroCn="敬魔仪式", code="CoQAMrNP5kak+EBqLfUa3dMm+uMGzMjmlZGLMzMLDAAAAAAwYZZGzMDbGGmZb2ahmxiZGjlZZmZGzAAzMmZmZmBzMzMjxAAAMmxMGzYWmxAeAA", pvp={ { id=3506, name="Gateway Mastery", cn="传送门大师" }, { id=5577, name="Impish Instincts", cn="小鬼本能" }, { id=5606, name="Soul Rip", cn="夺魂" } } },
        { rank=2, rating=2571, player="Stinkie", realm="nerzhul", hero="Demonic Soul", heroCn="恶魔之魂", code="CoQAMrNP5kak+EBqLfUa3dMm+uMGmZmmNzYZmZMLDAAAAAAwYZZGzMDbGGmZZ2ahmxmBjlxMzMzMAgxMjZmZwMzMzYMAAAzMzMjZmhlZGgB", pvp={ { id=3624, name="Nether Ward", cn="虚空守卫" }, { id=162, name="Call Fel Lord", cn="召唤邪能领主" }, { id=5606, name="Soul Rip", cn="夺魂" } } },
        { rank=3, rating=2534, player="Woopzÿ", realm="tichondrius", hero="Diabolic Ritual", heroCn="敬魔仪式", code="CoQAMrNP5kak+EBqLfUa3dMm+uMGzMjmlZGLMzMLDAAAAAAwYZZGzMDbGGmZb2ahmxiZGjlZZmZGzAAzMmZmZmBzMzMjxAAAMmxMGzYWmxAeAA", pvp={ { id=3624, name="Nether Ward", cn="虚空守卫" }, { id=5577, name="Impish Instincts", cn="小鬼本能" }, { id=3506, name="Gateway Mastery", cn="传送门大师" } } },
    } },
    [71] = { key = "WARRIOR/ARMS", n = 28, pvp = {
        { id=33, name="Sharpen Blade", cn="打磨利刃", pct=100.0 },
        { id=3534, name="Disarm", cn="缴械", pct=53.6 },
        { id=5625, name="Safeguard", cn="捍卫", pct=50.0 },
        { id=5701, name="Berserker Roar", cn="狂战士咆哮", pct=46.4 },
        { id=31, name="Storm of Destruction", cn="毁灭风暴", pct=32.1 },
    }, builds = {
        { rank=1, rating=2678, player="Îï", realm="sargeras", hero="Slayer's Dominance", heroCn="屠戮之霸", code="CcEASWsDSHNyPDXnbxuIhH3ZdDzMzsMzMzMzAAAAMMNMzYGLMzMzwYmZAAAAAMWMDMZxYZbWMzywmhhZmZajmZwGwMWMLzMYGDmZmZAYmhBA", pvp={ { id=33, name="Sharpen Blade", cn="打磨利刃" }, { id=31, name="Storm of Destruction", cn="毁灭风暴" }, { id=5372, name="Demolition", cn="毁灭" } } },
        { rank=2, rating=2644, player="Magnusz", realm="zuljin", hero="Slayer's Dominance", heroCn="屠戮之霸", code="CcEASWsDSHNyPDXnbxuIhH3ZdjZmZmFzMmZGAAAghphZGzMLMzMzwYmZAAAAAMWmZgJMW2mFzsNsZYYmZm2oZGsBMjlxyALzsNYmZmBAzwA", pvp={ { id=33, name="Sharpen Blade", cn="打磨利刃" }, { id=31, name="Storm of Destruction", cn="毁灭风暴" }, { id=5701, name="Berserker Roar", cn="狂战士咆哮" } } },
        { rank=3, rating=2637, player="Ilh", realm="sargeras", hero="Slayer's Dominance", heroCn="屠戮之霸", code="CcEASWsDSHNyPDXnbxuIhH3ZdDzMzsMzMzYAAAAMMNMzYGLMzMzwYmZAAAAAMWMDMZxYZbWMzywmhhZmZajmZwGwMWMLzMsMz2gZmZGAmZYA", pvp={ { id=33, name="Sharpen Blade", cn="打磨利刃" }, { id=31, name="Storm of Destruction", cn="毁灭风暴" }, { id=5372, name="Demolition", cn="毁灭" } } },
    } },
    [1480] = { key = "DEMONHUNTER/DEVOURER", n = 27, pvp = {
        { id=5735, name="Beckon", cn="召唤", pct=100.0 },
        { id=5729, name="Armor of Souls", cn="灵魂护甲", pct=70.4 },
        { id=5734, name="Glimpse", cn="转瞬即逝", pct=66.7 },
        { id=5730, name="Surrender to the Void", cn="向虚空屈服", pct=29.6 },
        { id=5728, name="Inevitable End", cn="必然归宿", pct=14.8 },
        { id=5738, name="Reverse Magic", cn="反转魔法", pct=11.1 },
    }, builds = {
        { rank=1, rating=2704, player="Mvqx", realm="illidan", hero="Demonsurge", heroCn="魔涌", code="CgcBp/epaxe7D0A403L+Tvk0iCAMjZmZmxMjhZAAAAAAAYMGzMDAAAAAAAAzYGmZmZmxMzMMz2Mjxm2WAQADwMmZmlZmpZZmlZmxwA", pvp={ { id=5735, name="Beckon", cn="召唤" }, { id=5734, name="Glimpse", cn="转瞬即逝" }, { id=5729, name="Armor of Souls", cn="灵魂护甲" } } },
        { rank=2, rating=2635, player="Akumma", realm="tichondrius", hero="Voidfall", heroCn="虚落", code="CgcBp/epaxe7D0A403L+Tvk0iCAMjZmZmZmZMMAAAAAAAYMGzMDAAAAAAAAzYGmHYmZmZmZmxMziZMW0yCzMzMbtNzMDgZMzMLzMTzyMLPwwwwA", pvp={ { id=5728, name="Inevitable End", cn="必然归宿" }, { id=5730, name="Surrender to the Void", cn="向虚空屈服" }, { id=5735, name="Beckon", cn="召唤" } } },
        { rank=3, rating=2598, player="Ttndhtwo", realm="proudmoore", hero="Voidfall", heroCn="虚落", code="CgcBp/epaxe7D0A403L+Tvk0iCAMjZmZMmZMMDAAAAAAgHYMGzMDAAAAAAAAzYGmxMzMmZmZmZWMjxiWWYmZmZrtZmZAMjZmZZmZaWmZbGGY+AA", pvp={ { id=5729, name="Armor of Souls", cn="灵魂护甲" }, { id=5735, name="Beckon", cn="召唤" }, { id=5730, name="Surrender to the Void", cn="向虚空屈服" } } },
    } },
    [102] = { key = "DRUID/BALANCE", n = 27, pvp = {
        { id=185, name="Moonkin Aura", cn="枭兽光环", pct=88.9 },
        { id=5407, name="Owlkin Adept", cn="枭兽专家", pct=81.5 },
        { id=5383, name="High Winds", cn="高天狂风", pct=70.4 },
        { id=836, name="Faerie Swarm", cn="精灵虫群", pct=37.0 },
        { id=3058, name="Star Burst", cn="星辰迸发", pct=14.8 },
    }, builds = {
        { rank=1, rating=2797, player="Wakeenfiendx", realm="tichondrius", hero="Dream Surge", heroCn="梦境涌现", code="CYGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAAAAAAWGlZpZMmZAmNzMzMbMeAegZbsMjZMDmlZMzMDzGGAM22mZ22mZbWmpZmlZCAAAwmZmZmBbGGjZAMzgZGYA", pvp={ { id=5383, name="High Winds", cn="高天狂风" }, { id=836, name="Faerie Swarm", cn="精灵虫群" }, { id=185, name="Moonkin Aura", cn="枭兽光环" } } },
        { rank=3, rating=2675, player="Gspx", realm="dalaran", hero="Dream Surge", heroCn="梦境涌现", code="CYGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAAAAAAWGlZpZMmZAmNzMzMbmxYmZZmlxyMmBWmxMzMYBDAGLbzMbbzsNLz0MzyMBAAAYjZegZGsZgxMAmZwMDMA", pvp={ { id=3058, name="Star Burst", cn="星辰迸发" }, { id=836, name="Faerie Swarm", cn="精灵虫群" }, { id=5383, name="High Winds", cn="高天狂风" } } },
        { rank=4, rating=2671, player="Monyet", realm="nazgrel", hero="Dream Surge", heroCn="梦境涌现", code="CYGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAAAAAAWoMLNjxMDwsZmZmZjxDMegZZsMjZMzwsMjZmZwGGAM22mZ22mZbWmpZmlZCAAAwmZmZmBbGGjZAMzgZGYA", pvp={ { id=185, name="Moonkin Aura", cn="枭兽光环" }, { id=5407, name="Owlkin Adept", cn="枭兽专家" }, { id=5383, name="High Winds", cn="高天狂风" } } },
    } },
    [104] = { key = "DRUID/GUARDIAN", n = 27, pvp = {
        { id=51, name="Den Mother", cn="兽穴之母", pct=88.9 },
        { id=196, name="Overrun", cn="蛮力冲锋", pct=74.1 },
        { id=52, name="Demoralizing Roar", cn="挫志咆哮", pct=48.1 },
        { id=842, name="Alpha Challenge", cn="头号挑战", pct=22.2 },
        { id=194, name="Charging Bash", cn="横冲直撞", pct=18.5 },
        { id=1237, name="Malorne's Swiftness", cn="玛洛恩的迅捷", pct=14.8 },
        { id=5410, name="Grove Protection", cn="林地守护", pct=11.1 },
    }, builds = {
        { rank=1, rating=1713, player="Zyhsul", realm="emerald-dream", hero="Boundless Moonlight", heroCn="天涯共银辉", code="CgGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAgZmxsYmZMzmZz4BMWGwmhRTz0MzsZmZmZZMzDYAAAAAAzYxMw22MDGzyAYqZWmlZmZAAsZMDgFDMgFLbAmZmZDG", pvp={ { id=52, name="Demoralizing Roar", cn="挫志咆哮" }, { id=51, name="Den Mother", cn="兽穴之母" }, { id=196, name="Overrun", cn="蛮力冲锋" } } },
        { rank=2, rating=1415, player="Kìjáÿâån", realm="illidan", hero="Ravage", heroCn="毁灭", code="CgGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAgZmxsMzMMzmZbYMWGY2MjRTz0MmNzMjZZMDDAAAAAYGbzAW2mZwY2GATNzysMzMDAgFjZAsYGMgtZxAMzMzGMA", pvp={ { id=51, name="Den Mother", cn="兽穴之母" }, { id=194, name="Charging Bash", cn="横冲直撞" }, { id=196, name="Overrun", cn="蛮力冲锋" } } },
        { rank=3, rating=1381, player="Bufferal", realm="malganis", hero="Ravage", heroCn="毁灭", code="CgGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAgZmxsMzMMzmZbYMWGY2MjRTz0MmtZmZMLjZYAAAAAAzYZGwy2MDGz2AYqZWmlZmZAAsYMDgFGMgtZxAMzMzGMA", pvp={ { id=51, name="Den Mother", cn="兽穴之母" }, { id=194, name="Charging Bash", cn="横冲直撞" }, { id=196, name="Overrun", cn="蛮力冲锋" } } },
    } },
    [66] = { key = "PALADIN/PROTECTION", n = 27, pvp = {
        { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫", pct=96.3 },
        { id=861, name="Shield of Virtue", cn="美德之盾", pct=85.2 },
        { id=5664, name="Bear the Burden", cn="当承其重", pct=48.1 },
        { id=860, name="Warrior of Light", cn="光明战士", pct=33.3 },
        { id=5582, name="Searing Glare", cn="灼热凝视", pct=11.1 },
        { id=91, name="Steed of Glory", cn="荣耀战马", pct=11.1 },
    }, builds = {
        { rank=1, rating=2584, player="Aluvia", realm="malygos", hero="Holy Bulwark", heroCn="神圣壁垒", code="CIEAzbn3egSOtoSwvPw1U1vTLsZYWmZmZGzMjFGzysYZYAAGAAAAAA00MzyMjZmxwWAwAADsNAAwMTLzMbzMzsst0yMjFbLMDDMGzYYAwMzyMwYGgxG", pvp={ { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫" }, { id=861, name="Shield of Virtue", cn="美德之盾" }, { id=860, name="Warrior of Light", cn="光明战士" } } },
        { rank=2, rating=2508, player="Cloudx", realm="shattered-hand", hero="Holy Bulwark", heroCn="神圣壁垒", code="CIEAzbn3egSOtoSwvPw1U1vTLsZsNbzMjZmZmxCjZbWsMMAADAAAAAAaamZZmxMDDbBADAMD2AAAzMtNzsNzMzy2SLzMWsthhBmZMjZmBAzMAYGgxC", pvp={ { id=860, name="Warrior of Light", cn="光明战士" }, { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫" }, { id=861, name="Shield of Virtue", cn="美德之盾" } } },
        { rank=3, rating=2467, player="Wheyprot", realm="gorefiend", hero="Holy Bulwark", heroCn="神圣壁垒", code="CIEAzbn3egSOtoSwvPw1U1vTLsZYWmZGzMzMjNMz2sYZYAAGAAAAAA00MzyMjZGG2aDADAMD2AAAIAzMLbLtMzYx2CGGYmxMmZGAMzAgZAGL", pvp={ { id=94, name="Guardian of the Forgotten Queen", cn="被遗忘的女王护卫" }, { id=5664, name="Bear the Burden", cn="当承其重" }, { id=861, name="Shield of Virtue", cn="美德之盾" } } },
    } },
    [1467] = { key = "EVOKER/DEVASTATION", n = 26, pvp = {
        { id=5460, name="Obsidian Mettle", cn="黑曜之勇", pct=84.6 },
        { id=5462, name="Scouring Flame", cn="冲刷之焰", pct=80.8 },
        { id=5469, name="Unburdened Flight", cn="轻驰飞翔", pct=76.9 },
        { id=5464, name="Time Stop", cn="时间停止", pct=46.2 },
    }, builds = {
        { rank=1, rating=2771, player="Bluechewer", realm="stonemaul", hero="Mass Disintegrate", heroCn="群体裂解", code="CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAwYmZgZYmxMMz8AGDTjZmpZmxyMMzMz8AzMzAMzMDzMLjZgBGD2glxox2AyMBYDDMzAMA", pvp={ { id=5469, name="Unburdened Flight", cn="轻驰飞翔" }, { id=5460, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5462, name="Scouring Flame", cn="冲刷之焰" } } },
        { rank=2, rating=2739, player="Gloomie", realm="tichondrius", hero="Mass Disintegrate", heroCn="群体裂解", code="CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAwYMDmZYGzMMzwYMTjZmpZmx2MzMzMzMzMzAMzMYmZZMDMwMzM2YzyYWasNzwkZyGYbYgZmZG8AA", pvp={ { id=5464, name="Time Stop", cn="时间停止" }, { id=5460, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5462, name="Scouring Flame", cn="冲刷之焰" } } },
        { rank=3, rating=2679, player="Zynjamin", realm="stonemaul", hero="Mass Disintegrate", heroCn="群体裂解", code="CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAwYmZgZYmxMMz8AGDTjZmpZmxyMMzMz8AzMzAMzMDzMLjZgBGD2glxox2AyMBYDDMzAMA", pvp={ { id=5469, name="Unburdened Flight", cn="轻驰飞翔" }, { id=5460, name="Obsidian Mettle", cn="黑曜之勇" }, { id=5462, name="Scouring Flame", cn="冲刷之焰" } } },
    } },
    [72] = { key = "WARRIOR/FURY", n = 26, pvp = {
        { id=3735, name="Slaughterhouse", cn="屠宰场", pct=100.0 },
        { id=177, name="Enduring Rage", cn="无尽之怒", pct=80.8 },
        { id=3533, name="Disarm", cn="缴械", pct=53.8 },
        { id=5624, name="Safeguard", cn="捍卫", pct=19.2 },
        { id=179, name="Death Wish", cn="死亡之愿", pct=19.2 },
        { id=5702, name="Berserker Roar", cn="狂战士咆哮", pct=19.2 },
    }, builds = {
        { rank=1, rating=2697, player="Kenstlols", realm="tichondrius", hero="Lightning Strikes", heroCn="闪电打击", code="CgEASWsDSHNyPDXnbxuIhH3ZdDAAAAAAgGDjZMzymZmZMGzMzMjZmZWGGzMzsYmZGAAImZZbsxmlNz0YmZYysxMjFAzsYsAAzMAMGDjZYM", pvp={ { id=3533, name="Disarm", cn="缴械" }, { id=177, name="Enduring Rage", cn="无尽之怒" }, { id=3735, name="Slaughterhouse", cn="屠宰场" } } },
        { rank=2, rating=2661, player="Isnlonely", realm="tichondrius", hero="Lightning Strikes", heroCn="闪电打击", code="CgEASWsDSHNyPDXnbxuIhH3ZdDAAAAAAgGDjZMzCzMzYmxMzMzYmZmlhxMzMLmZmBAAiZW2GbsZZzMNmZGmMbMzYBwMLGLAwMDAjxwYGGD", pvp={ { id=3533, name="Disarm", cn="缴械" }, { id=3735, name="Slaughterhouse", cn="屠宰场" }, { id=177, name="Enduring Rage", cn="无尽之怒" } } },
        { rank=3, rating=2650, player="Ãemon", realm="tichondrius", hero="Lightning Strikes", heroCn="闪电打击", code="CgEASWsDSHNyPDXnbxuIhH3ZdDAAAAAAgGDzMjZWYmZGjxMzMzYmZmlhxMzMLmZmBAAiZW2GbsZZzMNmZGmMbMzYBwMLGLAwMDAjxwYGGD", pvp={ { id=3533, name="Disarm", cn="缴械" }, { id=3735, name="Slaughterhouse", cn="屠宰场" }, { id=177, name="Enduring Rage", cn="无尽之怒" } } },
    } },
}
